# Creating datasets by variable category. These are used to create a smaller and more manageable, final exposure dataset.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load, results='hide'}

# import main UKB dataset
dat <- readRDS("/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/2. First raw dataset from UKB/ukb42114.rds")

library(Hmisc)
```

```{r elf, results='hide'}

### Early life factors
elf <- subset(dat,
              select = c(
                Cs(
                  f.eid,
                  f.1647.0.0,
                  f.1677.0.0,
                  f.1687.0.0,
                  f.1697.0.0,
                  f.1707.0.0,
                  f.1767.0.0,
                  f.1777.0.0,
                  f.1787.0.0,
                  f.20022.0.0,
                  f.120.0.0,
                  f.20115.0.0,
                  f.20489.0.0,
                  f.20488.0.0,
                  f.20487.0.0,
                  f.20490.0.0,
                  f.20491.0.0
                )
              ))

colnames(elf) <- c(
  Cs(
    eid,
    country_birth,
    breastfed,
    body_size_10yrs_old,
    height_10yrs_old,
    handedness,
    adopted,
    part_multiple_birth,
    maternal_smoking,
    birth_weight,
    birth_weight_known,
    country_birth_non_UK,
    childhood_love,
    childhood_physical_abuse,
    childhood_hate,
    childhood_sex_abuse,
    childhood_doctor
  )
)

saveRDS(elf, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_elf.rds") # save RDS to file
```

```{r sle, results='hide'}

### Adult stressful life events (SLE)
sle <- subset(dat,
              select = c(
                Cs(
                  f.eid,
                  f.6145.0.0,
                  f.6145.0.1,
                  f.6145.0.2,
                  f.6145.0.3,
                  f.6145.0.4,
                  f.6145.0.5
                )
              ))

colnames(sle) <- c(
  Cs(
    eid,
    sle.0.0,
    sle.0.1,
    sle.0.2,
    sle.0.3,
    sle.0.4,
    sle.0.5
  )
)

saveRDS(sle, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_sle.rds") # save RDS to file
```

```{r social, results='hide'}

### Social support
soc <- subset(dat,
              select = c(
                Cs(
                  f.eid,
                  f.1031.0.0,
                  f.6160.0.0,
                  f.6160.0.1,
                  f.6160.0.2,
                  f.6160.0.3,
                  f.6160.0.4,
                  f.2110.0.0,
                  f.2020.0.0
                )
              ))

colnames(soc) <- c(
  Cs(
    eid,
    family_visit_freq,
    social_activity.0.0,
    social_activity.0.1,
    social_activity.0.2,
    social_activity.0.3,
    social_activity.0.4,
    confide_freq,
    loneliness
  )
)


saveRDS(soc, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_social.rds") # save RDS to file
```

```{r socio_dem, results='hide'}

### Sociodemographics
socio_dem <- subset(dat,
                    select = c(
                      Cs(
                        f.eid,
                        f.670.0.0,
                        f.680.0.0,
                        f.6139.0.0,
                        f.6139.0.1,
                        f.6139.0.2,
                        f.6140.0.0,
                        f.6140.0.1,
                        f.6140.0.2,
                        f.699.0.0,
                        f.709.0.0,
                        f.6141.0.0,
                        f.6141.0.1,
                        f.6141.0.2,
                        f.6141.0.3,
                        f.6141.0.4,
                        f.728.0.0,
                        f.738.0.0,
                        f.6138.0.0,
                        f.6138.0.1,
                        f.6138.0.2,
                        f.6138.0.3,
                        f.6138.0.4,
                        f.6138.0.5,
                        f.845.0.0,
                        f.20119.0.0,
                        f.796.0.0,
                        f.6142.0.0,
                        f.6142.0.1,
                        f.6142.0.2,
                        f.6142.0.3,
                        f.6142.0.4,
                        f.6142.0.5,
                        f.6142.0.6,
                        f.757.0.0,
                        f.767.0.0,
                        f.777.0.0,
                        f.6143.0.0,
                        f.6143.0.1,
                        f.6143.0.2,
                        f.6143.0.3,
                        f.806.0.0,
                        f.816.0.0,
                        f.826.0.0,
                        f.3426.0.0,
                        f.4825.0.0,
                        f.3659.0.0,
                        f.21000.0.0,
                        f.6146.0.0,
                        f.6146.0.1,
                        f.6146.0.2,
                        f.4674.0.0,
                        f.21022.0.0,
                        f.34.0.0,
                        f.31.0.0,
                        f.54.0.0,
                        f.53.0.0
                      )
                    ))



colnames(socio_dem) <- c(
  Cs(
    eid,
    accommodation_type,
    own_or_rent,
    gas_fuel_heat.0.0,
    gas_fuel_heat.0.1,
    gas_fuel_heat.0.2,
    heating_type.0.0,
    heating_type.0.1,
    heating_type.0.2,
    years_at_address,
    hshld_number,
    hshld_relations.0.0,
    hshld_relations.0.1,
    hshld_relations.0.2,
    hshld_relations.0.3,
    hshld_relations.0.4,
    hshld_vehicles,
    hshld_income,
    education_years.0.0,
    education_years.0.1,
    education_years.0.2,
    education_years.0.3,
    education_years.0.4,
    education_years.0.5,
    education_age_complete,
    employment_corrected,
    employment_distance,
    employment.0.0,
    employment.0.1,
    employment.0.2,
    employment.0.3,
    employment.0.4,
    employment.0.5,
    employment.0.6,
    employment_years,
    employment_hours,
    employment_travel_freq,
    commute_transport.0.0,
    commute_transport.0.1,
    commute_transport.0.2,
    commute_transport.0.3,
    employment_standing,
    employment_heavy_manual,
    shift_work,
    night_shift_work,
    noisy_workplace,
    immigration_year,
    ethnicity,
    public_assistance.0.0,
    public_assistance.0.1,
    public_assistance.0.2,
    private_healthcare,
    recruitment_age,
    birth_year,
    sex,
    recruitment_centre,
    recruitment_date
  )
)

saveRDS(socio_dem, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_sociodemographics.rds") # save RDS to file)                     
```

```{r fam_health, results='hide'}

### family health history
fam_health <- subset(dat,
                     select = c(
                       Cs(
                         f.eid,
                         f.20112.0.0,
                         f.20112.0.1,
                         f.20112.0.2,
                         f.20112.0.3,
                         f.20112.0.4,
                         f.20112.0.5,
                         f.20112.0.6,
                         f.20113.0.0,
                         f.20113.0.1,
                         f.20113.0.2,
                         f.20113.0.3,
                         f.20113.0.4,
                         f.20113.0.5,
                         f.20114.0.0,
                         f.20114.0.1,
                         f.20114.0.2,
                         f.20114.0.3,
                         f.20114.0.4,
                         f.20114.0.5,
                         f.20114.0.6,
                         f.20107.0.0,
                         f.20107.0.1,
                         f.20107.0.2,
                         f.20107.0.3,
                         f.20107.0.4,
                         f.20107.0.5,
                         f.20107.0.6,
                         f.20107.0.7,
                         f.20107.0.8,
                         f.20107.0.9,
                         f.20110.0.0,
                         f.20110.0.1,
                         f.20110.0.2,
                         f.20110.0.3,
                         f.20110.0.4,
                         f.20110.0.5,
                         f.20110.0.6,
                         f.20110.0.7,
                         f.20110.0.8,
                         f.20110.0.9,
                         f.20110.0.10,
                         f.20111.0.0,
                         f.20111.0.1,
                         f.20111.0.2,
                         f.20111.0.3,
                         f.20111.0.4,
                         f.20111.0.5,
                         f.20111.0.6,
                         f.20111.0.7,
                         f.20111.0.8,
                         f.20111.0.9,
                         f.20111.0.10,
                         f.20111.0.11,
                         f.4501.0.0,
                         f.1797.0.0,
                         f.3912.0.0,
                         f.2946.0.0,
                         f.1807.0.0,
                         f.1835.0.0,
                         f.3942.0.0,
                         f.1845.0.0,
                         f.3526.0.0,
                         f.1873.0.0,
                         f.3972.0.0,
                         f.1883.0.0,
                         f.3982.0.0,
                         f.5057.0.0
                       )
                     ))

colnames(fam_health) <- c(
  Cs(
    eid,
    adopted_father_illness.0.0,
    adopted_father_illness.0.1,
    adopted_father_illness.0.2,
    adopted_father_illness.0.3,
    adopted_father_illness.0.4,
    adopted_father_illness.0.5,
    adopted_father_illness.0.6,
    adopted_mother_illness.0.0,
    adopted_mother_illness.0.1,
    adopted_mother_illness.0.2,
    adopted_mother_illness.0.3,
    adopted_mother_illness.0.4,
    adopted_mother_illness.0.5,
    adopted_sibling_illness.0.0,
    adopted_sibling_illness.0.1,
    adopted_sibling_illness.0.2,
    adopted_sibling_illness.0.3,
    adopted_sibling_illness.0.4,
    adopted_sibling_illness.0.5,
    adopted_sibling_illness.0.6,
    father_illness.0.0,
    father_illness.0.1,
    father_illness.0.2,
    father_illness.0.3,
    father_illness.0.4,
    father_illness.0.5,
    father_illness.0.6,
    father_illness.0.7,
    father_illness.0.8,
    father_illness.0.9,
    mother_illness.0.0,
    mother_illness.0.1,
    mother_illness.0.2,
    mother_illness.0.3,
    mother_illness.0.4,
    mother_illness.0.5,
    mother_illness.0.6,
    mother_illness.0.7,
    mother_illness.0.8,
    mother_illness.0.9,
    mother_illness.0.10,
    sibling_illness.0.0,
    sibling_illness.0.1,
    sibling_illness.0.2,
    sibling_illness.0.3,
    sibling_illness.0.4,
    sibling_illness.0.5,
    sibling_illness.0.6,
    sibling_illness.0.7,
    sibling_illness.0.8,
    sibling_illness.0.9,
    sibling_illness.0.10,
    sibling_illness.0.11,
    death_close_family,
    father_alive,
    adopted_father_alive,
    father_age,
    father_age_death,
    mother_alive,
    adopted_mother_alive,
    mother_age,
    mother_age_death,
    number_brothers,
    number_adopted_brothers,
    number_sisters,
    number_adopted_sisters,
    number_older_siblings
  )
)

saveRDS(fam_health, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_family_health_history.rds") # save RDS to file)                     
```

```{r med_cond, results='hide'}

### medical conditions - excluded cancer and non-cancer illness codes
med_cond <- subset(dat,
                   select = c(
                     Cs(
                       f.eid,
                       f.6150.0.0,
                       f.6150.0.1,
                       f.6150.0.2,
                       f.6150.0.3,
                       f.3894.0.0,
                       f.3627.0.0,
                       f.4056.0.0,
                       f.2966.0.0,
                       f.6152.0.0,
                       f.6152.0.1,
                       f.6152.0.2,
                       f.6152.0.3,
                       f.6152.0.4,
                       f.4012.0.0,
                       f.4022.0.0,
                       f.3992.0.0,
                       f.3786.0.0,
                       f.3761.0.0,
                       f.2443.0.0,
                       f.4041.0.0,
                       f.2976.0.0,
                       f.2453.0.0,
                       f.2463.0.0,
                       f.6151.0.0,
                       f.6151.0.1,
                       f.6151.0.2,
                       f.6151.0.3,
                       f.6151.0.4,
                       f.6151.0.5,
                       f.6151.0.6,
                       f.3005.0.0,
                       f.2473.0.0,
                       f.134.0.0,
                       f.135.0.0,
                       f.2207.0.0,
                       f.2217.0.0,
                       f.6147.0.0,
                       f.6147.0.1,
                       f.6147.0.2,
                       f.6147.0.3,
                       f.6147.0.4,
                       f.6147.0.5,
                       f.5843.0.0,
                       f.5832.0.0,
                       f.5610.0.0,
                       f.5855.0.0,
                       f.6205.0.0,
                       f.5408.0.0,
                       f.5877.0.0,
                       f.5934.0.0,
                       f.2227.0.0,
                       f.6148.0.0,
                       f.6148.0.1,
                       f.6148.0.2,
                       f.6148.0.3,
                       f.6148.0.4,
                       f.5890.0.0,
                       f.6119.0.0,
                       f.5419.0.0,
                       f.5441.0.0,
                       f.5912.0.0,
                       f.5901.0.0,
                       f.4689.0.0,
                       f.5430.0.0,
                       f.4700.0.0,
                       f.5923.0.0,
                       f.5945.0.0,
                       f.6149.0.0,
                       f.6149.0.1,
                       f.6149.0.2,
                       f.6149.0.3,
                       f.6149.0.4,
                       f.6149.0.5,
                       f.2178.0.0,
                       f.2188.0.0,
                       f.2296.0.0,
                       f.2306.0.0,
                       f.2316.0.0,
                       f.4717.0.0,
                       f.4728.0.0,
                       f.5452.0.0,
                       f.5463.0.0,
                       f.5474.0.0,
                       f.5485.0.0,
                       f.5496.0.0,
                       f.5507.0.0,
                       f.5518.0.0,
                       f.5529.0.0,
                       f.5540.0.0,
                       f.6159.0.0,
                       f.6159.0.1,
                       f.6159.0.2,
                       f.6159.0.3,
                       f.6159.0.4,
                       f.6159.0.5,
                       f.6159.0.6,
                       f.3799.0.0,
                       f.4067.0.0,
                       f.3404.0.0,
                       f.3571.0.0,
                       f.3741.0.0,
                       f.3414.0.0,
                       f.3773.0.0,
                       f.2956.0.0,
                       f.2335.0.0,
                       f.3606.0.0,
                       f.3616.0.0,
                       f.3751.0.0,
                       f.2415.0.0,
                       f.2844.0.0,
                       f.136.0.0,
                       f.3079.0.0,
                       f.2247.0.0,
                       f.2257.0.0,
                       f.3393.0.0,
                       f.4792.0.0,
                       f.4803.0.0,
                       f.4814.0.0,
                       f.4836.0.0,
                       f.2345.0.0,
                       f.2355.0.0,
                       f.2365.0.0,
                       f.3809.0.0
                     )
                   ))

colnames(med_cond) <- c(
  Cs(
    eid,
    heart_diagnosis.0.0,
    heart_diagnosis.0.1,
    heart_diagnosis.0.2,
    heart_diagnosis.0.3,
    MI_diagnosis_age,
    angina_diagnosis_age,
    stroke_diagnosis_age,
    bp_diagnosis_age,
    other_diagnosis.0.0,
    other_diagnosis.0.1,
    other_diagnosis.0.2,
    other_diagnosis.0.3,
    other_diagnosis.0.4,
    DVT_diagnosis_age,
    pulm_embolism_diagnosis_age,
    emphysema_diagnosis_age,
    asthma_diagnosis_age,
    rhinitis_diagnosis_age,
    diabetes_diagnosis,
    gest_diabetes_only,
    diabetes_diagnosis_age,
    cancer_diagnosis,
    fracture_last_5yrs,
    fracture_site.0.0,
    fracture_site.0.1,
    fracture_site.0.2,
    fracture_site.0.3,
    fracture_site.0.4,
    fracture_site.0.5,
    fracture_site.0.6,
    fracture_fall,
    other_diagnosis,
    number_cancers,
    number_illnesses,
    glasses,
    glasses_age,
    glasses_reason.0.0,
    glasses_reason.0.1,
    glasses_reason.0.2,
    glasses_reason.0.3,
    glasses_reason.0.4,
    glasses_reason.0.5,
    myopia_eye,
    hypertropia_eye,
    presbyopia_eye,
    astigmatism_eye,
    strabismus_eye,
    amblyopia_eye,
    other_eye,
    other_serious_eye,
    other_eye_problems,
    eye_disorders.0.0,
    eye_disorders.0.1,
    eye_disorders.0.2,
    eye_disorders.0.3,
    eye_disorders.0.4,
    diabetes_eye,
    glaucoma_eye,
    injury_eye,
    cataract_eye,
    macular_degeneration_eye,
    diabetes_eye_age,
    glaucoma_age,
    injury_eye_age,
    cataract_age,
    macular_degeneration_age,
    other_serious_eye_age,
    mouth_problems.0.0,
    mouth_problems.0.1,
    mouth_problems.0.2,
    mouth_problems.0.3,
    mouth_problems.0.4,
    mouth_problems.0.5,
    overall_health,
    chronic_illness,
    falls_last_1yr,
    weight_change_last_1yr,
    chest_weeze_last_1yr,
    shortness_breath,
    leg_pain_walking,
    leg_pain_standing,
    leg_pain_calves,
    leg_pain_walking_uphill,
    leg_pain_walking_normal,
    leg_pain_walking_disappears,
    leg_pain_walking_action,
    leg_pain_walking_standing,
    leg_artery_surgery,
    leg_surgery,
    pain_last_1month.0.0,
    pain_last_1month.0.1,
    pain_last_1month.0.2,
    pain_last_1month.0.3,
    pain_last_1month.0.4,
    pain_last_1month.0.5,
    pain_last_1month.0.6,
    headaches_3months,
    facial_pain_3months,
    neck_pain_3months,
    stomach_pain_3months,
    back_pain_3months,
    hip_pain_3months,
    knee_pain_3months,
    general_pain_3months,
    chest_pain,
    chest_pain_walking_normal,
    chest_pain_ceases_still,
    chest_pain_walking_uphill,
    major_operations,
    other_operations,
    number_operations,
    pace_maker,
    hearing_difficulty,
    hearing_difficulty_background,
    hearing_aid,
    cochlear_implant,
    tinnitus,
    tinnitus_severity,
    loud_music_exposure,
    bowel_cancer_screening,
    bowel_cancer_screening_recent,
    PSA_test,
    PSA_test_time_since
  )
)


saveRDS(med_cond, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_medical_conditions.rds") # save RDS to file                     
```

```{r medications, results='hide'}

### medications
meds <- subset(dat,
               select = c(
                 Cs(
                   f.eid,
                   f.6177.0.0,
                   f.6177.0.1,
                   f.6177.0.2,
                   f.6153.0.0,
                   f.6153.0.1,
                   f.6153.0.2,
                   f.6153.0.3,
                   f.2492.0.0,
                   f.6154.0.0,
                   f.6154.0.1,
                   f.6154.0.2,
                   f.6154.0.3,
                   f.6154.0.4,
                   f.6154.0.5,
                   f.6155.0.0,
                   f.6155.0.1,
                   f.6155.0.2,
                   f.6155.0.3,
                   f.6155.0.4,
                   f.6155.0.5,
                   f.6155.0.6,
                   f.6179.0.0,
                   f.6179.0.1,
                   f.6179.0.2,
                   f.6179.0.3,
                   f.6179.0.4,
                   f.6179.0.5,
                   f.137.0.0
                 )
               ))

colnames(meds) <- c(
  Cs(
    eid,
    meds.0.0,
    meds.0.1,
    meds.0.2,
    meds_hormones.0.0,
    meds_hormones.0.1,
    meds_hormones.0.2,
    meds_hormones.0.3,
    other_meds,
    pain_meds.0.0,
    pain_meds.0.1,
    pain_meds.0.2,
    pain_meds.0.3,
    pain_meds.0.4,
    pain_meds.0.5,
    vitamins.0.0,
    vitamins.0.1,
    vitamins.0.2,
    vitamins.0.3,
    vitamins.0.4,
    vitamins.0.5,
    vitamins.0.6,
    minerals.0.0,
    minerals.0.1,
    minerals.0.2,
    minerals.0.3,
    minerals.0.4,
    minerals.0.5,
    number_medications
  )
)

saveRDS(meds, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_medications.rds") # save RDS to file                     
```

```{r male_repro, results='hide'}

### male reproduction
male_repro <- subset(dat,
                     select = c(Cs(
                       f.eid,
                       f.2375.0.0,
                       f.2385.0.0,
                       f.2395.0.0,
                       f.2405.0.0
                     )))

colnames(male_repro) <- c(Cs(eid,
                             age_facial_hair,
                             age_voice,
                             balding,
                             number_children))

saveRDS(male_repro, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_male_reproduction.rds") # save RDS to file                
```                                      

```{r female_repro, results='hide'}

### female reproduction
female_repro <- subset(dat,
                       select = c(
                         Cs(
                           f.eid,
                           f.2674.0.0,
                           f.2684.0.0,
                           f.2694.0.0,
                           f.2704.0.0,
                           f.2714.0.0,
                           f.2724.0.0,
                           f.3700.0.0,
                           f.3710.0.0,
                           f.3720.0.0,
                           f.2734.0.0,
                           f.2744.0.0,
                           f.3872.0.0,
                           f.2754.0.0,
                           f.2764.0.0,
                           f.2774.0.0,
                           f.3829.0.0,
                           f.3839.0.0,
                           f.3849.0.0,
                           f.2784.0.0,
                           f.2794.0.0,
                           f.2804.0.0,
                           f.2814.0.0,
                           f.3536.0.0,
                           f.3546.0.0,
                           f.3591.0.0,
                           f.2824.0.0,
                           f.2834.0.0,
                           f.3882.0.0,
                           f.3140.0.0
                         )
                       ))

colnames(female_repro) <- c(
  Cs(
    eid,
    mammogram,
    mammogram_years_since,
    cervical_smear,
    cervical_smear_years_since,
    menarche_age,
    menopause,
    period_time_since,
    menstrual_cycle_length,
    menstruating_today,
    number_births,
    first_child_birth_weight,
    birth_age,
    first_birth_age,
    last_birth_age,
    stillbirth,
    number_stillbirths,
    number_miscarriages,
    number_pregnancy_terminations,
    oral_contraceptive,
    oral_contraceptive_age_first,
    oral_contraceptive_age_last,
    HRT,
    HRT_age_first,
    HRT_age_last,
    hysterectomy,
    hysterectomy_age,
    bilateral_oophorectomy,
    bilateral_oophorectomy_age,
    pregnant
  )
)

saveRDS(female_repro, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_female_reproduction.rds") # save RDS to file                           
```   

```{r mental_health, results='hide'}

### mental health
mental_health <- subset(dat,
                        select = c(
                          Cs(
                            f.eid,
                            f.20126.0.0,
                            f.20122.0.0,
                            f.20124.0.0,
                            f.20125.0.0,
                            f.20123.0.0,
                            f.20127.0.0,
                            f.1920.0.0,
                            f.1930.0.0,
                            f.1940.0.0,
                            f.1950.0.0,
                            f.1960.0.0,
                            f.1970.0.0,
                            f.1980.0.0,
                            f.1990.0.0,
                            f.2000.0.0,
                            f.2010.0.0,
                            f.2030.0.0,
                            f.2040.0.0,
                            f.2050.0.0,
                            f.2060.0.0,
                            f.2070.0.0,
                            f.2080.0.0,
                            f.2090.0.0,
                            f.2100.0.0,
                            f.4598.0.0,
                            f.4609.0.0,
                            f.4620.0.0,
                            f.4631.0.0,
                            f.5375.0.0,
                            f.5386.0.0,
                            f.4642.0.0,
                            f.4653.0.0,
                            f.6156.0.0,
                            f.6156.0.1,
                            f.6156.0.2,
                            f.6156.0.3,
                            f.5663.0.0,
                            f.5674.0.0
                          )
                        ))

colnames(mental_health) <- c(
  Cs(
    eid,
    bipolar_MDD,
    bipolar,
    MDD_moderate,
    MDD_severe,
    MDD_single_ep,
    neuroticism,
    mood_swings,
    miserableness,
    irritability,
    sensitivity,
    fed_up_feelings,
    nervous,
    worrier,
    tense,
    worry_embarassment,
    nerves,
    guilty_feelings,
    risk_taking,
    depressed_mood_freq,
    unenthusiasm_freq,
    tenseness_freq,
    tiredness_freq,
    doctor_visit_mental_health,
    psychiatrist_visit_mental_health,
    depressed_whole_week,
    depression_duration,
    depression_episodes,
    unenthusiastic_whole_week,
    unenthusiastic_duration,
    unenthusiastic_episodes,
    manic,
    irritable,
    manic_symptoms.0.0,
    manic_symptoms.0.1,
    manic_symptoms.0.2,
    manic_symptoms.0.3,
    manic_duration,
    manic_episodes
  )
)

saveRDS(mental_health, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_mental_health.rds") # save RDS to file                                
```


```{r electronics, results='hide'}

### electronics use
electronics <- subset(dat,
                      select = c(
                        Cs(
                          f.eid,
                          f.1110.0.0,
                          f.1120.0.0,
                          f.1130.0.0,
                          f.1140.0.0,
                          f.1150.0.0,
                          f.2237.0.0
                        )
                      ))

colnames(electronics) <- c(
  Cs(
    eid,
    mobile_phone_duration,
    mobile_phone_weekly_usage,
    speakerphone,
    mobile_phone_2yrs,
    head_side_phone,
    computer_games
  )
)

saveRDS(electronics, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_electronics.rds") # save RDS to file                                    
```


```{r sleep, results='hide'}

### sleep
sleep <- subset(dat,
                select = c(
                  Cs(
                    f.eid,
                    f.1160.0.0,
                    f.1170.0.0,
                    f.1180.0.0,
                    f.1190.0.0,
                    f.1200.0.0,
                    f.1210.0.0,
                    f.1220.0.0
                  )
                ))

colnames(sleep) <- c(
  Cs(
    eid,
    sleep_hours,
    easy_wake,
    chronotype,
    nap,
    sleep_difficulty,
    snoring,
    narcolepsy
  )
)

saveRDS(sleep, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_sleep.rds") # save RDS to file                                              
```

```{r smoking, results='hide'}

### smoking
smok <- subset(dat,
               select = c(
                 Cs(
                   f.eid,
                   f.20160.0.0,
                   f.20162.0.0,
                   f.20161.0.0,
                   f.20116.0.0,
                   f.1239.0.0,
                   f.1249.0.0,
                   f.2644.0.0,
                   f.3436.0.0,
                   f.3446.0.0,
                   f.5959.0.0,
                   f.3456.0.0,
                   f.6194.0.0,
                   f.6183.0.0,
                   f.3466.0.0,
                   f.3506.0.0,
                   f.6158.0.0,
                   f.6158.0.1,
                   f.6158.0.2,
                   f.6158.0.3,
                   f.2867.0.0,
                   f.2877.0.0,
                   f.2887.0.0,
                   f.2897.0.0,
                   f.2907.0.0,
                   f.6157.0.0,
                   f.6157.0.1,
                   f.6157.0.2,
                   f.6157.0.3,
                   f.2926.0.0,
                   f.1259.0.0,
                   f.1269.0.0,
                   f.1279.0.0
                 )
               ))

colnames(smok) <- c(
  Cs(
    eid,
    ever_smoked,
    pack_years_prop,
    pack_years,
    smoking_status,
    tobacco,
    past_tobacco,
    light_smoking,
    smoking_start_age_current,
    tobacco_type,
    previous_smoker,
    number_cigarettes,
    cigarettes_stop_age,
    previous_number_cigarettes,
    waking_smoke_time,
    smoking_10yrs,
    why_reduced_smoking.0.0,
    why_reduced_smoking.0.1,
    why_reduced_smoking.0.2,
    why_reduced_smoking.0.3,
    smoking_start_age_former,
    tobacco_type_previous,
    number_cigarettes_previous,
    smoking_stop_age,
    ever_stop_smoking_6months,
    why_stopped_smoking.0.0,
    why_stopped_smoking.0.1,
    why_stopped_smoking.0.2,
    why_stopped_smoking.0.3,
    number_quit_attempts,
    hshld_smokers,
    tobacco_exposure_home,
    tobacco_exposure_outside
  )
)

saveRDS(smok, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_smoking.rds") # save RDS to file                                             
```

```{r alcohol, results='hide'}

### alcohol
alcohol <- subset(dat,
                  select = c(
                    Cs(
                      f.eid,
                      f.20117.0.0,
                      f.1558.0.0,
                      f.3731.0.0,
                      f.4407.0.0,
                      f.4418.0.0,
                      f.4429.0.0,
                      f.4440.0.0,
                      f.4451.0.0,
                      f.4462.0.0,
                      f.1568.0.0,
                      f.1578.0.0,
                      f.1588.0.0,
                      f.1598.0.0,
                      f.1608.0.0,
                      f.5364.0.0,
                      f.1618.0.0,
                      f.1628.0.0,
                      f.2664.0.0,
                      f.3859.0.0
                    )
                  ))

colnames(alcohol) <- c(
  Cs(
    eid,
    alcohol_status,
    alcohol_freq,
    alcohol_former,
    red_wine_monthly,
    white_wine_monthly,
    beer_monthly,
    spirits_monthly,
    fortified_wine_monthly,
    other_alcohol_monthly,
    red_wine_weekly,
    white_wine_weekly,
    beer_weekly,
    spirits_weekly,
    fortified_wine_weekly,
    other_alcohol_weekly,
    alcohol_with_meals,
    alcohol_10yrs,
    reason_reducing_alcohol,
    reason_stopped_alcohol
  )
)

saveRDS(alcohol, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_alcohol.rds") # save RDS to file                                                    
```

```{r diet, results='hide'}

### diet
diet <- subset(dat, select = c(
  Cs(
    f.eid,
    f.1289.0.0,
    f.1299.0.0,
    f.1309.0.0,
    f.1319.0.0,
    f.1329.0.0,
    f.1339.0.0,
    f.1349.0.0,
    f.1359.0.0,
    f.1369.0.0,
    f.1379.0.0,
    f.1389.0.0,
    f.3680.0.0,
    f.6144.0.0,
    f.6144.0.1,
    f.6144.0.2,
    f.6144.0.3,
    f.1408.0.0,
    f.1418.0.0,
    f.1428.0.0,
    f.2654.0.0,
    f.1438.0.0,
    f.1448.0.0,
    f.1458.0.0,
    f.1468.0.0,
    f.1478.0.0,
    f.1488.0.0,
    f.1508.0.0,
    f.1518.0.0,
    f.1528.0.0,
    f.1538.0.0,
    f.1548.0.0
  )
))

colnames(diet) <- c(
  Cs(
    eid,
    cooked_veg,
    salad_or_raw_veg,
    fresh_fruit,
    dried_fruit,
    oily_fish,
    non_oily_fish,
    processed_meat,
    poultry,
    beef,
    lamb,
    pork,
    meat_age_last,
    never_eat0.0,
    never_eat0.1,
    never_eat0.2,
    never_eat0.3,
    cheese,
    milk_type,
    spread_type,
    spread_type_details,
    bread,
    bread_type,
    cereal,
    cereal_type,
    salt,
    tea,
    coffee_type,
    hot_drink_temp,
    water,
    diet_change_5yrs,
    diet_variation
  )
)

saveRDS(diet, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_diet.rds") # save RDS to file  
```

```{r sun, results='hide'}

### sun
sun <- subset(dat,
              select = c(
                Cs(
                  f.eid,
                  f.1050.0.0,
                  f.1060.0.0,
                  f.1717.0.0,
                  f.1727.0.0,
                  f.1737.0.0,
                  f.1747.0.0,
                  f.1757.0.0,
                  f.2267.0.0,
                  f.2277.0.0
                )
              ))

colnames(sun) <- c(
  Cs(
    eid,
    summer_outdoors_time,
    winter_outdoors_time,
    skin_color,
    skin_tan_ease,
    childhood_sunburn_number,
    hair_color,
    facial_aging,
    sun_protection_use,
    solarium_freq
  )
)

saveRDS(sun, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_sun.rds") # save RDS to file  
```

```{r sex_hist, results='hide'}

### sex history
sex_hist <- subset(dat,
                   select = c(
                     Cs(
                       f.eid,
                       f.2129.0.0,
                       f.2139.0.0,
                       f.2149.0.0,
                       f.2159.0.0,
                       f.3669.0.0
                     )
                   ))

colnames(sex_hist) <- c(
  Cs(
    eid,
    sex_questions_answered,
    sex_age_first,
    number_sex_partners,
    same_sex_intercourse,
    number_same_sex_partners
  )
)

saveRDS(sex_hist, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_sex_history.rds") # save RDS to file  
```

```{r phys_activity, results='hide'}

### physical activity
phys_act <- subset(dat,
                   select = c(
                     Cs(
                       f.eid,
                       f.22035.0.0,
                       f.22036.0.0,
                       f.22032.0.0,
                       f.22038.0.0,
                       f.22039.0.0,
                       f.22037.0.0,
                       f.22033.0.0,
                       f.22034.0.0,
                       f.1100.0.0,
                       f.2634.0.0,
                       f.1021.0.0,
                       f.894.0.0,
                       f.3647.0.0,
                       f.1001.0.0,
                       f.914.0.0,
                       f.874.0.0,
                       f.981.0.0,
                       f.2624.0.0,
                       f.1011.0.0,
                       f.3637.0.0,
                       f.943.0.0,
                       f.991.0.0,
                       f.971.0.0,
                       f.884.0.0,
                       f.904.0.0,
                       f.864.0.0,
                       f.1090.0.0,
                       f.1080.0.0,
                       f.1070.0.0,
                       f.6164.0.0,
                       f.6164.0.1,
                       f.6164.0.2,
                       f.6164.0.3,
                       f.6164.0.4,
                       f.6162.0.0,
                       f.6162.0.1,
                       f.6162.0.2,
                       f.6162.0.3,
                       f.924.0.0
                     )
                   ))

colnames(phys_act) <- c(
  Cs(
    eid,
    above_activity_recommendation,
    above_activity_recommendation_incl_walk,
    IPAQ_activity_group,
    MET_mins_moderate_activty,
    MET_mins_vigorous_activty,
    MET_mins_walking,
    days_activity_sum,
    mins_activity_sum,
    fast_driving,
    heavy_DIY_duration,
    light_DIY_duration,
    moderate_activity_duration,
    other_exercise_duration,
    strenuous_sports_duration,
    vigorous_activity_duration,
    walks_duration,
    pleasure_walks_duration,
    heavy_DIY_freq_4wks,
    light_DIY_freq_4wks,
    other_exercise_freq_4wks,
    stair_climbing_freq_4wks,
    strenuous_sports_freq_4wks,
    pleasure_walks_freq_4wks,
    moderate_activity_over_10mins_days,
    vigorous_activity_over_10mins_days,
    walked_over_10mins_days,
    driving_time,
    computer_time,
    TV_time,
    physical_activity_type.0.0,
    physical_activity_type.0.1,
    physical_activity_type.0.2,
    physical_activity_type.0.3,
    physical_activity_type.0.4,
    transport_type.0.0,
    transport_type.0.1,
    transport_type.0.2,
    transport_type.0.3,
    usual_walking_pace
  )
)

saveRDS(phys_act, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_physical_activity.rds") # save RDS to file  
```

```{r vision, results='hide'}

### vision
vision <- subset(dat,
                 select = c(
                   Cs(
                     f.eid,
                     f.5208.0.0,
                     f.5201.0.0
                     )
                   ))

colnames(vision) <- c(
  Cs(
    eid,
    visual_acuity_left,
    visual_acuity_right
  )
)

saveRDS(vision, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_vision.rds") # save RDS to file  
```

```{r hearing, results='hide'}

### hearing
hearing <- subset(dat,
                  select = c(
                    Cs(
                      f.eid,
                      f.20019.0.0,
                      f.20021.0.0
                    )
                  ))

colnames(hearing) <- c(
  Cs(
    eid,
    speech_reception_threshold_left,
    speech_reception_threshold_right
  )
)

saveRDS(hearing, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_hearing.rds") # save RDS to file  
```

```{r blood_pressure, results='hide'}

### blood pressure
bp <- subset(dat,
             select = c(
               Cs(
                 f.eid,
                 f.4079.0.0,
                 f.94.0.0,
                 f.4080.0.0,
                 f.93.0.0,
                 f.95.0.0,
                 f.102.0.0
               )
             ))

colnames(bp) <- c(
  Cs(
    eid,
    diastolic_bp,
    diastolic_bp_manual,
    systolic_bp,
    systolic_bp_manual,
    pulse_rate_manual,
    pulse_rate
  )
)

saveRDS(bp, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_blood_pressure.rds") # save RDS to file  
```

```{r art_stiff, results='hide'}

### arterial stiffness
a_stiff <- subset(dat,
                  select = c(
                    Cs(
                      f.eid,
                      f.4199.0.0,
                      f.4198.0.0,
                      f.4200.0.0,
                      f.4194.0.0,
                      f.21021.0.0,
                      f.4196.0.0,
                      f.4195.0.0
                    )
                  ))

colnames(a_stiff) <- c(
  Cs(
    eid,
    pulse_wave_notch_position,
    pulse_wave_peak_position,
    pulse_wave_shoulder_position,
    pulse_rate_a_stiff,
    pulse_wave_arterial_stiffness_index,
    pulse_wave_peak_to_peak_time,
    pulse_wave_reflection_index
  )
)

saveRDS(a_stiff, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_arterial_stiffness.rds") # save RDS to file  
```

```{r anthro, results='hide'}

### anthropometrics
anthro <- subset(dat,
                 select = c(
                   Cs(
                     f.eid,
                     f.48.0.0,
                     f.21002.0.0,
                     f.21001.0.0,
                     f.49.0.0,
                     f.50.0.0,
                     f.51.0.0,
                     f.20015.0.0,
                     f.3077.0.0,
                     f.3160.0.0,
                     f.46.0.0,
                     f.47.0.0,
                     f.23098.0.0,
                     f.23104.0.0,
                     f.23113.0.0,
                     f.23118.0.0,
                     f.23114.0.0,
                     f.23123.0.0,
                     f.23119.0.0,
                     f.23124.0.0,
                     f.23120.0.0,
                     f.23121.0.0,
                     f.23125.0.0,
                     f.23126.0.0,
                     f.23122.0.0,
                     f.23127.0.0,
                     f.23128.0.0,
                     f.23129.0.0,
                     f.23130.0.0,
                     f.23099.0.0,
                     f.23100.0.0,
                     f.23101.0.0,
                     f.23102.0.0,
                     f.23115.0.0,
                     f.23111.0.0,
                     f.23116.0.0,
                     f.23112.0.0,
                     f.23117.0.0,
                     f.23106.0.0,
                     f.23110.0.0,
                     f.23109.0.0,
                     f.23108.0.0,
                     f.23107.0.0,
                     f.6218.0.0,
                     f.6222.0.0,
                     f.6221.0.0,
                     f.6220.0.0,
                     f.6219.0.0
                   )
                 ))

colnames(anthro) <- c(
  Cs(
    eid,
    waist_circumference,
    weight,
    BMI,
    hip_circumference,
    standing_height,
    seated_height,
    sitting_height,
    seating_box_height,
    weight_manual,
    hand_grip_strenght_left,
    hand_grip_strenght_right,
    weight_impedance,
    BMI_impedance,
    leg_fat_free_mass_right,
    leg_predicted_mass_left,
    leg_predicted_mass_right,
    arm_fat_percentage_left,
    arm_fat_percentage_right,
    arm_fat_mass_left,
    arm_fat_mass_right,
    arm_fat_free_mass_right,
    arm_fat_free_mass_left,
    arm_predicted_mass_left,
    arm_predicted_mass_right,
    trunk_fat_percentage,
    trunk_fat_mass,
    trunk_fat_free_mass,
    trunk_predicted_mass,
    body_fat_percent,
    whole_body_fat_mass,
    whole_body_fat_free_mass,
    whole_body_water_mass,
    leg_fat_percentage_left,
    leg_fat_percentage_right,
    leg_fat_mass_left,
    leg_fat_mass_right,
    leg_fat_free_mass_left,
    whole_body_impedance,
    arm_left_impedance,
    arm_right_impedance,
    leg_left_impedance,
    leg_right_impedance,
    whole_body_impedance_manual,
    arm_left_impedance_manual,
    arm_right_impedance_manual,
    leg_left_impedance_manual,
    leg_right_impedance_manual
  )
)

saveRDS(anthro, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_anthropometry.rds") # save RDS to file  
```

```{r spiro, results='hide'}

### spirometry (lung function)
spiro <- subset(dat, 
                select = c(
                  Cs(
                    f.eid,
                    f.20031.0.0,
                    f.20031.0.1,
                    f.20031.0.2,
                    f.3061.0.0,
                    f.3061.0.1,
                    f.3061.0.2,
                    f.3137.0.0,
                    f.20255.0.0,
                    f.3065.0.0,
                    f.3065.0.1,
                    f.3065.0.2,
                    f.3065.0.0,
                    f.3065.0.1,
                    f.3065.0.2,
                    f.3066.0.0,
                    f.3066.0.1,
                    f.3066.0.2,
                    f.3062.0.0,
                    f.3062.0.1,
                    f.3062.0.2,
                    f.20151.0.0,
                    f.20257.0.0,
                    f.3063.0.0,
                    f.3063.0.1,
                    f.3063.0.2,
                    f.20150.0.0,
                    f.20153.0.0,
                    f.20154.0.0,
                    f.20256.0.0,
                    f.20258.0.0,
                    f.3064.0.0,
                    f.3064.0.1,
                    f.3064.0.2
                  )
                ))


colnames(spiro) <- c(
  Cs(
    eid,
    blow_acceptability_text.0.0,
    blow_acceptability_text.0.1,
    blow_acceptability_text.0.2,
    blow_acceptability.0.0,
    blow_acceptability.0.1,
    blow_acceptability.0.2,
    number_spirometry_measurements,
    spirometry_QC,
    blow_ordering.0.0,
    blow_ordering.0.1,
    blow_ordering.0.2,
    blow_result_ranking.0.0,
    blow_result_ranking.0.1,
    blow_result_ranking.0.2,
    blow_data_points.0.0,
    blow_data_points.0.1,
    blow_data_points.0.2,
    FVC.0.0,
    FVC.0.1,
    FVC.0.2,
    FVC_best,
    FVC_z_score,
    FEV1.0.0,
    FEV1.0.1,
    FEV1.0.2,
    FEV1_best,
    FEV1_predicted,
    FEV1_predicted_percentage,
    FEV1_z_score,
    FEV1_FVC_ratio_z_score,
    peak_expiratory_flow.0.0,
    peak_expiratory_flow.0.1,
    peak_expiratory_flow.0.2
  )
)


saveRDS(spiro, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_spirometry.rds") # save RDS to file  
```

```{r bmd, results='hide'}

### heel bone mineral density
bmd <- subset(dat,
              select = c(
                Cs(
                  f.eid,
                  f.3082.0.0,
                  f.3081.0.0,
                  f.3146.0.0,
                  f.3143.0.0,
                  f.3144.0.0,
                  f.3147.0.0,
                  f.3148.0.0,
                  f.78.0.0,
                  f.3086.0.0,
                  f.3085.0.0,
                  f.3083.0.0,
                  f.3084.0.0,
                  f.77.0.0,
                  f.4093.0.0,
                  f.4096.0.0,
                  f.4100.0.0,
                  f.4119.0.0,
                  f.4103.0.0,
                  f.4122.0.0,
                  f.4101.0.0,
                  f.4120.0.0,
                  f.4104.0.0,
                  f.4123.0.0,
                  f.4105.0.0,
                  f.4124.0.0,
                  f.4106.0.0,
                  f.4125.0.0,
                  f.4142.0.0,
                  f.4147.0.0,
                  f.4141.0.0,
                  f.4146.0.0,
                  f.4139.0.0,
                  f.4144.0.0,
                  f.4140.0.0,
                  f.4145.0.0,
                  f.4138.0.0,
                  f.4143.0.0
                )
              ))

colnames(bmd) <- c(
  Cs(
    eid,
    fractured_heel,
    bone_density_measure_foot,
    heel_sound_speed,
    ankle_spacing_width,
    heel_broadband_attenuation,
    heel_QUI,
    heel_bone_mineral_density,
    heel_bone_mineral_density_t_score,
    heel_sound_speed_manual,
    heel_broadband_attenuation_manual,
    heel_QUI_manual,
    heel_bone_mineral_density_manual,
    heel_bone_ultrasound_t_score_manual,
    fractured_heel_left,
    fractured_heel_right,
    ankle_spacing_width_left,
    ankle_spacing_width_right,
    heel_sound_speed_left,
    heel_sound_speed_right,
    heel_broadband_attenuation_left,
    heel_broadband_attenuation_right,
    heel_QUI_left,
    heel_QUI_right,
    heel_bone_mineral_density_left,
    heel_bone_mineral_density_right,
    heel_bone_mineral_density_t_score_left,
    heel_bone_mineral_density_t_score_right,
    heel_sound_speed_manual_left,
    heel_sound_speed_manual_right,
    heel_broadband_attenuation_manual_left,
    heel_broadband_attenuation_manual_right,
    heel_QUI_manual_left,
    heel_QUI_manual_right,
    heel_bone_mineral_density_manual_left,
    heel_bone_mineral_density_manual_right,
    heel_bone_mineral_density_t_score_manual_left,
    heel_bone_mineral_density_t_score_manual_right
  )
)


saveRDS(bmd, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_bone_mineral_density.rds") # save RDS to file  
```

```{r imd, results='hide'}

### indices of material deprivation + townsend deprivation index
imd <- subset(dat,
              select = c(
                Cs(
                  f.eid,
                  f.26433.0.0,
                  f.26422.0.0,
                  f.26425.0.0,
                  f.26416.0.0,
                  f.26434.0.0,
                  f.26414.0.0,
                  f.26431.0.0,
                  f.26421.0.0,
                  f.26412.0.0,
                  f.26419.0.0,
                  f.26413.0.0,
                  f.26430.0.0,
                  f.26420.0.0,
                  f.26415.0.0,
                  f.26432.0.0,
                  f.26423.0.0,
                  f.26411.0.0,
                  f.26428.0.0,
                  f.26418.0.0,
                  f.26410.0.0,
                  f.26427.0.0,
                  f.26426.0.0,
                  f.26417.0.0,
                  f.26424.0.0,
                  f.189.0.0
                )
              ))

colnames(imd) <- c(
  Cs(
    eid,
    IMD_services_Scotland,
    IMD_services_Wales,
    IMD_community_safety_Wales,
    IMD_crime_England,
    IMD_crime_Scotland,
    IMD_education_England,
    IMD_education_Scotland,
    IMD_education_Wales,
    IMD_employment_England,
    IMD_employment_Wales,
    IMD_health_England,
    IMD_health_Scotland,
    IMD_health_Wales,
    IMD_housing_England,
    IMD_housing_Scotland,
    IMD_housing_Wales,
    IMD_income_England,
    IMD_income_Scotland,
    IMD_income_Wales,
    IMD_total_England,
    IMD_total_Scotland,
    IMD_total_Wales,
    IMD_living_environ_England,
    IMD_phsyical_environ_Wales,
    townsend_deprivation_index
  )
)

saveRDS(imd, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_imd.rds") # save RDS to file  
```

```{r blood, results='hide'}

### blood biomarkers
blood <- subset(dat,
                select = c(
                  Cs(
                    f.eid,
                    f.30620.0.0,
                    f.30600.0.0,
                    f.30610.0.0,
                    f.30630.0.0,
                    f.30640.0.0,
                    f.30650.0.0,
                    f.30710.0.0,
                    f.30680.0.0,
                    f.30690.0.0,
                    f.30700.0.0,
                    f.30720.0.0,
                    f.30660.0.0,
                    f.30730.0.0,
                    f.30740.0.0,
                    f.30750.0.0,
                    f.30760.0.0,
                    f.30770.0.0,
                    f.30780.0.0,
                    f.30790.0.0,
                    f.30800.0.0,
                    f.30810.0.0,
                    f.30820.0.0,
                    f.30830.0.0,
                    f.30850.0.0,
                    f.30840.0.0,
                    f.30860.0.0,
                    f.30870.0.0,
                    f.30880.0.0,
                    f.30670.0.0,
                    f.30890.0.0
                  )
                ))

colnames(blood) <- c(
  Cs(
    eid,
    alanine_aminotransferase,
    albumin,
    alkaline_phosphatase,
    apolipoprotein_A,
    apolipoprotein_B,
    aspartate_aminotransferase,
    C_reactive_protein,
    calcium,
    cholesterol,
    creatinine,
    cystatin_C,
    direct_bilirubin,
    gamma_glutamyltransferase,
    glucose,
    hbA1c,
    HDL_cholesterol,
    IGF1,
    LDL_direct,
    lipoprotein_A,
    oestradiol,
    phosphate,
    rheumatoid_factor,
    SHBG,
    testosterone,
    total_bilirubin,
    total_protein,
    triglycerides,
    urate,
    urea,
    vitamin_D
  )
)


saveRDS(blood, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_blood_biomarkers.rds") # save RDS to file  
```

```{r blood_count, results='hide'}

### blood counts
blood_count <- subset(dat,
                      select = c(
                        Cs(
                          f.eid,
                          f.30160.0.0,
                          f.30220.0.0,
                          f.30150.0.0,
                          f.30210.0.0,
                          f.30030.0.0,
                          f.30020.0.0,
                          f.30300.0.0,
                          f.30290.0.0,
                          f.30280.0.0,
                          f.30120.0.0,
                          f.30180.0.0,
                          f.30050.0.0,
                          f.30060.0.0,
                          f.30040.0.0,
                          f.30100.0.0,
                          f.30260.0.0,
                          f.30270.0.0,
                          f.30130.0.0,
                          f.30190.0.0,
                          f.30140.0.0,
                          f.30200.0.0,
                          f.30170.0.0,
                          f.30230.0.0,
                          f.30080.0.0,
                          f.30090.0.0,
                          f.30110.0.0,
                          f.30010.0.0,
                          f.30070.0.0,
                          f.30250.0.0,
                          f.30240.0.0,
                          f.30000.0.0
                        )
                      ))

colnames(blood_count) <- c(
  Cs(
    eid,
    basophill_count,
    basophill_percentage,
    eosinophill_count,
    eosinophill_percentage,
    haematocrit_percentage,
    haemoglobin_concentration,
    high_light_scatter_reticulocyte_count,
    high_light_scatter_reticulocyte_percentage,
    immature_reticulocyte_fraction,
    lymphocyte_count,
    lymphocyte_percentage,
    mean_corpuscular_haemoglobin,
    mean_corpuscular_haemoglobin_concentration,
    mean_corpuscular_volume,
    mean_platelet_volume,
    mean_reticulocyte_volume,
    mean_sphered_cell_volume,
    monocyte_count,
    monocyte_percentage,
    neutrophill_count,
    neutrophill_percentage,
    nucleated_red_blood_cell_count,
    nucleated_red_blood_cell_percentage,
    platelet_count,
    platelet_crit,
    platelet_distribution_width,
    erythrocyte_count,
    erythrocyte_distribution_width,
    reticulocyte_count,
    reticulocyte_percentage,
    leukocyte_count
  )
)

saveRDS(blood_count, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_blood_count.rds") # save RDS to file  
```

```{r urine, results='hide'}

### urine biomarkers
urine <- subset(dat,
                select = c(
                  Cs(
                    f.eid,
                    f.30510.0.0,
                    f.30500.0.0,
                    f.30520.0.0,
                    f.30530.0.0
                  )
                ))

colnames(urine) <- c(
  Cs(
    eid,
    creatinine_urine,
    microalbumin_urine,
    potassium_urine,
    sodium_urine
  )
)

saveRDS(urine, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_urine.rds") # save RDS to file  
```

```{r enviro, results='hide'}

### physical environment
enviro <- subset(dat,
                 select = c(
                   Cs(
                     f.eid,
                     f.24014.0.0,
                     f.24012.0.0,
                     f.24010.0.0,
                     f.24016.0.0,
                     f.24017.0.0,
                     f.24018.0.0,
                     f.24003.0.0,
                     f.24004.0.0,
                     f.24019.0.0,
                     f.24005.0.0,
                     f.24007.0.0,
                     f.24006.0.0,
                     f.24008.0.0,
                     f.24015.0.0,
                     f.24013.0.0,
                     f.24011.0.0,
                     f.24009.0.0,
                     f.24020.0.0,
                     f.24021.0.0,
                     f.24022.0.0,
                     f.24506.0.0,
                     f.24507.0.0,
                     f.24500.0.0,
                     f.24503.0.0,
                     f.24501.0.0,
                     f.24504.0.0,
                     f.24502.0.0,
                     f.24505.0.0,
                     f.24508.0.0,
                     f.20118.0.0
                   )
                 ))

colnames(enviro) <- c(
  Cs(
    eid,
    close_to_major_road,
    inverse_distance_nearest_major_road,
    inverse_distance_nearest_road,
    NO2_2005,
    NO2_2006,
    NO2_2007,
    NO2_2010,
    NO_2010,
    PM10_2007,
    PM10_2010,
    PM2.5_absorbance_2010,
    PM2.5_2010,
    PM2.5_to_10_2010,
    road_length_sum_100m,
    traffic_load_major_roads,
    traffic_intensity_nearest_major_road,
    traffic_intensity_nearest_road,
    daytime_sound_average,
    evening_sound_average,
    night_sound_average,
    natural_environment_buffer_1000m,
    natural_environment_buffer_300m,
    greenspace_buffer_1000m,
    greenspace_buffer_300m,
    domestic_garden_buffer_1000m,
    domestic_garden_buffer_300m,
    water_buffer_1000m,
    water_buffer_300m,
    distance_to_coast,
    home_population_density
  )
)

saveRDS(enviro, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_environment.rds") # save RDS to file  
```

```{r merge, results='hide'}

#merge all exposure datasets into single, raw dataset
exposures <- list(
  elf,
  sle,
  soc,
  socio_dem,
  fam_health,
  med_cond,
  meds,
  male_repro,
  female_repro,
  mental_health,
  electronics,
  sleep,
  smok,
  alcohol,
  diet,
  sun,
  sex_hist,
  phys_act,
  vision,
  hearing,
  bp,
  a_stiff,
  anthro,
  spiro,
  bmd,
  imd,
  blood,
  blood_count,
  urine,
  enviro
)

# reduce all individuals datasets into single dataframe
reduce <- Reduce(function(x, y) merge(x = x, 
                                   y = y, 
                                   by = "eid",  
                                   all = TRUE), 
              exposures)

saveRDS(reduce, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_all_exposures.rds")
```

```{r new, results='hide'}

# There were variables missing in the first UKB dataset sent to us, which we had to request that they resend. These are those variables.

# Load new variables
new <- readRDS("/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/3. Second dataset from UKB/ukb43025.rds")

new <- subset(new,
              select = c(
                Cs(
                  f.eid,
                  f.20023.0.0,
                  f.4282.0.0,
                  f.20016.0.0,
                  f.20018.0.0,
                  f.399.0.1,
                  f.399.0.2,
                  f.26429.0.0,
                  f.24023.0.0,
                  f.24024.0.0,
                  f.23105.0.0,
                  f.1498.0.0,
                  f.2936.0.0,
                  f.3476.0.0,
                  f.3486.0.0,
                  f.3496.0.0,
                  f.4526.0.0,
                  f.4537.0.0,
                  f.4548.0.0,
                  f.4559.0.0,
                  f.4570.0.0,
                  f.4581.0.0,
                  f.3581.0.0,
                  f.2986.0.0,
                  f.22040.0.0
                )
              ))


colnames(new) <- c(
  Cs(
    eid,
    identify_matches_mean_time,
    maximum_digits_remembered,
    fluid_intelligence,
    prospective_memory,
    incorrect_matches_round1,
    incorrect_matches_round2,
    IMD_employment_Scotland,
    sound_average_16hr,
    sound_average_24hr,
    basal_metabolic_rate,
    coffee,
    resume_smoking_likelihood,
    difficulty_not_smoking_1day,
    stop_smoking_attempt,
    stop_smoking_desire,
    happiness,
    job_satisfaction,
    health_satisfaction,
    family_satisfaction,
    friends_satisfaction,
    financial_satisfaction,
    menopause_age,
    diabetes_insulin_1yr,
    MET_mins_sum
  )
)

saveRDS(new, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_new_vars.rds") # save RDS to file  
```

```{r re-merge, results='hide'}

#merge new vars with all other exposures into updated, raw dataset
combined <- merge(reduce, 
                  new, 
                  by = "eid", 
                  all = TRUE)

saveRDS(combined, file = "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Datasets/4. Categorized raw datasets/ukb_all_exposures_updated.rds")
```