```{r path}
path <- "."
```

```{r load}
# load analysis datasets
load("./data/ACM_final_analysis_datasets_jan_25_2023_all_data.RData")

# load NCD data
load("./data/NCD_all_subsets_jan_22_2023.RData")

# load interview baseline dx data
load("./data/baseline_dx_data_july_07_2022.RData")

# load variable categories
categories <- read.csv("./data/Argentieri UKB dataset data dictionary.csv")
categories$Category[which(categories$Variable == "gym")] <- "Physical activity"

# load XWAS function
source("./functions/XWAS_function.R") 

# set date for saving
date <- "dec_3_2024"
```

```{r merge_disease_data}

# merge ICD-10 data with ACM datasets
all_data <- lapply(all_data, function(x)
    as.data.frame(
        merge(x, 
              dat_NCD_all,
              by = "eid",
              all.x = TRUE,
              all.y = FALSE,
              sort = FALSE)
    )
)

all_data <- lapply(all_data, function(x)
    as.data.frame(
        merge(x, 
              dat_dx,
              by = "eid",
              all.x = TRUE,
              all.y = FALSE,             
              sort = FALSE)
    )
)

```

```{r exposures}

library(survival)
library(mice)
library(Hmisc)
library(pbapply)
library(data.table)

### Setting exposures -------------------------------------------------------------------

# create vector of exposure names
exposures <- as.vector(colnames(all_data[[1]]))

# make list of variables in dataset to exclude from analysis as exposures (including covariates in model)
exclude <- c(
  Cs(
    eid, # participant ID
    hazard, # outcome
    ACM_event_indicator, # outcome
    ACM_survival_time, # outcome
    birth_year, # used for creation of birth cohort strata
    recruitment_date, # recruitment metric only
    recruitment_age, # covariate/outcome
    recruitment_centre, # covariate
    education_years, # covariate
    ethnicity, # covariate
    sex, # covariate
    alcohol_freq_old, # only used to create NA for alcohol_freq
    alcohol_status_old, # only used to create NA for alcohol_freq
    alcohol_status, # only used to create NA for alcohol_freq
    sleep_hours, # old var before normalization
    education_college, # redundant to covariate
    education_A_levels, # redundant to covariate
    education_O_levels, # redundant to covariate
    education_CSEs, # redundant to covariate
    education_NVQ, # redundant to covariate
    education_other_professional, # redundant to covariate
    education_none, # redundant to covariate
    
    partial_fiber_score,
    skin_color,
    hair_color,
    cereal,
    bread,
    never_eat_sugar,
    never_eat_eggs,
    never_eat_wheat,
    never_eat_dairy,
    dairy_milk,
    head_side_phone,
    psychiatrist_visit_mental_health,
    doctor_visit_mental_health,
    
    # remove for any XWAS after mortality analysis.
    # hshld_parents,
    # hshld_siblings,
    # mobile_phone_use,
    # mobile_phone_duration,
    # mobile_phone_2yrs,
    # relative_illness_injury_assault,
    # fast_driving,
    # hshld_vehicles,
    # facial_aging,
    # number_sex_partners,
    # sex_age_first,
    
    hot_drink_temp, # not interpretable
    cereal_type, # only used for determining fiber
    bread_type, # only used for determining fiber
    milk_type, # only used to code dairy milk intake
    coffee_type, # only used for determining fiber
    spread_type, # only used for determining fiber
    beef, # component of total red meat
    lamb, # component of total red meat
    pork, # component of total red meat
    cooked_veg, # component of total veg
    salad_or_raw_veg, # component of total veg
    fresh_fruit, # component of total fruit
    dried_fruit, # component of total fruit
    beer_monthly,
    beer_weekly,
    fortified_wine_monthly,
    fortified_wine_weekly,
    other_alcohol_monthly, 
    other_alcohol_weekly,
    red_wine_monthly,
    red_wine_weekly,
    spirits_monthly,
    spirits_weekly,
    white_wine_monthly,
    white_wine_weekly,
    
    LTPA_raw, # numeric version of LTPA variable
    OPA_raw, # numeric version of OPA variable
    sedentary_raw, # numeric version of sedentary variable
    TV_time, # component of sedentary variable
    computer_time, # component of sedentary variable
    driving_time, # component of sedentary variable
    heavy_DIY_4wks, # component of LTPA
    light_DIY_4wks, # component of LTPA
    other_exercise_4wks, # component of LTPA
    pleasure_walks_4wks, # component of LTPA
    strenuous_sports_4wks, # component of LTPA
    above_activity_recommendation, # non-summary
    above_activity_recommendation_incl_walk, # non-summary

    MET_mins_moderate_activty, # components of IPAQ
    MET_mins_vigorous_activty, # components of IPAQ
    MET_mins_walking, # components of IPAQ
    MET_mins_sum, # components of IPAQ
    days_activity_sum, # components of IPAQ
    mins_activity_sum, # components of IPAQ
    moderate_activity_over_10mins_days, # components of IPAQ
    vigorous_activity_over_10mins_days, # components of IPAQ
    walked_over_10mins_days, # components of IPAQ
    
    portable_gas_heat, # remove after crosstab QC
    solid_fuel_heat, # remove after crosstab QC
    open_fire_no_central_heat, # remove after crosstab QC
    hshld_grandparent, # remove after crosstab QC
    hshld_other_related, # not interpretable
    hshld_other_unrelated, # not interpretable
    pregnant # remove after crosstab QC
  )
)

# remove variables I don't want to test in XWAS as exposures
exposures <- exposures[exposures %nin% exclude]

# add in categories to sort
exposures <- as.data.frame(exposures) # create df from exposure list
summary <- merge(exposures,
                 categories,
                 by.x = "exposures",
                 by.y = "Variable",
                 all = F) # merge with categories
summary <- summary[order(summary$Category), ] # order exposures by category

## separate out non-exposome variables

# get row positions for non-exposome
non_exposome <- which(
    # categories of non-exposome vars
    summary$Category %in% 
        c("Blood biomarkers",
          "Blood count",
          "Cognitive function",
          "General health",
          "Medical conditions",
          "Physical measures",
          "Urine biomarkers",
          "Medications",
          "Family medical history") |
        # individual disability or illness vars and response levels
        summary$exposures %in% 
        c("blue_badge",
          "attendance_allowance",
          "usual_walking_pace",
          "disability_allowance",
          "unemployed_disability",
          "health_satisfaction",
          "self_illness_injury_assault",
          "MDD",
          "bipolar",
          "narcolepsy")
    )

# remove non-exposome variables
summary <- summary[-non_exposome, ]

# sex variables
sex_vars <- which(summary$Category %in% c("Female reproductive factors", "Male reproductive factors"))
male_vars <- which(summary$Category %in% c("Male reproductive factors"))
femmale_vars <- which(summary$Category %in% c("Female reproductive factors"))

# remove female variables
summary <- summary[-sex_vars, ]

# make final vector of exposures ordered by category
exposures <- as.vector(summary$exposures) 
```

```{r dict, eval=FALSE}
# load data dictionary
dict <- read.csv("./dictionaries/Argentieri UKB dataset data dictionary.csv")

# subset data dictionary to just variables used in imputation
dict <- dict[which(dict$Variable %in% exposures), ]

# subset columns
dict <- dict[c(1:3,5:7)]

# save 
write.csv(dict, 
          row.names = FALSE, 
          ".//dictionaries/exposome_data_dictionary_jan_25_2023.csv")

```

```{r data_prep}
library(caret)

# disc and rep sets
split_disc <- function(x){

  set.seed(2345) # set the seed to make partition reproducible
  train.rows <- createDataPartition(y = x$ACM_event_indicator, 
                                    p = 0.50, # 50% random subsample
                                    list = FALSE) # do not return data as list
  
  # subset the data
  dat_disc <- x[train.rows, ]
  return(dat_disc)
}

split_rep <- function(x){

  set.seed(2345) # set the seed to make partition reproducible
  train.rows <- createDataPartition(y = x$ACM_event_indicator, 
                                    p = 0.50, # 50% random subsample
                                    list = FALSE) # do not return data as list
  
  # subset the data
  dat_rep <- x[-train.rows, ]
  return(dat_rep)
}

disc <- lapply(all_data, split_disc)
rep <- lapply(all_data, split_rep)

### Survival variables -------------------------------------------------------------------

# create age at censoring variables for age-at-risk analysis - discovery
for(j in seq_along(disc)) {
    # divide survival time (days) by 365.25 to get time in years
    disc[[j]]$time <-
        as.numeric(disc[[j]]$ACM_survival_time / 365.25) # change to numeric

    # add time (years) to recruitment age to get censor age
    disc[[j]]$censor_age <-
        disc[[j]]$recruitment_age + disc[[j]]$time
}

# create age at censoring variables for age-at-risk analysis - replication
for(j in seq_along(rep)) {
    # divide survival time (days) by 365.25 to get time in years
    rep[[j]]$time <-
        as.numeric(rep[[j]]$ACM_survival_time / 365.25) # change to numeric

    # add time (years) to recruitment age to get censor age
    rep[[j]]$censor_age <-
        rep[[j]]$recruitment_age + rep[[j]]$time
}

# create age at censoring variables for age-at-risk analysis - all_datalication
for(j in seq_along(all_data)) {
    # divide survival time (days) by 365.25 to get time in years
    all_data[[j]]$time <- 
        as.numeric(all_data[[j]]$ACM_survival_time / 365.25) # change to numeric 
    
    # add time (years) to recruitment age to get censor age
    all_data[[j]]$censor_age <- 
        all_data[[j]]$recruitment_age + all_data[[j]]$time 
}

### Create 5-year birth cohorts -------------------------------------------------------------------

# function to calculate birth cohorts
split_birth_year <- function(x){
  x$birth_cohort <- ifelse(
    x$birth_year >= 1935 & x$birth_year < 1940,
    "1935-1940",
    ifelse(
      x$birth_year >= 1940 & x$birth_year < 1945,
      "1940-1945",
      ifelse(
        x$birth_year >= 1945 & x$birth_year < 1950,
        "1945-1950",
        ifelse(
          x$birth_year >= 1950 & x$birth_year < 1955,
          "1950-1955",
          ifelse(
            x$birth_year >= 1955 & x$birth_year < 1960,
            "1955-1960",
            ifelse(
              x$birth_year >= 1960 & x$birth_year < 1965,
              "1960-1965",
              ifelse(
                x$birth_year >= 1965 & x$birth_year <= 1970, 
                "1965-1970", 
                NA
              )
            )
          )
        )
      )
    )
  )
  
  x$birth_cohort <- as.factor(x$birth_cohort)
  return(x)
}

# execute function across imputed datasets to create 5-year age bands
disc <- lapply(disc, split_birth_year)
rep <- lapply(rep, split_birth_year)
all_data <- lapply(all_data, split_birth_year)

### Ordinal contrasts -------------------------------------------------------------------

# overriding default polynomial contrasts to only return linear contrasts
set_contrasts <- function(x) {

  # find ordered variables
  ord <- sapply(x, is.ordered)

  # set contrasts to only linear
  for (k in seq(ncol(x[ord]))) {
    contrasts(x[ord][[k]], how.many = 1) <- contr.poly(nlevels(x[ord][[k]]))
  }

  return(x)

}

# run in datasets
disc <- lapply(disc, set_contrasts)
rep <- lapply(rep, set_contrasts)
all_data <- lapply(all_data, set_contrasts)

```

``` {r prev_disease}

# function to code baseline disease indicator - no blood measures
identify_prev_disease <- function(x) {
  
    # identify hospital inpatient ICD-10 diagnosis dates <= to recruitment date
    baseline_colon <- which(x$colon_cancer_censor_date <= x$recruitment_date)
    baseline_lung <- which(x$lung_cancer_censor_date <= x$recruitment_date)
    baseline_eso <- which(x$eso_cancer_censor_date <= x$recruitment_date)
    baseline_liver_cancer <- which(x$liver_cancer_censor_date <= x$recruitment_date)
    baseline_pancreatic <- which(x$pancreatic_cancer_censor_date <= x$recruitment_date)
    baseline_brain <- which(x$brain_cancer_censor_date <= x$recruitment_date)
    baseline_leukemia <- which(x$leukemia_censor_date <= x$recruitment_date)
    baseline_lymphoma <- which(x$lymphoma_censor_date <= x$recruitment_date)
    baseline_breast <- which(x$breast_cancer_censor_date <= x$recruitment_date)
    baseline_ovarian <- which(x$ovarian_cancer_censor_date <= x$recruitment_date)
    baseline_prostate <- which(x$prostate_cancer_censor_date <= x$recruitment_date)
    baseline_diabetes <- which(x$diabetes_censor_date <= x$recruitment_date)
    baseline_CVD <- which(x$CVD_censor_date <= x$recruitment_date)
    baseline_cerebro <- which(x$cerebro_cancer_censor_date <= x$recruitment_date)
    baseline_COPD <- which(x$COPD_censor_date <= x$recruitment_date)
    baseline_liver <- which(x$liver_censor_date <= x$recruitment_date)
    baseline_kidney <- which(x$kidney_censor_date <= x$recruitment_date)
    baseline_all_dementia <- which(x$all_dementia_censor_date <= x$recruitment_date)
    baseline_vasc_dementia <- which(x$vasc_dementia_censor_date <= x$recruitment_date)
    baseline_alzheimers <- which(x$alzheimers_censor_date <= x$recruitment_date)
    baseline_parkinsons <- which(x$parkinsons_censor_date <= x$recruitment_date)
    baseline_rheumatoid <- which(x$rheumatoid_censor_date <= x$recruitment_date)
    baseline_macular <- which(x$macular_censor_date <= x$recruitment_date)
    baseline_osteoporosis <- which(x$osteoporosis_censor_date <= x$recruitment_date)
    baseline_osteoarthritis <- which(x$osteoarthritis_censor_date <= x$recruitment_date)
    
    # creating empty health indicator for baseline disease
    x$baseline_disease_indicator <- NA
    
    # hospital inpatient ICD-10 code exclusions
    x$baseline_disease_indicator[baseline_colon] <- 1
    x$baseline_disease_indicator[baseline_lung] <- 1
    x$baseline_disease_indicator[baseline_eso] <- 1
    x$baseline_disease_indicator[baseline_liver_cancer] <- 1
    x$baseline_disease_indicator[baseline_pancreatic] <- 1
    x$baseline_disease_indicator[baseline_brain] <- 1
    x$baseline_disease_indicator[baseline_leukemia] <- 1
    x$baseline_disease_indicator[baseline_lymphoma] <- 1
    x$baseline_disease_indicator[baseline_breast] <- 1
    x$baseline_disease_indicator[baseline_ovarian] <- 1
    x$baseline_disease_indicator[baseline_prostate] <- 1
    x$baseline_disease_indicator[baseline_diabetes] <- 1
    x$baseline_disease_indicator[baseline_CVD] <- 1
    x$baseline_disease_indicator[baseline_cerebro] <- 1
    x$baseline_disease_indicator[baseline_COPD] <- 1
    x$baseline_disease_indicator[baseline_liver] <- 1
    x$baseline_disease_indicator[baseline_kidney] <- 1
    x$baseline_disease_indicator[baseline_all_dementia] <- 1
    x$baseline_disease_indicator[baseline_vasc_dementia] <- 1
    x$baseline_disease_indicator[baseline_alzheimers] <- 1
    x$baseline_disease_indicator[baseline_parkinsons] <- 1
    x$baseline_disease_indicator[baseline_rheumatoid] <- 1
    x$baseline_disease_indicator[baseline_macular] <- 1
    x$baseline_disease_indicator[baseline_osteoporosis] <- 1
    x$baseline_disease_indicator[baseline_osteoarthritis] <- 1
    
    # baseline verbal interview dx exclusions
    x$baseline_disease_indicator[which(x$colon_cancer_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$lung_cancer_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$eso_cancer_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$liver_cancer_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$pancreatic_cancer_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$brain_cancer_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$leukemia_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$lymphoma_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$breast_cancer_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$ovarian_cancer_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$prostate_cancer_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$diabetes_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$CVD_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$cerebro_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$COPD_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$liver_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$kidney_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$all_dementia_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$vasc_dementia_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$alzheimers_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$parkinsons_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$rheumatoid_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$macular_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$osteoporosis_baseline_dx == 1)] <- 1
    x$baseline_disease_indicator[which(x$osteoarthritis_baseline_dx == 1)] <- 1
    
    # baseline self-report questionnaire exclusions
    x$baseline_disease_indicator[which(x$heart_attack_diagnosis == "Yes")] <- 1
    x$baseline_disease_indicator[which(x$angina_diagnosis == "Yes")] <- 1
    x$baseline_disease_indicator[which(x$stroke_diagnosis == "Yes")] <- 1
    x$baseline_disease_indicator[which(x$bronchitis_emphysema_diagnosis == "Yes")] <- 1
    x$baseline_disease_indicator[which(x$cancer_diagnosis == "Yes")] <- 1
    x$baseline_disease_indicator[which(x$number_cancers >= 1)] <- 1
    x$baseline_disease_indicator[which(x$diabetes_diagnosis == "Yes")] <- 1
    x$baseline_disease_indicator[which(x$insulin == "Yes")] <- 1
    x$baseline_disease_indicator[which(x$overall_health == "Poor")] <- 1
    
    ### risk factors / intermediates
    x$baseline_disease_indicator[which(x$blood_pressure_meds == "Yes")] <- 1
    x$baseline_disease_indicator[which(x$high_blood_pressure_diagnosis == "Yes")] <- 1
    x$baseline_disease_indicator[which(x$cholesterol_meds == "Yes")] <- 1

    baseline_hypertension <- which(x$hypertension_censor_date <= x$recruitment_date)
    baseline_dyslipidemia <- which(x$dyslipidemia_censor_date <= x$recruitment_date)
    baseline_obesity <- which(x$obesity_censor_date <= x$recruitment_date)

    x$baseline_disease_indicator[baseline_hypertension] <- 1
    x$baseline_disease_indicator[baseline_dyslipidemia] <- 1
    x$baseline_disease_indicator[baseline_obesity] <- 1

    x$baseline_disease_indicator[which(x$hypertension_baseline_dx == 1)] <- 1

    # code rest as 0
    x$baseline_disease_indicator[which(is.na(x$baseline_disease_indicator))] <- 0
    
    # make factor
    x$baseline_disease_indicator <- factor(x$baseline_disease_indicator)
    
    return(x)
}

# run function in each dataset
all_data <- lapply(all_data, identify_prev_disease)

# remove large objects to save memory
rm(
    dat_NCD_all,
    dat_dx
)
gc()
```

``` {r XWAS}

# set parameters
outcome <- "Surv(recruitment_age, censor_age, ACM_event_indicator)"
strata <- c(Cs(birth_cohort, sex))
covariates <- c(Cs(recruitment_centre, education_years, ethnicity))

library(parallel)
# set cores for parallel computation
cores <- detectCores(logical = FALSE) - 1
cores <- 2

source("./functions/XWAS_function.R") 

XWAS_model <- XWAS(
    disc_data = disc,
    rep_data = rep,
    model_type = "coxph",
    outcome = outcome,
    strata = strata,
    covariates = covariates,
    exposures = exposures,
    extra.covar = "overall_health",
    extra.var = "alcohol_freq",
    categories = categories,
    replication = TRUE,
    multi_imputation = TRUE,
    scale = TRUE,
    p_adjust = "BH",
    cores = cores,
    interaction = FALSE
)

# df of results
XWAS_total <- XWAS_model$summary

# remove ".L" from exposure names for ordinal variables
XWAS_total$Exposure <- gsub(".L", "", XWAS_total$Exposure, fixed = TRUE)

# save
# filename = glue("./results/ACM_XWAS_results_{Sys.Date()}_all_sexes.RData"
# save(
#     XWAS_model,
#     XWAS_total,
#     file = filename
# )

library(glue)
filename <- glue("./results/ACM_XWAS_results_{Sys.Date()}_all_sexes_summary.RData")

save(
    XWAS_total,
    file = filename
)

```

``` {r sensitivity_prep}

load(glue("./results/ACM_XWAS_results_{Sys.Date()}_all_sexes_summary.RData"))

# create vector of exposures (only variables replicated in the main XWAS)
exposures <- XWAS_total[which(XWAS_total$FDR.rep < 0.05), ]
exposures <- unique(exposures$Variable)

# add in categories to sort
exposures <- as.data.frame(exposures) # create df from exposure list
summary <- merge(exposures,
                 categories,
                 by.x = "exposures",
                 by.y = "Variable",
                 all = F) # merge with categories
summary <- summary[order(summary$Category), ] # order exposures by category

# get vector of just exposure names
exposures <- as.vector(summary$exposures) # make final vector of exposures ordered by category

```

``` {r XWAS_indicator_covar, eval=FALSE}

## add baseline disease indicator as fixed covariate
### test in full dataset without replication

# set parameters 
outcome <- "Surv(recruitment_age, censor_age, ACM_event_indicator)"
strata <- c(Cs(birth_cohort, sex))
covariates <- c(Cs(recruitment_centre, education_years, ethnicity, baseline_disease_indicator))
cores <- 2

# run XWAS
XWAS_model8 <- XWAS(
    data = all_data,
    model_type = "coxph",
    outcome = outcome,
    strata = strata,
    covariates = covariates,
    exposures = exposures,
    categories = categories,
    replication = FALSE,
    multi_imputation = TRUE,
    scale = TRUE,
    p_adjust = "BH",
    cores = cores,
    interaction = FALSE
)

# df of results
XWAS_total <- XWAS_model8$summary

# remove ".L" from exposure names for ordinal variables
XWAS_total$Exposure <- gsub(".L", "", XWAS_total$Exposure, fixed = TRUE)

# save
save(
    XWAS_model8,
    XWAS_total,
    file = paste0(paste0(paste0(path, "/results/ACM_XWAS_results_"), date), "_indicator_covar_all_data.RData")
)

save(
    XWAS_total,
    file = paste0(paste0(paste0(path, "/results/ACM_XWAS_results_"), date), "_indicator_covar_all_data_summary.RData")
)

```

``` {r XWAS_interaction}

# add interaction term for baseline indicator
## use all data

# set parameters
outcome <- "Surv(recruitment_age, censor_age, ACM_event_indicator)"
strata <- c(Cs(birth_cohort, sex))
covariates <- c(Cs(recruitment_centre, education_years, ethnicity))
int.var <- "baseline_disease_indicator"
cores <- 2

## interactions with baseline indicator - intermediates but no undiagnosed blood diabetes
# run XWAS
XWAS_model9 <- XWAS(
    data = all_data,
    model_type = "coxph",
    outcome = outcome,
    strata = strata,
    covariates = covariates,
    exposures = exposures,
    categories = categories,
    replication = FALSE, 
    multi_imputation = TRUE,
    scale = TRUE,
    p_adjust = "BH",
    cores = cores,
    interaction = TRUE,
    int.var = int.var,
    int.type = "*",
    int.option = "both"
    )

# df of results
XWAS_total <- XWAS_model9$summary

# remove ".L" from exposure names for ordinal variables
XWAS_total$Exposure <- gsub(".L", "", XWAS_total$Exposure, fixed = TRUE)

# save
# save(
#     XWAS_model9,
#     XWAS_total,
#     file = paste0(paste0(paste0(path, "/results/ACM_XWAS_sensitivity_results_"), date), "_interactions_intermediates_no_blood_all_data.RData")
# )

filename <- glue("./results/ACM_XWAS_sensitivity_results_{Sys.Date()}_interactions_intermediates_no_blood_all_data_summary.RData")
save(
    XWAS_total,
    file = filename
)

```

``` {r XWAS_exclusion}

# exclude those with baseline indicator
## use all data

# subset to those without disease at baseline
all_data_excl <- lapply(all_data, function(x) {
    x <- x[which(x$baseline_disease_indicator == 0), ]
    return(x)
}
)

# set parameters
outcome <- "Surv(recruitment_age, censor_age, ACM_event_indicator)"
strata <- c(Cs(birth_cohort, sex))
covariates <- c(Cs(recruitment_centre, education_years, ethnicity))

# run XWAS
XWAS_model10 <- XWAS(
    data = all_data_excl,
    model_type = "coxph",
    outcome = outcome,
    strata = strata,
    covariates = covariates,
    exposures = exposures,
    categories = categories,
    replication = FALSE,
    multi_imputation = TRUE,
    scale = TRUE,
    p_adjust = "BH",
    cores = cores,
    interaction = FALSE
)

# df of results
XWAS_total <- XWAS_model10$summary

# remove ".L" from exposure names for ordinal variables
XWAS_total$Exposure <- gsub(".L", "", XWAS_total$Exposure, fixed = TRUE)

# save(
#     XWAS_model10,
#     XWAS_total,
#     file = paste0(paste0(paste0(path, "/results/ACM_XWAS_sensitivity_results_"), date), "_exclusions_intermediates_nb_all_data.RData")
# )
filename <- glue("./results/ACM_XWAS_sensitivity_results_{Sys.Date()}_exclusions_intermediates_nb_all_data_summary.RData")
save(
    XWAS_total,
    file = filename
)


```

``` {r XWAS_exclusion_time, eval=FALSE}

# exclude those with survival time < 2 years 
## use all data

# subset to those without disease at baseline
all_data_excl <- lapply(all_data, function(x) {
    x <- x[which(x$ACM_survival_time >= 730.5), ]
    return(x)
}
)

# set exposures
load(paste0(path, "/results/ACM_XWAS_results_sept_07_2022_all_sexes_summary.RData"))
exposures <- XWAS_total[which(XWAS_total$FDR.rep < 0.05), ]
exposures <- unique(exposures$Variable)

# set parameters
outcome <- "Surv(recruitment_age, censor_age, ACM_event_indicator)"
strata <- c(Cs(birth_cohort, sex))
covariates <- c(Cs(recruitment_centre, education_years, ethnicity))
cores <- 2

# run XWAS
XWAS_model11 <- XWAS(
    data = all_data_excl,
    model_type = "coxph",
    outcome = outcome,
    strata = strata,
    covariates = covariates,
    exposures = exposures,
    categories = categories,
    replication = FALSE,
    multi_imputation = TRUE,
    scale = TRUE,
    p_adjust = "BH",
    cores = cores,
    interaction = FALSE
)

# df of results
XWAS_total <- XWAS_model11$summary

# remove ".L" from exposure names for ordinal variables
XWAS_total$Exposure <- gsub(".L", "", XWAS_total$Exposure, fixed = TRUE)

save(
    XWAS_model11,
    XWAS_total,
    file = paste0(paste0(paste0(path, "/results/ACM_XWAS_sensitivity_results_"), date), "_exclusions_time_all_data.RData")
)

save(
    XWAS_total,
    file = paste0(paste0(paste0(path, "/results/ACM_XWAS_sensitivity_results_"), date), "_exclusions_time_all_data_summary.RData")
)


sig_vars <- unique(XWAS_total$Variable[which(XWAS_total$p.value < 0.05)])
non_sig_vars <- unique(XWAS_total$Variable[which(XWAS_total$p.value > 0.05)])

sig_vars <- unique(XWAS_total$Variable[which(XWAS_total$FDR < 0.05)])
non_sig_vars <- unique(XWAS_total$Variable[which(XWAS_total$FDR > 0.05)])

non_sig_vars <- non_sig_vars[non_sig_vars %nin% sig_vars]


```

``` {r XWAS_exclusion_time2}

# exclude those with survival time < 4 years 
## use all data

time <- 365.25*4

# subset to those without disease at baseline
all_data_excl <- lapply(all_data, function(x) {
    x <- x[which(x$ACM_survival_time >= time), ]
    return(x)
}
)

# set exposures
load("./results/ACM_XWAS_results_2024-12-03_all_sexes_summary.RData")
exposures <- XWAS_total[which(XWAS_total$FDR.rep < 0.05), ]
exposures <- unique(exposures$Variable)

# set parameters
outcome <- "Surv(recruitment_age, censor_age, ACM_event_indicator)"
strata <- c(Cs(birth_cohort, sex))
covariates <- c(Cs(recruitment_centre, education_years, ethnicity))
cores <- 2

# run XWAS
XWAS_model12 <- XWAS(
    data = all_data_excl,
    model_type = "coxph",
    outcome = outcome,
    strata = strata,
    covariates = covariates,
    exposures = exposures,
    categories = categories,
    replication = FALSE,
    multi_imputation = TRUE,
    scale = TRUE,
    p_adjust = "BH",
    cores = cores,
    interaction = FALSE
)

# df of results
XWAS_total <- XWAS_model12$summary

# remove ".L" from exposure names for ordinal variables
XWAS_total$Exposure <- gsub(".L", "", XWAS_total$Exposure, fixed = TRUE)

# save(
#     XWAS_model12,
#     XWAS_total,
#     file = paste0(paste0(paste0(path, "/results/ACM_XWAS_sensitivity_results_"), date), "_exclusions_time_all_data_4yrs.RData")
# )

filename <- glue("./results/ACM_XWAS_sensitivity_results_{Sys.Date()}_exclusions_time_all_data_summary_4yrs.RData")
save(
    XWAS_total,
    file = filename
)


sig_vars <- unique(XWAS_total$Variable[which(XWAS_total$p.value < 0.05)])
non_sig_vars <- unique(XWAS_total$Variable[which(XWAS_total$p.value > 0.05)])

# sig_vars <- unique(XWAS_total$Variable[which(XWAS_total$FDR < 0.05)])
# non_sig_vars <- unique(XWAS_total$Variable[which(XWAS_total$FDR > 0.05)])

non_sig_vars <- non_sig_vars[non_sig_vars %nin% sig_vars]
non_sig_vars

```

```{r comparison_plot_time_excl, eval=FALSE}
library(plotly)
library(ggplot2)
library(htmlwidgets)
library(ggpubr)
library(ggrepel)

options(scipen = 999)

# load color palette
load(paste0(path,"/files/color_palette.RData"))

# load full results
load("./results/ACM_XWAS_results_dec_11_2022_all_sexes_summary.RData")

# rename
full_XWAS_total <- XWAS_total

# load exclusion results
load(paste0(path, "/results/ACM_XWAS_sensitivity_results_dec_11_2022_exclusions_time_all_data_summary.RData"))

# limit to sig_vars
full_XWAS_total <- full_XWAS_total[which(full_XWAS_total$Variable %in% XWAS_total$Variable), ]

# merge
plots_df <- merge(full_XWAS_total, 
                  XWAS_total,
                  by = "Exposure",
                  all = TRUE,
                  sort = FALSE)

plots_df$label <- plots_df$Variable.x

# plots_df$col2 <- ""
# plots_df$col2 <- ifelse(plots_df$label %in% nominal_vars,
#                         "red",
#                         "blue")
# plots_df$col2[which(plots_df$label %nin% combined)] <- ""


# merge categories for plot
plots_df$Category <- ifelse(!is.na(plots_df$Category.x),
                            plots_df$Category.x,
                            plots_df$Category.y)

color_map$color[which(color_map$sequence == "Stressful life events")] <- 
    color_map$color[which(color_map$sequence == "General health")]

color_map$sequence[which(color_map$sequence == "Medications")] <- "Supplements"
color_map$color[which(color_map$sequence == "Supplements")] <- 
    color_map$color[which(color_map$sequence == "Urine biomarkers")]

# merge color map with plots df
plots_df <- merge(plots_df, 
                  color_map, 
                  by.x = "Category",
                  by.y = "sequence", 
                  all = F)

# # add in grey/black color for non-significant points
# plots_df$color <- ifelse((plots_df$FDR.rep > 0.05 |
#                              is.na(plots_df$FDR.rep)) &
#                              (plots_df$FDR > 0.05 |
#                              is.na(plots_df$FDR)),
#                          "#4c4c4c",
#                          plots_df$color)

# # add in red color for points only significant in full cohort
# plots_df$color[which(plots_df$FDR.rep.x < 0.05 &
#                          (plots_df$FDR.rep.y > 0.05 |
#                               is.na(plots_df$FDR.rep.y)))] <- "#cc0610"
# 
# # add in "non-significant" category for plots
# plots_df$Category <- ifelse(plots_df$color == "#4c4c4c",
#                             "* Non-replicated",
#                             plots_df$Category)

# # add in "non-significant" category for plots
# plots_df$Category <- ifelse(plots_df$color == "#cc0610",
#                             "* Only replicated in full cohort",
#                             plots_df$Category)

# names(plots_df)[names(plots_df) == "Hazard.Ratio.x"] <- "Hazard.Ratio.Full.Cohort"
# names(plots_df)[names(plots_df) == "Hazard.Ratio.y"] <- "Hazard.Ratio.Healthy.Subset"

names(plots_df)[names(plots_df) == "Beta.x"] <- "Beta.Full.Cohort"
names(plots_df)[names(plots_df) == "Beta.y"] <- "Beta.Time.Subset"

# re-order so that black dots are behind colored dots
plots_df <- plots_df[order(plots_df$Category), ]

# correlation coefficient between men and women
# hr_corr <- cor(plots_df$Hazard.Ratio.Full.Cohort, 
#                plots_df$Hazard.Ratio.Healthy.Subset)

beta_corr <- cor(plots_df$Beta.Full.Cohort, 
               plots_df$Beta.Time.Subset)

# regression line for plot
# hazard.ratio.lm <- lm(Hazard.Ratio.Healthy.Subset ~ Hazard.Ratio.Full.Cohort, plots_df)

beta.lm <- lm(Beta.Time.Subset ~ Beta.Full.Cohort, plots_df)

# ggplot
comp_plot <- 
    ggplot(
        plots_df,
        aes(x = Beta.Full.Cohort, 
            y = Beta.Time.Subset, 
            label = Exposure
        )) + 
    geom_point(
        aes(color = Category),
        size = 3) + 
    scale_color_manual(values = unique(plots_df$color)) +
    # ggtitle("Comparison of Mortality XWAS Hazard Ratios in the UK Biobank - Full Cohort vs. Healthy Subset") +
    labs(x = "Mortality XWAS beta - full sample",
         y = "Mortality beta - participants with survival time \u2265 2 years") +
    theme_classic(base_size = 18) +
    # theme(legend.position = "none") +
    geom_hline(yintercept = 0, 
               color = "gray", 
               linetype = "dashed") + 
    geom_vline(xintercept = 0, 
               color = "gray", 
               linetype = "dashed") +
    # breaks have function to only use integers and no decimals for axis values
    # scale_x_continuous(limits = c(-1,1.1)) +
    # scale_y_continuous(limits = c(-1,1.1)) +
    scale_x_continuous(breaks = function(x) seq(ceiling(x[1]), floor(x[2]), by = 1)) +
    scale_y_continuous(breaks = function(x) seq(ceiling(x[1]), floor(x[2]), by = 1)) +
    # show correlation coefficient between hazard ratios and p-value for correlation
    stat_cor(method = "pearson",
             label.x.npc = "center",
             label.y.npc = "bottom",
             p.digits = 5,
             size = 6) +
    # show regression line between hazard ratios
    geom_abline(slope = coef(beta.lm)[[2]], 
                intercept = coef(beta.lm)[[1]],
                color = "red")


ggsave(comp_plot, 
       filename = paste0(path, "/output/comparing_betas_time_excl_nov_04_2022_all_data.png"), width = 15, height = 10)

# text styling for plotly
t <- list(family = "sans-serif",
          size = 18,
          color = 'black')

# plotly interactive plot
fig <- ggplotly(comp_plot, 
                tooltip = c("x", 
                            "y", 
                            "label")) %>% 
  layout(title = "Comparison of Mortality XWAS Hazard Ratios in the Biobank - Full Cohort vs. Those with Survival Time \u2265 2 Years", 
         font = t)

hide_legend(fig) 

# save
saveWidget(fig, 
           file = paste0(path, "/output/html/comparing_betas_non_sig_sept_08_2022_intermediates_no_blood_all_data.html"))
```

```{r comparison_plot_time_excl2, eval=FALSE}
library(plotly)
library(ggplot2)
library(htmlwidgets)
library(ggpubr)
library(ggrepel)


# load color palette
load("./files/color_palette.RData")
# load full results
load("./results/ACM_XWAS_results_2024-12-03_all_sexes_summary.RData")

# rename
full_XWAS_total <- XWAS_total

# load exclusion results
load("./results/ACM_XWAS_sensitivity_results_2024-12-03_exclusions_time_all_data_summary_4yrs.RData")

# limit to sig_vars
full_XWAS_total <- full_XWAS_total[which(full_XWAS_total$Variable %in% XWAS_total$Variable), ]

# merge
plots_df <- merge(full_XWAS_total, 
                  XWAS_total,
                  by = "Exposure",
                  all = TRUE,
                  sort = FALSE)

plots_df$label <- plots_df$Variable.x

# plots_df$col2 <- ""
# plots_df$col2 <- ifelse(plots_df$label %in% nominal_vars,
#                         "red",
#                         "blue")
# plots_df$col2[which(plots_df$label %nin% combined)] <- ""


# merge categories for plot
plots_df$Category <- ifelse(!is.na(plots_df$Category.x),
                            plots_df$Category.x,
                            plots_df$Category.y)

color_map$color[which(color_map$sequence == "Stressful life events")] <- 
    color_map$color[which(color_map$sequence == "General health")]

color_map$sequence[which(color_map$sequence == "Medications")] <- "Supplements"
color_map$color[which(color_map$sequence == "Supplements")] <- 
    color_map$color[which(color_map$sequence == "Urine biomarkers")]

# merge color map with plots df
plots_df <- merge(plots_df, 
                  color_map, 
                  by.x = "Category",
                  by.y = "sequence", 
                  all = F)

# # add in grey/black color for non-significant points
# plots_df$color <- ifelse((plots_df$FDR.rep > 0.05 |
#                              is.na(plots_df$FDR.rep)) &
#                              (plots_df$FDR > 0.05 |
#                              is.na(plots_df$FDR)),
#                          "#4c4c4c",
#                          plots_df$color)

# # add in red color for points only significant in full cohort
# plots_df$color[which(plots_df$FDR.rep.x < 0.05 &
#                          (plots_df$FDR.rep.y > 0.05 |
#                               is.na(plots_df$FDR.rep.y)))] <- "#cc0610"
# 
# # add in "non-significant" category for plots
# plots_df$Category <- ifelse(plots_df$color == "#4c4c4c",
#                             "* Non-replicated",
#                             plots_df$Category)

# # add in "non-significant" category for plots
# plots_df$Category <- ifelse(plots_df$color == "#cc0610",
#                             "* Only replicated in full cohort",
#                             plots_df$Category)

# names(plots_df)[names(plots_df) == "Hazard.Ratio.x"] <- "Hazard.Ratio.Full.Cohort"
# names(plots_df)[names(plots_df) == "Hazard.Ratio.y"] <- "Hazard.Ratio.Healthy.Subset"

names(plots_df)[names(plots_df) == "Beta.x"] <- "Beta.Full.Cohort"
names(plots_df)[names(plots_df) == "Beta.y"] <- "Beta.Time.Subset"

# re-order so that black dots are behind colored dots
plots_df <- plots_df[order(plots_df$Category), ]

# correlation coefficient between men and women
# hr_corr <- cor(plots_df$Hazard.Ratio.Full.Cohort, 
#                plots_df$Hazard.Ratio.Healthy.Subset)

beta_corr <- cor(plots_df$Beta.Full.Cohort, 
               plots_df$Beta.Time.Subset)

# regression line for plot
# hazard.ratio.lm <- lm(Hazard.Ratio.Healthy.Subset ~ Hazard.Ratio.Full.Cohort, plots_df)

beta.lm <- lm(Beta.Time.Subset ~ Beta.Full.Cohort, plots_df)

options(scipen = 0)

# Calculate Pearson correlation and p-value
cor_test <- cor.test(plots_df$Beta.Full.Cohort, plots_df$Beta.Time.Subset, method = "pearson")
cor_value <- round(cor_test$estimate, 2) # Rounded correlation coefficient
p_value <- formatC(cor_test$p.value, format = "e", digits = 2) # P-value in scientific notation


# ggplot
comp_plot <- 
  ggplot(
    plots_df,
    aes(x = Beta.Full.Cohort, 
        y = Beta.Time.Subset, 
        label = Exposure
    )) + 
  geom_point(
    aes(color = Category),
    size = 3) + 
  annotate(
    "text", 
    x = mean(range(plots_df$Beta.Full.Cohort)) + 0.1, # Center x-position
    y = min(plots_df$Beta.Time.Subset) + 0.2,        # Bottom y-position
    label = paste0("r = ", cor_value, "\np = ", p_value),
    size = 3,
    hjust = 0
  ) +
  scale_color_manual(values = unique(plots_df$color)) +
  # ggtitle("Comparison of Mortality XWAS Hazard Ratios in the UK Biobank - Full Cohort vs. Healthy Subset") +
  labs(x = "Mortality XWAS beta - full sample",
       y = "Mortality XWAS beta - participants with survival time \u2265 4 years") +
  theme_classic(base_size = 10) +
  theme(legend.key.size = unit(0, 'lines')) +
  # theme(legend.position = "none") +
  geom_hline(yintercept = 0, 
             color = "gray", 
             linetype = "dashed") + 
  geom_vline(xintercept = 0, 
             color = "gray", 
             linetype = "dashed") +
  # breaks have function to only use integers and no decimals for axis values
  # scale_x_continuous(limits = c(-1,1.1)) +
  # scale_y_continuous(limits = c(-1,1.1)) +
  scale_x_continuous(breaks = function(x) seq(ceiling(x[1]), floor(x[2]), by = 1)) +
  scale_y_continuous(breaks = function(x) seq(ceiling(x[1]), floor(x[2]), by = 1)) +
  # show regression line between hazard ratios
  geom_abline(slope = coef(beta.lm)[[2]], 
              intercept = coef(beta.lm)[[1]],
              color = "red")


# save
name = "./figures/Ext_Data_fig_2.jpg"
width_in_inches <- 16 * 0.393701
height_in_inches <- 13  * 0.393701
ggsave(comp_plot, filename = name, width = width_in_inches, height = height_in_inches, dpi=600)


# # text styling for plotly
# t <- list(family = "sans-serif",
#           size = 18,
#           color = 'black')
# 
# # plotly interactive plot
# fig <- ggplotly(comp_plot, 
#                 tooltip = c("x", 
#                             "y", 
#                             "label")) %>% 
#   layout(title = "Comparison of Mortality XWAS Hazard Ratios in the Biobank - Full Cohort vs. Those with Survival Time \u2265 4 Years", 
#          font = t)
# 
# hide_legend(fig) 
# 
# # save
# saveWidget(fig, 
#            file = paste0(path, "/output/comparing_betas_time_excl_feb_21_2023_all_data_4yrs.html"))
```

```{r exposures_men}

load(paste0(path, "/datasets/ACM_final_analysis_datasets_dec_10_2022_sex_data.RData"))

# create vector of exposure names
exposures <- as.vector(colnames(mult_disc[[1]]))

# make list of variables in dataset to exclude from analysis as exposures (including covariates in model)
exclude <- c(
  Cs(
    eid, # participant ID
    hazard, # outcome
    ACM_event_indicator, # outcome
    ACM_survival_time, # outcome
    birth_year, # used for creation of birth cohort strata
    recruitment_date, # recruitment metric only
    recruitment_age, # covariate/outcome
    recruitment_centre, # covariate
    education_years, # covariate
    ethnicity, # covariate
    sex, # covariate
    alcohol_freq_old, # only used to create NA for alcohol_freq
    alcohol_status_old, # only used to create NA for alcohol_freq
    alcohol_status, # only used to create NA for alcohol_freq
    sleep_hours, # old var before normalization
    education_college, # redundant to covariate
    education_A_levels, # redundant to covariate
    education_O_levels, # redundant to covariate
    education_CSEs, # redundant to covariate
    education_NVQ, # redundant to covariate
    education_other_professional, # redundant to covariate
    education_none, # redundant to covariate
    
    partial_fiber_score,
    skin_color,
    hair_color,
    cereal,
    bread,
    never_eat_sugar,
    never_eat_eggs,
    never_eat_wheat,
    never_eat_dairy,
    dairy_milk,
    head_side_phone,
    psychiatrist_visit_mental_health,
    doctor_visit_mental_health,
    
    hot_drink_temp, # not interpretable
    cereal_type, # only used for determining fiber
    bread_type, # only used for determining fiber
    milk_type, # only used to code dairy milk intake
    coffee_type, # only used for determining fiber
    spread_type, # only used for determining fiber
    beef, # component of total red meat
    lamb, # component of total red meat
    pork, # component of total red meat
    cooked_veg, # component of total veg
    salad_or_raw_veg, # component of total veg
    fresh_fruit, # component of total fruit
    dried_fruit, # component of total fruit
    beer_monthly,
    beer_weekly,
    fortified_wine_monthly,
    fortified_wine_weekly,
    other_alcohol_monthly, 
    other_alcohol_weekly,
    red_wine_monthly,
    red_wine_weekly,
    spirits_monthly,
    spirits_weekly,
    white_wine_monthly,
    white_wine_weekly,
    
    LTPA_raw, # numeric version of LTPA variable
    OPA_raw, # numeric version of OPA variable
    sedentary_raw, # numeric version of sedentary variable
    TV_time, # component of sedentary variable
    computer_time, # component of sedentary variable
    driving_time, # component of sedentary variable
    heavy_DIY_4wks, # component of LTPA
    light_DIY_4wks, # component of LTPA
    other_exercise_4wks, # component of LTPA
    pleasure_walks_4wks, # component of LTPA
    strenuous_sports_4wks, # component of LTPA
    above_activity_recommendation, # non-summary
    above_activity_recommendation_incl_walk, # non-summary

    MET_mins_moderate_activty, # components of IPAQ
    MET_mins_vigorous_activty, # components of IPAQ
    MET_mins_walking, # components of IPAQ
    MET_mins_sum, # components of IPAQ
    days_activity_sum, # components of IPAQ
    mins_activity_sum, # components of IPAQ
    moderate_activity_over_10mins_days, # components of IPAQ
    vigorous_activity_over_10mins_days, # components of IPAQ
    walked_over_10mins_days, # components of IPAQ
    
    portable_gas_heat, # remove after crosstab QC
    solid_fuel_heat, # remove after crosstab QC
    open_fire_no_central_heat, # remove after crosstab QC
    hshld_grandparent, # remove after crosstab QC
    hshld_other_related, # not interpretable
    hshld_other_unrelated, # not interpretable
    pregnant # remove after crosstab QC
  )
)

# remove variables I don't want to test in XWAS as exposures
exposures <- exposures[exposures %nin% exclude]

# add in categories to sort
exposures <- as.data.frame(exposures) # create df from exposure list
summary <- merge(exposures,
                 categories,
                 by.x = "exposures",
                 by.y = "Variable",
                 all = F) # merge with categories
summary <- summary[order(summary$Category), ] # order exposures by category

## separate out non-exposome variables

# get row positions for non-exposome
non_exposome <- which(
    # categories of non-exposome vars
    summary$Category %in% 
        c("Blood biomarkers",
          "Blood count",
          "Cognitive function",
          "General health",
          "Medical conditions",
          "Physical measures",
          "Urine biomarkers",
          "Medications",
          "Family medical history") |
        # individual disability or illness vars and response levels
        summary$exposures %in% 
        c("blue_badge",
          "attendance_allowance",
          "usual_walking_pace",
          "disability_allowance",
          "unemployed_disability",
          "health_satisfaction",
          "self_illness_injury_assault",
          "MDD",
          "bipolar",
          "narcolepsy")
    )

# remove non-exposome variables
summary <- summary[-non_exposome, ]

# female variables
female_vars <- which(summary$Category == "Female reproductive factors")

# remove female variables
summary <- summary[-female_vars, ]

# make final vector of exposures ordered by category
exposures <- as.vector(summary$exposures) 
```

```{r data_prep_men}

# create age at censoring variables for age-at-risk analysis - discovery
for(j in seq_along(mult_disc)) {
  # divide survival time (days) by 365.25 to get time in years
  mult_disc[[j]]$time <- 
    as.numeric(mult_disc[[j]]$ACM_survival_time / 365.25) # change to numeric 
  
  # add time (years) to recruitment age to get censor age
  mult_disc[[j]]$censor_age <-
    mult_disc[[j]]$recruitment_age + mult_disc[[j]]$time 
}

# create age at censoring variables for age-at-risk analysis - replication
for(j in seq_along(mult_rep)) {
  # divide survival time (days) by 365.25 to get time in years
  mult_rep[[j]]$time <- 
    as.numeric(mult_rep[[j]]$ACM_survival_time / 365.25) # change to numeric 
  
  # add time (years) to recruitment age to get censor age
  mult_rep[[j]]$censor_age <- 
    mult_rep[[j]]$recruitment_age + mult_rep[[j]]$time 
}

# function to calculate birth cohorts
split_birth_year <- function(x){
  x$birth_cohort <- ifelse(
    x$birth_year >= 1935 & x$birth_year < 1940,
    "1935-1940",
    ifelse(
      x$birth_year >= 1940 & x$birth_year < 1945,
      "1940-1945",
      ifelse(
        x$birth_year >= 1945 & x$birth_year < 1950,
        "1945-1950",
        ifelse(
          x$birth_year >= 1950 & x$birth_year < 1955,
          "1950-1955",
          ifelse(
            x$birth_year >= 1955 & x$birth_year < 1960,
            "1955-1960",
            ifelse(
              x$birth_year >= 1960 & x$birth_year < 1965,
              "1960-1965",
              ifelse(
                x$birth_year >= 1965 & x$birth_year <= 1970, 
                "1965-1970", 
                NA
              )
            )
          )
        )
      )
    )
  )
  
  x$birth_cohort <- as.factor(x$birth_cohort)
  return(x)
}

# execute function across imputed datasets to create 5-year age bands
mult_disc <- lapply(mult_disc, split_birth_year)
mult_rep <- lapply(mult_rep, split_birth_year)

# overriding default polynomial contrasts to only return linear contrasts
set_contrasts <- function(x) {
  
  # find ordered variables
  ord <- sapply(x, is.ordered)
  
  # set contrasts to only linear
  for (k in seq(ncol(x[ord]))) {
    contrasts(x[ord][[k]], how.many = 1) <- contr.poly(nlevels(x[ord][[k]]))
  }
  
  return(x)
  
}

# run in datasets
mult_disc <- lapply(mult_disc, set_contrasts)
mult_rep <- lapply(mult_rep, set_contrasts)
```

```{r XWAS_men}

# set parameters
outcome <- "Surv(recruitment_age, censor_age, ACM_event_indicator)"
strata <- c(Cs(birth_cohort, sex))
covariates <- c(Cs(recruitment_centre, education_years, ethnicity))
cores <- 2

# run XWAS
XWAS_model_men <- XWAS(
  disc_data = mult_disc,
  rep_data = mult_rep,
  model_type = "coxph",
  outcome = outcome,
  strata = strata,
  covariates = covariates,
  exposures = exposures,
  extra.covar = "overall_health",
  extra.var = "alcohol_freq",
  categories = categories,
  replication = TRUE,
  multi_imputation = TRUE,
  scale = TRUE,
  p_adjust = "BH",
  cores = cores,
  interaction = FALSE
)

# df of results
XWAS_total <- XWAS_model_men$summary

# remove ".L" from exposure names for ordinal variables
XWAS_total$Exposure <- gsub(".L", "", XWAS_total$Exposure, fixed = TRUE)

# save
save(
  XWAS_model_men,
  XWAS_total,
  file = paste0(paste0(paste0(path, "/results/sex-specific results/ACM_XWAS_results_"), date), "_men.RData")
)

save(
  XWAS_total,
  file = paste0(paste0(paste0(path, "/results/sex-specific results/ACM_XWAS_results_"), date), "_men_summary.RData")
)

```

```{r exposures_women}

# create vector of exposure names
exposures <- as.vector(colnames(fmult_disc[[1]]))

# make list of variables in dataset to exclude from analysis as exposures (including covariates in model)
exclude <- c(
  Cs(
      eid, # participant ID
      hazard, # outcome
      ACM_event_indicator, # outcome
      ACM_survival_time, # outcome
      birth_year, # used for creation of birth cohort strata
      recruitment_date, # recruitment metric only
      recruitment_age, # covariate/outcome
      recruitment_centre, # covariate
      education_years, # covariate
      ethnicity, # covariate
      sex, # covariate
      alcohol_freq_old, # only used to create NA for alcohol_freq
      alcohol_status_old, # only used to create NA for alcohol_freq
      alcohol_status, # only used to create NA for alcohol_freq
      sleep_hours, # old var before normalization
      education_college, # redundant to covariate
      education_A_levels, # redundant to covariate
      education_O_levels, # redundant to covariate
      education_CSEs, # redundant to covariate
      education_NVQ, # redundant to covariate
      education_other_professional, # redundant to covariate
      education_none, # redundant to covariate
      
      partial_fiber_score,
      skin_color,
      hair_color,
      cereal,
      bread,
      never_eat_sugar,
      never_eat_eggs,
      never_eat_wheat,
      never_eat_dairy,
      dairy_milk,
      head_side_phone,
      psychiatrist_visit_mental_health,
      doctor_visit_mental_health,
      
      hot_drink_temp, # not interpretable
      cereal_type, # only used for determining fiber
      bread_type, # only used for determining fiber
      milk_type, # only used to code dairy milk intake
      coffee_type, # only used for determining fiber
      spread_type, # only used for determining fiber
      beef, # component of total red meat
      lamb, # component of total red meat
      pork, # component of total red meat
      cooked_veg, # component of total veg
      salad_or_raw_veg, # component of total veg
      fresh_fruit, # component of total fruit
      dried_fruit, # component of total fruit
      beer_monthly,
      beer_weekly,
      fortified_wine_monthly,
      fortified_wine_weekly,
      other_alcohol_monthly, 
      other_alcohol_weekly,
      red_wine_monthly,
      red_wine_weekly,
      spirits_monthly,
      spirits_weekly,
      white_wine_monthly,
      white_wine_weekly,
      
      LTPA_raw, # numeric version of LTPA variable
      OPA_raw, # numeric version of OPA variable
      sedentary_raw, # numeric version of sedentary variable
      TV_time, # component of sedentary variable
      computer_time, # component of sedentary variable
      driving_time, # component of sedentary variable
      heavy_DIY_4wks, # component of LTPA
      light_DIY_4wks, # component of LTPA
      other_exercise_4wks, # component of LTPA
      pleasure_walks_4wks, # component of LTPA
      strenuous_sports_4wks, # component of LTPA
      above_activity_recommendation, # non-summary
      above_activity_recommendation_incl_walk, # non-summary
      
      MET_mins_moderate_activty, # components of IPAQ
      MET_mins_vigorous_activty, # components of IPAQ
      MET_mins_walking, # components of IPAQ
      MET_mins_sum, # components of IPAQ
      days_activity_sum, # components of IPAQ
      mins_activity_sum, # components of IPAQ
      moderate_activity_over_10mins_days, # components of IPAQ
      vigorous_activity_over_10mins_days, # components of IPAQ
      walked_over_10mins_days, # components of IPAQ
      
      portable_gas_heat, # remove after crosstab QC
      solid_fuel_heat, # remove after crosstab QC
      open_fire_no_central_heat, # remove after crosstab QC
      hshld_grandparent, # remove after crosstab QC
      hshld_other_related, # not interpretable
      hshld_other_unrelated, # not interpretable
      pregnant, # remove after crosstab QC
      
      menopause_age, # only subset of dataset - nested
      birth_age, # only subset of dataset - nested
      first_birth_age, # only subset of dataset - nested
      last_birth_age # only subset of dataset - nested
  )
)

# remove variables I don't want to test in XWAS as exposures
exposures <- exposures[exposures %nin% exclude]

# add in categories to sort
exposures <- as.data.frame(exposures) # create df from exposure list
summary <- merge(exposures,
                 categories,
                 by.x = "exposures",
                 by.y = "Variable",
                 all = F) # merge with categories
summary <- summary[order(summary$Category), ] # order exposures by category

## separate out non-exposome variables

# get row positions for non-exposome
non_exposome <- which(
    # categories of non-exposome vars
    summary$Category %in% 
        c("Blood biomarkers",
          "Blood count",
          "Cognitive function",
          "General health",
          "Medical conditions",
          "Physical measures",
          "Urine biomarkers",
          "Medications",
          "Family medical history") |
        # individual disability or illness vars and response levels
        summary$exposures %in% 
        c("blue_badge",
          "attendance_allowance",
          "usual_walking_pace",
          "disability_allowance",
          "unemployed_disability",
          "health_satisfaction",
          "self_illness_injury_assault",
          "MDD",
          "bipolar",
          "narcolepsy")
)

# remove non-exposome variables
summary <- summary[-non_exposome, ]

# male variables
male_vars <- which(summary$Category == "Male reproductive factors")

# remove male variables
summary <- summary[-male_vars, ]

# make final vector of exposures ordered by category
exposures <- as.vector(summary$exposures) 

```

```{r data_prep_women}

# create age at censoring variables for age-at-risk analysis - discovery
for(j in seq_along(fmult_disc)) {
  # divide survival time (days) by 365.25 to get time in years
  fmult_disc[[j]]$time <- 
    as.numeric(fmult_disc[[j]]$ACM_survival_time / 365.25) # change to numeric 
  
  # add time (years) to recruitment age to get censor age
  fmult_disc[[j]]$censor_age <-
    fmult_disc[[j]]$recruitment_age + fmult_disc[[j]]$time 
}

# create age at censoring variables for age-at-risk analysis - replication
for(j in seq_along(fmult_rep)) {
  # divide survival time (days) by 365.25 to get time in years
  fmult_rep[[j]]$time <- 
    as.numeric(fmult_rep[[j]]$ACM_survival_time / 365.25) # change to numeric 
  
  # add time (years) to recruitment age to get censor age
  fmult_rep[[j]]$censor_age <- 
    fmult_rep[[j]]$recruitment_age + fmult_rep[[j]]$time 
}

# function to calculate birth cohorts
split_birth_year <- function(x){
  x$birth_cohort <- ifelse(
    x$birth_year >= 1935 & x$birth_year < 1940,
    "1935-1940",
    ifelse(
      x$birth_year >= 1940 & x$birth_year < 1945,
      "1940-1945",
      ifelse(
        x$birth_year >= 1945 & x$birth_year < 1950,
        "1945-1950",
        ifelse(
          x$birth_year >= 1950 & x$birth_year < 1955,
          "1950-1955",
          ifelse(
            x$birth_year >= 1955 & x$birth_year < 1960,
            "1955-1960",
            ifelse(
              x$birth_year >= 1960 & x$birth_year < 1965,
              "1960-1965",
              ifelse(
                x$birth_year >= 1965 & x$birth_year <= 1970, 
                "1965-1970", 
                NA
              )
            )
          )
        )
      )
    )
  )
  
  x$birth_cohort <- as.factor(x$birth_cohort)
  return(x)
}

# execute function across imputed datasets to create 5-year age bands
fmult_disc <- lapply(fmult_disc, split_birth_year)
fmult_rep <- lapply(fmult_rep, split_birth_year)

# overriding default polynomial contrasts to only return linear contrasts
set_contrasts <- function(x) {
  
  # find ordered variables
  ord <- sapply(x, is.ordered)
  
  # set contrasts to only linear
  for (k in seq(ncol(x[ord]))) {
    contrasts(x[ord][[k]], how.many = 1) <- contr.poly(nlevels(x[ord][[k]]))
  }
  
  return(x)
  
}

# run in datasets
fmult_disc <- lapply(fmult_disc, set_contrasts)
fmult_rep <- lapply(fmult_rep, set_contrasts)

```

```{r XWAS_women}

# set parameters
outcome <- "Surv(recruitment_age, censor_age, ACM_event_indicator)"
strata <- c(Cs(birth_cohort, sex))
covariates <- c(Cs(recruitment_centre, education_years, ethnicity))
cores <- 2

# run XWAS
XWAS_model_women <- XWAS(
  disc_data = fmult_disc,
  rep_data = fmult_rep,
  model_type = "coxph",
  outcome = outcome,
  strata = strata,
  covariates = covariates,
  exposures = exposures,
  extra.covar = "overall_health",
  extra.var = "alcohol_freq",
  categories = categories,
  replication = TRUE,
  multi_imputation = TRUE,
  scale = TRUE,
  p_adjust = "BH",
  cores = cores,
  interaction = FALSE
)

# df of results
XWAS_total <- XWAS_model_women$summary

# remove ".L" from exposure names for ordinal variables
XWAS_total$Exposure <- gsub(".L", "", XWAS_total$Exposure, fixed = TRUE)

# save
save(
  XWAS_model_women,
  XWAS_total,
  file = paste0(paste0(paste0(path, "/results/sex-specific results/ACM_XWAS_results_"), date), "_women.RData")
)

save(
  XWAS_total,
  file = paste0(paste0(paste0(path, "/results/sex-specific results/ACM_XWAS_results_"), date), "_women_summary.RData")
)
```

```{r load_results,eval=FALSE}
load("./results/ACM_XWAS_sensitivity_results_2024-12-03_exclusions_intermediates_nb_all_data_summary.RData")
XWAS_total10 <- XWAS_total

load("./results/ACM_XWAS_results_2024-12-03_all_sexes_summary.RData")

load(paste0(path, "/results/ACM_XWAS_sensitivity_results_jan_30_2022_interactions_intermediates_no_blood_all_data.RData"))

load(paste0(path, "/results/ACM_XWAS_sensitivity_results_jan_30_2022_exclusions_intermediates_nb_all_data.RData"))

load(paste0(path, "/results/ACM_XWAS_sensitivity_results_dec_11_2022_exclusions_time_all_data_4yrs.RData"))

XWAS_model$summary$Variable[which(XWAS_model$summary$Exposure == "non_oily_fish.L")] <- "non_oily_fish"

# full XWAS
XWAS_total <- XWAS_model$summary
XWAS_total$Exposure <- gsub(".L", "", XWAS_total$Exposure, fixed = TRUE)

# XWAS with indicator interaction - all data
XWAS_total9 <- XWAS_model9$summary
XWAS_total9$Exposure <- gsub(".L", "", XWAS_total9$Exposure, fixed = TRUE)

# XWAS with indicator exclusion - all data
XWAS_total10 <- XWAS_model10$summary
XWAS_total10$Exposure <- gsub(".L", "", XWAS_total10$Exposure, fixed = TRUE)

```

```{r}

## full XWAS
load(paste0(path, "/results/ACM_XWAS_results_aug_20_2022_all_sexes.RData"))

XWAS_model$summary$Variable[which(XWAS_model$summary$Exposure == "non_oily_fish.L")] <- "non_oily_fish"

# df of results
XWAS_total <- XWAS_model$summary

# remove ".L" from exposure names for ordinal variables
XWAS_total$Exposure <- gsub(".L", "", XWAS_total$Exposure, fixed = TRUE)

# save
save(
    XWAS_model,
    XWAS_total,
    file = paste0(paste0(paste0(path, "/results/ACM_XWAS_results_"), date), "_all_sexes.RData")
)

save(
    XWAS_total,
    file = paste0(paste0(paste0(path, "/results/ACM_XWAS_results_"), date), "_all_sexes_summary.RData")
)

rm(XWAS_total, XWAS_model)

### interactions
load(paste0(path, "/results/ACM_XWAS_sensitivity_results_aug_20_2022_interactions_intermediates_no_blood_all_data.RData"))

XWAS_model9$summary$Variable[which(XWAS_model9$summary$Exposure == "non_oily_fish.L")] <- "non_oily_fish"

# df of results
XWAS_total <- XWAS_model9$summary

# remove ".L" from exposure names for ordinal variables
XWAS_total$Exposure <- gsub(".L", "", XWAS_total$Exposure, fixed = TRUE)

# save
save(
    XWAS_model9,
    XWAS_total,
    file = paste0(paste0(paste0(path, "/results/ACM_XWAS_sensitivity_results_"), date), "_interactions_intermediates_no_blood_all_data.RData")
)

save(
    XWAS_total,
    file = paste0(paste0(paste0(path, "/results/ACM_XWAS_sensitivity_results_"), date), "_interactions_intermediates_no_blood_all_data_summary.RData")
)

rm(XWAS_total, XWAS_model9)


## exclusions
load(paste0(path, "/results/ACM_XWAS_sensitivity_results_aug_20_2022_exclusions_intermediates_nb_all_data.RData"))

XWAS_model10$summary$Variable[which(XWAS_model10$summary$Exposure == "non_oily_fish.L")] <- "non_oily_fish"

# df of results
XWAS_total <- XWAS_model10$summary

# remove ".L" from exposure names for ordinal variables
XWAS_total$Exposure <- gsub(".L", "", XWAS_total$Exposure, fixed = TRUE)

save(
    XWAS_model10,
    XWAS_total,
    file = paste0(paste0(paste0(path, "/results/ACM_XWAS_sensitivity_results_"), date), "_exclusions_intermediates_nb_all_data.RData")
)

save(
    XWAS_total,
    file = paste0(paste0(paste0(path, "/results/ACM_XWAS_sensitivity_results_"), date), "_exclusions_intermediates_nb_all_data_summary.RData")
)

rm(XWAS_total, XWAS_model10)


### men
load(paste0(path, "/results/sex-specific results/ACM_XWAS_results_aug_20_2022_men.RData"))

XWAS_model_men$summary$Variable[which(XWAS_model_men$summary$Exposure == "non_oily_fish.L")] <- "non_oily_fish"

# df of results
XWAS_total <- XWAS_model_men$summary

# remove ".L" from exposure names for ordinal variables
XWAS_total$Exposure <- gsub(".L", "", XWAS_total$Exposure, fixed = TRUE)

# save
save(
  XWAS_model_men,
  XWAS_total,
  file = paste0(paste0(paste0(path, "/results/sex-specific results/ACM_XWAS_results_"), date), "_men.RData")
)

save(
  XWAS_total,
  file = paste0(paste0(paste0(path, "/results/sex-specific results/ACM_XWAS_results_"), date), "_men_summary.RData")
)

rm(XWAS_total, XWAS_model_men)


### women
load(paste0(path, "/results/sex-specific results/ACM_XWAS_results_aug_20_2022_women.RData"))

XWAS_model_women$summary$Variable[which(XWAS_model_women$summary$Exposure == "non_oily_fish.L")] <- "non_oily_fish"

# df of results
XWAS_total <- XWAS_model_women$summary

# remove ".L" from exposure names for ordinal variables
XWAS_total$Exposure <- gsub(".L", "", XWAS_total$Exposure, fixed = TRUE)

# save
save(
  XWAS_model_women,
  XWAS_total,
  file = paste0(paste0(paste0(path, "/results/sex-specific results/ACM_XWAS_results_"), date), "_women.RData")
)

save(
  XWAS_total,
  file = paste0(paste0(paste0(path, "/results/sex-specific results/ACM_XWAS_results_"), date), "_women_summary.RData")
)


rm(XWAS_total, XWAS_model_women)


```





```{r compare_indicator_fixed_covar, eval=FALSE}

## find variables significant when adding interaction term for disease status

## replication data
# sig_vars <- unique(XWAS_total7$Variable[which(XWAS_total7$FDR.rep < 0.05)])
sig_vars <- unique(XWAS_total7$Variable[which(XWAS_total7$p.value < 0.05 & XWAS_total7$p.value.rep < 0.05)])


# non_sig_vars <- unique(XWAS_total7$Variable[which(XWAS_total7$FDR.disc > 0.05 | XWAS_total7$FDR.rep > 0.05)])
non_sig_vars <- unique(XWAS_total7$Variable[which(XWAS_total7$p.value > 0.05 | XWAS_total7$p.value.rep > 0.05)])

non_sig_vars <- non_sig_vars[non_sig_vars %nin% sig_vars]
sort(non_sig_vars)


### all data
sig_vars <- unique(XWAS_total8$Variable[which(XWAS_total8$p.value < 0.05)])
# sig_vars <- unique(XWAS_total8$Variable[which(XWAS_total8$FDR < 0.05)])
non_sig_vars <- unique(XWAS_total8$Variable[which(XWAS_total8$p.value > 0.05)])
# non_sig_vars <- unique(XWAS_total8$Variable[which(XWAS_total8$FDR > 0.05)])
non_sig_vars <- non_sig_vars[non_sig_vars %nin% sig_vars]
sort(non_sig_vars)

```

```{r compare_exclusions, eval=FALSE}

# rename
full_XWAS_total <- XWAS_total[which(XWAS_total$Variable %in% exposures), ]

# # merge
# compare_df <- merge(full_XWAS_total, 
#                     XWAS_total10,
#                     by = "Exposure",
#                     all = TRUE,
#                     sort = FALSE)
# 
# 
# compare_df$label <- ifelse(compare_df$Beta.x > 0 & compare_df$Beta.y < 0 |
#                              compare_df$Beta.x < 0 & compare_df$Beta.y > 0,
#                          compare_df$Exposure,
#                          "")
# 
# switch_vars <- unique(compare_df$Variable.x[which(compare_df$label != "")])
# non_switch_vars <- unique(compare_df$Variable.x[which(compare_df$label == "")])
# 
# switch_vars <- switch_vars[switch_vars %nin% non_switch_vars]
# 
# 
# 
# ###
# nominal_sig_vars <- unique(compare_df$Variable[which(compare_df$p.value < 0.05 & compare_df$p.value < 0.05)])
# nominal_vars <- unique(compare_df$Variable[which(compare_df$p.value > 0.05 | compare_df$p.value.rep > 0.05)])
# nominal_vars <- nominal_vars[nominal_vars %nin% nominal_sig_vars]
# sort(nominal_vars)
# sort(disease_vars)
# 
# nominal_vars[nominal_vars %nin% disease_vars]
# 
# FDR_sig_vars <- unique(compare_df$Variable[which(compare_df$FDR.rep < 0.05)])
# FDR_vars <- unique(compare_df$Variable[which(is.na(compare_df$FDR.rep) | compare_df$FDR.rep > 0.05)])
# FDR_vars <- FDR_vars[FDR_vars %nin% FDR_sig_vars]
# 


### all data
nominal_sig_vars <- unique(XWAS_total10$Variable[which(XWAS_total10$p.value < 0.05)])
nominal_vars <- unique(XWAS_total10$Variable[which(XWAS_total10$p.value > 0.05)])
nominal_vars <- nominal_vars[nominal_vars %nin% nominal_sig_vars]
sort(nominal_vars)


FDR_sig_vars <- unique(XWAS_total10$Variable[which(XWAS_total10$FDR < 0.05)])
FDR_vars <- unique(XWAS_total10$Variable[which(XWAS_total10$FDR > 0.05)])
FDR_vars <- FDR_vars[FDR_vars %nin% FDR_sig_vars]
sort(FDR_vars)

```

```{r beta_compare, eval=FALSE}

# formulas source: 
## https://stats.stackexchange.com/questions/93540/testing-equality-of-coefficients-from-two-different-regressions
## https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.1025.8565&rep=rep1&type=pdf
## 

XWAS_comp <- XWAS_total[which(XWAS_total$Exposure %in% XWAS_total10$Exposure), ]
XWAS_excl <- XWAS_total10[match(XWAS_comp$Exposure, XWAS_total10$Exposure),]
all.equal(as.vector(XWAS_comp$Exposure), as.vector(XWAS_excl$Exposure))

# z-test to compare betas
beta_compare <- function(x,y) {
    df <- data.frame(matrix(nrow = nrow(y), ncol = 2))
    df$z <- (x$Beta - y$Beta) / sqrt((x$std.error)^2 + (y$std.error)^2)
    df$exposure <- x$Exposure
    return(df)
}

# run
beta_comp <- beta_compare(x = XWAS_comp, y = XWAS_excl)

z_mean <- mean(beta_comp$z)
z_SD <- sd(beta_comp$z)

# p-value for two-tailed test using actual mean
beta_comp$p.value.2t <- 2*pnorm(-abs(beta_comp$z),
                                mean = z_mean,
                                sd = z_SD)

# p-value for two-tailed test using assumed mean (0)
beta_comp$p.value.2tmean <- 2*pnorm(-abs(beta_comp$z))

## map variable names to results
beta_comp$Variable <- NA
# must sort for variable matching to work properly
variables <- sort(exposures)

# add variable names based on partial match with exposure column
# (e.g., match "alcohol_freq" to "alcohol_freqDaily or almost daily")
for(j in seq_along(variables)) {
    beta_comp$Variable[grepl(variables[[j]], beta_comp$exposure)] <- variables[[j]]
}

sig_z <- unique(beta_comp$Variable[which(beta_comp$p.value.2t < 0.05)])
non_sig_z <- unique(beta_comp$Variable[which(beta_comp$p.value.2t > 0.05)])
sig_z <- sig_z[which(sig_z %nin% non_sig_z)]


sig_z2 <- unique(beta_comp$Variable[which(beta_comp$p.value.2tmean < 0.05)])
non_sig_z2 <- unique(beta_comp$Variable[which(beta_comp$p.value.2tmean > 0.05)])
sig_z2 <- sig_z2[which(sig_z2 %nin% non_sig_z2)]
```

```{r interaction_compare, eval=FALSE}

load("./results/ACM_XWAS_sensitivity_results_2024-12-04_interactions_intermediates_no_blood_all_data_summary.RData")
XWAS_total9 <- XWAS_total

# load full results
load("./results/ACM_XWAS_results_2024-12-03_all_sexes_summary.RData")

### all data 
### replication
# index of where the interaction terms are
terms <- grep("baseline_disease_indicator", XWAS_total9$Exposure)

# interaction terms significant
int_sig_term <- XWAS_total9[terms, ]
# int_sig_term <- unique(int_sig_term$Variable[which(int_sig_term$FDR < 0.05)])
int_sig_term <- unique(int_sig_term$Variable[which(int_sig_term$p.value < 0.05)])

# exposures significant
int_sig_exp <- XWAS_total9[-terms, ]
# int_sig_exp <- unique(int_sig_exp$Variable[which(int_sig_exp$FDR < 0.05)])
int_sig_exp <- unique(int_sig_exp$Variable[which(int_sig_exp$p.value < 0.05)])

# interaction terms not significant
int_non_sig_term <- XWAS_total9[terms, ]
# int_non_sig_term <- unique(int_non_sig_term$Variable[which(int_non_sig_term$FDR > 0.05)])
int_non_sig_term <- unique(int_non_sig_term$Variable[which(int_non_sig_term$p.value > 0.05)])
int_non_sig_term <- int_non_sig_term[int_non_sig_term %nin% int_sig_term]

# exposures not significant
int_non_sig_exp <- XWAS_total9[-terms, ]
# int_non_sig_exp <- unique(int_non_sig_exp$Variable[which(int_non_sig_exp$FDR > 0.05)])
int_non_sig_exp <- unique(int_non_sig_exp$Variable[which(int_non_sig_exp$p.value > 0.05)])

int_non_sig_exp <- int_non_sig_exp[int_non_sig_exp %nin% int_sig_exp]


# exposures where the interaction term is significant and the exposure is not
int_sig_term[int_sig_term %in% int_non_sig_exp]

# exposures where the interaction term is significant and the exposure is
int_sig_term[int_sig_term %in% int_sig_exp]

# exposures where the interaction term is not significant and the exposure is not
int_non_sig_term[int_non_sig_term %in% int_non_sig_exp]

# exposures where the interaction term is not significant and the exposure is
int_non_sig_term[int_non_sig_term %in% int_sig_exp]

```

```{r compare_beta_interaction, eval=FALSE}
## get just replicated variables from sensitivity XWAS 
# sig_vars <- unique(XWAS_total3$Variable[which(XWAS_total3$FDR.rep < 0.05)])
sig_vars <- unique(XWAS_total4$Variable[which(XWAS_total4$FDR.rep < 0.05)])
non_sig_vars <- unique(XWAS_total4$Variable[which(XWAS_total4$FDR.rep > 0.05)])
non_sig_vars <- non_sig_vars[non_sig_vars %nin% sig_vars]

## get just replicated variables from full XWAS
full_sig_vars <- unique(XWAS_total$Variable[which(XWAS_total$FDR.rep < 0.05)])

# get variables replicated in full cohort but not in sensitivity
diff_vars <- full_sig_vars[which(full_sig_vars %nin% sig_vars)]

# not sig in exclusion and sig different beta
diff_vars[diff_vars %in% non_sig_z]
diff_vars[diff_vars %nin% non_sig_z]

non_sig_z[non_sig_z %nin% diff_vars]


non_sig_z[non_sig_z %in% int_sig]

diff_vars[diff_vars %in% int_sig]

# not sig in exclusion and sig different beta and sig interaction
diff_vars[(diff_vars %in% non_sig_z) & (diff_vars %in% int_sig)]


##### interaction vs beta z-score
# exposures where the interaction term is significant and the exposure is not
int1 <- int_sig_term[int_sig_term %in% int_non_sig_exp]
# exposures where interaction term says exclude and also p-val for difference in beta is significant
int1[int1 %in% sig_z]
int1[int1 %in% sig_z2]

int_sig_term[int_sig_term %in% sig_z]
int_sig_term[int_sig_term %in% sig_z2]

# variables with sig z score that weren't sig in exclusion analysis
sig_z[sig_z %nin% sig_vars]
sig_z2[sig_z2 %nin% sig_vars]

# variables with sig interaction terms that weren't sig in exclusion analysis
int_sig_term[int_sig_term %nin% sig_vars]

```

```{r combine, eval=FALSE}

int_list <- int_sig_term[int_sig_term %in% int_non_sig_exp]

# combined <- unique(c(int_list, switch_vars, non_sig_vars))

# combined <- unique(c(int_list, nominal_vars))
# combined <- unique(c(int_list, non_sig_vars))
combined <- unique(c(int_list))


write.csv(combined, file = "./results/ACM_XWAS_sensitivity_non_sig_vars_list_dec_4_2024_all_sexes.csv")

sigvars1 <- unique(intermediates$Variable[which(intermediates$FDR.rep < 0.05)])
sigvars2 <- unique(XWAS_total$Variable[which(XWAS_total$FDR.rep < 0.05)])
diff_vars <- sigvars2[which(sigvars2 %nin% sigvars1)]

vars <- as.list(rep(1,3))
vars[[1]] <- sigvars2
vars[[2]] <- sigvars1
vars[[3]] <- diff_vars

vars <- sapply(vars, "length<-", max(lengths(vars)))
vars <- as.data.frame(vars)

write.csv(vars, file = paste0(path, "/output/ACM_XWAS_sensitivity_non_sig_vars_table_aug_16_2022_all_sexes.csv", rownames = FALSE))

```

```{r comparison_plot_non_sig, eval=FALSE}
library(plotly)
library(ggplot2)
library(htmlwidgets)
library(ggpubr)
library(ggrepel)

options(scipen = 999)

# load color palette
load("./files/color_palette.RData")

# load full results
load("./results/ACM_XWAS_results_2024-12-03_all_sexes_summary.RData")

# rename
full_XWAS_total <- XWAS_total[which(XWAS_total$Variable %in% XWAS_total10$Variable), ]

   #load healthy subset results
# load(paste0(path, "/results/ACM_XWAS_sensitivity_results_jan_30_2023_exclusions_intermediates_nb_all_data_summary.RData"))

combined <- read.csv( "./results/ACM_XWAS_sensitivity_non_sig_vars_list_dec_4_2024_all_sexes.csv")

combined <- as.vector(combined[[2]])

# merge
plots_df <- merge(full_XWAS_total, 
                  XWAS_total10,
                  by = "Exposure",
                  all = TRUE,
                  sort = FALSE)

plots_df$label <- plots_df$Variable.x
plots_df$label[which(plots_df$label %nin% combined)] <- ""

# plots_df$col2 <- ""
# plots_df$col2 <- ifelse(plots_df$label %in% nominal_vars,
#                         "red",
#                         "blue")
# plots_df$col2[which(plots_df$label %nin% combined)] <- ""


# merge categories for plot
plots_df$Category <- ifelse(!is.na(plots_df$Category.x),
                            plots_df$Category.x,
                            plots_df$Category.y)

color_map$color[which(color_map$sequence == "Stressful life events")] <- 
    color_map$color[which(color_map$sequence == "General health")]

color_map$sequence[which(color_map$sequence == "Medications")] <- "Supplements"
color_map$color[which(color_map$sequence == "Supplements")] <- 
    color_map$color[which(color_map$sequence == "Urine biomarkers")]

# merge color map with plots df
plots_df <- merge(plots_df, 
                  color_map, 
                  by.x = "Category",
                  by.y = "sequence", 
                  all = F)

# # add in grey/black color for non-significant points
# plots_df$color <- ifelse((plots_df$FDR.rep > 0.05 |
#                              is.na(plots_df$FDR.rep)) &
#                              (plots_df$FDR > 0.05 |
#                              is.na(plots_df$FDR)),
#                          "#4c4c4c",
#                          plots_df$color)

# # add in red color for points only significant in full cohort
# plots_df$color[which(plots_df$FDR.rep.x < 0.05 &
#                          (plots_df$FDR.rep.y > 0.05 |
#                               is.na(plots_df$FDR.rep.y)))] <- "#cc0610"
# 
# # add in "non-significant" category for plots
# plots_df$Category <- ifelse(plots_df$color == "#4c4c4c",
#                             "* Non-replicated",
#                             plots_df$Category)

# # add in "non-significant" category for plots
# plots_df$Category <- ifelse(plots_df$color == "#cc0610",
#                             "* Only replicated in full cohort",
#                             plots_df$Category)

# names(plots_df)[names(plots_df) == "Hazard.Ratio.x"] <- "Hazard.Ratio.Full.Cohort"
# names(plots_df)[names(plots_df) == "Hazard.Ratio.y"] <- "Hazard.Ratio.Healthy.Subset"

names(plots_df)[names(plots_df) == "Beta.x"] <- "Beta.Full.Cohort"
names(plots_df)[names(plots_df) == "Beta.y"] <- "Beta.Healthy.Subset"

# re-order so that black dots are behind colored dots
plots_df <- plots_df[order(plots_df$Category), ]

# correlation coefficient between men and women
# hr_corr <- cor(plots_df$Hazard.Ratio.Full.Cohort, 
#                plots_df$Hazard.Ratio.Healthy.Subset)

beta_corr <- cor(plots_df$Beta.Full.Cohort, 
               plots_df$Beta.Healthy.Subset)

# regression line for plot
# hazard.ratio.lm <- lm(Hazard.Ratio.Healthy.Subset ~ Hazard.Ratio.Full.Cohort, plots_df)

beta.lm <- lm(Beta.Healthy.Subset ~ Beta.Full.Cohort, plots_df)

# Calculate Pearson correlation and p-value
cor_test <- cor.test(plots_df$Beta.Full.Cohort, plots_df$Beta.Healthy.Subset, method = "pearson")
cor_value <- round(cor_test$estimate, 2) # Rounded correlation coefficient
p_value <- formatC(cor_test$p.value, format = "e", digits = 2) # P-value in scientific notation


options(scipen = 0)

# ggplot
comp_plot <- 
  ggplot(
    plots_df,
    aes(x = Beta.Full.Cohort, 
        y = Beta.Healthy.Subset, 
        label = Exposure
    )) + 
  geom_point(
    aes(color = Category),
    size = 3) + 
  annotate(
    "text", 
    x = mean(range(plots_df$Beta.Full.Cohort)) + 0.1, # Center x-position
    y = min(plots_df$Beta.Healthy.Subset) + 0.2,        # Bottom y-position
    label = paste0("r = ", cor_value, "\np = ", p_value),
    size = 3,
    hjust = 0
  ) +
  scale_color_manual(values = unique(plots_df$color)) +
  # ggtitle("Comparison of Mortality XWAS Hazard Ratios in the UK Biobank - Full Cohort vs. Healthy Subset") +
  labs(x = "Mortality XWAS beta - full sample",
       y = "Mortality XWAS beta - no disease at baseline") +
  theme_classic(base_size = 10) +
  theme(legend.key.size = unit(0, 'lines')) +
  geom_hline(yintercept = 0, 
             color = "gray", 
             linetype = "dashed") + 
  geom_vline(xintercept = 0, 
             color = "gray", 
             linetype = "dashed") +
  # breaks have function to only use integers and no decimals for axis values
  # scale_x_continuous(limits = c(-1,1.1)) +
  # scale_y_continuous(limits = c(-1,1.1)) +
  scale_x_continuous(breaks = function(x) seq(ceiling(x[1]), floor(x[2]), by = 1)) +
  scale_y_continuous(breaks = function(x) seq(ceiling(x[1]), floor(x[2]), by = 1)) +
  # show regression line between hazard ratios
  geom_abline(slope = coef(beta.lm)[[2]], 
              intercept = coef(beta.lm)[[1]],
              color = "red") +
  geom_text_repel(
    aes(label = label),
    size = 3,
    # aes(label = Exposure),
    box.padding = unit(.3, 'lines'),
    # always draw lines
    min.segment.length = 0,
    # Add extra padding around each data point.
    point.padding = unit(0.2, 'lines'),
    max.overlaps = Inf,
    force = 10,
    seed = 5678
    # min.segment.length = 0,
    # point.size = 2
  )

# save
name = "./figures/Ext_Data_fig_3.jpg"
width_in_inches <- 16 * 0.393701
height_in_inches <- 13  * 0.393701
ggsave(comp_plot, filename = name, width = width_in_inches, height = height_in_inches, dpi=600)

```