```{r packages, eval=TRUE}
library(Hmisc)
library(survival)
library(mice)
library(CoxR2)
library(car)
library(DescTools)
library(ggplot2)
library(reshape2)
library(rms)
library(viridis)
library(pbapply)
library(parallel)
library(glue)
# library(xlsx)

```

```{r load, results='hide'}

# load analysis datasets
load("./data/ACM_final_analysis_datasets_jan_25_2023_all_data.RData")
load('./data/ACM_final_recoded_analysis_data_april_28_2023_scotwales.RData')

# load NCD data
load("./data/NCD_all_subsets_jan_22_2023.RData")

# load interview baseline dx data
load("./data/baseline_dx_data_july_07_2022.RData")

# load variable categories
categories <- read.csv("./data/Argentieri UKB dataset data dictionary.csv")
categories$Category[which(categories$Variable == "gym")] <- "Physical activity"

# load PRS data
load('./data/PRS_data_mar_09_2023.RData')

# load disease analysis results
load("./results/all_disease_analysis_output_with_cs_2024-08-20.RData")

# load list of vars significant in cluster multivariate analyses
exposures <- read.csv('./results/total_sig_vars_list_2024-08-15.csv')
exposures <- as.vector(unlist(exposures[1]))

# set global R options
options(scipen = 999) # turn off scientific notation
pboptions(type = "timer", char = "=") # initialize progress bar

# set number of cores for parallel running
cores <- detectCores(logical = FALSE)
cores <- cores/2

```

```{r PRS_quintiles}

# lung quintile
PRS_data$PRS_breast_quintile <- NA
PRS_data$PRS_breast_quintile <- cut(PRS_data$PRS_breast, quantile(PRS_data$PRS_breast, probs = seq(0, 1, 0.20), na.rm = TRUE))
table(PRS_data$PRS_breast_quintile)
PRS_data$PRS_breast_quintile <- factor(PRS_data$PRS_breast_quintile, ordered = FALSE)
PRS_data$PRS_breast_quintile <- relevel(PRS_data$PRS_breast_quintile, ref = "(-4.98,-0.977]")

PRS_data$PRS_bowel_quintile <- NA
PRS_data$PRS_bowel_quintile <- cut(PRS_data$PRS_bowel, quantile(PRS_data$PRS_bowel, probs = seq(0, 1, 0.20), na.rm = TRUE))
table(PRS_data$PRS_bowel_quintile)
PRS_data$PRS_bowel_quintile <- factor(PRS_data$PRS_bowel_quintile, ordered = FALSE)
PRS_data$PRS_bowel_quintile <- relevel(PRS_data$PRS_bowel_quintile, ref = "(-4.67,-0.664]")

PRS_data$PRS_prostate_quintile <- NA
PRS_data$PRS_prostate_quintile <- cut(PRS_data$PRS_prostate, quantile(PRS_data$PRS_prostate, probs = seq(0, 1, 0.20), na.rm = TRUE))
table(PRS_data$PRS_prostate_quintile)
PRS_data$PRS_prostate_quintile <- factor(PRS_data$PRS_prostate_quintile, ordered = FALSE)
PRS_data$PRS_prostate_quintile <- relevel(PRS_data$PRS_prostate_quintile, ref = "(-4.44,-0.271]")

PRS_data$PRS_T2D_quintile <- NA
PRS_data$PRS_T2D_quintile <- cut(PRS_data$PRS_T2D, quantile(PRS_data$PRS_T2D, probs = seq(0, 1, 0.20), na.rm = TRUE))
table(PRS_data$PRS_T2D_quintile)
PRS_data$PRS_T2D_quintile <- factor(PRS_data$PRS_T2D_quintile, ordered = FALSE)
PRS_data$PRS_T2D_quintile <- relevel(PRS_data$PRS_T2D_quintile, ref = "(-4.57,-0.945]")

PRS_data$PRS_CVD_quintile <- NA
PRS_data$PRS_CVD_quintile <- cut(PRS_data$PRS_CVD, quantile(PRS_data$PRS_CVD, probs = seq(0, 1, 0.20), na.rm = TRUE))
table(PRS_data$PRS_CVD_quintile)
PRS_data$PRS_CVD_quintile <- factor(PRS_data$PRS_CVD_quintile, ordered = FALSE)
PRS_data$PRS_CVD_quintile <- relevel(PRS_data$PRS_CVD_quintile, ref = "(-4.8,-0.928]")

PRS_data$PRS_CAD_quintile <- NA
PRS_data$PRS_CAD_quintile <- cut(PRS_data$PRS_CAD, quantile(PRS_data$PRS_CAD, probs = seq(0, 1, 0.20), na.rm = TRUE))
table(PRS_data$PRS_CAD_quintile)
PRS_data$PRS_CAD_quintile <- factor(PRS_data$PRS_CAD_quintile, ordered = FALSE)
PRS_data$PRS_CAD_quintile <- relevel(PRS_data$PRS_CAD_quintile, ref = "(-4.95,-0.968]")

PRS_data$PRS_stroke_quintile <- NA
PRS_data$PRS_stroke_quintile <- cut(PRS_data$PRS_stroke, quantile(PRS_data$PRS_stroke, probs = seq(0, 1, 0.20), na.rm = TRUE))
table(PRS_data$PRS_stroke_quintile)
PRS_data$PRS_stroke_quintile <- factor(PRS_data$PRS_stroke_quintile, ordered = FALSE)
PRS_data$PRS_stroke_quintile <- relevel(PRS_data$PRS_stroke_quintile, ref = "(-4.22,-0.805]")

PRS_data$PRS_alzheimers_quintile <- NA
PRS_data$PRS_alzheimers_quintile <- cut(PRS_data$PRS_alzheimers, quantile(PRS_data$PRS_alzheimers, probs = seq(0, 1, 0.20), na.rm = TRUE))
table(PRS_data$PRS_alzheimers_quintile)
PRS_data$PRS_alzheimers_quintile <- factor(PRS_data$PRS_alzheimers_quintile, ordered = FALSE)
PRS_data$PRS_alzheimers_quintile <- relevel(PRS_data$PRS_alzheimers_quintile, ref = "(-3.73,-0.776]")

PRS_data$PRS_parkinsons_quintile <- NA
PRS_data$PRS_parkinsons_quintile <- cut(PRS_data$PRS_parkinsons, quantile(PRS_data$PRS_parkinsons, probs = seq(0, 1, 0.20), na.rm = TRUE))
table(PRS_data$PRS_parkinsons_quintile)
PRS_data$PRS_parkinsons_quintile <- factor(PRS_data$PRS_parkinsons_quintile, ordered = FALSE)
PRS_data$PRS_parkinsons_quintile <- relevel(PRS_data$PRS_parkinsons_quintile, ref = "(-4.55,-0.998]")

PRS_data$PRS_rheumatoid_quintile <- NA
PRS_data$PRS_rheumatoid_quintile <- cut(PRS_data$PRS_rheumatoid, quantile(PRS_data$PRS_rheumatoid, probs = seq(0, 1, 0.20), na.rm = TRUE))
table(PRS_data$PRS_rheumatoid_quintile)
PRS_data$PRS_rheumatoid_quintile <- factor(PRS_data$PRS_rheumatoid_quintile, ordered = FALSE)
PRS_data$PRS_rheumatoid_quintile <- relevel(PRS_data$PRS_rheumatoid_quintile, ref = "(-3.74,-0.709]")

PRS_data$PRS_macular_quintile <- NA
PRS_data$PRS_macular_quintile <- cut(PRS_data$PRS_macular, quantile(PRS_data$PRS_macular, probs = seq(0, 1, 0.20), na.rm = TRUE))
table(PRS_data$PRS_macular_quintile)
PRS_data$PRS_macular_quintile <- factor(PRS_data$PRS_macular_quintile, ordered = FALSE)
PRS_data$PRS_macular_quintile <- relevel(PRS_data$PRS_macular_quintile, ref = "(-4.32,-0.754]")

PRS_data$PRS_osteoporosis_quintile <- NA
PRS_data$PRS_osteoporosis_quintile <- cut(PRS_data$PRS_osteoporosis, quantile(PRS_data$PRS_osteoporosis, probs = seq(0, 1, 0.20), na.rm = TRUE))
table(PRS_data$PRS_osteoporosis_quintile)
PRS_data$PRS_osteoporosis_quintile <- factor(PRS_data$PRS_osteoporosis_quintile, ordered = FALSE)
PRS_data$PRS_osteoporosis_quintile <- relevel(PRS_data$PRS_osteoporosis_quintile, ref = "(-4.49,-0.831]")

PRS_data$PRS_ovarian_quintile <- NA
PRS_data$PRS_ovarian_quintile <- cut(PRS_data$PRS_ovarian, quantile(PRS_data$PRS_ovarian, probs = seq(0, 1, 0.20), na.rm = TRUE))
table(PRS_data$PRS_ovarian_quintile)
PRS_data$PRS_ovarian_quintile <- factor(PRS_data$PRS_ovarian_quintile, ordered = FALSE)
PRS_data$PRS_ovarian_quintile <- relevel(PRS_data$PRS_ovarian_quintile, ref = "(-5.06,-1.07]")

```

```{r merge_disease_data}

### all data

# merge ICD-10 data with ACM datasets
all_data_ncd <- lapply(all_data, function(x)
    as.data.frame(
        merge(x, 
              dat_NCD_all,
              by = "eid",
              all.x = TRUE,
              all.y = FALSE,
              sort = FALSE)
    )
)

# merge baseline dx data with ACM datasets
all_data_ncd <- lapply(all_data_ncd, function(x)
    as.data.frame(
        merge(x, 
              dat_dx,
              by = "eid",
              all.x = TRUE,
              all.y = FALSE,
              sort = FALSE)
    )
)

# merge PRS data with ACM datasets
all_data_ncd <- lapply(all_data_ncd, function(x)
    as.data.frame(
        merge(x, 
              PRS_data,
              by = "eid",
              all.x = TRUE,
              all.y = FALSE,
              sort = FALSE)
    )
)

### scotwales

# merge ICD-10 data with ACM datasets
scotwales_ncd <- lapply(scotwales, function(x)
    as.data.frame(
        merge(x, 
              dat_NCD_all,
              by = "eid",
              all.x = TRUE,
              all.y = FALSE,
              sort = FALSE)
    )
)

# merge baseline dx data with ACM datasets
scotwales_ncd <- lapply(scotwales_ncd, function(x)
    as.data.frame(
        merge(x, 
              dat_dx,
              by = "eid",
              all.x = TRUE,
              all.y = FALSE,
              sort = FALSE)
    )
)

# merge PRS data with ACM datasets
scotwales_ncd <- lapply(scotwales_ncd, function(x)
    as.data.frame(
        merge(x, 
              PRS_data,
              by = "eid",
              all.x = TRUE,
              all.y = FALSE,
              sort = FALSE)
    )
)


```

```{r remove_objects2, eval=TRUE}
rm(
    all_data,
    scotwales,
    dat_dx,
    dat_NCD_all
)

invisible(gc())
```

```{r variable_prep}

# make new var for scaled age
for (k in seq_along(all_data_ncd)) {
    all_data_ncd[[k]]$age_scaled <- scale(all_data_ncd[[k]]$recruitment_age, scale = TRUE)
    scotwales_ncd[[k]]$age_scaled <- scale(scotwales_ncd[[k]]$recruitment_age, scale = TRUE)
}

# scale function
scale_numeric <- function(x) { 
    # create logical vector of numeric columns
    nums <- sapply(x, is.numeric)
    
    # list of numeric variables to exclude from scaling
    scale_exclude <- c(
        Cs(
            censor_age,
            recruitment_age,
            ACM_event_indicator,
            eid,
            time,
            ACM_survival_time,
            hazard     
        )
    )
    
    # exclude those columns I don't want to scale
    nums[names(nums) %in% scale_exclude] <- FALSE # don't want to scale these
    
    # # don't bother scaling other numeric cols not in analysis
    nums[names(nums) %nin% exposures] <- FALSE

    # perform scale
    x[nums] <- scale(x[nums],
                     scale = TRUE)
    
    # return entire dataset
    return(x)
}

# scale desired numeric columns
all_data_ncd <- lapply(all_data_ncd, scale_numeric)
scotwales_ncd <- lapply(scotwales_ncd, scale_numeric)

# # set contrasts for regression
# set_contrasts <- function(x) {
#     
#     # find ordered variables
#     ord <- sapply(x, is.ordered)
#     
#     # set contrasts to only linear
#     for (k in seq(ncol(x[ord]))) {
#         contrasts(x[ord][[k]], how.many = 1) <- contr.poly(nlevels(x[ord][[k]]))
#     }
#     
#     return(x)
#     
# }
# 
# # run in datasets
# all_data <- lapply(all_data, set_contrasts)

```

```{r disease_list}

disease_list <- c(
    "All-cause mortality",
    "Colorectal cancer",
    "Lung cancer",
    "Esophageal cancer",
    "Liver cancer",
    "Pancreatic cancer",
    "Brain cancer",
    "Leukemia",
    "Lymphoma",
    "Breast cancer",
    "Ovarian cancer",
    "Prostate cancer",
    "Type II diabetes",
    "Ischemic heart disease",
    "Cerebrovascular diseases",
    "Emphysema, COPD",
    "Chronic liver diseases",
    "Chronic kidney diseases",
    "All-cause dementia",
    "Vascular dementia",
    "Alzheimer's disease",
    "Parkinson's disease",
    "Rheumatoid arthritis",
    "Macular degeneration",
    "Osteoporosis",
    "Osteoarthritis"
)

indicator <- c(
    Cs(
        ACM_event_indicator,
        colon_cancer_event,
        lung_cancer_event,
        eso_cancer_event,
        liver_cancer_event,
        pancreatic_cancer_event,
        brain_cancer_event,
        leukemia_event,
        lymphoma_event,
        breast_cancer_event,
        ovarian_cancer_event,
        prostate_cancer_event,
        diabetes_event,
        CVD_event,
        cerebro_event,
        COPD_event,
        liver_event,
        kidney_event,
        all_dementia_event,
        vasc_dementia_event,
        alzheimers_event,
        parkinsons_event,
        rheumatoid_event,
        macular_event,
        osteoporosis_event,
        osteoarthritis_event
    )
)

surv_time <- c(
    Cs(
        ACM_survival_time,
        colon_cancer_survival_time,
        lung_cancer_survival_time,
        eso_cancer_survival_time,
        liver_cancer_survival_time,
        pancreatic_cancer_survival_time,
        brain_cancer_survival_time,
        leukemia_survival_time,
        lymphoma_survival_time,
        breast_cancer_survival_time,
        ovarian_cancer_survival_time,
        prostate_cancer_survival_time,
        diabetes_survival_time,
        CVD_survival_time,
        cerebro_survival_time,
        COPD_survival_time,
        liver_survival_time,
        kidney_survival_time,
        all_dementia_survival_time,
        vasc_dementia_survival_time,
        alzheimers_survival_time,
        parkinsons_survival_time,
        rheumatoid_survival_time,
        macular_survival_time,
        osteoporosis_survival_time,
        osteoarthritis_survival_time
    )
)



```

```{r surv_list}

# list of survival objects

surv_list <- c(
    "Surv(ACM_survival_time, ACM_event_indicator) ~
                  age_scaled + sex +   ",
    "Surv(colon_cancer_survival_time, colon_cancer_event) ~
                  age_scaled + sex +   ",
    "Surv(lung_cancer_survival_time, lung_cancer_event) ~
                  age_scaled + sex +   ",
    "Surv(eso_cancer_survival_time, eso_cancer_event) ~
                  age_scaled + sex +   ",
    "Surv(liver_cancer_survival_time, liver_cancer_event) ~
                  age_scaled + sex +   ",
    "Surv(pancreatic_cancer_survival_time, pancreatic_cancer_event) ~
                  age_scaled + sex +   ",
    "Surv(brain_cancer_survival_time, brain_cancer_event) ~
                  age_scaled + sex +   ",
    "Surv(leukemia_survival_time, leukemia_event) ~
                  age_scaled + sex +   ",
    "Surv(lymphoma_survival_time, lymphoma_event) ~
                  age_scaled + sex +   ",
    "Surv(breast_cancer_survival_time, breast_cancer_event) ~
                  age_scaled +   ",
    "Surv(ovarian_cancer_survival_time, ovarian_cancer_event) ~
                  age_scaled +   ",
    "Surv(prostate_cancer_survival_time, prostate_cancer_event) ~
                  age_scaled +   ",
    "Surv(diabetes_survival_time, diabetes_event) ~
                  age_scaled + sex +   ",
    "Surv(CVD_survival_time, CVD_event) ~
                  age_scaled + sex +   ",
    "Surv(cerebro_survival_time, cerebro_event) ~
                  age_scaled + sex +   ",
    "Surv(COPD_survival_time, COPD_event) ~
                  age_scaled + sex +   ",
    "Surv(liver_survival_time, liver_event) ~
                  age_scaled + sex +   ",
    "Surv(kidney_survival_time, kidney_event) ~
                  age_scaled + sex +   ",
    "Surv(all_dementia_survival_time, all_dementia_event) ~
                  age_scaled + sex +   ",
    "Surv(vasc_dementia_survival_time, vasc_dementia_event) ~
                  age_scaled + sex +   ",
    "Surv(alzheimers_survival_time, alzheimers_event) ~
                  age_scaled + sex +   ",
    "Surv(parkinsons_survival_time, parkinsons_event) ~
                  age_scaled + sex +   ",
    "Surv(rheumatoid_survival_time, rheumatoid_event) ~
                  age_scaled + sex +   ",
    "Surv(macular_survival_time, macular_event) ~
                  age_scaled + sex +   ",
    "Surv(osteoporosis_survival_time, osteoporosis_event) ~
                  age_scaled + sex +   ",
    "Surv(osteoarthritis_survival_time, osteoarthritis_event) ~
                  age_scaled + sex +   "
    
)

surv_list_tt <- c(
    "Surv(Start_time, Stop_time, ACM_event_indicator) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, colon_cancer_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, lung_cancer_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, eso_cancer_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, liver_cancer_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, pancreatic_cancer_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, brain_cancer_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, leukemia_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, lymphoma_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, breast_cancer_event) ~
                  age_scaled +   ",
    "Surv(Start_time, Stop_time, ovarian_cancer_event) ~
                  age_scaled +   ",
    "Surv(Start_time, Stop_time, prostate_cancer_event) ~
                  age_scaled +   ",
    "Surv(Start_time, Stop_time, diabetes_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, CVD_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, cerebro_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, COPD_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, liver_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, kidney_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, all_dementia_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, vasc_dementia_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, alzheimers_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, parkinsons_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, rheumatoid_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, macular_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, osteoporosis_event) ~
                  age_scaled + sex +   ",
    "Surv(Start_time, Stop_time, osteoarthritis_event) ~
                  age_scaled + sex +   "
)

surv_list_age_sex <- c(
    "Surv(ACM_survival_time, ACM_event_indicator) ~
                  age_scaled + sex",
    "Surv(colon_cancer_survival_time, colon_cancer_event) ~
                  age_scaled + sex",
    "Surv(lung_cancer_survival_time, lung_cancer_event) ~
                  age_scaled + sex",
    "Surv(eso_cancer_survival_time, eso_cancer_event) ~
                  age_scaled + sex",
    "Surv(liver_cancer_survival_time, liver_cancer_event) ~
                  age_scaled + sex",
    "Surv(pancreatic_cancer_survival_time, pancreatic_cancer_event) ~
                  age_scaled + sex",
    "Surv(brain_cancer_survival_time, brain_cancer_event) ~
                  age_scaled + sex",
    "Surv(leukemia_survival_time, leukemia_event) ~
                  age_scaled + sex",
    "Surv(lymphoma_survival_time, lymphoma_event) ~
                  age_scaled + sex",
    "Surv(breast_cancer_survival_time, breast_cancer_event) ~
                  age_scaled",
    "Surv(ovarian_cancer_survival_time, ovarian_cancer_event) ~
                  age_scaled",
    "Surv(prostate_cancer_survival_time, prostate_cancer_event) ~
                  age_scaled",
    "Surv(diabetes_survival_time, diabetes_event) ~
                  age_scaled + sex",
    "Surv(CVD_survival_time, CVD_event) ~
                  age_scaled + sex",
    "Surv(cerebro_survival_time, cerebro_event) ~
                  age_scaled + sex",
    "Surv(COPD_survival_time, COPD_event) ~
                  age_scaled + sex",
    "Surv(liver_survival_time, liver_event) ~
                  age_scaled + sex",
    "Surv(kidney_survival_time, kidney_event) ~
                  age_scaled + sex",
    "Surv(all_dementia_survival_time, all_dementia_event) ~
                  age_scaled + sex",
    "Surv(vasc_dementia_survival_time, vasc_dementia_event) ~
                  age_scaled + sex",
    "Surv(alzheimers_survival_time, alzheimers_event) ~
                  age_scaled + sex",
    "Surv(parkinsons_survival_time, parkinsons_event) ~
                  age_scaled + sex",
    "Surv(rheumatoid_survival_time, rheumatoid_event) ~
                  age_scaled + sex",
    "Surv(macular_survival_time, macular_event) ~
                  age_scaled + sex",
    "Surv(osteoporosis_survival_time, osteoporosis_event) ~
                  age_scaled + sex",
    "Surv(osteoarthritis_survival_time, osteoarthritis_event) ~
                  age_scaled + sex"
)


```

```{r exposures_list}

exposures_list <- as.list(seq(1, length(disease_list)))

exposures_list[[1]] <- exposures

for (k in 2:length(exposures_list)) {
    sig_vars <- disease_results[[k-1]]
    exposures_list[[k]] <- unique(sig_vars$Variable[which(sig_vars$FDR < 0.05)])
    
}

names(exposures_list) <- disease_list

```

```{r prevalent_cases_list}
# load list of functions to identify and exclude prevalent cases
source("/Users/aargenti/Library/CloudStorage/GoogleDrive-austin.argentieri@gmail.com/My Drive/Computer backup/DPhil Research/UKB/Analysis projects/ACM EWAS 2021/code/identify_prev_cases.R")

identify_prev_cases_list <- identify_prev_cases_list[1:26]
names(identify_prev_cases_list) <- disease_list
```

```{r prevalent_cases_list, eval=FALSE}

identify_prev_cases_list <- as.list(seq(1, length(disease_list)))

# mortality (no subset)
identify_prev_cases_list[[1]] <- function(x) {x <- x}

# colorectal cancer
identify_prev_cases_list[[2]] <- function(x) {
  
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$colon_cancer_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_colon_cancer <- NA
    x$baseline_colon_cancer[baseline_ncd] <- 1
    x$baseline_colon_cancer[which(x$colon_cancer_baseline_dx == 1)] <- 1
    x$baseline_colon_cancer[which(is.na(x$baseline_colon_cancer))] <- 0
    x$baseline_colon_cancer <- factor(x$baseline_colon_cancer)
    
    x <- x[which(x$baseline_colon_cancer == 0), ]
    return(x)
}

# lung cancer
identify_prev_cases_list[[3]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$lung_cancer_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_lung_cancer <- NA
    x$baseline_lung_cancer[baseline_ncd] <- 1
    x$baseline_lung_cancer[which(x$lung_cancer_baseline_dx == 1)] <- 1
    x$baseline_lung_cancer[which(is.na(x$baseline_lung_cancer))] <- 0
    x$baseline_lung_cancer <- factor(x$baseline_lung_cancer)
    
    x <- x[which(x$baseline_lung_cancer == 0), ]
    return(x)
}

# eso cancer
identify_prev_cases_list[[4]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$eso_cancer_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_eso_cancer <- NA
    x$baseline_eso_cancer[baseline_ncd] <- 1
    x$baseline_eso_cancer[which(x$eso_cancer_baseline_dx == 1)] <- 1
    x$baseline_eso_cancer[which(is.na(x$baseline_eso_cancer))] <- 0
    x$baseline_eso_cancer <- factor(x$baseline_eso_cancer)
    
    x <- x[which(x$baseline_eso_cancer == 0), ]
    return(x)
}

# liver cancer
identify_prev_cases_list[[5]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$liver_cancer_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_liver_cancer <- NA
    x$baseline_liver_cancer[baseline_ncd] <- 1
    x$baseline_liver_cancer[which(x$liver_cancer_baseline_dx == 1)] <- 1
    x$baseline_liver_cancer[which(is.na(x$baseline_liver_cancer))] <- 0
    x$baseline_liver_cancer <- factor(x$baseline_liver_cancer)
    
    x <- x[which(x$baseline_liver_cancer == 0), ]
    return(x)
}

# pancreatic cancer
identify_prev_cases_list[[6]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$pancreatic_cancer_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_pancreatic_cancer <- NA
    x$baseline_pancreatic_cancer[baseline_ncd] <- 1
    x$baseline_pancreatic_cancer[which(x$pancreatic_cancer_baseline_dx == 1)] <- 1
    x$baseline_pancreatic_cancer[which(is.na(x$baseline_pancreatic_cancer))] <- 0
    x$baseline_pancreatic_cancer <- factor(x$baseline_pancreatic_cancer)
    
    x <- x[which(x$baseline_pancreatic_cancer == 0), ]
    return(x)
}

# brain cancer
identify_prev_cases_list[[7]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$brain_cancer_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_brain_cancer <- NA
    x$baseline_brain_cancer[baseline_ncd] <- 1
    x$baseline_brain_cancer[which(x$brain_cancer_baseline_dx == 1)] <- 1
    x$baseline_brain_cancer[which(is.na(x$baseline_brain_cancer))] <- 0
    x$baseline_brain_cancer <- factor(x$baseline_brain_cancer)
    
    x <- x[which(x$baseline_brain_cancer == 0), ]
    return(x)
}

# leukemia
identify_prev_cases_list[[8]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$leukemia_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_leukemia <- NA
    x$baseline_leukemia[baseline_ncd] <- 1
    x$baseline_leukemia[which(x$leukemia_baseline_dx == 1)] <- 1
    x$baseline_leukemia[which(is.na(x$baseline_leukemia))] <- 0
    x$baseline_leukemia <- factor(x$baseline_leukemia)
    
    x <- x[which(x$baseline_leukemia == 0), ]
    return(x)
}

# lymphoma
identify_prev_cases_list[[9]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$lymphoma_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_lymphoma <- NA
    x$baseline_lymphoma[baseline_ncd] <- 1
    x$baseline_lymphoma[which(x$lymphoma_baseline_dx == 1)] <- 1
    x$baseline_lymphoma[which(is.na(x$baseline_lymphoma))] <- 0
    x$baseline_lymphoma <- factor(x$baseline_lymphoma)
    
    x <- x[which(x$baseline_lymphoma == 0), ]
    return(x)
}

# breast cancer
identify_prev_cases_list[[10]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$breast_cancer_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_breast_cancer <- NA
    x$baseline_breast_cancer[baseline_ncd] <- 1
    x$baseline_breast_cancer[which(x$breast_cancer_baseline_dx == 1)] <- 1
    x$baseline_breast_cancer[which(is.na(x$baseline_breast_cancer))] <- 0
    x$baseline_breast_cancer <- factor(x$baseline_breast_cancer)
    
    x <- x[which(x$baseline_breast_cancer == 0), ]
    x <- x[which(x$sex == "Female"), ]
    return(x)
}

# ovarian cancer
identify_prev_cases_list[[11]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$ovarian_cancer_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_ovarian_cancer <- NA
    x$baseline_ovarian_cancer[baseline_ncd] <- 1
    x$baseline_ovarian_cancer[which(x$ovarian_cancer_baseline_dx == 1)] <- 1
    x$baseline_ovarian_cancer[which(is.na(x$baseline_ovarian_cancer))] <- 0
    x$baseline_ovarian_cancer <- factor(x$baseline_ovarian_cancer)
    
    x <- x[which(x$baseline_ovarian_cancer == 0), ]
    x <- x[which(x$sex == "Female"), ]
    return(x)
}

# prostate cancer
identify_prev_cases_list[[12]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$prostate_cancer_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_prostate_cancer <- NA
    x$baseline_prostate_cancer[baseline_ncd] <- 1
    x$baseline_prostate_cancer[which(x$prostate_cancer_baseline_dx == 1)] <- 1
    x$baseline_prostate_cancer[which(is.na(x$baseline_prostate_cancer))] <- 0
    x$baseline_prostate_cancer <- factor(x$baseline_prostate_cancer)
    
    x <- x[which(x$baseline_prostate_cancer == 0), ]
    x <- x[which(x$sex == "Male"), ]
    return(x)
}

# diabetes
identify_prev_cases_list[[13]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$diabetes_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_diabetes <- NA
    x$baseline_diabetes[baseline_ncd] <- 1
    x$baseline_diabetes[which(x$diabetes_diagnosis == "Yes")] <- 1
    x$baseline_diabetes[which(x$diabetes_baseline_dx == 1)] <- 1
    x$baseline_diabetes[which(x$insulin == "Yes")] <- 1
    x$baseline_diabetes[which(x$hbA1c >= 48)] <- 1
    x$baseline_diabetes[which(x$glucose >= 11.1)] <- 1
    x$baseline_diabetes[which(is.na(x$baseline_diabetes))] <- 0
    x$baseline_diabetes <- factor(x$baseline_diabetes)
    
    x <- x[which(x$baseline_diabetes == 0), ]
    return(x)
}

# cvd
identify_prev_cases_list[[14]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$cvd_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_cvd <- NA
    x$baseline_cvd[baseline_ncd] <- 1
    x$baseline_cvd[which(x$heart_attack_diagnosis == "Yes")] <- 1
    x$baseline_cvd[which(x$angina_diagnosis == "Yes")] <- 1
    x$baseline_cvd[which(x$CVD_baseline_dx == 1)] <- 1
    x$baseline_cvd[which(is.na(x$baseline_cvd))] <- 0
    x$baseline_cvd <- factor(x$baseline_cvd)
    
    x <- x[which(x$baseline_cvd == 0), ]
    return(x)
}

# cerebro
identify_prev_cases_list[[15]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$cerebro_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_cerebro <- NA
    x$baseline_cerebro[baseline_ncd] <- 1
    x$baseline_cerebro[which(x$stroke_diagnosis == "Yes")] <- 1
    x$baseline_cerebro[which(x$cerebro_baseline_dx == 1)] <- 1
    x$baseline_cerebro[which(is.na(x$baseline_cerebro))] <- 0
    x$baseline_cerebro <- factor(x$baseline_cerebro)
    
    x <- x[which(x$baseline_cerebro == 0), ]
    return(x)
}

# copd
identify_prev_cases_list[[16]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$copd_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_copd <- NA
    x$baseline_copd[baseline_ncd] <- 1
    x$baseline_copd[which(x$bronchitis_emphysema_diagnosis == "Yes")] <- 1
    x$baseline_copd[which(x$COPD_baseline_dx == 1)] <- 1
    x$baseline_copd[which(is.na(x$baseline_copd))] <- 0
    x$baseline_copd <- factor(x$baseline_copd)
    
    x <- x[which(x$baseline_copd == 0), ]
    return(x)
}

# liver
identify_prev_cases_list[[17]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$liver_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_liver <- NA
    x$baseline_liver[baseline_ncd] <- 1
    x$baseline_liver[which(x$liver_baseline_dx == 1)] <- 1
    x$baseline_liver[which(is.na(x$baseline_liver))] <- 0
    x$baseline_liver <- factor(x$baseline_liver)
    
    x <- x[which(x$baseline_liver == 0), ]
    return(x)
}

# kidney
identify_prev_cases_list[[18]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$kidney_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_kidney <- NA
    x$baseline_kidney[baseline_ncd] <- 1
    x$baseline_kidney[which(x$kidney_baseline_dx == 1)] <- 1
    x$baseline_kidney[which(is.na(x$baseline_kidney))] <- 0
    x$baseline_kidney <- factor(x$baseline_kidney)
    
    x <- x[which(x$baseline_kidney == 0), ]
    return(x)
}

# all_dementia
identify_prev_cases_list[[19]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$all_dementia_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_all_dementia <- NA
    x$baseline_all_dementia[baseline_ncd] <- 1
    x$baseline_all_dementia[which(x$all_dementia_baseline_dx == 1)] <- 1
    x$baseline_all_dementia[which(is.na(x$baseline_all_dementia))] <- 0
    x$baseline_all_dementia <- factor(x$baseline_all_dementia)
    
    x <- x[which(x$baseline_all_dementia == 0), ]
    return(x)
}

# vasc_dementia
identify_prev_cases_list[[20]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$vasc_dementia_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_vasc_dementia <- NA
    x$baseline_vasc_dementia[baseline_ncd] <- 1
    x$baseline_vasc_dementia[which(x$vasc_dementia_baseline_dx == 1)] <- 1
    x$baseline_vasc_dementia[which(is.na(x$baseline_vasc_dementia))] <- 0
    x$baseline_vasc_dementia <- factor(x$baseline_vasc_dementia)
    
    x <- x[which(x$baseline_vasc_dementia == 0), ]
    return(x)
}

# alzheimers
identify_prev_cases_list[[21]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$alzheimers_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_alzheimers <- NA
    x$baseline_alzheimers[baseline_ncd] <- 1
    x$baseline_alzheimers[which(x$alzheimers_baseline_dx == 1)] <- 1
    x$baseline_alzheimers[which(is.na(x$baseline_alzheimers))] <- 0
    x$baseline_alzheimers <- factor(x$baseline_alzheimers)
    
    x <- x[which(x$baseline_alzheimers == 0), ]
    return(x)
}

# parkinsons
identify_prev_cases_list[[22]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$parkinsons_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_parkinsons <- NA
    x$baseline_parkinsons[baseline_ncd] <- 1
    x$baseline_parkinsons[which(x$parkinsons_baseline_dx == 1)] <- 1
    x$baseline_parkinsons[which(is.na(x$baseline_parkinsons))] <- 0
    x$baseline_parkinsons <- factor(x$baseline_parkinsons)
    
    x <- x[which(x$baseline_parkinsons == 0), ]
    return(x)
}

# rheumatoid
identify_prev_cases_list[[23]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$rheumatoid_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_rheumatoid <- NA
    x$baseline_rheumatoid[baseline_ncd] <- 1
    x$baseline_rheumatoid[which(x$rheumatoid_baseline_dx == 1)] <- 1
    x$baseline_rheumatoid[which(is.na(x$baseline_rheumatoid))] <- 0
    x$baseline_rheumatoid <- factor(x$baseline_rheumatoid)
    
    x <- x[which(x$baseline_rheumatoid == 0), ]
    return(x)
}

# macular
identify_prev_cases_list[[24]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$macular_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_macular <- NA
    x$baseline_macular[baseline_ncd] <- 1
    x$baseline_macular[which(x$macular_baseline_dx == 1)] <- 1
    x$baseline_macular[which(is.na(x$baseline_macular))] <- 0
    x$baseline_macular <- factor(x$baseline_macular)
    
    x <- x[which(x$baseline_macular == 0), ]
    return(x)
}

# osteoporosis
identify_prev_cases_list[[25]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$osteoporosis_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_osteoporosis <- NA
    x$baseline_osteoporosis[baseline_ncd] <- 1
    x$baseline_osteoporosis[which(x$osteoporosis_baseline_dx == 1)] <- 1
    x$baseline_osteoporosis[which(is.na(x$baseline_osteoporosis))] <- 0
    x$baseline_osteoporosis <- factor(x$baseline_osteoporosis)
    
    x <- x[which(x$baseline_osteoporosis == 0), ]
    return(x)
}

# osteoarthritis
identify_prev_cases_list[[26]] <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$osteoarthritis_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_osteoarthritis <- NA
    x$baseline_osteoarthritis[baseline_ncd] <- 1
    x$baseline_osteoarthritis[which(x$osteoarthritis_baseline_dx == 1)] <- 1
    x$baseline_osteoarthritis[which(is.na(x$baseline_osteoarthritis))] <- 0
    x$baseline_osteoarthritis <- factor(x$baseline_osteoarthritis)
    
    x <- x[which(x$baseline_osteoarthritis == 0), ]
    return(x)
}



```

```{r PRS_prep}

PRS_disease_list <- c(
    "All-cause mortality",
    "Colorectal cancer",
    "Lung cancer",
    "Esophageal cancer",
    # "Liver cancer",
    "Pancreatic cancer",
    # "Brain cancer",
    "Leukemia",
    # "Lymphoma",
    "Breast cancer",
    "Ovarian cancer",
    "Prostate cancer",
    "Type II diabetes",
    "Ischemic heart disease",
    "Cerebrovascular diseases",
    "Emphysema, COPD",
    "Chronic liver diseases",
    "Chronic kidney diseases",
    "All-cause dementia",
    "Vascular dementia",
    "Alzheimer's disease",
    "Parkinson's disease",
    "Rheumatoid arthritis",
    "Macular degeneration",
    "Osteoporosis",
    "Osteoarthritis"
)


# list of PRS vars
PRS_list <- c(
    "PRS_bowel_quintile",
    "PRS_lung_quintile",
    "PRS_eso_quintile",
    "PRS_pancreatic_quintile",
    "PRS_leukemia_quintile",
    "PRS_breast_quintile",
    "PRS_ovarian_quintile",
    "PRS_prostate_quintile",
    "PRS_T2D_quintile",
    "PRS_CVD_quintile",
    "PRS_CAD_quintile",
    "PRS_stroke_quintile",
    "PRS_COPD_quintile",
    "PRS_nafld_quintile",
    "PRS_cirrhosis_quintile",
    "PRS_ckd_quintile",
    "PRS_alzheimers_quintile",
    "PRS_parkinsons_quintile",
    "PRS_rheumatoid_quintile",
    "PRS_macular_quintile",
    "PRS_osteoporosis_quintile",
    "PRS_knee_OA_quintile"
)

PRS_covars <- c(
    "GeP_PC1",
    "GeP_PC2",
    "GeP_PC3",
    "GeP_PC4",
    "GeP_PC5",
    "GeP_PC6",
    "GeP_PC7",
    "GeP_PC8",
    "GeP_PC9",
    "GeP_PC10",
    "GeP_PC11",
    "GeP_PC12",
    "GeP_PC13",
    "GeP_PC14",
    "GeP_PC15",
    "GeP_PC16",
    "GeP_PC17",
    "GeP_PC18",
    "GeP_PC19",
    "GeP_PC20",
    "GeP_Array"
)

names(exposures_list) <- disease_list

PRS_exposures <- as.list(rep(1, length(exposures_list)))
names(PRS_exposures) <- disease_list
PRS_exposures <- PRS_exposures[which(names(exposures_list) %in% PRS_disease_list)]

exposome_PRS_list <- as.list(rep(1, length(exposures_list)))
names(exposome_PRS_list) <- disease_list
exposome_PRS_list <- exposome_PRS_list[which(names(exposures_list) %in% PRS_disease_list)]

### PRS only
PRS_exposures$`All-cause mortality` <- c(PRS_covars, PRS_list)

PRS_exposures$`Colorectal cancer` <- c(PRS_covars, "PRS_bowel_quintile")

PRS_exposures$`Breast cancer` <- c(PRS_covars, "PRS_breast_quintile")

PRS_exposures$`Ovarian cancer` <- c(PRS_covars, "PRS_ovarian_quintile")

PRS_exposures$`Prostate cancer` <- c(PRS_covars, "PRS_prostate_quintile")

PRS_exposures$`Type II diabetes` <- c(PRS_covars, "PRS_T2D_quintile")

PRS_exposures$`Ischemic heart disease` <- c(PRS_covars, "PRS_CVD_quintile", "PRS_CAD_quintile")

PRS_exposures$`Cerebrovascular diseases` <- c(PRS_covars, "PRS_stroke_quintile")

PRS_exposures$`Emphysema, COPD` <- c(PRS_covars, "PRS_COPD_quintile")

PRS_exposures$`All-cause dementia` <- c(PRS_covars, "PRS_alzheimers_quintile")

PRS_exposures$`Vascular dementia` <- c(PRS_covars, "PRS_alzheimers_quintile")

PRS_exposures$`Alzheimer's disease` <- c(PRS_covars, "PRS_alzheimers_quintile")

PRS_exposures$`Parkinson's disease` <- c(PRS_covars, "PRS_parkinsons_quintile")

PRS_exposures$`Rheumatoid arthritis` <- c(PRS_covars, "PRS_rheumatoid_quintile")

PRS_exposures$`Macular degeneration` <- c(PRS_covars, "PRS_macular_quintile")

PRS_exposures$Osteoporosis <- c(PRS_covars, "PRS_osteoporosis_quintile")

PRS_exposures$`Lung cancer` <- c(PRS_covars, "PRS_lung_quintile")

PRS_exposures$Leukemia <- c(PRS_covars, "PRS_leukemia_quintile")

PRS_exposures$`Esophageal cancer` <- c(PRS_covars, "PRS_eso_quintile")

PRS_exposures$`Pancreatic cancer` <- c(PRS_covars, "PRS_pancreatic_quintile")

PRS_exposures$`Chronic kidney diseases` <- c(PRS_covars, "PRS_ckd_quintile")

PRS_exposures$`Chronic liver diseases` <- c(PRS_covars, "PRS_nafld_quintile", "PRS_cirrhosis_quintile")

PRS_exposures$Osteoarthritis <- c(PRS_covars, "PRS_knee_OA_quintile")

### PRS and exposome
exposome_PRS_list$`All-cause mortality` <- 
    c(exposures_list$`All-cause mortality`, c(PRS_covars, PRS_list))

exposome_PRS_list$`Colorectal cancer` <- 
    c(exposures_list$`Colorectal cancer`, c(PRS_covars, "PRS_bowel_quintile"))

exposome_PRS_list$`Breast cancer` <- 
    c(exposures_list$`Breast cancer`, c(PRS_covars, "PRS_breast_quintile"))

exposome_PRS_list$`Ovarian cancer` <-
    c(exposures_list$`Ovarian cancer`, c(PRS_covars, "PRS_ovarian_quintile"))

exposome_PRS_list$`Prostate cancer` <- 
    c(exposures_list$`Prostate cancer`, c(PRS_covars, "PRS_prostate_quintile"))

exposome_PRS_list$`Type II diabetes` <- 
    c(exposures_list$`Type II diabetes`, c(PRS_covars, "PRS_T2D_quintile"))

exposome_PRS_list$`Ischemic heart disease` <- 
    c(exposures_list$`Ischemic heart disease`, c(PRS_covars, "PRS_CVD_quintile", "PRS_CAD_quintile"))

exposome_PRS_list$`Cerebrovascular diseases` <- 
    c(exposures_list$`Cerebrovascular diseases`, c(PRS_covars, "PRS_stroke_quintile"))

exposome_PRS_list$`Emphysema, COPD` <- 
    c(exposures_list$`Emphysema, COPD`, c(PRS_covars, "PRS_COPD_quintile"))

exposome_PRS_list$`All-cause dementia` <- 
    c(exposures_list$`All-cause dementia`, c(PRS_covars, "PRS_alzheimers_quintile"))

exposome_PRS_list$`Vascular dementia` <- 
    c(exposures_list$`Vascular dementia`, c(PRS_covars, "PRS_alzheimers_quintile"))

exposome_PRS_list$`Alzheimer's disease` <- 
    c(exposures_list$`Alzheimer's disease`, c(PRS_covars, "PRS_alzheimers_quintile"))

exposome_PRS_list$`Parkinson's disease` <- 
    c(exposures_list$`Parkinson's disease`, c(PRS_covars, "PRS_parkinsons_quintile"))

exposome_PRS_list$`Rheumatoid arthritis` <- 
    c(exposures_list$`Rheumatoid arthritis`, c(PRS_covars, "PRS_rheumatoid_quintile"))

exposome_PRS_list$`Macular degeneration` <- 
    c(exposures_list$`Macular degeneration`, c(PRS_covars, "PRS_macular_quintile"))

exposome_PRS_list$Osteoporosis <- 
    c(exposures_list$Osteoporosis, c(PRS_covars, "PRS_osteoporosis_quintile"))

exposome_PRS_list$`Lung cancer` <- 
    c(exposures_list$`Lung cancer`, c(PRS_covars, "PRS_lung_quintile"))

exposome_PRS_list$Leukemia <- 
    c(exposures_list$Leukemia, c(PRS_covars, "PRS_leukemia_quintile"))

exposome_PRS_list$`Esophageal cancer` <- 
    c(exposures_list$`Esophageal cancer`, c(PRS_covars, "PRS_eso_quintile"))

exposome_PRS_list$`Pancreatic cancer` <- 
    c(exposures_list$`Pancreatic cancer`, c(PRS_covars, "PRS_pancreatic_quintile"))

exposome_PRS_list$`Chronic kidney diseases` <- 
    c(exposures_list$`Chronic kidney diseases`, c(PRS_covars, "PRS_ckd_quintile"))

exposome_PRS_list$`Chronic liver diseases` <- 
    c(exposures_list$`Chronic liver diseases`, c(PRS_covars, "PRS_nafld_quintile", "PRS_cirrhosis_quintile"))

exposome_PRS_list$Osteoarthritis <- 
    c(exposures_list$Osteoarthritis, c(PRS_covars, "PRS_knee_OA_quintile"))

```

```{r crosstab_check}

library(caret)

sig_exposures <- sapply(exposures_list, length)
sig_exposures <- which(sig_exposures != 0)

problem_vars <- as.list(rep(1, length(exposures_list)))
crosstabs <- as.list(rep(1, length(exposures_list)))

for (k in sig_exposures) {
    
    
    # subset the data
    test_data <- all_data_ncd[[1]]
    test_data <- identify_prev_cases_list[[k]](test_data)
    test_data <- test_data[c(exposures_list[[k]], indicator[k])]
    test_data <- na.omit(test_data)
    
    ### crosstab check
    
    # convert mortality event indicator to factor for crosstabs
    test_data[[indicator[k]]] <- factor(test_data[[indicator[k]]])
    
    # identify all factor variables
    vars <- names(test_data[exposures_list[[k]]])
    fact_vars <- sapply(test_data[exposures_list[[k]]], is.factor)
    trial_vars <- vars[fact_vars]
    
    # subset dataset to just factors
    crosstab_data <- test_data[c(trial_vars, indicator[k])]
    
    # get column number for event indicator
    mort_index <- which(colnames(crosstab_data) == indicator[k])
    
    # create list for crosstab of results
    tables <- as.list(rep(1, ncol(crosstab_data)-1))
    
    # create list of column positions
    col_position <- seq(1, ncol(crosstab_data))
    
    # remove mortality event column from list of columns
    col_position <- col_position[which(col_position != mort_index)]
    
    # run loop of crosstabs between variables and mortality
    for (j in col_position) {
        tables[[j]] <- 
            as.data.frame.matrix(table(crosstab_data[[j]], crosstab_data[[indicator[k]]]))
        tables[[j]][3] <- names(crosstab_data[j])
    }
    
    # rbind all results together into single table
    crosstabs[[k]] <- Reduce(function(x, y) 
        rbind(x = x, 
              y = y), 
        tables)
    
    # make column for variable levels
    crosstabs[[k]]$levels <- NA
    
    # add in levels to each variable
    for (j in col_position) {
        crosstabs[[k]]$levels[which(crosstabs[[k]]$V3 == names(crosstab_data[j]))] <- levels(crosstab_data[[j]])
    }
    
    # fix rownames
    rownames(crosstabs[[k]]) <- NULL
    
    # get list of variables with <30 mortality cases in a response level
    low_variance <- crosstabs[[k]]$V3[which(crosstabs[[k]]$'1' < 5)]
    
    # get a df of these problem vars that shows all response categories and the cross-tab tables
    problem_vars[[k]] <- crosstabs[[k]][which(crosstabs[[k]]$V3 %in% low_variance), ]
    
    cat("\r", paste("completed:", paste(k, length(problem_vars), sep = "/")))
}

# subset to only models that were run
names(problem_vars) <- disease_list

```

```{r crosstab_check_PRS}

library(caret)

sig_exposures_prs <- sapply(exposome_PRS_list, length)
sig_exposures_prs <- which(sig_exposures_prs != 0)

problem_vars_prs <- as.list(rep(1, length(exposome_PRS_list)))

for (k in sig_exposures_prs) {
    
    
    # subset the data
    test_data <- all_data_ncd[[1]]
    test_data <- identify_prev_cases_list[[k]](test_data)
    test_data <- test_data[c(exposome_PRS_list[[k]], indicator[k])]
    test_data <- na.omit(test_data)
    
    ### crosstab check
    
    # convert mortality event indicator to factor for crosstabs
    test_data[[indicator[k]]] <- factor(test_data[[indicator[k]]])
    
    # identify all factor variables
    vars <- names(test_data[exposome_PRS_list[[k]]])
    fact_vars <- sapply(test_data[exposome_PRS_list[[k]]], is.factor)
    trial_vars <- vars[fact_vars]
    
    # subset dataset to just factors
    crosstab_data <- test_data[c(trial_vars, indicator[k])]
    
    # get column number for event indicator
    mort_index <- which(colnames(crosstab_data) == indicator[k])
    
    # create list for crosstab of results
    tables <- as.list(rep(1, ncol(crosstab_data)-1))
    
    # create list of column positions
    col_position <- seq(1, ncol(crosstab_data))
    
    # remove mortality event column from list of columns
    col_position <- col_position[which(col_position != mort_index)]
    
    # run loop of crosstabs between variables and mortality
    for (j in col_position) {
        tables[[j]] <- 
            as.data.frame.matrix(table(crosstab_data[[j]], crosstab_data[[indicator[k]]]))
        tables[[j]][3] <- names(crosstab_data[j])
    }
    
    # rbind all results together into single table
    crosstabs <- Reduce(function(x, y) 
        rbind(x = x, 
              y = y), 
        tables)
    
    # make column for variable levels
    crosstabs$levels <- NA
    
    # add in levels to each variable
    for (j in col_position) {
        crosstabs$levels[which(crosstabs$V3 == names(crosstab_data[j]))] <- levels(crosstab_data[[j]])
    }
    
    # fix rownames
    rownames(crosstabs) <- NULL
    
    # get list of variables with <30 mortality cases in a response level
    low_variance <- crosstabs$V3[which(crosstabs$'1' < 5)]
    
    # get a df of these problem vars that shows all response categories and the cross-tab tables
    problem_vars_prs[[k]] <- crosstabs[which(crosstabs$V3 %in% low_variance), ]
    
    cat("\r", paste("completed:", paste(k, length(problem_vars_prs), sep = "/")))
}

# subset to only models that were run
names(problem_vars_prs) <- names(exposome_PRS_list)
# 
# View(problem_vars_prs[[9]])
# 
# probs <- sapply(problem_vars_prs, function(x){nrow(x) == 0})
# probs <- which(probs == FALSE)
# prob_diseases <- names(problem_vars_prs)[probs]
# 
# # view
# for (k in probs) {
#     View(problem_vars_prs[[k]])
# }



```

```{r remove_problem_vars}

sig_exposures <- sapply(exposures_list, length)
sig_exposures <- which(sig_exposures != 0)

other <- which(names(exposures_list) %nin% names(exposome_PRS_list))
together <- which(names(exposures_list) %in% names(exposome_PRS_list))
together_vars <- exposures_list

exp_vars <- as.list(seq_along(problem_vars))
for (k in sig_exposures) {
    exp_vars[[k]] <- problem_vars[[k]]$V3
    exp_vars[[k]] <- exp_vars[[k]][exp_vars[[k]] %nin% c("accommodation_type", "family_visit_freq", "own_or_rent")]
    exp_vars[[k]] <- unique(exp_vars[[k]])
}

prs_vars <- as.list(seq_along(problem_vars_prs))
for (k in seq_along(prs_vars)) {
    prs_vars[[k]] <- problem_vars_prs[[k]]$V3
    prs_vars[[k]] <- prs_vars[[k]][prs_vars[[k]] %nin% c("accommodation_type", "family_visit_freq", "own_or_rent")]
    prs_vars[[k]] <- unique(prs_vars[[k]])

}

# remove problem variables for exposome only
for (k in other) {
    exposures_list[[k]] <- exposures_list[[k]][which(exposures_list[[k]] %nin% exp_vars[[k]])]
}

for (k in together) {
    exposures_list[[k]] <- exposures_list[[k]][which(exposures_list[[k]] %nin% prs_vars[[which(names(problem_vars_prs) == names(exposures_list)[k])]])]
}

# remove problem variables for PRS
for (k in seq_along(exposome_PRS_list)) {
    exposome_PRS_list[[k]] <- exposome_PRS_list[[k]][which(exposome_PRS_list[[k]] %nin% prs_vars[[k]])]
}

```

```{r crosstab_recode}

crosstab_recode <- function(x) {
 
    # accommodation_type
    x$accommodation_type[which(x$accommodation_type == "Mobile or temporary structure (i.e. caravan)")] <- NA
    old_levels <- levels(x$accommodation_type)
    x$accommodation_type <- 
        factor(x$accommodation_type,
               ordered = FALSE,
               levels = old_levels[which(old_levels != "Mobile or temporary structure (i.e. caravan)")])
    
    # own_or_rent
    x$own_or_rent[which(x$own_or_rent == "Live in accommodation rent free")] <- NA
    x$own_or_rent[which(x$own_or_rent == "Pay part rent and part mortgage (shared ownership)")] <- NA
    old_levels <- levels(x$own_or_rent)
    x$own_or_rent <- 
        factor(x$own_or_rent,
               ordered = FALSE,
               levels = old_levels[which(old_levels %nin% c("Live in accommodation rent free","Pay part rent and part mortgage (shared ownership)"))])
    
    
    # family_visit_freq
    x$family_visit_freq[which(x$family_visit_freq == "No friends/family outside household")] <- "Never or almost never"
    old_levels <- levels(x$family_visit_freq)
    x$family_visit_freq <- 
        factor(x$family_visit_freq,
               ordered = TRUE,
               levels = old_levels[which(old_levels != "No friends/family outside household")])
    
    return(x)
    
}

all_data_ncd <- lapply(all_data_ncd, crosstab_recode)
scotwales_ncd <- lapply(scotwales_ncd, crosstab_recode)

```

```{r save dataset}

# save for quicker loading next time
save(all_data_ncd,
     scotwales_ncd,
     exposures_list,
     PRS_exposures,
     exposome_PRS_list,
     disease_list,
     PRS_list,
     PRS_disease_list,
     indicator,
     surv_time,
     identify_prev_cases_list,
     surv_list_tt,
     surv_list_age_sex,
     surv_list,
     file = glue("./data/R2_model_datasets_{Sys.Date()}.RData"))

```

```{r}
load("./data/R2_model_datasets_2024-08-20.RData")
```

```{r run_models_age_sex}

# make index of diseases with at least 1 significant exposure
sig_exposures <- sapply(exposures_list, length)
sig_exposures <- which(sig_exposures != 0)

# list to store model results
R2_results_as <- as.list(seq(1, length(disease_list)))
names(R2_results_as) <- disease_list

# list to store sample sizes
sample_sizes <- as.list(seq(1, length(disease_list)))
names(sample_sizes) <- disease_list

for (k in seq_along(R2_results_as)) {
  
    # subset data
    # data <- all_data_ncd
    data <- all_data_ncd
    data <- lapply(data, identify_prev_cases_list[[k]])
    
    # make sub-list for model results
    R2_results_as[[k]] <- as.list(seq(1, length(data)))
    
    # run model in each imputed dataset
    for (j in seq_along(data)) {

        R2_results_as[[k]][[j]] <-
            coxph(as.formula(
                surv_list_age_sex[[k]]
            ), data = data[[j]])

    }
    
    # record sample size
    rm(data)
    
    cat("\r", paste("completed:", paste(k, length(R2_results_as), sep = "/")))
}


# subset to only models that were run
exclude <- which(names(exposures_list) == "Brain cancer")
R2_results_as <- R2_results_as[-exclude]

# create table_as for results
table_as <- data.frame(matrix(ncol = 5, nrow = length(R2_results_as)))
colnames(table_as) <- c("Disease", "C-index", "R-squared", "Cases", "Sample size")

# get R2 and C-index for all models
for (k in seq_along(R2_results_as)) {

    # get r-squared across imputations
    avg_rsq <- c(coxr2(R2_results_as[[k]][[1]])$rsq,
                 coxr2(R2_results_as[[k]][[2]])$rsq,
                 coxr2(R2_results_as[[k]][[3]])$rsq,
                 coxr2(R2_results_as[[k]][[4]])$rsq,
                 coxr2(R2_results_as[[k]][[5]])$rsq)
    
    # transform to correlation scale (sqrt)
    avg_rsq <- sapply(avg_rsq, sqrt)
    
    # transform using Fischer's Z
    avg_rsq <- sapply(avg_rsq, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_rsq <- mean(avg_rsq)
    
    # transform coefficients back to r scale
    avg_rsq <- FisherZInv(avg_rsq)
    
    # transform r squared scale
    avg_rsq <- (avg_rsq)^2
    
    # add to table_as
    table_as[k,3] <- avg_rsq
    
    
    # get c-index across imputations
    avg_index <- c(summary(R2_results_as[[k]][[1]])$concordance[1],
                   summary(R2_results_as[[k]][[2]])$concordance[1],
                   summary(R2_results_as[[k]][[3]])$concordance[1],
                   summary(R2_results_as[[k]][[4]])$concordance[1],
                   summary(R2_results_as[[k]][[5]])$concordance[1])
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table_as
    table_as[k,2] <- avg_index


}

table_as$Disease <- names(R2_results_as)

# add in number of cases and sample sizes
for (k in seq_along(R2_results_as)) {

    table_as[k,4] <- R2_results_as[[k]][[1]]$nevent
    table_as[k,5] <- R2_results_as[[k]][[1]]$n
}


### save
save(R2_results_as,
     table_as,
     file = glue("./results/R2_models_{Sys.Date()}_age_sex.RData"))

```

```{r prediction_age_sex, eval=TRUE}

# subset surv list
indicator_val <- indicator[sig_exposures]
surv_time_val <- surv_time[sig_exposures]

# subset prev cases function list
identify_prev_cases_list_val <- identify_prev_cases_list[sig_exposures]

# get prediction values for each disease
# pred_list <- as.list(seq_along(R2_results_exp))
# cindex_list <- as.list(seq_along(R2_results_exp))

pred_list <- as.list(seq_along(R2_results_as))
cindex_list_as <- as.list(seq_along(R2_results_as))
rsq_list_as <- as.list(seq_along(R2_results_as))

table_scotwales_as <- data.frame(matrix(ncol = 5, nrow = length(cindex_list_as)))
colnames(table_scotwales_as) <- c("Disease", "C-index", "R-squared", "Cases", "Sample size")


for (k in seq_along(pred_list)) {
    
    # subset data
    data <- scotwales_ncd
    data <- lapply(data, identify_prev_cases_list_val[[k]])
    
    # make sub-list for model results
    pred_list[[k]] <- as.list(seq(1, length(data)))
    cindex_list_as[[k]] <- as.list(seq(1, length(data)))
    rsq_list_as[[k]] <- as.list(seq(1, length(data)))
    
    # run model in each imputed dataset
    for (j in seq_along(data)) {
        
        # get linear predictors using scotwales data
        pred_list[[k]][[j]] <-
            predict(R2_results_as[[k]][[j]],
                    newdata = data[[j]])
        
        # Surv object in scotwales
        yrep <- Surv(data[[j]][[surv_time_val[k]]], data[[j]][[indicator_val[k]]])
        # calculate concordance outcomes using linear predictors and Surv object
        rs.corr <- rcorr.cens(x = pred_list[[k]][[j]], S = yrep)
        # take Dxy, negate, and then get C using formula Dxy=2*(C−0.5)
        cindex_list_as[[k]][[j]] <- (-rs.corr[2]/2) + 0.5
        
        # Get R-squared using predicted values from scotwales data
        cox <- coxph(yrep ~ pred_list[[k]][[j]], data = data[[j]])
        rsq_list_as[[k]][[j]] <- coxr2(cox)
        
    }
    
    table_scotwales_as[k,4] <- as.numeric(table(data[[1]][indicator_val[k]])[2])
    table_scotwales_as[k,5] <- nrow(data[[1]])
    
    # record sample size
    rm(data)
    
    cat("\r", paste("completed:", paste(k, length(pred_list), sep = "/")))
    
}

### For further discussion of Dxy calculation, see comment here from Harrell on using linear predictors with rcorr.cens: https://stats.stackexchange.com/questions/48298/computing-c-index-for-an-external-validation-of-a-cox-ph-model-with-r#comment93976_48369


# get C-index for all models
for (k in seq_along(cindex_list_as)) {
    
    # Rsq
    avg_index <- c(rsq_list_as[[k]][[1]]$rsq,
                   rsq_list_as[[k]][[2]]$rsq,
                   rsq_list_as[[k]][[3]]$rsq,
                   rsq_list_as[[k]][[4]]$rsq,
                   rsq_list_as[[k]][[5]]$rsq)
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table
    table_scotwales_as[k,3] <- avg_index
    
    # C-index
    avg_index <- c(cindex_list_as[[k]][[1]],
                   cindex_list_as[[k]][[2]],
                   cindex_list_as[[k]][[3]],
                   cindex_list_as[[k]][[4]],
                   cindex_list_as[[k]][[5]])
    
   
### save # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table
    table_scotwales_as[k,2] <- avg_index

}

table_scotwales_as$Disease <- names(R2_results_as)

save(rsq_list_as,
     cindex_list_as,
     table_scotwales_as,
     file = glue("./results/R2_models_{Sys.Date()}_scotwales_age_sex.RData"))

```

```{r run_models_exposome}

# make index of diseases with at least 1 significant exposure
sig_exposures <- sapply(exposures_list, length)
sig_exposures <- which(sig_exposures != 0)

# make list of diseases with at least 1 significant exposure
sig_diseases <- disease_list[sig_exposures]

# list to store model results
R2_results_exp <- as.list(seq(1, length(disease_list)))
names(R2_results_exp) <- disease_list

# list to store sample sizes
sample_sizes <- as.list(seq(1, length(disease_list)))
names(sample_sizes) <- disease_list

# make model exposures
model_exposures <- lapply(exposures_list, paste, collapse = " + ")
cores <- NULL
# run all models
for (k in sig_exposures) {
  
    # subset data
    data <- all_data_ncd
    data <- lapply(data, identify_prev_cases_list[[k]])
    
    
    # make sub-list for model results
    R2_results_exp[[k]] <- as.list(seq(1, length(data)))
    
    # # run model in each imputed dataset
    # model_function <- function(x) {
    #   coxph(as.formula(
    #     paste0(
    #       surv_list[[k]],
    #       model_exposures[[k]])
    #   ), data = x)
    # }
    # 
    # R2_results_exp[[k]] <- pblapply(data, model_function, cl=cores)
    # 
    # run model in each imputed dataset
    for (j in seq_along(data)) {

        R2_results_exp[[k]][[j]] <-
            coxph(as.formula(
                paste0(
                    surv_list[[k]],
                    model_exposures[[k]])
            ), data = data[[j]])
    }
    
    # remove
    rm(data)
    invisible(gc())
    
    cat("\r", paste("completed:", paste(k, length(R2_results_exp), sep = "/")))
}


# subset to only models that were run
exclude <- which(sapply(R2_results_exp, is.numeric))
R2_results_exp <- R2_results_exp[-exclude]

# create table_exp for results
table_exp <- data.frame(matrix(ncol = 5, nrow = length(R2_results_exp)))
colnames(table_exp) <- c("Disease", "C-index", "R-squared", "Cases", "Sample size")

# get R2 and C-index for all models
for (k in seq_along(R2_results_exp)) {

    # get r-squared across imputations
    avg_rsq <- c(coxr2(R2_results_exp[[k]][[1]])$rsq,
                 coxr2(R2_results_exp[[k]][[2]])$rsq,
                 coxr2(R2_results_exp[[k]][[3]])$rsq,
                 coxr2(R2_results_exp[[k]][[4]])$rsq,
                 coxr2(R2_results_exp[[k]][[5]])$rsq)
    
    # transform to correlation scale (sqrt)
    avg_rsq <- sapply(avg_rsq, sqrt)
    
    # transform using Fischer's Z
    avg_rsq <- sapply(avg_rsq, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_rsq <- mean(avg_rsq)
    
    # transform coefficients back to r scale
    avg_rsq <- FisherZInv(avg_rsq)
    
    # transform r squared scale
    avg_rsq <- (avg_rsq)^2
    
    # add to table_exp
    table_exp[k,3] <- avg_rsq
    
    
    # get c-index across imputations
    avg_index <- c(summary(R2_results_exp[[k]][[1]])$concordance[1],
                   summary(R2_results_exp[[k]][[2]])$concordance[1],
                   summary(R2_results_exp[[k]][[3]])$concordance[1],
                   summary(R2_results_exp[[k]][[4]])$concordance[1],
                   summary(R2_results_exp[[k]][[5]])$concordance[1])
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table_exp
    table_exp[k,2] <- avg_index


}

table_exp$Disease <- names(R2_results_exp)

# add in number of cases and sample sizes
for (k in seq_along(R2_results_exp)) {

    table_exp[k,4] <- R2_results_exp[[k]][[1]]$nevent
    table_exp[k,5] <- R2_results_exp[[k]][[1]]$n
}

### save
save(R2_results_exp,
     table_exp,
     file = glue("./results/R2_models_{Sys.Date()}_exposome.RData"))

```

```{r sig_vars_exp, eval=FALSE}

sig_vars <- as.list(seq_along(R2_results_exp))
non_sig_vars <- as.list(seq_along(R2_results_exp))
covariates <- c("age_scaled", "sexMale")
covar_remove <- paste(covariates, collapse = "|")
variables <- unique(unlist(exposures_list))

# run loop to get significant vars
for (k in seq_along(R2_results_exp)) {
    
    # pool models
    pool <- pool(R2_results_exp[[k]])
    
    # make df of summary of regression results
    pool_df <- summary(pool)
    # remove covariate rows
    pool_df <- pool_df[!grepl(covar_remove, pool_df$term),]
    # make new row for variable name
    pool_df$Variable <- NA
    
    # add variable names based on partial match with term
    for(j in seq_along(variables)) {
        pool_df$Variable[grepl(variables[[j]], pool_df$term)] <- variables[[j]]
    }
    
    # get all significant cluster exposures 
    sig_vars[[k]] <- unique(pool_df$Variable[which(pool_df$p.value < 0.05)])
    # get all non-significant cluster exposures 
    non_sig_vars[[k]] <- unique(pool_df$Variable[which(pool_df$p.value >= 0.05)])
    # get non-sig vars where all levels are non-sig
    non_sig_vars[[k]] <- non_sig_vars[[k]][non_sig_vars[[k]] %nin% sig_vars[[k]]]
    
}

save(sig_vars,
     non_sig_vars,
     file = paste0(path, "/results/incident disease/R2_exposome_sig_vars_nov_09_2022_.RData"))

```

```{r sig_only_models_exposome, eval=FALSE}

# make index of diseases with at least 1 significant exposure
sig_exposures <- sapply(exposures_list, length)
sig_exposures <- which(sig_exposures != 0)

# make list of diseases with at least 1 significant exposure
sig_diseases <- disease_list[sig_exposures]
sig_prev <- identify_prev_cases_list[sig_exposures]
sig_surv <- surv_list[sig_exposures]

# list to store model results
R2_results_exp2 <- as.list(seq(1, length(sig_diseases)))
names(R2_results_exp2) <- sig_diseases

# make model exposures
model_exposures <- lapply(sig_vars, paste, collapse = " + ")

# run all models
for (k in seq_along(R2_results_exp2)) {
  
    # subset data
    data <- all_data_ncd
    data <- lapply(data, sig_prev[[k]])
    
    
    # make sub-list for model results
    R2_results_exp2[[k]] <- as.list(seq(1, length(data)))
    
    # run model in each imputed dataset
    for (j in seq_along(data)) {

        R2_results_exp2[[k]][[j]] <-
            coxph(as.formula(
                paste0(
                    sig_surv[[k]],
                    model_exposures[[k]])
            ), data = data[[j]])
    }
    
    # remove
    rm(data)
    invisible(gc())
    
    cat("\r", paste("completed:", paste(k, length(R2_results_exp2), sep = "/")))
}

# create table_exp2 for results
table_exp2 <- data.frame(matrix(ncol = 5, nrow = length(R2_results_exp2)))
colnames(table_exp2) <- c("Disease", "C-index", "R-squared", "Cases", "Sample size")

# get R2 and C-index for all models
for (k in seq_along(R2_results_exp2)) {

    # get r-squared across imputations
    avg_rsq <- c(coxr2(R2_results_exp2[[k]][[1]])$rsq,
                 coxr2(R2_results_exp2[[k]][[2]])$rsq,
                 coxr2(R2_results_exp2[[k]][[3]])$rsq,
                 coxr2(R2_results_exp2[[k]][[4]])$rsq,
                 coxr2(R2_results_exp2[[k]][[5]])$rsq)
    
    # transform to correlation scale (sqrt)
    avg_rsq <- sapply(avg_rsq, sqrt)
    
    # transform using Fischer's Z
    avg_rsq <- sapply(avg_rsq, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_rsq <- mean(avg_rsq)
    
    # transform coefficients back to r scale
    avg_rsq <- FisherZInv(avg_rsq)
    
    # transform r squared scale
    avg_rsq <- (avg_rsq)^2
    
    # add to table_exp2
    table_exp2[k,3] <- avg_rsq
    
    
    # get c-index across imputations
    avg_index <- c(summary(R2_results_exp2[[k]][[1]])$concordance[1],
                   summary(R2_results_exp2[[k]][[2]])$concordance[1],
                   summary(R2_results_exp2[[k]][[3]])$concordance[1],
                   summary(R2_results_exp2[[k]][[4]])$concordance[1],
                   summary(R2_results_exp2[[k]][[5]])$concordance[1])
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table_exp2
    table_exp2[k,2] <- avg_index


}

table_exp2$Disease <- names(R2_results_exp2)

# add in number of cases and sample sizes
for (k in seq_along(R2_results_exp2)) {

    table_exp2[k,4] <- R2_results_exp2[[k]][[1]]$nevent
    table_exp2[k,5] <- R2_results_exp2[[k]][[1]]$n
}

### save
save(R2_results_exp2,
     table_exp2,
     file = paste0(path, "/results/incident disease/R2_models_sept_10_2022_exposome_sig_only.RData"))

# export all results as single xlsx file
file <- paste0(path, "/output/incident disease/R2_table_sept_10_2022_exposome_sig_only.xlsx")

# first sheet
write.xlsx(
    table_exp2,
    file = file,
    sheetName = "R-squared",
    row.names = FALSE
)

```

```{r ph_check_exp, eval=FALSE}

load(paste0(path, "/datasets/R2_model_datasets_nov_09_2022.RData"))
load(paste0(path, "/results/incident disease/R2_models_nov_09_2022_exposome.RData"))

sig_exposures <- sapply(exposures_list, length)
sig_exposures <- which(sig_exposures != 0)
cph_identify_prev <- identify_prev_cases_list[sig_exposures]
surv_list <- surv_list[sig_exposures]
model_exposures <- lapply(exposures_list, paste, collapse = " + ")
model_exposures <- model_exposures[sig_exposures]

j <- 1

test <- as.list(seq_along(cph_identify_prev))
for (k in 1:length(cph_identify_prev)) {
    data <- lapply(all_data_ncd, cph_identify_prev[[k]])
    test[[k]] <- cox.zph(R2_results_exp[[k]][[j]])
    rm(data)
    cat("\r", paste("completed:", paste(k, length(R2_results_exp), sep = "/")))
}

names(test) <- disease_list[sig_exposures]

# save
save(test,
     file = paste0(path, "/results/incident disease/cph_check_nov_09_2022_exposome.RData"))
```

```{r ph_residuals_exposome, eval=FALSE}

# load(paste0(path, "/results/incident disease/cph_check_nov_09_2022_exposome.RData"))

### find variables with low p-value from coxzph test
cph_var <- sapply(test, function(x){rownames(as.data.frame(x$table))[which(as.data.frame(x$table)$p < 0.00001)]})
cph_var <- lapply(cph_var, function(x) {x <- x[x != "GLOBAL"]})


### check schoenfield residuals for each

# residuals **could be skewed - test further
plot(test$`All-cause mortality`, var = cph_var$`All-cause mortality`, resid = TRUE)

# residuals look fine
for (k in 1:length(cph_var$`Prostate cancer`)) {
plot(test$`Prostate cancer`, var = cph_var$`Prostate cancer`[k], resid = TRUE)
}

# residuals look fine
for (k in 1:length(cph_var$`Ischemic heart disease`)) {
plot(test$`Ischemic heart disease`, var = cph_var$`Ischemic heart disease`[k], resid = TRUE)
}

# residuals look fine
for (k in 1:length(cph_var$`Emphysema, COPD`)) {
plot(test$`Emphysema, COPD`, var = cph_var$`Emphysema, COPD`[k], resid = TRUE)
}

# residuals look fine
plot(test$`Chronic liver diseases`, var = cph_var$`Chronic liver diseases`, resid = TRUE)

# residuals look fine
for (k in 1:length(cph_var$`Chronic kidney diseases`)) {
plot(test$`Chronic kidney diseases`, var = cph_var$`Chronic kidney diseases`[k], resid = TRUE)
}

# residuals look fine
plot(test$`Rheumatoid arthritis`, var = cph_var$`Rheumatoid arthritis`, resid = TRUE)

# residuals look fine
for (k in 1:length(cph_var$Osteoarthritis)) {
plot(test$Osteoarthritis, var = cph_var$Osteoarthritis[k], resid = TRUE)
}

# one variable to correct:
## all-cause mortality

```

```{r ph_run_models_exposome}

# get list of outcomes to redo with time interaction
# redo <- which(names(cph_var) %in% c("All-cause mortality"))
redo <- 1

# make index of diseases with at least 1 significant exposure
sig_exposures <- sapply(exposures_list, length)
sig_exposures <- which(sig_exposures != 0)
cph_exposures_list <- exposures_list[sig_exposures]
cph_identify_prev <- identify_prev_cases_list[sig_exposures]
surv_list_time <- surv_list_tt[sig_exposures]
cph_indicator <- indicator[sig_exposures]
cph_surv <- surv_time[sig_exposures]
ph.test <- as.list(seq(1, length(R2_results_exp)))

# make model exposures
time_int_var <- as.list(seq(1, length(R2_results_exp)))
names(time_int_var) <- names(R2_results_exp)

for (k in redo) {
    time_int_var[[k]] <- paste0(time_int_var[[k]], ":Start_time")
}

for (k in seq_along(time_int_var)[-redo]) {
    time_int_var[[k]] <- vector()
}

time_int_var <- lapply(time_int_var, function(x) paste(x, collapse = " + "))
model_exposures <- lapply(cph_exposures_list, paste, collapse = " + ")


library(magrittr)
library(Greg)

# copy old R2 results
R2_results_exp_cph <- R2_results_exp

# redo interaction models
for (k in redo) {
  
    # subset data
    data <- all_data_ncd
    data <- lapply(data, cph_identify_prev[[k]])
    
    # timesplit function
    data <- lapply(data, function(x){
        # reduce data to just colnames of model variables to improve runtime with timesplit
        x <- x[c(cph_exposures_list[[k]], cph_indicator[k], cph_surv[k], "recruitment_age", "age_scaled", "sex")]
        # turn survival time to years to be on same scale as age
        x$time <- as.numeric(x[[cph_surv[k]]] / 365.25)
        # timesplit data
        x <- x %>% 
            timeSplitter(by = 2,  
                         event_var = cph_indicator[k],
                         event_start_status = 0,
                         time_var = "time",
                         time_related_vars = "recruitment_age")
        return(x)
    })
    
    # make sub-list for model results
    R2_results_exp_cph[[k]] <- as.list(seq(1, length(data)))
    ph.test[[k]] <- as.list(seq(1, length(data)))
    # run model in each imputed dataset
    for (j in seq_along(data)) {

        R2_results_exp_cph[[k]][[j]] <-
            coxph(as.formula(
                paste(
                    paste0(
                        surv_list_time[[k]],
                        model_exposures[[k]]),
                    time_int_var[[k]], sep = " + ")
                ), data = data[[j]])
        
        # test ph assumption, stop if not fixed
        ph.test[[k]][[j]] <- cox.zph(R2_results_exp_cph[[k]][[j]])
        # trial <- any(as.data.frame(ph.test$table)$p < 0.00001)
        # if (trial == TRUE) {
            # print(ph.test)
            # stop("non-proportional hazards not fixed")
        # }
    }
    
    # remove
    rm(data)
    invisible(gc())
    
    cat("\r", paste("completed:", paste(k, length(R2_results_exp_cph), sep = "/")))
}

# create table_exp_cph for results
table_exp_cph <- data.frame(matrix(ncol = 5, nrow = length(R2_results_exp_cph)))
colnames(table_exp_cph) <- c("Disease", "C-index", "R-squared", "Cases", "Sample size")

# get R2 and C-index for all models
for (k in seq_along(R2_results_exp_cph)) {

    # get r-squared across imputations
    avg_rsq <- c(coxr2(R2_results_exp_cph[[k]][[1]])$rsq,
                 coxr2(R2_results_exp_cph[[k]][[2]])$rsq,
                 coxr2(R2_results_exp_cph[[k]][[3]])$rsq,
                 coxr2(R2_results_exp_cph[[k]][[4]])$rsq,
                 coxr2(R2_results_exp_cph[[k]][[5]])$rsq)
    
    # transform to correlation scale (sqrt)
    avg_rsq <- sapply(avg_rsq, sqrt)
    
    # transform using Fischer's Z
    avg_rsq <- sapply(avg_rsq, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_rsq <- mean(avg_rsq)
    
    # transform coefficients back to r scale
    avg_rsq <- FisherZInv(avg_rsq)
    
    # transform r squared scale
    avg_rsq <- (avg_rsq)^2
    
    # add to table_exp_cph
    table_exp_cph[k,3] <- avg_rsq
    
    
    # get c-index across imputations
    avg_index <- c(summary(R2_results_exp_cph[[k]][[1]])$concordance[1],
                   summary(R2_results_exp_cph[[k]][[2]])$concordance[1],
                   summary(R2_results_exp_cph[[k]][[3]])$concordance[1],
                   summary(R2_results_exp_cph[[k]][[4]])$concordance[1],
                   summary(R2_results_exp_cph[[k]][[5]])$concordance[1])
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table_exp_cph
    table_exp_cph[k,2] <- avg_index


}

table_exp_cph$Disease <- names(R2_results_exp_cph)

# add in number of cases and sample sizes
for (k in seq_along(R2_results_exp_cph)[-redo]) {

    table_exp_cph[k,4] <- R2_results_exp_cph[[k]][[1]]$nevent
    table_exp_cph[k,5] <- R2_results_exp_cph[[k]][[1]]$n
}

# use old table for new time split models, since sample will be in millions
for (k in seq_along(R2_results_exp_cph)[redo]) {

    table_exp_cph[k,4] <- table_exp[k,4]
    table_exp_cph[k,5] <- table_exp[k,5]
}


### save
save(R2_results_exp_cph,
     table_exp_cph,
     file = glue("./results/R2_models_{Sys.Date()}_exposome_cph.RData"))

```

```{r prediction_exposome, eval=TRUE}

# load(paste0(path, "/results/incident disease/R2_models_aug_25_2022_exposome.RData"))
# subset surv list
indicator_val <- indicator[sig_exposures]
surv_time_val <- surv_time[sig_exposures]

# subset prev cases function list
identify_prev_cases_list_val <- identify_prev_cases_list[sig_exposures]

# get prediction values for each disease
# pred_list <- as.list(seq_along(R2_results_exp))
# cindex_list_exp <- as.list(seq_along(R2_results_exp))

pred_list <- as.list(seq_along(R2_results_exp))
cindex_list_exp <- as.list(seq_along(R2_results_exp))
rsq_list_exp <- as.list(seq_along(R2_results_exp))

table_scotwales_exp <- data.frame(matrix(ncol = 5, nrow = length(cindex_list_exp)))
colnames(table_scotwales_exp) <- c("Disease", "C-index", "R-squared", "Cases", "Sample size")


for (k in seq_along(pred_list)) {
    
    # subset data
    data <- scotwales_ncd
    data <- lapply(data, identify_prev_cases_list_val[[k]])
    
    # make sub-list for model results
    pred_list[[k]] <- as.list(seq(1, length(data)))
    cindex_list_exp[[k]] <- as.list(seq(1, length(data)))
    rsq_list_exp[[k]] <- as.list(seq(1, length(data)))
    
    # run model in each imputed dataset
    for (j in seq_along(data)) {
        
        # get linear predictors using scotwales data
        pred_list[[k]][[j]] <-
            predict(R2_results_exp[[k]][[j]],
                    newdata = data[[j]])
        
        # Surv object in scotwales
        yrep <- Surv(data[[j]][[surv_time_val[k]]], data[[j]][[indicator_val[k]]])
        # calculate concordance outcomes using linear predictors and Surv object
        rs.corr <- rcorr.cens(x = pred_list[[k]][[j]], S = yrep)
        # take Dxy, negate, and then get C using formula Dxy=2*(C−0.5)
        cindex_list_exp[[k]][[j]] <- (-rs.corr[2]/2) + 0.5
        
        # Get R-squared using predicted values from scotwales data
        cox <- coxph(yrep ~ pred_list[[k]][[j]], data = data[[j]])
        rsq_list_exp[[k]][[j]] <- coxr2(cox)
        
    }
    
    table_scotwales_exp[k,4] <- as.numeric(table(data[[1]][indicator_val[k]])[2])
    table_scotwales_exp[k,5] <- nrow(data[[1]])
    
    # record sample size
    rm(data)
    
    cat("\r", paste("completed:", paste(k, length(pred_list), sep = "/")))
    
}

### For further discussion of Dxy calculation, see comment here from Harrell on using linear predictors with rcorr.cens: https://stats.stackexchange.com/questions/48298/computing-c-index-for-an-external-validation-of-a-cox-ph-model-with-r#comment93976_48369


# get C-index for all models
for (k in seq_along(cindex_list_exp)) {
    
    # Rsq
    avg_index <- c(rsq_list_exp[[k]][[1]]$rsq,
                   rsq_list_exp[[k]][[2]]$rsq,
                   rsq_list_exp[[k]][[3]]$rsq,
                   rsq_list_exp[[k]][[4]]$rsq,
                   rsq_list_exp[[k]][[5]]$rsq)
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table
    table_scotwales_exp[k,3] <- avg_index
    
    # C-index
    avg_index <- c(cindex_list_exp[[k]][[1]],
                   cindex_list_exp[[k]][[2]],
                   cindex_list_exp[[k]][[3]],
                   cindex_list_exp[[k]][[4]],
                   cindex_list_exp[[k]][[5]])
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table
    table_scotwales_exp[k,2] <- avg_index

}

table_scotwales_exp$Disease <- names(R2_results_exp)

### save
save(rsq_list_exp,
     cindex_list_exp,
     table_scotwales_exp,
     file = glue("./results/R2_models_{Sys.Date()}_scotwales_exposome.RData"))

```

```{r prediction_exposome_cph, eval=TRUE}

# load(paste0(path, "/results/incident disease/R2_models_sept_10_2022_scotwales_exposome.RData"))

# subset surv list
indicator_val <- indicator[sig_exposures]
surv_time_val <- surv_time[sig_exposures]

# subset prev cases function list
identify_prev_cases_list_val <- identify_prev_cases_list[sig_exposures]

# list for prediction values for each disease
pred_list <- as.list(seq_along(R2_results_exp_cph))

# copy results from previous
cindex_list_exp_cph <- cindex_list_exp
rsq_list_exp_cph <- rsq_list_exp

table_scotwales_exp_cph <- table_scotwales_exp

for (k in redo) {
    
    # subset data
    data <- scotwales_ncd
    data <- lapply(data, identify_prev_cases_list_val[[k]])
    data2 <- data
    
    data <- lapply(data, function(x){
        # reduce data to just colnames of model variables to improve runtime with timesplit
        x <- x[c(cph_exposures_list[[k]], cph_indicator[k], cph_surv[k], "recruitment_age", "age_scaled", "sex")]
        # turn survival time to years to be on same scale as age
        x$time <- as.numeric(x[[cph_surv[k]]] / 365.25)
        # timesplit data
        x <- x %>% 
            timeSplitter(by = 2,  
                         event_var = cph_indicator[k],
                         event_start_status = 0,
                         time_var = "time",
                         time_related_vars = "recruitment_age")
        return(x)
    })
    
    # make sub-list for model results
    pred_list[[k]] <- as.list(seq(1, length(data)))
    cindex_list_exp_cph[[k]] <- as.list(seq(1, length(data)))
    rsq_list_exp_cph[[k]] <- as.list(seq(1, length(data)))
    
    # run model in each imputed dataset
    for (j in seq_along(data)) {
        
        # get linear predictors using scotwales data
        pred_list[[k]][[j]] <-
            predict(R2_results_exp_cph[[k]][[j]],
                    newdata = data[[j]])
        # Surv object in scotwales using interval time for cph interaction
        yrep <- Surv(data[[j]][["Start_time"]], data[[j]][["Stop_time"]], data[[j]][[indicator_val[k]]])
        # Get R-squared using predicted values from scotwales data
        cox <- coxph(yrep ~ pred_list[[k]][[j]], data = data[[j]])
        cindex_list_exp_cph[[k]][[j]] <- summary(cox)$concordance[1]
        rsq_list_exp_cph[[k]][[j]] <- coxr2(cox)
    }
    
    # add no. cases and sample size to table
    table_scotwales_exp_cph[k,4] <- as.numeric(table(data2[[1]][indicator_val[k]])[2])
    table_scotwales_exp_cph[k,5] <- nrow(data2[[1]])
    
    # record sample size
    rm(data, data2)
    
    cat("\r", paste("completed:", paste(k, length(pred_list), sep = "/")))
    
}

### For further discussion of Dxy calculation, see comment here from Harrell on using linear predictors with rcorr.cens: https://stats.stackexchange.com/questions/48298/computing-c-index-for-an-external-validation-of-a-cox-ph-model-with-r#comment93976_48369


# get C-index for all models
for (k in redo) {
    
    # Rsq
    avg_index <- c(rsq_list_exp_cph[[k]][[1]]$rsq,
                   rsq_list_exp_cph[[k]][[2]]$rsq,
                   rsq_list_exp_cph[[k]][[3]]$rsq,
                   rsq_list_exp_cph[[k]][[4]]$rsq,
                   rsq_list_exp_cph[[k]][[5]]$rsq)
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table
    table_scotwales_exp_cph[k,3] <- avg_index
    
    # C-index
    avg_index <- c(cindex_list_exp_cph[[k]][[1]],
                   cindex_list_exp_cph[[k]][[2]],
                   cindex_list_exp_cph[[k]][[3]],
                   cindex_list_exp_cph[[k]][[4]],
                   cindex_list_exp_cph[[k]][[5]])
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table
    table_scotwales_exp_cph[k,2] <- avg_index

}

### save
save(rsq_list_exp_cph,
     cindex_list_exp_cph,
     table_scotwales_exp_cph,
     file = glue("./results/R2_models_{Sys.Date()}_scotwales_exposome_cph.RData"))

```

```{r run_models_prs_only, eval=TRUE}

PRS_index <- which(disease_list %in% PRS_disease_list)
PRS_identify_prev <- identify_prev_cases_list[PRS_index]
PRS_surv_list <- surv_list[PRS_index]

# list to store model results
R2_results_prs <- as.list(seq(1, length(PRS_disease_list)))
names(R2_results_prs) <- PRS_disease_list

# list to store sample sizes
sample_sizes <- as.list(seq(1, length(PRS_disease_list)))
names(sample_sizes) <- PRS_disease_list

# make model exposures
model_exposures <- lapply(PRS_exposures, paste, collapse = " + ")

# run all models
for (k in seq_along(R2_results_prs)) {
  
    # subset data
    data <- all_data_ncd
    data <- lapply(data, PRS_identify_prev[[k]])
    
    # make sub-list for model results
    R2_results_prs[[k]] <- as.list(seq(1, length(data)))
    
    # run model in each imputed dataset
    for (j in seq_along(data)) {

        R2_results_prs[[k]][[j]] <-
            coxph(as.formula(
                paste0(
                    PRS_surv_list[[k]],
                    model_exposures[[k]])
            ), data = data[[j]])
    }
    
    # record sample size
    rm(data)
    
    cat("\r", paste("completed:", paste(k, length(R2_results_prs), sep = "/")))
}

# create table_prs for results
table_prs <- data.frame(matrix(ncol = 5, nrow = length(R2_results_prs)))
colnames(table_prs) <- c("Disease", "C-index", "R-squared", "Cases", "Sample size")

# get R2 and C-index for all models
for (k in seq_along(R2_results_prs)) {

    # get r-squared across imputations
    avg_rsq <- c(coxr2(R2_results_prs[[k]][[1]])$rsq,
                 coxr2(R2_results_prs[[k]][[2]])$rsq,
                 coxr2(R2_results_prs[[k]][[3]])$rsq,
                 coxr2(R2_results_prs[[k]][[4]])$rsq,
                 coxr2(R2_results_prs[[k]][[5]])$rsq)
    
    # transform to correlation scale (sqrt)
    avg_rsq <- sapply(avg_rsq, sqrt)
    
    # transform using Fischer's Z
    avg_rsq <- sapply(avg_rsq, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_rsq <- mean(avg_rsq)
    
    # transform coefficients back to r scale
    avg_rsq <- FisherZInv(avg_rsq)
    
    # transform r squared scale
    avg_rsq <- (avg_rsq)^2
    
    # add to table_prs
    table_prs[k,3] <- avg_rsq
    
    
    # get c-index across imputations
    avg_index <- c(summary(R2_results_prs[[k]][[1]])$concordance[1],
                   summary(R2_results_prs[[k]][[2]])$concordance[1],
                   summary(R2_results_prs[[k]][[3]])$concordance[1],
                   summary(R2_results_prs[[k]][[4]])$concordance[1],
                   summary(R2_results_prs[[k]][[5]])$concordance[1])
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table_prs
    table_prs[k,2] <- avg_index


}

table_prs$Disease <- names(R2_results_prs)

# add in number of cases and sample sizes
for (k in seq_along(R2_results_prs)) {

    table_prs[k,4] <- R2_results_prs[[k]][[1]]$nevent
    table_prs[k,5] <- R2_results_prs[[k]][[1]]$n
}


### save
save(R2_results_prs,
     table_prs,
     file = glue("./results/R2_models_{Sys.Date()}_PRS.RData"))

```

```{r ph_check_prs, eval=FALSE}

# load(paste0(path, "/datasets/R2_model_datasets_aug_30_2022.RData"))
# load(paste0(path, "/results/incident disease/R2_models_nov_09_2022_PRS.RData"))

PRS_index <- which(disease_list %in% PRS_disease_list)

cph_identify_prev <- identify_prev_cases_list[PRS_index]
# must reset surv list above first
cph_surv_list <- surv_list[PRS_index]
model_exposures <- lapply(PRS_exposures, paste, collapse = " + ")

j <- 1

test <- as.list(seq_along(cph_identify_prev))
for (k in 1:length(cph_identify_prev)) {
    data <- lapply(all_data_ncd, cph_identify_prev[[k]])
    test[[k]] <- cox.zph(R2_results_prs[[k]][[j]])
    rm(data)
    cat("\r", paste("completed:", paste(k, length(R2_results_prs), sep = "/")))
}

names(test) <- disease_list[PRS_index]

# save
save(test,
     file = paste0(path, "/results/incident disease/cph_check_mar_15_2024_prs.RData"))
```

```{r ph_residuals_prs, eval=FALSE}

# load(paste0(path, "/results/incident disease/cph_check_nov_09_2022_prs.RData"))

### find variables with low p-value from coxzph test
cph_var <- sapply(test, function(x){rownames(as.data.frame(x$table))[which(as.data.frame(x$table)$p < 0.00001)]})
cph_var <- lapply(cph_var, function(x) {x <- x[x != "GLOBAL"]})


### check schoenfield residuals for each

# residuals **could be skewed - test further
plot(test$`All-cause mortality`, var = cph_var$`All-cause mortality`, resid = TRUE)

# residuals look fine
for (k in 1:length(cph_var$`Prostate cancer`)) {
plot(test$`Prostate cancer`, var = cph_var$`Prostate cancer`[k], resid = TRUE)
}

# residuals look fine
for (k in 1:length(cph_var$`Ischemic heart disease`)) {
plot(test$`Ischemic heart disease`, var = cph_var$`Ischemic heart disease`[k], resid = TRUE)
}

# residuals look fine
plot(test$`Rheumatoid arthritis`, var = cph_var$`Rheumatoid arthritis`, resid = TRUE)

# one variables to correct:
## all-cause mortality


```

```{r ph_run_models_prs_only}

# get index of outcomes to redo with time interaction
redo <- which(names(R2_results_prs) %in% c("All-cause mortality"))

# make index of diseases with PRS
PRS_index <- which(disease_list %in% PRS_disease_list)
cph_exposures_list <- PRS_exposures
cph_identify_prev <- identify_prev_cases_list[PRS_index]
surv_list_time <- surv_list_tt[PRS_index]
cph_indicator <- indicator[PRS_index]
cph_surv <- surv_time[PRS_index]
ph.test <- as.list(seq(1, length(R2_results_prs)))

# make model exposures
# time_int_var <- cph_var
time_int_var <- as.list(seq(1, length(R2_results_prs)))
names(time_int_var) <- PRS_disease_list

# subset to vars with bad residuals
time_int_var$`All-cause mortality` <- c("age_scaled")

for (k in redo) {
    time_int_var[[k]] <- paste0(time_int_var[[k]], ":Start_time")
}

for (k in seq_along(time_int_var)[-redo]) {
    time_int_var[[k]] <- vector()
}

time_int_var <- lapply(time_int_var, function(x) paste(x, collapse = " + "))
model_exposures <- lapply(cph_exposures_list, paste, collapse = " + ")


library(magrittr)
library(Greg)

# copy old R2 results
R2_results_prs_cph <- R2_results_prs

# redo interaction models
for (k in redo) {
  
    # subset data
    data <- all_data_ncd
    data <- lapply(data, cph_identify_prev[[k]])
    
    # timesplit function
    data <- lapply(data, function(x){
        # reduce data to just colnames of model variables to improve runtime with timesplit
        x <- x[c(cph_exposures_list[[k]], cph_indicator[k], cph_surv[k], "recruitment_age", "age_scaled", "sex")]
        # turn survival time to years to be on same scale as age
        x$time <- as.numeric(x[[cph_surv[k]]] / 365.25)
        # timesplit data
        x <- x %>% 
            timeSplitter(by = 2,  
                         event_var = cph_indicator[k],
                         event_start_status = 0,
                         time_var = "time",
                         time_related_vars = "recruitment_age")
        return(x)
    })
    
    # make sub-list for model results
    R2_results_prs_cph[[k]] <- as.list(seq(1, length(data)))
    ph.test[[k]] <- as.list(seq(1, length(data)))
    
    # run model in each imputed dataset
    for (j in seq_along(data)) {

        R2_results_prs_cph[[k]][[j]] <-
            coxph(as.formula(
                paste(
                    paste0(
                        surv_list_time[[k]],
                        model_exposures[[k]]),
                    time_int_var[[k]], sep = " + ")
                ), data = data[[j]])
        
        # test ph assumption, stop if not fixed
        ph.test[[k]][[j]] <- cox.zph(R2_results_prs_cph[[k]][[j]])
    }
    
    # remove
    rm(data)
    invisible(gc())
    
    cat("\r", paste("completed:", paste(k, length(R2_results_prs_cph), sep = "/")))
}


# create table_prs_cph for results
table_prs_cph <- data.frame(matrix(ncol = 5, nrow = length(R2_results_prs_cph)))
colnames(table_prs_cph) <- c("Disease", "C-index", "R-squared", "Cases", "Sample size")

# get R2 and C-index for all models
for (k in seq_along(R2_results_prs_cph)) {

    # get r-squared across imputations
    avg_rsq <- c(coxr2(R2_results_prs_cph[[k]][[1]])$rsq,
                 coxr2(R2_results_prs_cph[[k]][[2]])$rsq,
                 coxr2(R2_results_prs_cph[[k]][[3]])$rsq,
                 coxr2(R2_results_prs_cph[[k]][[4]])$rsq,
                 coxr2(R2_results_prs_cph[[k]][[5]])$rsq)
    
    # transform to correlation scale (sqrt)
    avg_rsq <- sapply(avg_rsq, sqrt)
    
    # transform using Fischer's Z
    avg_rsq <- sapply(avg_rsq, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_rsq <- mean(avg_rsq)
    
    # transform coefficients back to r scale
    avg_rsq <- FisherZInv(avg_rsq)
    
    # transform r squared scale
    avg_rsq <- (avg_rsq)^2
    
    # add to table_prs_cph
    table_prs_cph[k,3] <- avg_rsq
    
    
    # get c-index across imputations
    avg_index <- c(summary(R2_results_prs_cph[[k]][[1]])$concordance[1],
                   summary(R2_results_prs_cph[[k]][[2]])$concordance[1],
                   summary(R2_results_prs_cph[[k]][[3]])$concordance[1],
                   summary(R2_results_prs_cph[[k]][[4]])$concordance[1],
                   summary(R2_results_prs_cph[[k]][[5]])$concordance[1])
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table_prs_cph
    table_prs_cph[k,2] <- avg_index


}

table_prs_cph$Disease <- names(R2_results_prs_cph)

# add in number of cases and sample sizes
for (k in seq_along(R2_results_prs_cph)[-redo]) {

    table_prs_cph[k,4] <- R2_results_prs_cph[[k]][[1]]$nevent
    table_prs_cph[k,5] <- R2_results_prs_cph[[k]][[1]]$n
}

# use old table for new time split models, since sample will be in millions
for (k in seq_along(R2_results_prs_cph)[redo]) {

    table_prs_cph[k,4] <- table_prs[k,4]
    table_prs_cph[k,5] <- table_prs[k,5]
}


### save
save(R2_results_prs_cph,
     table_prs_cph,
     file = glue("./results/R2_models_{Sys.Date()}_PRS_cph.RData"))

```

```{r prediction_prs_only, eval=TRUE}

PRS_index <- which(disease_list %in% PRS_disease_list)
PRS_identify_prev <- identify_prev_cases_list[PRS_index]
PRS_surv_list <- surv_list[PRS_index]

# subset surv list
indicator_val <- indicator[PRS_index]
surv_time_val <- surv_time[PRS_index]

pred_list <- as.list(seq_along(R2_results_prs))
cindex_list_prs <- as.list(seq_along(R2_results_prs))
rsq_list_prs <- as.list(seq_along(R2_results_prs))

table_scotwales_prs <- data.frame(matrix(ncol = 5, nrow = length(cindex_list_prs)))
colnames(table_scotwales_prs) <- c("Disease", "C-index", "R-squared", "Cases", "Sample size")


for (k in seq_along(pred_list)) {
    
    # subset data
    data <- scotwales_ncd
    data <- lapply(data, PRS_identify_prev[[k]])
    
    # make sub-list for model results
    pred_list[[k]] <- as.list(seq(1, length(data)))
    cindex_list_prs[[k]] <- as.list(seq(1, length(data)))
    rsq_list_prs[[k]] <- as.list(seq(1, length(data)))
    
    # run model in each imputed dataset
    for (j in seq_along(data)) {
        
        # get linear predictors using scotwales data
        pred_list[[k]][[j]] <-
            predict(R2_results_prs[[k]][[j]],
                    newdata = data[[j]])
        
        # Surv object in scotwales
        yrep <- Surv(data[[j]][[surv_time_val[k]]], data[[j]][[indicator_val[k]]])
        # calculate concordance outcomes using linear predictors and Surv object
        rs.corr <- rcorr.cens(x = pred_list[[k]][[j]], S = yrep)
        # take Dxy, negate, and then get C using formula Dxy=2*(C−0.5)
        cindex_list_prs[[k]][[j]] <- (-rs.corr[2]/2) + 0.5
        
        # Get R-squared using predicted values from scotwales data
        cox <- coxph(yrep ~ pred_list[[k]][[j]], data = data[[j]])
        rsq_list_prs[[k]][[j]] <- coxr2(cox)
        
    }
    
    table_scotwales_prs[k,4] <- as.numeric(table(data[[1]][indicator_val[k]])[2])
    table_scotwales_prs[k,5] <- nrow(data[[1]])
    
    # record sample size
    rm(data)
    
    cat("\r", paste("completed:", paste(k, length(pred_list), sep = "/")))
    
}

### For further discussion of Dxy calculation, see comment here from Harrell on using linear predictors with rcorr.cens: https://stats.stackexchange.com/questions/48298/computing-c-index-for-an-external-validation-of-a-cox-ph-model-with-r#comment93976_48369


# get C-index for all models
for (k in seq_along(cindex_list_prs)) {
    
    # Rsq
    avg_index <- c(rsq_list_prs[[k]][[1]]$rsq,
                   rsq_list_prs[[k]][[2]]$rsq,
                   rsq_list_prs[[k]][[3]]$rsq,
                   rsq_list_prs[[k]][[4]]$rsq,
                   rsq_list_prs[[k]][[5]]$rsq)
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table
    table_scotwales_prs[k,3] <- avg_index
    
    # C-index
    avg_index <- c(cindex_list_prs[[k]][[1]],
                   cindex_list_prs[[k]][[2]],
                   cindex_list_prs[[k]][[3]],
                   cindex_list_prs[[k]][[4]],
                   cindex_list_prs[[k]][[5]])
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table
    table_scotwales_prs[k,2] <- avg_index

}

table_scotwales_prs$Disease <- names(R2_results_prs)

### save
save(rsq_list_prs,
     cindex_list_prs,
     table_scotwales_prs,
     file = glue("./results/R2_models_{Sys.Date()}_scotwales_PRS.RData"))

```

```{r prediction_prs_only_cph, eval=TRUE}
# load(paste0(path, "/results/incident disease/R2_models_aug_25_2022_PRS.RData"))
# load(paste0(path, "/results/incident disease/R2_models_sept_01_2022_PRS_cph.RData"))
# load(paste0(path, "/results/incident disease/R2_models_sept_10_2022_scotwales_PRS.RData"))

# get index of outcomes to redo with time interaction
redo <- which(names(R2_results_prs_cph) %in% c("All-cause mortality"))

# subset prev cases function list
PRS_index <- which(disease_list %in% PRS_disease_list)
identify_prev_cases_list_val <- identify_prev_cases_list[PRS_index]

# subset surv list
indicator_val <- indicator[PRS_index]
surv_time_val <- surv_time[PRS_index]

# list for prediction values for each disease
pred_list <- as.list(seq_along(R2_results_prs_cph))
cindex_list_prs_cph <- cindex_list_prs
rsq_list_prs_cph <- rsq_list_prs

table_scotwales_prs_cph <- table_scotwales_prs


for (k in redo) {
    
    # subset data
    data <- scotwales_ncd
    data <- lapply(data, identify_prev_cases_list_val[[k]])
    data2 <- data
    
    # timesplit function
    data <- lapply(data, function(x){
        # reduce data to just colnames of model variables to improve runtime with timesplit
        x <- x[c(PRS_exposures[[k]], indicator_val[k], cph_surv[k], "recruitment_age", "age_scaled", "sex")]
        # turn survival time to years to be on same scale as age
        x$time <- as.numeric(x[[cph_surv[k]]] / 365.25)
        # timesplit data
        x <- x %>% 
            timeSplitter(by = 2,  
                         event_var = indicator_val[k],
                         event_start_status = 0,
                         time_var = "time",
                         time_related_vars = "recruitment_age")
        return(x)
    })
    
    # make sub-list for model results
    pred_list[[k]] <- as.list(seq(1, length(data)))
    cindex_list_prs_cph[[k]] <- as.list(seq(1, length(data)))
    rsq_list_prs_cph[[k]] <- as.list(seq(1, length(data)))
    
    # run model in each imputed dataset
    for (j in seq_along(data)) {
        
        # get linear predictors using scotwales data
        pred_list[[k]][[j]] <-
            predict(R2_results_prs_cph[[k]][[j]],
                    newdata = data[[j]])
        
        # Surv object in scotwales using interval time for cph interaction
        yrep <- Surv(data[[j]][["Start_time"]], data[[j]][["Stop_time"]], data[[j]][[indicator_val[k]]])
        # Get R-squared using predicted values from scotwales data
        cox <- coxph(yrep ~ pred_list[[k]][[j]], data = data[[j]])
        cindex_list_prs_cph[[k]][[j]] <- summary(cox)$concordance[1]
        rsq_list_prs_cph[[k]][[j]] <- coxr2(cox)
    }
    
    
    table_scotwales_prs_cph[k,4] <- as.numeric(table(data2[[1]][indicator_val[k]])[2])
    table_scotwales_prs_cph[k,5] <- nrow(data2[[1]])
    
    # record sample size
    rm(data, data2)
    
    cat("\r", paste("completed:", paste(k, length(pred_list), sep = "/")))
    
}

### For further discussion of Dxy calculation, see comment here from Harrell on using linear predictors with rcorr.cens: https://stats.stackexchange.com/questions/48298/computing-c-index-for-an-external-validation-of-a-cox-ph-model-with-r#comment93976_48369


# get C-index for all models
for (k in seq_along(cindex_list_prs_cph)) {
    
    # Rsq
    avg_index <- c(rsq_list_prs_cph[[k]][[1]]$rsq,
                   rsq_list_prs_cph[[k]][[2]]$rsq,
                   rsq_list_prs_cph[[k]][[3]]$rsq,
                   rsq_list_prs_cph[[k]][[4]]$rsq,
                   rsq_list_prs_cph[[k]][[5]]$rsq)
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table
    table_scotwales_prs_cph[k,3] <- avg_index
    
    # C-index
    avg_index <- c(cindex_list_prs_cph[[k]][[1]],
                   cindex_list_prs_cph[[k]][[2]],
                   cindex_list_prs_cph[[k]][[3]],
                   cindex_list_prs_cph[[k]][[4]],
                   cindex_list_prs_cph[[k]][[5]])
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table
    table_scotwales_prs_cph[k,2] <- avg_index

}

table_scotwales_prs_cph$Disease <- names(R2_results_prs_cph)

### save
save(rsq_list_prs_cph,
     cindex_list_prs_cph,
     table_scotwales_prs_cph,
     file = glue("./results/R2_models_{Sys.Date()}_scotwales_PRS_cph.RData"))

```

```{r run_models_exp_prs, eval=TRUE}

PRS_index <- which(disease_list %in% PRS_disease_list)
PRS_identify_prev <- identify_prev_cases_list[PRS_index]
PRS_surv_list <- surv_list[PRS_index]

# list to store model results
R2_results_exp_prs <- as.list(seq(1, length(PRS_disease_list)))
names(R2_results_exp_prs) <- PRS_disease_list

# list to store sample sizes
sample_sizes <- as.list(seq(1, length(PRS_disease_list)))
names(sample_sizes) <- PRS_disease_list

# make model exposures
model_exposures <- lapply(exposome_PRS_list, paste, collapse = " + ")

# run all models
for (k in seq_along(R2_results_exp_prs)) {
  
    # subset data
    data <- all_data_ncd
    data <- lapply(data, PRS_identify_prev[[k]])
    
    # make sub-list for model results
    R2_results_exp_prs[[k]] <- as.list(seq(1, length(data)))
    
    # run model in each imputed dataset
    for (j in seq_along(data)) {

        R2_results_exp_prs[[k]][[j]] <-
            coxph(as.formula(
                paste0(
                    PRS_surv_list[[k]],
                    model_exposures[[k]])
            ), data = data[[j]])
    }
    
    # record sample size
    rm(data)
    
    cat("\r", paste("completed:", paste(k, length(R2_results_exp_prs), sep = "/")))
}

# create table_exp_prs for results
table_exp_prs <- data.frame(matrix(ncol = 5, nrow = length(R2_results_exp_prs)))
colnames(table_exp_prs) <- c("Disease", "C-index", "R-squared", "Cases", "Sample size")

# get R2 and C-index for all models
for (k in seq_along(R2_results_exp_prs)) {

    # get r-squared across imputations
    avg_rsq <- c(coxr2(R2_results_exp_prs[[k]][[1]])$rsq,
                 coxr2(R2_results_exp_prs[[k]][[2]])$rsq,
                 coxr2(R2_results_exp_prs[[k]][[3]])$rsq,
                 coxr2(R2_results_exp_prs[[k]][[4]])$rsq,
                 coxr2(R2_results_exp_prs[[k]][[5]])$rsq)
    
    # transform to correlation scale (sqrt)
    avg_rsq <- sapply(avg_rsq, sqrt)
    
    # transform using Fischer's Z
    avg_rsq <- sapply(avg_rsq, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_rsq <- mean(avg_rsq)
    
    # transform coefficients back to r scale
    avg_rsq <- FisherZInv(avg_rsq)
    
    # transform r squared scale
    avg_rsq <- (avg_rsq)^2
    
    # add to table_exp_prs
    table_exp_prs[k,3] <- avg_rsq
    
    
    # get c-index across imputations
    avg_index <- c(summary(R2_results_exp_prs[[k]][[1]])$concordance[1],
                   summary(R2_results_exp_prs[[k]][[2]])$concordance[1],
                   summary(R2_results_exp_prs[[k]][[3]])$concordance[1],
                   summary(R2_results_exp_prs[[k]][[4]])$concordance[1],
                   summary(R2_results_exp_prs[[k]][[5]])$concordance[1])
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table_exp_prs
    table_exp_prs[k,2] <- avg_index


}

table_exp_prs$Disease <- names(R2_results_exp_prs)

# add in number of cases and sample sizes
for (k in seq_along(R2_results_exp_prs)) {

    table_exp_prs[k,4] <- R2_results_exp_prs[[k]][[1]]$nevent
    table_exp_prs[k,5] <- R2_results_exp_prs[[k]][[1]]$n
}


### save
save(R2_results_exp_prs,
     table_exp_prs,
     file = glue("./results/R2_models_{Sys.Date()}_exp_PRS.RData"))

```

```{r ph_run_models_exp_prs}

# get index of outcomes to redo with time interaction
redo <- which(names(R2_results_exp_prs) %in% c("All-cause mortality"))

# make index of diseases with PRS
PRS_index <- which(disease_list %in% PRS_disease_list)
cph_exposures_list <- exposome_PRS_list
cph_identify_prev <- identify_prev_cases_list[PRS_index]
surv_list_time <- surv_list_tt[PRS_index]
cph_indicator <- indicator[PRS_index]
cph_surv <- surv_time[PRS_index]
ph.test <- as.list(seq(1, length(R2_results_exp_prs)))

# make model exposures
# time_int_var <- cph_var
time_int_var <- as.list(seq(1, length(R2_results_exp_prs)))
names(time_int_var) <- PRS_disease_list

# subset to vars with bad residuals
time_int_var$`All-cause mortality` <- c("age_scaled")

for (k in redo) {
    time_int_var[[k]] <- paste0(time_int_var[[k]], ":Start_time")
}

for (k in seq_along(time_int_var)[-redo]) {
    time_int_var[[k]] <- vector()
}

time_int_var <- lapply(time_int_var, function(x) paste(x, collapse = " + "))
model_exposures <- lapply(cph_exposures_list, paste, collapse = " + ")


library(magrittr)
library(Greg)

# copy old R2 results
R2_results_exp_prs_cph <- R2_results_exp_prs

# redo interaction models
for (k in redo) {
  
    # subset data
    data <- all_data_ncd
    data <- lapply(data, cph_identify_prev[[k]])
    
    # timesplit function
    data <- lapply(data, function(x){
        # reduce data to just colnames of model variables to improve runtime with timesplit
        x <- x[c(cph_exposures_list[[k]], cph_indicator[k], cph_surv[k], "recruitment_age", "age_scaled", "sex")]
        # turn survival time to years to be on same scale as age
        x$time <- as.numeric(x[[cph_surv[k]]] / 365.25)
        # timesplit data
        x <- x %>% 
            timeSplitter(by = 2,  
                         event_var = cph_indicator[k],
                         event_start_status = 0,
                         time_var = "time",
                         time_related_vars = "recruitment_age")
        return(x)
    })
    
    # make sub-list for model results
    R2_results_exp_prs_cph[[k]] <- as.list(seq(1, length(data)))
    ph.test[[k]] <- as.list(seq(1, length(data)))
    
    # run model in each imputed dataset
    for (j in seq_along(data)) {

        R2_results_exp_prs_cph[[k]][[j]] <-
            coxph(as.formula(
                paste(
                    paste0(
                        surv_list_time[[k]],
                        model_exposures[[k]]),
                    time_int_var[[k]], sep = " + ")
                ), data = data[[j]])
        
        # test ph assumption, stop if not fixed
        ph.test[[k]][[j]] <- cox.zph(R2_results_exp_prs_cph[[k]][[j]])
    }
    
    # remove
    rm(data)
    invisible(gc())
    
    cat("\r", paste("completed:", paste(k, length(R2_results_exp_prs_cph), sep = "/")))
}


# create table_exp_prs_cph for results
table_exp_prs_cph <- data.frame(matrix(ncol = 5, nrow = length(R2_results_exp_prs_cph)))
colnames(table_exp_prs_cph) <- c("Disease", "C-index", "R-squared", "Cases", "Sample size")

# get R2 and C-index for all models
for (k in seq_along(R2_results_exp_prs_cph)) {

    # get r-squared across imputations
    avg_rsq <- c(coxr2(R2_results_exp_prs_cph[[k]][[1]])$rsq,
                 coxr2(R2_results_exp_prs_cph[[k]][[2]])$rsq,
                 coxr2(R2_results_exp_prs_cph[[k]][[3]])$rsq,
                 coxr2(R2_results_exp_prs_cph[[k]][[4]])$rsq,
                 coxr2(R2_results_exp_prs_cph[[k]][[5]])$rsq)
    
    # transform to correlation scale (sqrt)
    avg_rsq <- sapply(avg_rsq, sqrt)
    
    # transform using Fischer's Z
    avg_rsq <- sapply(avg_rsq, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_rsq <- mean(avg_rsq)
    
    # transform coefficients back to r scale
    avg_rsq <- FisherZInv(avg_rsq)
    
    # transform r squared scale
    avg_rsq <- (avg_rsq)^2
    
    # add to table_exp_prs_cph
    table_exp_prs_cph[k,3] <- avg_rsq
    
    
    # get c-index across imputations
    avg_index <- c(summary(R2_results_exp_prs_cph[[k]][[1]])$concordance[1],
                   summary(R2_results_exp_prs_cph[[k]][[2]])$concordance[1],
                   summary(R2_results_exp_prs_cph[[k]][[3]])$concordance[1],
                   summary(R2_results_exp_prs_cph[[k]][[4]])$concordance[1],
                   summary(R2_results_exp_prs_cph[[k]][[5]])$concordance[1])
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table_exp_prs_cph
    table_exp_prs_cph[k,2] <- avg_index


}

table_exp_prs_cph$Disease <- names(R2_results_exp_prs_cph)

# add in number of cases and sample sizes
for (k in seq_along(R2_results_exp_prs_cph)[-redo]) {

    table_exp_prs_cph[k,4] <- R2_results_exp_prs_cph[[k]][[1]]$nevent
    table_exp_prs_cph[k,5] <- R2_results_exp_prs_cph[[k]][[1]]$n
}

# use old table for new time split models, since sample will be in millions
for (k in seq_along(R2_results_exp_prs_cph)[redo]) {

    table_exp_prs_cph[k,4] <- table_exp_prs[k,4]
    table_exp_prs_cph[k,5] <- table_exp_prs[k,5]
}


### save
save(R2_results_exp_prs_cph,
     table_exp_prs_cph,
     file = glue("./results/R2_models_{Sys.Date()}_exp_PRS_cph.RData"))

```

```{r prediction_exp_prs, eval=TRUE}

PRS_index <- which(disease_list %in% PRS_disease_list)
PRS_identify_prev <- identify_prev_cases_list[PRS_index]
PRS_surv_list <- surv_list[PRS_index]

# subset surv list
indicator_val <- indicator[PRS_index]
surv_time_val <- surv_time[PRS_index]

pred_list <- as.list(seq_along(R2_results_exp_prs))
cindex_list_exp_prs <- as.list(seq_along(R2_results_exp_prs))
rsq_list_exp_prs <- as.list(seq_along(R2_results_exp_prs))

table_scotwales_exp_prs <- data.frame(matrix(ncol = 5, nrow = length(cindex_list_exp_prs)))
colnames(table_scotwales_exp_prs) <- c("Disease", "C-index", "R-squared", "Cases", "Sample size")


for (k in seq_along(pred_list)) {
    
    # subset data
    data <- scotwales_ncd
    data <- lapply(data, PRS_identify_prev[[k]])
    
    # make sub-list for model results
    pred_list[[k]] <- as.list(seq(1, length(data)))
    cindex_list_exp_prs[[k]] <- as.list(seq(1, length(data)))
    rsq_list_exp_prs[[k]] <- as.list(seq(1, length(data)))
    
    # run model in each imputed dataset
    for (j in seq_along(data)) {
        
        # get linear predictors using scotwales data
        pred_list[[k]][[j]] <-
            predict(R2_results_exp_prs[[k]][[j]],
                    newdata = data[[j]])
        
        # Surv object in scotwales
        yrep <- Surv(data[[j]][[surv_time_val[k]]], data[[j]][[indicator_val[k]]])
        # calculate concordance outcomes using linear predictors and Surv object
        rs.corr <- rcorr.cens(x = pred_list[[k]][[j]], S = yrep)
        # take Dxy, negate, and then get C using formula Dxy=2*(C−0.5)
        cindex_list_exp_prs[[k]][[j]] <- (-rs.corr[2]/2) + 0.5
        
        # Get R-squared using predicted values from scotwales data
        cox <- coxph(yrep ~ pred_list[[k]][[j]], data = data[[j]])
        rsq_list_exp_prs[[k]][[j]] <- coxr2(cox)
        
    }
    
    table_scotwales_exp_prs[k,4] <- as.numeric(table(data[[1]][indicator_val[k]])[2])
    table_scotwales_exp_prs[k,5] <- nrow(data[[1]])
    
    # record sample size
    rm(data)
    
    cat("\r", paste("completed:", paste(k, length(pred_list), sep = "/")))
    
}

### For further discussion of Dxy calculation, see comment here from Harrell on using linear predictors with rcorr.cens: https://stats.stackexchange.com/questions/48298/computing-c-index-for-an-external-validation-of-a-cox-ph-model-with-r#comment93976_48369


# get C-index for all models
for (k in seq_along(cindex_list_exp_prs)) {
    
    # Rsq
    avg_index <- c(rsq_list_exp_prs[[k]][[1]]$rsq,
                   rsq_list_exp_prs[[k]][[2]]$rsq,
                   rsq_list_exp_prs[[k]][[3]]$rsq,
                   rsq_list_exp_prs[[k]][[4]]$rsq,
                   rsq_list_exp_prs[[k]][[5]]$rsq)
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table
    table_scotwales_exp_prs[k,3] <- avg_index
    
    # C-index
    avg_index <- c(cindex_list_exp_prs[[k]][[1]],
                   cindex_list_exp_prs[[k]][[2]],
                   cindex_list_exp_prs[[k]][[3]],
                   cindex_list_exp_prs[[k]][[4]],
                   cindex_list_exp_prs[[k]][[5]])
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table
    table_scotwales_exp_prs[k,2] <- avg_index

}

table_scotwales_exp_prs$Disease <- names(R2_results_exp_prs)

### save
save(rsq_list_exp_prs,
     cindex_list_exp_prs,
     table_scotwales_exp_prs,
     file = glue("./results/R2_models_{Sys.Date()}_scotwales_exp_PRS.RData"))

```

```{r prediction_exp_prs_cph, eval=TRUE}
# load(paste0(path, "/results/incident disease/R2_models_aug_25_2022_PRS.RData"))
# load(paste0(path, "/results/incident disease/R2_models_sept_01_2022_PRS_cph.RData"))
# load(paste0(path, "/results/incident disease/R2_models_sept_10_2022_scotwales_PRS.RData"))

# get index of outcomes to redo with time interaction
redo <- which(names(R2_results_exp_prs_cph) %in% c("All-cause mortality"))

# subset prev cases function list
PRS_index <- which(disease_list %in% PRS_disease_list)
identify_prev_cases_list_val <- identify_prev_cases_list[PRS_index]

# subset surv list
indicator_val <- indicator[PRS_index]
surv_time_val <- surv_time[PRS_index]

# list for prediction values for each disease
pred_list <- as.list(seq_along(R2_results_exp_prs_cph))
cindex_list_exp_prs_cph <- cindex_list_exp_prs
rsq_list_exp_prs_cph <- rsq_list_exp_prs

table_scotwales_exp_prs_cph <- table_scotwales_exp_prs


for (k in redo) {
    
    # subset data
    data <- scotwales_ncd
    data <- lapply(data, identify_prev_cases_list_val[[k]])
    data2 <- data
    
    # timesplit function
    data <- lapply(data, function(x){
        # reduce data to just colnames of model variables to improve runtime with timesplit
        x <- x[c(exposome_PRS_list[[k]], indicator_val[k], cph_surv[k], "recruitment_age", "age_scaled", "sex")]
        # turn survival time to years to be on same scale as age
        x$time <- as.numeric(x[[cph_surv[k]]] / 365.25)
        # timesplit data
        x <- x %>% 
            timeSplitter(by = 2,  
                         event_var = indicator_val[k],
                         event_start_status = 0,
                         time_var = "time",
                         time_related_vars = "recruitment_age")
        return(x)
    })
    
    # make sub-list for model results
    pred_list[[k]] <- as.list(seq(1, length(data)))
    cindex_list_exp_prs_cph[[k]] <- as.list(seq(1, length(data)))
    rsq_list_exp_prs_cph[[k]] <- as.list(seq(1, length(data)))
    
    # run model in each imputed dataset
    for (j in seq_along(data)) {
        
        # get linear predictors using scotwales data
        pred_list[[k]][[j]] <-
            predict(R2_results_exp_prs_cph[[k]][[j]],
                    newdata = data[[j]])
        
        # Surv object in scotwales using interval time for cph interaction
        yrep <- Surv(data[[j]][["Start_time"]], data[[j]][["Stop_time"]], data[[j]][[indicator_val[k]]])
        # Get R-squared using predicted values from scotwales data
        cox <- coxph(yrep ~ pred_list[[k]][[j]], data = data[[j]])
        cindex_list_exp_prs_cph[[k]][[j]] <- summary(cox)$concordance[1]
        rsq_list_exp_prs_cph[[k]][[j]] <- coxr2(cox)
    }
    
    
    table_scotwales_exp_prs_cph[k,4] <- as.numeric(table(data2[[1]][indicator_val[k]])[2])
    table_scotwales_exp_prs_cph[k,5] <- nrow(data2[[1]])
    
    # record sample size
    rm(data, data2)
    
    cat("\r", paste("completed:", paste(k, length(pred_list), sep = "/")))
    
}

### For further discussion of Dxy calculation, see comment here from Harrell on using linear predictors with rcorr.cens: https://stats.stackexchange.com/questions/48298/computing-c-index-for-an-external-validation-of-a-cox-ph-model-with-r#comment93976_48369


# get C-index for all models
for (k in seq_along(cindex_list_exp_prs_cph)) {
    
    # Rsq
    avg_index <- c(rsq_list_exp_prs_cph[[k]][[1]]$rsq,
                   rsq_list_exp_prs_cph[[k]][[2]]$rsq,
                   rsq_list_exp_prs_cph[[k]][[3]]$rsq,
                   rsq_list_exp_prs_cph[[k]][[4]]$rsq,
                   rsq_list_exp_prs_cph[[k]][[5]]$rsq)
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table
    table_scotwales_exp_prs_cph[k,3] <- avg_index
    
    # C-index
    avg_index <- c(cindex_list_exp_prs_cph[[k]][[1]],
                   cindex_list_exp_prs_cph[[k]][[2]],
                   cindex_list_exp_prs_cph[[k]][[3]],
                   cindex_list_exp_prs_cph[[k]][[4]],
                   cindex_list_exp_prs_cph[[k]][[5]])
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table
    table_scotwales_exp_prs_cph[k,2] <- avg_index

}

table_scotwales_exp_prs_cph$Disease <- names(R2_results_exp_prs_cph)

### save
save(rsq_list_exp_prs_cph,
     cindex_list_exp_prs_cph,
     table_scotwales_exp_prs_cph,
     file = glue("./results/R2_models_{Sys.Date()}_scotwales_exp_PRS_cph.RData"))

```

```{r combined_table, eval=FALSE}

# load("./results/R2_models_2024-05-03_age_sex.RData")
# load("./results/R2_models_2024-05-03_exposome_cph.RData")
# load("./results/R2_models_2024-05-03_PRS_cph.RData")
# load("./results/R2_models_2024-05-03_exp_PRS_cph.RData")

colnames(table_as) <- paste(colnames(table_as), "_ageSex") 
colnames(table_as)[1] <- "Disease"

# colnames(table_exp) <- paste(colnames(table_exp), "_exp") 
# colnames(table_exp)[1] <- "Disease"
colnames(table_exp_cph) <- paste(colnames(table_exp_cph), "_exp")
colnames(table_exp_cph)[1] <- "Disease"

# colnames(table_prs) <- paste(colnames(table_prs), "_PRS") 
# colnames(table_prs)[1] <- "Disease"
colnames(table_prs_cph) <- paste(colnames(table_prs_cph), "_PRS")
colnames(table_prs_cph)[1] <- "Disease"

# colnames(table_clin) <- paste(colnames(table_clin), "_clinical") 
# colnames(table_clin)[1] <- "Disease"
colnames(table_exp_prs_cph) <- paste(colnames(table_exp_prs_cph), "_exp_PRS") 
colnames(table_exp_prs_cph)[1] <- "Disease"

table_combined <-
    merge(table_as,
          # table_exp,
          table_prs_cph,
          by = "Disease",
          all.x = TRUE,
          all.y = FALSE)

table_combined <-
    merge(table_combined,
          # table_prs,
          table_exp_cph,
          by = "Disease",
          all.x = TRUE,
          all.y = FALSE)

table_combined <-
    merge(table_combined,
          # table_clin,
          table_exp_prs_cph,
          by = "Disease",
          all.x = TRUE,
          all.y = FALSE)

new_order <- colnames(table_combined)[c(1,2,6,10,14,3,7,11,15,4,8,12,16,5,9,13,17)]
row_order <- order(table_combined$`R-squared _exp`, decreasing = TRUE)
mort_ind <- which(table_combined$Disease == "All-cause mortality")
row_order <- c(mort_ind, row_order[which(row_order != mort_ind)])
table_combined <- table_combined[row_order, new_order]

# make combined exposome + PRS table
colnames(table_combined) <- c("Disease", 
                              "Model 1 C-index",
                              "Model 2 C-index", 
                              "Model 3 C-index", 
                              "Model 4 C-index",
                              "Model 1 R\u00B2", 
                              "Model 2 R\u00B2", 
                              "Model 3 R\u00B2",
                              "Model 4 R\u00B2",
                              "Cases",
                              "Cases PRS",
                              "Cases exposome",
                              "Cases exposome + PRS",
                              "Sample",
                              "Sample PRS",
                              "Sample exposome",
                              "Sample exposome + PRS")

table_combined_red <- table_combined
table_combined_red$Cases <- 
    ifelse(
        !is.na(table_combined$`Model 2 C-index`),
        paste(trimws(format(table_combined$`Cases exposome + PRS`, big.mark = ",")),
              trimws(format(table_combined$Cases, big.mark = ",")), sep = " - "),
        paste(trimws(format(table_combined$`Cases exposome`, big.mark = ",")),
              trimws(format(table_combined$Cases, big.mark = ",")), sep = " - ")
    )

table_combined_red$Sample <- 
    ifelse(
        !is.na(table_combined$`Model 2 C-index`),
        paste(trimws(format(table_combined$`Sample exposome + PRS`, big.mark = ",")),
              trimws(format(table_combined$Sample, big.mark = ",")), sep = " - "),
        paste(trimws(format(table_combined$`Sample exposome`, big.mark = ",")),
              trimws(format(table_combined$Sample, big.mark = ",")), sep = " - ")
    )

table_combined_red <- table_combined_red[c(1:10,14)]

library(flextable)
table_combinedfl <- 
    flextable(table_combined_red) %>%
    add_header_row(top = TRUE, values = "Table S15. Explained variation and C-index across multivariable models in UK Biobank participants recruited in England", colwidths = 11) %>%
    width(j = 1, 1.7) %>%
    width(j = c(2:9), 0.63) %>%
    width(j = 10, 1.1) %>%
    width(j = 11, 1.3) %>%
    align(j = c(10:11), align = "right", part = "body") %>%
    align(j = c(10:11), align = "center", part = "header") %>%
    padding(padding.top = 0, padding.bottom = 0,part = "body") %>% 
    font(fontname = "Arial", part = "all") 

table_combinedfl <- 
    colformat_double(x = table_combinedfl,
                     j = c(1:9),
                     digits = 4,
                     na_str = "-")

table_combinedfl <- 
    colformat_double(x = table_combinedfl,
                     j = c(10:11),
                     big.mark = ",",
                     digits = 0)

library(officer)
sect_properties <- prop_section(
  page_size = page_size(orient = "landscape"),
  type = "continuous",
  page_margins = page_mar()
)

# save
save_as_docx(table_combinedfl, pr_section = sect_properties, path = glue("./output/rsq_all_England_{Sys.Date()}_cph.docx"))

```

```{r combined_table_validation}

load("./results/R2_models_2024-08-20_scotwales_age_sex.RData")
load("./results/R2_models_2024-08-20_scotwales_exposome_cph.RData")
load("./results/R2_models_2024-08-20_scotwales_PRS_cph.RData")
load("./results/R2_models_2024-08-20_scotwales_exp_PRS_cph.RData")

### validation
colnames(table_scotwales_as) <- paste(colnames(table_scotwales_as), "_ageSex") 
colnames(table_scotwales_as)[1] <- "Disease"
# 
# colnames(table_scotwales_exp) <- paste(colnames(table_scotwales_exp), "_exp") 
# colnames(table_scotwales_exp)[1] <- "Disease"

colnames(table_scotwales_exp_cph) <- paste(colnames(table_scotwales_exp_cph), "_exp")
colnames(table_scotwales_exp_cph)[1] <- "Disease"

# colnames(table_scotwales_prs) <- paste(colnames(table_scotwales_prs), "_PRS") 
# colnames(table_scotwales_prs)[1] <- "Disease"
colnames(table_scotwales_prs_cph) <- paste(colnames(table_scotwales_prs_cph), "_PRS")
colnames(table_scotwales_prs_cph)[1] <- "Disease"

# colnames(table_scotwales_clin) <- paste(colnames(table_scotwales_clin), "_clin") 
# colnames(table_scotwales_clin)[1] <- "Disease"
colnames(table_scotwales_exp_prs_cph) <- paste(colnames(table_scotwales_exp_prs_cph), "_clin")
colnames(table_scotwales_exp_prs_cph)[1] <- "Disease"

table_combined_sw <-
    merge(table_scotwales_as,
          # table_scotwales_exp,
          table_scotwales_prs_cph,
          by = "Disease",
          all.x = TRUE,
          all.y = FALSE)

table_combined_sw <-
    merge(table_combined_sw,
          # table_scotwales_prs,
          table_scotwales_exp_cph,
          by = "Disease",
          all.x = TRUE,
          all.y = FALSE)

table_combined_sw <-
    merge(table_combined_sw,
          # table_scotwales_clin,
          table_scotwales_exp_prs_cph,
          by = "Disease",
          all.x = TRUE,
          all.y = FALSE)

new_order <- colnames(table_combined_sw)[c(1,2,6,10,14,3,7,11,15,4,8,12,16,5,9,13,17)]
row_order <- order(table_combined_sw$`R-squared _exp`, decreasing = TRUE)
mort_ind <- which(table_combined_sw$Disease == "All-cause mortality")
row_order <- c(mort_ind, row_order[which(row_order != mort_ind)])
table_combined_sw <- table_combined_sw[row_order, new_order]

# make combined exposome + PRS table
colnames(table_combined_sw) <- c("Disease", 
                                 "Model 1 C-index",
                                 "Model 2 C-index", 
                                 "Model 3 C-index", 
                                 "Model 4 C-index",
                                 "Model 1 R\u00B2", 
                                 "Model 2 R\u00B2", 
                                 "Model 3 R\u00B2",
                                 "Model 4 R\u00B2",
                                 "Cases",
                                 "Cases PRS",
                                 "Cases exposome",
                                 "Cases exposome + PRS",
                                 "Sample",
                                 "Sample PRS",
                                 "Sample exposome",
                                 "Sample exposome + PRS")

table_combined_sw_red <- table_combined_sw[c(1:10,14)]

library(flextable)
table_combined_swfl <- 
    flextable(table_combined_sw_red) %>%
    add_header_row(top = TRUE, values = "Table S16. Explained variation and C-index across multivariable models in UK Biobank participants recruited in Scotland/Wales", colwidths = 11) %>%
    width(j = 1, 1.7) %>%
    width(j = c(2:9), 0.63) %>%
    width(j = 10, 0.63) %>%
    width(j = 11, 0.7) %>%
    align(j = c(10:11), align = "right", part = "body") %>%
    align(j = c(10:11), align = "right", part = "header") %>%
    padding(padding.top = 0, padding.bottom = 0,part = "body") %>% 
    font(fontname = "Arial", part = "all") 

table_combined_swfl <- 
    colformat_double(x = table_combined_swfl,
                     j = c(1:9),
                     digits = 4,
                     na_str = "-")

table_combined_swfl <- 
    colformat_double(x = table_combined_swfl,
                     j = c(10:11),
                     big.mark = ",",
                     digits = 0)

library(officer)
sect_properties <- prop_section(
  page_size = page_size(orient = "landscape"),
  type = "continuous",
  page_margins = page_mar()
)

# save
save_as_docx(table_combined_swfl, pr_section = sect_properties, path = glue("./output/rsq_all_scotwales_{Sys.Date()}_cph.docx"))

```

```{r age_band_sensitivity}

# make model exposures
model_exposures <- exposures_list[[1]]
model_exposures <- paste(model_exposures, collapse = " + ")


data_young <- all_data_ncd
data_old <- all_data_ncd

# subset data

# for (k in seq_along(data_young)) {
#   data_young[[k]] <- data_young[[k]][which((data_young[[k]]$recruitment_age >= 40) & (data_young[[k]]$recruitment_age < 50)), ]
# }
# 
# for (k in seq_along(data_old)) {
#   data_old[[k]] <- data_old[[k]][which((data_old[[k]]$recruitment_age >= 60) & (data_old[[k]]$recruitment_age < 70)), ]
# }

data_young <- lapply(all_data_ncd, function(x){
  x[which((x$recruitment_age >= 40) & (x$recruitment_age < 50)), ]
})

data_old <- lapply(all_data_ncd, function(x){
  x[which(x$recruitment_age >= 60 & x$recruitment_age < 70), ]
})

models_young <- lapply(data_young, function(x) {
  coxph(as.formula(
    paste0(
      surv_list[[1]],
      model_exposures)
  ), data = x)
})

models_old <- lapply(data_old, function(x) {
  coxph(as.formula(
    paste0(
      surv_list[[1]],
      model_exposures)
  ), data = x)
})

library(mice)
pooled_models_young <- pool(models_young)
pooled_models_old <- pool(models_old)

betas_young <- pooled_models_young$pooled$estimate
betas_old <- pooled_models_old$pooled$estimate

# remove first two estimates for age and sex
# betas_young <- betas_young[-c(1, 2)]
# betas_old <- betas_old[-c(1, 2)]

sig_young <- summary(pooled_models_young)$p.value
sig_young <- which(sig_young < 0.05)
# sig_young <- which(sig_young < 0.3)

sig_old <- summary(pooled_models_old)$p.value
sig_old <- which(sig_old < 0.05)
# sig_old <- which(sig_old < 0.3)

sig_both <- intersect(sig_young, sig_old)

plots_df <- as.data.frame(cbind(betas_young, betas_old))
colnames(plots_df) <- c('betas_young', 'betas_old')
rownames(plots_df) <- pooled_models_old$pooled$term

plots_df <- plots_df[sig_both, ]

# regression line for plot
beta.lm <- lm(betas_young ~ betas_old, plots_df)

pl <- plot(betas_young, betas_old, main = "", xlab = "Mortality betas (age 40-50)", ylab = "Mortality betas (age 60-70)", pch = 16, col = "blue")

library(ggrepel)
comp_plot <- 
    ggplot(
        plots_df,
        aes(x = betas_young, 
            y = betas_old
        )) +
  geom_point(
        size = 3) + 
    # ggtitle("Comparison of Mortality XWAS Hazard Ratios - Men vs. Women") +
    labs(x = "Mortality betas (age 40-50)",
         y = "Mortality betas (age 60-70)") +
    theme_classic(base_size = 18) +
    # theme(legend.position = "none") +
    geom_hline(yintercept = 0, 
               color = "gray", 
               linetype = "dashed") + 
    geom_vline(xintercept = 0, 
               color = "gray", 
               linetype = "dashed") +
    scale_x_continuous(limits = c(-1,1), breaks = seq(-1, 2, by = 1)) +
    scale_y_continuous(limits = c(-1,1), breaks = seq(-1, 2, by = 1)) +
    # scale_x_continuous(breaks = function(x) seq(ceiling(x[1]), floor(x[2]), by = 1)) +
    # scale_y_continuous(breaks = function(x) seq(ceiling(x[1]), floor(x[2]), by = 1)) +    # show correlation coefficient and p-value between betas
    stat_cor(method = "pearson",
             label.x.npc = "center",
             label.y.npc = "bottom",
             p.digits = 5,
             size = 6) +
    # show regression line between betas
    geom_abline(slope = coef(beta.lm)[[2]], 
                intercept = coef(beta.lm)[[1]],
                color = "red") 


setwd('./output/')
jpeg(glue("age_bands_mortality_{Sys.Date()}.jpeg"),
    width = 10,
    height = 7,
    units = "in",
    res = 1200)

comp_plot

dev.off()
```

```{r NCD_mortality_sensitivity}

# load data
# load("./data/R2_model_datasets_2024-08-20.RData")

# load chronic disease mortality data
load('./data/ukb_NCM_mortality_nov_01_2023.RData')

# merge
all_data_ncd <- lapply(all_data_ncd, function(x)
    as.data.frame(
        merge(x, 
              mort,
              by = "eid",
              all.x = TRUE,
              all.y = FALSE,
              sort = FALSE)
    )
)

scotwales_ncd <- lapply(scotwales_ncd, function(x)
    as.data.frame(
        merge(x, 
              mort,
              by = "eid",
              all.x = TRUE,
              all.y = FALSE,
              sort = FALSE)
    )
)

# extract mortality exposures
ncd_mort_exposures <- as.list(seq(1:3))
ncd_mort_exposures[[1]] <- paste(PRS_exposures[[1]], collapse = " + ")
ncd_mort_exposures[[2]] <- paste(exposures_list[[1]], collapse = " + ")
ncd_mort_exposures[[3]] <- paste(exposome_PRS_list[[1]], collapse = " + ")

# model names
model_names <- c('Model 2', 'Model 3', 'Model 4')

# empty list for results
table_r2 <- data.frame(matrix(ncol = 3, nrow = length(ncd_mort_exposures)))
table_r2_sw <- data.frame(matrix(ncol = 3, nrow = length(ncd_mort_exposures)))
colnames(table_r2) <- c("Model", "C-index", "R-squared")
colnames(table_r2_sw) <- c("Model", "C-index", "R-squared")

for (k in seq(1:3)) {
  
  models <- lapply(all_data_ncd, function(x) {
    coxph(as.formula(glue('Surv(NCDM_survival_time, NCDM_event_indicator) ~ recruitment_age + sex + {ncd_mort_exposures[[k]]}')), data = x)
  })
  
  # get r-squared across imputations
  avg_rsq <- c(coxr2(models[[1]])$rsq,
               coxr2(models[[2]])$rsq,
               coxr2(models[[3]])$rsq,
               coxr2(models[[4]])$rsq,
               coxr2(models[[5]])$rsq)
  
  # transform to correlation scale (sqrt)
  avg_rsq <- sapply(avg_rsq, sqrt)
  
  # transform using Fischer's Z
  avg_rsq <- sapply(avg_rsq, FisherZ)
  
  # pool coefficients (which is just the average)
  avg_rsq <- mean(avg_rsq)
  
  # transform coefficients back to r scale
  avg_rsq <- FisherZInv(avg_rsq)
  
  # transform r squared scale
  avg_rsq <- (avg_rsq)^2
  
  # add to table
  table_r2[k,3] <- avg_rsq
  
  
  # get c-index across imputations
  avg_index <- c(summary(models[[1]])$concordance[1],
                 summary(models[[2]])$concordance[1],
                 summary(models[[3]])$concordance[1],
                 summary(models[[4]])$concordance[1],
                 summary(models[[5]])$concordance[1])
  
  # transform to correlation scale (sqrt)
  avg_index <- sapply(avg_index, sqrt)
  
  # transform using Fischer's Z
  avg_index <- sapply(avg_index, FisherZ)
  
  # pool coefficients (which is just the average)
  avg_index <- mean(avg_index)
  
  # transform coefficients back to r scale
  avg_index <- FisherZInv(avg_index)
  
  # transform r squared scale
  avg_index <- (avg_index)^2
  
  # add to table
  table_r2[k,2] <- avg_index
  
  # add model name
  table_r2[k,1] <- model_names[k]
  
  ## validate in scotland/wales

  # make sub-list for model results
  pred_list <- as.list(seq(1, length(scotwales_ncd)))
  cindex_list <- as.list(seq(1, length(scotwales_ncd)))
  rsq_list <- as.list(seq(1, length(scotwales_ncd)))
    
    # run model in each imputed dataset
    for (j in seq_along(scotwales_ncd)) {

      # get linear predictors using scotwales data
      pred_list[[j]] <-
        predict(models[[j]],
                newdata = scotwales_ncd[[j]])
      
      # Surv object in scotwales
      yrep <- Surv(scotwales_ncd[[j]]$NCDM_survival_time, scotwales_ncd[[j]]$NCDM_event_indicator)
      # calculate concordance outcomes using linear predictors and Surv object
      rs.corr <- rcorr.cens(x = pred_list[[j]], S = yrep)
      # take Dxy, negate, and then get C using formula Dxy=2*(C−0.5)
      cindex_list[[j]] <- (-rs.corr[2]/2) + 0.5
      
      # Get R-squared using predicted values from scotwales data
      cox <- coxph(yrep ~ pred_list[[j]], data = scotwales_ncd[[j]])
      rsq_list[[j]] <- coxr2(cox)
      
    }
  
  # get r-squared across imputations
  avg_rsq <- c(rsq_list[[1]]$rsq,
               rsq_list[[2]]$rsq,
               rsq_list[[3]]$rsq,
               rsq_list[[4]]$rsq, 
               rsq_list[[5]]$rsq)
  
  # transform to correlation scale (sqrt)
  avg_rsq <- sapply(avg_rsq, sqrt)
  
  # transform using Fischer's Z
  avg_rsq <- sapply(avg_rsq, FisherZ)
  
  # pool coefficients (which is just the average)
  avg_rsq <- mean(avg_rsq)
  
  # transform coefficients back to r scale
  avg_rsq <- FisherZInv(avg_rsq)
  
  # transform r squared scale
  avg_rsq <- (avg_rsq)^2
  
  # add to table
  table_r2_sw[k,3] <- avg_rsq
  
  
  # get c-index across imputations
  avg_index <- c(cindex_list[[1]],
                 cindex_list[[2]],
                 cindex_list[[3]],
                 cindex_list[[4]],
                 cindex_list[[5]])
  
  # transform to correlation scale (sqrt)
  avg_index <- sapply(avg_index, sqrt)
  
  # transform using Fischer's Z
  avg_index <- sapply(avg_index, FisherZ)
  
  # pool coefficients (which is just the average)
  avg_index <- mean(avg_index)
  
  # transform coefficients back to r scale
  avg_index <- FisherZInv(avg_index)
  
  # transform r squared scale
  avg_index <- (avg_index)^2
  
  # add to table
  table_r2_sw[k,2] <- avg_index
  
  # add model name
  table_r2_sw[k,1] <- model_names[k]
  
  
  cat("\r", paste("completed:", paste(k, length(ncd_mort_exposures), sep = "/")))
}

# round to 4 digits
table_r2 <- as.data.frame(lapply(table_r2, function(x) if(is.numeric(x)) round(x, 4) else x))
table_r2_sw <- as.data.frame(lapply(table_r2_sw, function(x) if(is.numeric(x)) round(x, 4) else x))

### save
save(table_r2,
     file = glue("./results/R2_models_{Sys.Date()}_exp_PRS_NCDM.RData"))

save(table_r2_sw,
     file = glue("./results/R2_models_{Sys.Date()}_scotwales_exp_PRS_NCDM.RData"))
```

```{r, eval=FALSE}
load("./results/R2_models_2024-08-20_exp_PRS_NCDM.RData")
load("./results/R2_models_2024-08-20_scotwales_exp_PRS_NCDM.RData")

```

```{r APOE_FOXO3}

ped_FOXO3 <- read.table('./data/FOXO3_genotype.ped', h = FALSE)

# make APOE allele variable
ped_FOXO3$genotype <- paste0(ped_FOXO3[, 7], ped_FOXO3[, 8])
ped_FOXO3$genotype[which(ped_FOXO3$genotype == '00')] <- NA

# make APOE genotype variable
ped_FOXO3$FOXO3 <- factor(ped_FOXO3$genotype, ordered = FALSE)

# check most common level
sort(table(ped_FOXO3$FOXO3), decreasing = TRUE)

ped_FOXO3$FOXO3 <- relevel(ped_FOXO3$FOXO3, ref = 'TT')

# set col name for eid
colnames(ped_FOXO3)[1] <- "eid"

# check for missing
table(ped_FOXO3$FOXO3, useNA = "always")


APOE <- read.csv('./data/APOE_july_31_2023.csv')

APOE <- APOE[c('eid', 'APOE')]

APOE$APOE <- factor(APOE$APOE, ordered = FALSE)
APOE$APOE <- relevel(APOE$APOE, ref = 'e33')

genotypes <- merge(
    ped_FOXO3, 
    APOE,
    by = 'eid',
    all = TRUE,
    sort = FALSE
)

genotypes <- genotypes[c('eid', 'APOE', 'FOXO3')]
```

```{r genotype_models}

genotype_data <- lapply(all_data_ncd, function(x){
    x <- merge(x,
               genotypes,
               by = 'eid',
               all.x = TRUE,
               all.y = FALSE,
               sort = FALSE)
    return(x)
})

genotypes_scotwales <- lapply(scotwales_ncd, function(x){
    x <- merge(x,
               genotypes,
               by = 'eid',
               all.x = TRUE,
               all.y = FALSE,
               sort = FALSE)
    return(x)
})

# NCD mortality columns and surv object
NCDM_event <- 'ACM_event_indicator'
NCDM_surv <- 'Surv(ACM_survival_time, ACM_event_indicator) ~ age_scaled + sex + '
NCDM_surv_time <- 'ACM_survival_time'

# list of models
models_list <- c(
    'PRS only',
    'Exposome + PRS'
)

# list of exposures per model
NCDM_exposures <- list(
    c(PRS_exposures[[1]], 'APOE', 'FOXO3'),
    c(exposome_PRS_list[[1]], 'APOE', 'FOXO3')
)


# make model exposures
model_exposures <- lapply(NCDM_exposures, paste, collapse = " + ")

# create table for results
table_exp_prs_APOE <- data.frame(matrix(ncol = 5, nrow = length(models_list)))
colnames(table_exp_prs_APOE) <- c("Model", "C-index", "R-squared", "Cases", "Sample size")

# create table for validation results
table_scotwales_exp_prs_APOE <- data.frame(matrix(ncol = 5, nrow = length(models_list)))
colnames(table_scotwales_exp_prs_APOE) <- c("Model", "C-index", "R-squared", "Cases", "Sample size")

for (k in seq_along(models_list)) {
  
    #### English sample
    
    # remove prevalent cases
    data <- genotype_data

    # list of models
    models <- as.list(seq(1, length(data)))
    
    # run model in each imputed dataset
    for (j in seq_along(data)) {

       models[[j]] <-
            coxph(as.formula(
                paste0(
                    NCDM_surv,
                    model_exposures[[k]])
            ), data = data[[j]])
    }
    
    # remove dataset from memory
    rm(data)
    
    # get r-squared across imputations
    avg_rsq <- c(coxr2(models[[1]])$rsq,
                 coxr2(models[[2]])$rsq,
                 coxr2(models[[3]])$rsq,
                 coxr2(models[[4]])$rsq,
                 coxr2(models[[5]])$rsq)
    
    # transform to correlation scale (sqrt)
    avg_rsq <- sapply(avg_rsq, sqrt)
    
    # transform using Fischer's Z
    avg_rsq <- sapply(avg_rsq, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_rsq <- mean(avg_rsq)
    
    # transform coefficients back to r scale
    avg_rsq <- FisherZInv(avg_rsq)
    
    # transform r squared scale
    avg_rsq <- (avg_rsq)^2
    
    # get c-index across imputations
    avg_index <- c(summary(models[[1]])$concordance[1],
                   summary(models[[2]])$concordance[1],
                   summary(models[[3]])$concordance[1],
                   summary(models[[4]])$concordance[1],
                   summary(models[[5]])$concordance[1])
    
    # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # get name of disease 
    table_exp_prs_APOE[k,1] <- models_list[k]
    
    # add C-index to table
    table_exp_prs_APOE[k,2] <- avg_index
    
    # add R squared to table
    table_exp_prs_APOE[k,3] <- avg_rsq

    # add number of cases
    table_exp_prs_APOE[k,4] <- models[[1]]$nevent
    
    # add sample size
    table_exp_prs_APOE[k,5] <- models[[1]]$n
    
    
    #### validation (Scotland/Wales)
    
    # subset data
    data_val <- genotypes_scotwales
    
    # list of models
    models_val <- as.list(seq(1, length(data_val)))
    c_index_list <- as.list(seq(1, length(data_val)))
    rsq_list <- as.list(seq(1, length(data_val)))

    # run model in each imputed dataset
    for (j in seq_along(data_val)) {
        
        # get linear predictors using scotwales data
        models_val[[j]] <-
            predict(models[[j]], newdata = data_val[[j]])
        
        # Surv object in scotwales
        yrep <- Surv(data_val[[j]][[NCDM_surv_time]], data_val[[j]][[NCDM_event]])
        # calculate concordance outcomes using linear predictors and Surv object
        rs.corr <- rcorr.cens(x = models_val[[j]], S = yrep)
        # take Dxy, negate, and then get C-index using formula Dxy=2*(C−0.5)
        c_index_list[[j]] <- (-rs.corr[2]/2) + 0.5
        
        # Get R-squared using predicted values from scotwales data
        cox <- coxph(yrep ~ models_val[[j]], data = data_val[[j]])
        rsq_list[[j]] <- coxr2(cox)
        
    }
    
    # Rsq
    avg_rsq <- c(rsq_list[[1]]$rsq,
                 rsq_list[[2]]$rsq,
                 rsq_list[[3]]$rsq,
                 rsq_list[[4]]$rsq,
                 rsq_list[[5]]$rsq)
    
    # transform to correlation scale (sqrt)
    avg_rsq <- sapply(avg_rsq, sqrt)
    
    # transform using Fischer's Z
    avg_rsq <- sapply(avg_rsq, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_rsq <- mean(avg_rsq)
    
    # transform coefficients back to r scale
    avg_rsq <- FisherZInv(avg_rsq)
    
    # transform r squared scale
    avg_rsq <- (avg_rsq)^2
    
    # C-index
    avg_index <- c(c_index_list[[1]],
                   c_index_list[[2]],
                   c_index_list[[3]],
                   c_index_list[[4]],
                   c_index_list[[5]])
    
   
    ### save # transform to correlation scale (sqrt)
    avg_index <- sapply(avg_index, sqrt)
    
    # transform using Fischer's Z
    avg_index <- sapply(avg_index, FisherZ)
    
    # pool coefficients (which is just the average)
    avg_index <- mean(avg_index)
    
    # transform coefficients back to r scale
    avg_index <- FisherZInv(avg_index)
    
    # transform r squared scale
    avg_index <- (avg_index)^2
    
    # add to table
    table_scotwales_exp_prs_APOE[k,1] <- models_list[k]
    table_scotwales_exp_prs_APOE[k,2] <- avg_index
    table_scotwales_exp_prs_APOE[k,3] <- avg_rsq
    table_scotwales_exp_prs_APOE[k,4] <- as.numeric(table(data_val[[1]][NCDM_event])[2])
    table_scotwales_exp_prs_APOE[k,5] <- nrow(data_val[[1]])
    
    # remove
    rm(data_val, models, models_val)

    # show progress
    cat("\r", paste("completed:", paste(k, length(models_list), sep = "/")))
}


### save
save(table_exp_prs_APOE,
     file = glue("./results/R2_models_{Sys.Date()}_exp_PRS_APOE_FOXO3.RData"))

save(table_scotwales_exp_prs_APOE,
     file = glue("./results/R2_models_{Sys.Date()}_scotwales_exp_PRS_APOE_FOXO3.RData"))


```

```{r chisq_prep_prs}
### exposome + PRS model

# list of mortality + outcomes with c-index > 0.80
# disease_index <- c(
#     "All-cause mortality",
#     "Lung cancer",
#     "Emphysema, COPD",
#     "All-cause dementia",
#     "Vascular dementia",
#     "Alzheimer's disease",
#     # "Type II diabetes",
#     # "Osteoporosis",
#     "Chronic liver diseases"
#     # "Chronic kidney diseases"
# )

# set options for rms
options(contrasts=c("contr.treatment", "contr.treatment"))

disease_index <- disease_list[which(disease_list != "Brain cancer")]

PRS_index <- which(disease_list %in% PRS_disease_list)

# index of these diseases
cdis <- which(disease_list %in% disease_index)
comb_vars <- exposures_list
comb_vars[PRS_index] <- exposome_PRS_list

anova_df_prs <- function(x) {

    for (k in cdis) {
        
        model_list <- as.list(seq_along(x))
        
         
        if (disease_list[k] %in% c("Breast cancer", "Ovarian cancer", "Prostate cancer")) {
            
            for (i in seq_along(x)){
                model_exposures <- paste(comb_vars[[k]], collapse = " + ")
                data <- identify_prev_cases_list[[k]](x[[i]])
                S <- Surv(data[[surv_time[k]]], data[[indicator[k]]])
                model_list[[i]] <- cph(as.formula(paste("S ~ age_scaled + ",
                                                        model_exposures)),
                                       x = TRUE, y = TRUE, data = data)
                
                # df of anova results per variable
                df <- as.data.frame(anova(model_list[[i]]))
                # df <- df[c(1:(nrow(df)-1)), ]
                df$Variable <- rownames(df)
                
                if (i == 1) {
                    dw <- df[c(4,2,1)]
                } else {
                    dw <- merge(
                        dw, 
                        df[c(1,4)],
                        by = "Variable"
                    )
                }
            }
            
        } else {
            
            for (i in seq_along(x)){
                model_exposures <- paste(comb_vars[[k]], collapse = " + ")
                data <- identify_prev_cases_list[[k]](x[[i]])
                S <- Surv(data[[surv_time[k]]], data[[indicator[k]]])
                model_list[[i]] <- cph(as.formula(paste("S ~ age_scaled + sex + ",
                                                        model_exposures)),
                                       x = TRUE, y = TRUE, data = data)
                
                # df of anova results per variable
                df <- as.data.frame(anova(model_list[[i]]))
                # df <- df[c(1:(nrow(df)-1)), ]
                df$Variable <- rownames(df)
                
                if (i == 1) {
                    dw <- df[c(4,2,1)]
                } else {
                    dw <- merge(
                        dw, 
                        df[c(1,4)],
                        by = "Variable"
                    )
                }
            }
            
        }
        
        if (k == 1) {

            csub <- which(grepl("Chi-Square", colnames(dw)))
            totals <- unlist(dw[which(dw$Variable == "TOTAL"), csub])
            # dw$mean_chisq <- NA
            # for (j in 1:nrow(dw)) {
            #     dw$mean_chisq[j] <- micombine.chisquare(
            #         unlist(dw[j, csub]),
            #         df = dw$d.f.[j],
            #         display = FALSE)[1]
            # }
            
            # get percentage of total variation
            for (j in 1:nrow(dw)) {
                dw$pctexp[j] <- sum(dw[j,csub])/sum(totals)
            }
            # add group for disease
            dw$group <- disease_list[k]
            # duplicate
            rw <- dw
            
            # make df of anova results by category
            df2 <- data.frame(matrix(nrow = 3, ncol = 2))
            colnames(df2) <- c("Category", "pctexp")
            df2$Category <- c("age, sex", "exposome", "PRS")
            
            # get % explained for age + sex
            df2$pctexp[which(df2$Category == "age, sex")] <- 
                sum(dw[which(dw$Variable %in% c("age_scaled", "sex")), csub])/sum(totals)
            
            # get % explained for exposome
            df2$pctexp[which(df2$Category == "exposome")] <- 
                sum(dw[which(dw$Variable %in% exposures_list[[k]]), csub])/sum(totals)
            
            # get % explained for PRS
            df2$pctexp[which(df2$Category == "PRS")] <- 
                sum(dw[which(dw$Variable %in% PRS_list), csub])/sum(totals)
            
            df2$group <- disease_list[k]
            df2$Category <- factor(df2$Category, 
                                   levels = c("PRS",
                                              "exposome", 
                                              "age, sex"))
            
            # duplicate
            rw2 <- df2
            
        } else {
            
            csub <- which(grepl("Chi-Square", colnames(dw)))
            totals <- unlist(dw[which(dw$Variable == "TOTAL"), csub])
            # dw$mean_chisq <- NA
            # for (j in 1:nrow(dw)) {
            #     dw$mean_chisq[j] <- micombine.chisquare(
            #         unlist(dw[j, csub]),
            #         df = dw$d.f.[j],
            #         display = FALSE)[1]
            # }
            
            # get percentage of total variation
            for (j in 1:nrow(dw)) {
                dw$pctexp[j] <- sum(dw[j,csub])/sum(totals)
            }
            # add group for disease
            dw$group <- disease_list[k]
            # rbind
            rw <- rbind(rw, dw)
            
            # make df of anova results by category
            df2 <- data.frame(matrix(nrow = 3, ncol = 2))
            colnames(df2) <- c("Category", "pctexp")
            df2$Category <- c("age, sex", "exposome", "PRS")
            
            # get % explained for age + sex
            df2$pctexp[which(df2$Category == "age, sex")] <- 
                sum(dw[which(dw$Variable %in% c("age_scaled", "sex")), csub])/sum(totals)
            
            # get % explained for exposome
            df2$pctexp[which(df2$Category == "exposome")] <- 
                sum(dw[which(dw$Variable %in% exposures_list[[k]]), csub])/sum(totals)
            
            # get % explained for PRS
            df2$pctexp[which(df2$Category == "PRS")] <- 
                sum(dw[which(dw$Variable %in% PRS_list), csub])/sum(totals)
            
            df2$group <- disease_list[k]
            df2$Category <- factor(df2$Category, 
                                   levels = c("PRS",
                                              "exposome", 
                                              "age, sex"))
            # rbind
            rw2 <- rbind(rw2, df2)
        }
        cat("\r", paste("completed:", paste(which(cdis == k), length(cdis), sep = "/")))
    }
    
    # list of two df results
    rw_list <- list(
        "var" = rw,
        "cat" = rw2
    )
    
    return(rw_list)
}

# run model
plots2 <- anova_df_prs(all_data_ncd)
save(plots2,
     file = glue("./results/chisq_models_{Sys.Date()}_prs.RData"))

```

```{r process}
load("./results/chisq_models_2024-08-20_prs.RData")

disease_list <- c(
    "All-cause mortality",
    "Colorectal cancer",
    "Lung cancer",
    "Esophageal cancer",
    "Liver cancer",
    "Pancreatic cancer",
    "Brain cancer",
    "Leukemia",
    "Lymphoma",
    "Breast cancer",
    "Ovarian cancer",
    "Prostate cancer",
    "Type II diabetes",
    "Ischemic heart disease",
    "Cerebrovascular diseases",
    "Emphysema, COPD",
    "Chronic liver diseases",
    "Chronic kidney diseases",
    "All-cause dementia",
    "Vascular dementia",
    "Alzheimer's disease",
    "Parkinson's disease",
    "Macular degeneration",
    "Rheumatoid arthritis",
    "Osteoporosis",
    "Osteoarthritis"
)

disease_index <- disease_list[which(disease_list != "Brain cancer")]


plots2$cat$group <- factor(plots2$cat$group, levels = disease_index)
plots2$cat$Category <- as.character(plots2$cat$Category)
plots2$cat$Category[seq(1, 75, 3)] <- "Age and sex"
plots2$cat$Category[seq(2, 75, 3)] <- "Exposome"
plots2$cat$Category[seq(3, 75, 3)] <- "PRS"
plots2$cat$Category <- factor(plots2$cat$Category, levels = c(
    "Age and sex",
    "Exposome",
    "PRS"
))

```

```{r partial_r2}

# disease_index <- c(
#     "All-cause mortality",
#     "Lung cancer",
#     "Emphysema, COPD",
#     "All-cause dementia",
#     "Vascular dementia",
#     "Alzheimer's disease",
#     "Type II diabetes",
#     "Osteoporosis",
#     "Chronic liver diseases",
#     "Chronic kidney diseases"
# )

# disease_index <- disease_list[which(disease_list != "Brain cancer")]
# 
tab <- table_combined_sw
# row_order <- order(tab$`R2 exposome + PRS + clinical`, decreasing = TRUE)
tab <- tab[match(disease_index, tab$Disease), ]


# t1 <- table_combined_red$Disease[which(round(table_combined_red$`R2 exposome + PRS + clinical`, digits = 2) >= 0.7)]
# t2 <- tab$Disease[which(round(tab$`R2 exposome + PRS + clinical`, digits = 2) >= 0.7)]

# disease_index <- intersect(t1,t2)
# disease_index <- t2

tab$`Model 1 R²`

no_PRS_index <- which(disease_index %in% c("Liver cancer", "Lymphoma"))

partialr2 <- function(x) {
    
    bar_mat <- x[c(1,6:9)]
    bar_mat$partial_R2_prs <- 1 - ((1 - bar_mat$`Model 2 R²`) / (1 - bar_mat$`Model 1 R²`))
    bar_mat$partial_R2_exp_prs <- 1 - ((1 - bar_mat$`Model 4 R²`) / (1 - bar_mat$`Model 2 R²`))
    
    bar_mat$partial_R2_exp_prs <-
        ifelse(!is.na(bar_mat$partial_R2_prs),
               1 - ((1 - bar_mat$`Model 4 R²`) / (1 - bar_mat$`Model 2 R²`)),
               1 - ((1 - bar_mat$`Model 3 R²`) / (1 - bar_mat$`Model 1 R²`))
        )
    
    for (k in seq_along(disease_index)){
        
        if (k == 1) {
            
            mat <- as.data.frame(matrix(nrow = 3, ncol = 3))
            colnames(mat) <- c("Model", "R\u00B2", "Partial R\u00B2")
            mat$Model <- c("Age, sex", "+PRS", "+Exposome")
            
            if (k %in% no_PRS_index) {
                mat$"R\u00B2" <- as.numeric(bar_mat[which(bar_mat$Disease == disease_index[k]), c(2,3,4)])
            } else {
                mat$"R\u00B2" <- as.numeric(bar_mat[which(bar_mat$Disease == disease_index[k]), c(2,3,5)])
            }
                  
            mat$"Partial R\u00B2" <- c(NA, as.numeric(bar_mat[which(bar_mat$Disease == disease_index[k]), 6:7]))
            
            matw <- mat
            
        } else {
            
            mat <- as.data.frame(matrix(nrow = 3, ncol = 3))
            # colnames(mat) <- paste(c("Model", "R2", "Partial_R2"), k)
            colnames(mat) <- c("Model", "R\u00B2", "Partial R\u00B2")
            mat$Model <- c("Age, sex", "+PRS", "+Exposome")
            
            if (k %in% no_PRS_index) {
                mat$"R\u00B2" <- as.numeric(bar_mat[which(bar_mat$Disease == disease_index[k]), c(2,3,4)])
            } else {
                mat$"R\u00B2" <- as.numeric(bar_mat[which(bar_mat$Disease == disease_index[k]), c(2,3,5)])
            }
            
            mat$"Partial R\u00B2" <- c(NA, as.numeric(bar_mat[which(bar_mat$Disease == disease_index[k]), 6:7]))
            
            matw <- cbind(matw, mat)
        }
    }
    
    mats <- list(
        total = bar_mat,
        partial = matw
    )
    return(mats)

}

partials <- partialr2(tab)

ptable <- as.data.frame(partials$partial)
mcols <- which(grepl("Model",names(ptable)))
mcols <- mcols[-1]
ptable <- ptable[-mcols]
headers <- colnames(partials$partial)[-mcols]

for (k in 1:length(colnames(ptable))) {
    headers[k] <- paste0(headers[k], paste0(rep("\r", k), collapse = ""), collapse = "")
}
colnames(ptable) <- headers
nums <- sapply(ptable, is.numeric)
nums <- as.numeric(nums)
nums <- which(nums == 1)
ptable[nums] <- format(round(ptable[nums], digits = 4), nsmall = 4)
for (k in nums) {
    ptable[[k]][which(ptable[[k]] == "    NA")] <- "-"
    ptable[[k]][which(ptable[[k]] == "     NA")] <- "-"
}


# library(flextable)

ptable2 <- as.data.frame(t(ptable))
colnames(ptable2) <- ptable2[1, ]

ptable2 <- ptable2[-1, ]

ptable2$Model <- rownames(ptable2)

keep <- grep("Partial R", ptable2$Model)

ptable2 <- ptable2[keep, -1]

ptable2$Disease <- disease_index

ptable3 <- reshape(ptable2, 
                   direction = "long",
                   idvar = "Disease",
                   varying = list(1:2),
                   sep = "")




```

```{r R2_line_chart}
library(viridis)
library(cowplot)
library(dplyr)

# copy
plots3 <- plots2

# Calculate the proportion
plots3$cat <- plots3$cat  %>%
  group_by(group) %>%
  mutate(proportion = pctexp / sum(pctexp))

# Filter for 'Age and sex' and arrange by 'proportion' in ascending order
ordered_groups <- plots3$cat %>%
  filter(Category == "Age and sex") %>%
  # filter(Category == "Exposome") %>%
  arrange(proportion) %>%
  select(group, proportion)

# re-order
outcome_order <- as.vector(ordered_groups$group)
plots3$cat$group <- factor(plots3$cat$group, levels = outcome_order)

# subset table to necessary columns
R2_lines <- table_combined_sw_red[c(1,6:9)]

R2_lines$`Model 4 R²` <- ifelse(
    is.na(R2_lines$`Model 4 R²`),
    R2_lines$`Model 3 R²`,
    R2_lines$`Model 4 R²`
)

# re-order
R2_lines <- R2_lines[match(disease_index, R2_lines$Disease), ]

# remove column for model 3 (exposome and not PRS)
R2_lines <- R2_lines[c(1:3, 5)]

R2_lines2 <- reshape(R2_lines, 
                     direction = "long",
                     idvar = "Disease",
                     varying = list(2:ncol(R2_lines)),
                     sep = "")

R2_lines2$time <- factor(R2_lines2$time)
R2_lines2$Disease <- factor(R2_lines2$Disease, ordered = TRUE, levels = disease_index)

# Sort the data frame according to outcome_order for each time
R2_lines3 <- R2_lines2 %>%
  mutate(Disease_clean = sub("\\..*", "", Disease)) %>%  # Clean up the Disease column to match the outcome_order
  arrange(time, factor(Disease_clean, levels = outcome_order))
R2_lines3$Disease <- factor(R2_lines3$Disease, ordered = TRUE, levels = outcome_order)



# R2 plot
g4a <- ggplot(R2_lines3, aes(x = Disease, y = `Model 1 R²`, group = time)) + 
    geom_line(aes(color = time), size = 1) +
    geom_point(aes(color = time), size = 1) +
    scale_color_discrete(type = viridis(n = 3)[c(1,3,2)],
                         labels = c("Age and sex", "Age, sex, PRS", "Age, sex, PRS, exposome")
                         ) +
    # scale_fill_manual(values = pal) +
    theme_classic() +
    ylab("Model R\u00B2") +
    xlab("") +
    scale_y_continuous(limits = c(0,1), breaks = seq(0,1, by = 0.25)) +
    # scale_x_discrete(expand = expansion(mult = c(0.025, 0.01))) +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.y = element_text(size = 8),
          axis.title.y = element_text(size = 8, face = "bold", margin = margin(r = 10)),
          legend.position = "bottom",
          legend.title = element_blank(),
          legend.text = element_text(size = 8),
          legend.box.spacing = unit(0, "lines")
          )

# exposome, PRS model
g2 <- ggplot(plots3$cat, aes(x = group, y = pctexp, fill = Category)) + 
  geom_bar(position = position_fill(reverse = TRUE), stat = "identity") +
  scale_fill_manual(values = viridis(n = 3)) +
  # scale_color_discrete(type = viridis(n = 3)[c(1,3,2)]) +
  # scale_fill_viridis(discrete = T, direction = -1) +
  theme_classic() +
  ylab(expression(bold("Relative proportion of total ") * bold(chi^2))) +
  xlab("") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10)) +
  scale_y_continuous(expand = expansion(mult = c(0.025, 0.05)))

g2t <- g2 +
    theme(axis.text.x = element_text(angle = 45, 
                                     hjust = 1, size = 8, face = "bold"),
          axis.text.y = element_text(size = 8),
          axis.title.y = element_text(size = 8, 
                                      margin = margin(r = 10), face = "bold"),
          legend.text = element_text(size = 8),
          legend.title = element_blank(),
          legend.key.size = unit(1, 'lines'),
          legend.position = "bottom",
          legend.box.spacing = unit(0, "lines")  # Reduce spacing between plot and legend
          ) 

#### save plots ----
setwd("./manuscript/Revision 3/figures/")
name = "Figure_5.pdf"
width_in_inches <- 18.5 * 0.393701
height_in_inches <- 14 * 0.393701
pdf(name, width = width_in_inches, height = height_in_inches)

plot_grid(NULL, g4a, NULL,
          NULL, g2t, NULL,
          ncol = 3,
          nrow = 2,
          labels = c("a", "", "", "b", "", ""),
          label_size = 16,
          hjust = -1.5,
          vjust = c(1.5, 1.5, 1.5, 1.5, 1.5, 1.5),
          axis = "l",
          align = "v",
          # rel_heights = c(1.8, 1),
          rel_heights = c(2.5, 5),
          rel_widths = c(0.1, 1.8, 0.05)
)

dev.off()

```

```{r export_fig5_data}

color1 = "#440154FF"
color2 = "#FDE725FF"
color3 = "#21908CFF"

### Fig. 5A
R2_data <- R2_lines3

# rename
R2_data$model <- NA
R2_data$model[which(R2_data$time == 1)] <- "Age and sex"
R2_data$model[which(R2_data$time == 2)] <- "Age, sex, PRS"
R2_data$model[which(R2_data$time == 3)] <- "Age, sex, PRS, exposome"

# remove unecessary cols
R2_data <- R2_data[c(3,4,5)]

# rename
colnames(R2_data) <- c("R_squared", "Disease/Outcome", "Category")

# reorder cols
R2_data <- R2_data[c(3,2,1)]

# reorder rows
R2_data$`Disease/Outcome` <- factor(R2_data$`Disease/Outcome`, levels = outcome_order)
R2_data <- R2_data %>% arrange(`Disease/Outcome`)

# add color
R2_data$Color <- NA
R2_data$Color[which(R2_data$Category == "Age and sex")] <- color1
R2_data$Color[which(R2_data$Category == "Age, sex, PRS")] <- color2
R2_data$Color[which(R2_data$Category == "Age, sex, PRS, exposome")] <- color3

# save
file <- './press/Fig5A_data_exposome_NatureMed.csv'
write.csv(R2_data, file = file, row.names = FALSE)

### Fig. 5B

# pull out proportions for categories
Fig5b_data <- plots3$cat

# remove column
Fig5b_data <- Fig5b_data[colnames(Fig5b_data) %nin% c('pctexp')]

# rename
colnames(Fig5b_data) <- c("Category", "Disease/Outcome", "Relative_proportion_of_total_variance")

# reorder rows
Fig5b_data$`Disease/Outcome` <- factor(Fig5b_data$`Disease/Outcome`, levels = outcome_order)
Fig5b_data <- Fig5b_data %>% arrange(`Disease/Outcome`)

# add color
Fig5b_data$Color <- NA
Fig5b_data$Color[which(Fig5b_data$Category == "Age and sex")] <- color1
Fig5b_data$Color[which(Fig5b_data$Category == "PRS")] <- color2
Fig5b_data$Color[which(Fig5b_data$Category == "Exposome")] <- color3

# save
file <- './press/Fig5B_data_exposome_NatureMed.csv'
write.csv(Fig5b_data, file = file, row.names = FALSE)
```


```{r combined_plot}
library(magick)
library(flextable)
library(ggplot2)
library(grid)
library(cowplot)


# partial R2 table
# pt <- 
#     flextable(ptable) %>% 
#     add_header_row(top = TRUE, values = c("", disease_index), colwidths = c(1, rep(2, (ncol(ptable)-1)/2)))  %>% 
#     add_header_row(top = TRUE, values = "Partial R\u00B2 across outcomes - Scottish/Welsh validation set", colwidths = ncol(ptable)) %>% 
#     align(align = "left", part = "all") %>% 
#     align(align = "center", part = "header", i = 2) %>% 
#     align(align = "center", part = "body", j = seq(2,21))
# 
# 
# pt <- vline(
#     pt,
#     # i = c(1:4),
#     j = c(1, seq(3,ncol(ptable),2)),
#     part = "body"
# )
# 
# ptr <- pt %>%
#     as_raster()
# 
# gg2 <- ggplot() +
#     theme_void() +
#     annotation_custom(rasterGrob(ptr), xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf)
# 
# 
# # clinical model
# g1 <- ggplot(plots$cat, aes(x = group, y = pctexp, fill = Category)) + 
#     geom_bar(position = "fill", stat = "identity") +
#     scale_fill_viridis(discrete = T, direction = -1) +
#     theme_classic() +
#     ylab("Relative proportion of total \u03C7\u00B2") +
#     # ylab("") +
#     xlab("") +
#     theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10)) +
#     scale_y_continuous(expand = expansion(mult = c(0.025, 0.05)))
# 
# g1t <- g1 +
#     theme(axis.text.x = element_text(angle = 45, 
#                                      hjust = 1, size = 13, face = "bold"),
#           axis.text.y = element_text(size = 11),
#           axis.title.y = element_text(size = 16, 
#                                       margin = margin(r = 20), face = "bold"),
#           legend.text = element_text(size = 12),
#           legend.title = element_blank(),
#           legend.position = "bottom") 
# 

# exposome, PRS model
g2 <- ggplot(plots2$cat, aes(x = group, y = pctexp, fill = Category)) + 
    geom_bar(position = "fill", stat = "identity") +
    # scale_fill_manual(values = viridis(4)[c(4,3,1)]) +
    scale_fill_viridis(discrete = T, direction = -1) +
    theme_classic() +
    ylab("Relative proportion of total \u03C7\u00B2") +
    xlab("") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10)) +
    scale_y_continuous(expand = expansion(mult = c(0.025, 0.05)))

g2t <- g2 +
    theme(axis.text.x = element_text(angle = 45, 
                                     hjust = 1, size = 14, face = "bold"),
          axis.text.y = element_text(size = 11),
          axis.title.y = element_text(size = 16, 
                                      margin = margin(r = 20), face = "bold"),
          legend.text = element_text(size = 12),
          legend.title = element_blank(),
          legend.position = "bottom") 

library(cowplot)

setwd("./output/")
jpeg(glue("chisq_partial_R2_{Sys.Date()}.jpeg"),
    width = 16,
    height = 12,
    units = "in",
    res = 1200)
# svg("chisq_partial_R2_mar_15_2024.svg",
#     width = 16,
#     height = 12)

x <- plot_grid(g2t, g1t, ncol = 2, nrow = 1, rel_widths = c(1,1.35), rel_heights = c(1,1.1), labels = c("", "b"), label_size = 18, align = "v",
               axis = "b")

plot_grid(NULL, x, NULL,
          NULL, gg2, NULL, 
          ncol = 3,
          nrow = 2,
          labels = c("a", "", "", "c", "", ""),
          label_size = 18,
          hjust = -1.5,
          vjust = c(1.5, 1.5, 1.5, 5, 1.5, 1.5),
          axis = "l",
          align = "v",
          rel_heights = c(1.8, 1),
          rel_widths = c(0.1, 1.8, 0.05)
)
dev.off()


### full figure ----
ptable1 <- ptable[c(1:25)]
ptable2 <- ptable[c(1,26:51)]


# partial R2 table
pt1 <- 
    flextable(ptable1) %>% 
    add_header_row(top = TRUE, values = c("", disease_index[1:12]), colwidths = c(1, rep(2, 12)))  %>% 
    add_header_row(top = TRUE, values = "Partial R\u00B2 across outcomes - Scottish/Welsh validation set", colwidths = 25) %>% 
    align(align = "left", part = "all") %>% 
    align(align = "center", part = "header", i = 2) %>% 
    align(align = "center", part = "body", j = seq(2,21))

pt2 <- 
    flextable(ptable2) %>% 
    add_header_row(top = TRUE, values = c("", disease_index[13:25]), colwidths = c(1, rep(2, 13)))  %>% 
    add_header_row(top = TRUE, values = "Partial R\u00B2 across outcomes - Scottish/Welsh validation set", colwidths = 27) %>% 
    align(align = "left", part = "all") %>% 
    align(align = "center", part = "header", i = 2) %>% 
    align(align = "center", part = "body", j = seq(2,21))


pt1 <- vline(
    pt1,
    # i = c(1:4),
    j = c(1, seq(3,20,2)),
    part = "body"
)

pt2 <- vline(
    pt2,
    # i = c(1:4),
    j = c(1, seq(3,20,2)),
    part = "body"
)

ptr1 <- pt1 %>%
    as_raster()

ptr2 <- pt2 %>%
    as_raster()

gg2a <- ggplot() +
    theme_void() +
    annotation_custom(rasterGrob(ptr1), xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf)

gg2b <- ggplot() +
    theme_void() +
    annotation_custom(rasterGrob(ptr2), xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf)


# exposome, PRS model
g2 <- ggplot(plots2$cat, aes(x = group, y = pctexp, fill = Category)) + 
    geom_bar(position = "fill", stat = "identity") +
    # scale_fill_manual(values = viridis(4)[c(4,3,1)]) +
    scale_fill_viridis(discrete = T, direction = -1) +
    theme_classic() +
    ylab("Relative proportion of total \u03C7\u00B2") +
    xlab("") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10)) +
    scale_y_continuous(expand = expansion(mult = c(0.025, 0.05)))

g2t <- g2 +
    theme(axis.text.x = element_text(angle = 45, 
                                     hjust = 1, size = 14, face = "bold"),
          axis.text.y = element_text(size = 11),
          axis.title.y = element_text(size = 16, 
                                      margin = margin(r = 20), face = "bold"),
          legend.text = element_text(size = 12),
          legend.title = element_blank(),
          legend.position = "bottom") 

setwd("./output/")
jpeg(glue("chisq_partial_R2_{Sys.Date()}_all.jpeg"),
    width = 16,
    height = 12,
    units = "in",
    res = 1200)
# svg("chisq_partial_R2_dec_08_2022.svg",
#     width = 16,
#     height = 12)

# x <- plot_grid(g2t, g1t, ncol = 2, nrow = 1, rel_widths = c(1,1.35), rel_heights = c(1,1.1), labels = c("", "b"), label_size = 18, align = "v",
               # axis = "b")

plot_grid(NULL, g2t, NULL,
          NULL, gg2a, NULL, 
          NULL, gg2b, NULL,
          ncol = 3,
          # nrow = 2,
          nrow = 3,
          labels = c("a", "", "", "b", "", ""),
          label_size = 18,
          hjust = -1.5,
          vjust = c(1.5, 1.5, 1.5, 5, 1.5, 1.5),
          axis = "l",
          align = "v",
          # rel_heights = c(1.8, 1),
          rel_heights = c(2.8, 1, 1),
          rel_widths = c(0.1, 1.8, 0.05)
)
dev.off()

```

```{r pretty_labels}

pretty_lables <- function(x) {
    
    x$pretty_labels <- x$Variable
    # make pretty labels for plot
    # this section will need to be tweaked for each new set of results
    x$pretty_labels <-
        gsub("_England", "", 
             x$pretty_labels, 
             fixed = TRUE)
    x$pretty_labels <-
        gsub("_", " ",
             x$pretty_labels,
             fixed = TRUE)
    x$pretty_labels <-
        gsub("hshld", "household", 
             x$pretty_labels, 
             fixed = TRUE)
    x$pretty_labels <-
        gsub("freq", "frequency", 
             x$pretty_labels, 
             fixed = TRUE)
    x$pretty_labels <-
        gsub("prop", "prop.",
             x$pretty_labels,
             fixed = TRUE)
    x$pretty_labels <- 
        gsub("pack", "smoking pack",
             x$pretty_labels,
             fixed = TRUE)
    x$pretty_labels <- 
        gsub("tobacco", "tobacco use",
             x$pretty_labels,
             fixed = TRUE)
    x$pretty_labels <- 
        gsub("environ", "environment",
             x$pretty_labels,
             fixed = TRUE)
    x$pretty_labels <- 
        gsub("10yrs", "10 yrs",
             x$pretty_labels,
             fixed = TRUE)
    
    x$pretty_labels[x$Variable == "worry_embarassment"] <- 
        "worry after embarassment"
    
    x$pretty_labels[x$Variable == "psychiatrist_visit_mental_health"] <- 
        "psychiatrist visit for MH"
    x$pretty_labels[x$Variable == "doctor_visit_mental_health"] <- 
        "doctor visit for MH"
    
    x$pretty_labels[x$Variable == "maternal_smoking"] <- 
        "maternal smoking around birth"
    
    x$pretty_labels[x$Variable == "open_fire_heat"] <- 
        "uses open fire for heating"
    x$pretty_labels[x$Variable == "gas_hob_heat"] <- 
        "uses gas hob for heating"
    x$pretty_labels[x$Variable == "gas_fire_heat"] <- 
        "uses gas fire for heating"
    
    x$pretty_labels[x$Variable == "mobile_phone_duration"] <- 
        "years using mobile phone"
    x$pretty_labels[x$Variable == "mobile_phone_2yrs"] <- 
        "mobile phone use now vs. 2 yrs ago"
    
    x$pretty_labels[x$Variable == "sex_age_first"] <- 
        "age first sexual intercourse"
    
    x$pretty_labels[x$Variable == "easy_wake"] <- 
        "easy to wake in the morning"
    
    x$pretty_labels[x$Variable == "hshld_vehicles"] <- 
        "no. household vehicles"
    
    x$pretty_labels[x$Variable == "hshld_number"] <- 
        "no. people living in household"
    
    x$pretty_labels[x$Variable == "own_or_rent"] <- 
        "home ownership"
    
    x$pretty_labels[x$Variable == "air_pollution_PC1"] <- 
        "air pollution"
    
    x$pretty_labels[x$Variable == "greenspace_PC1"] <- 
        "greenspace"
    
    return(x)
    
}

```

```{r exposome_chisq_per_outcome}

# set options for rms
options(contrasts=c("contr.treatment", "contr.treatment"))

# list of mortality + outcomes with c-index > 0.80
disease_index <- disease_list[which(disease_list != "Brain cancer")]

# index of these diseases
cdis <- which(disease_list %in% disease_index)

# function to extra variable proportion of chisq explained
anova_df_exp <- function(x) {

    df_list <- as.list(rep(1, length(disease_list)))
    
     for (k in cdis) {
        
        model_list <- as.list(seq_along(x))
        
        if (disease_list[k] %in% c("Breast cancer", "Ovarian cancer", "Prostate cancer")) {
            
            for (i in seq_along(x)){
                model_exposures <- paste(exposures_list[[k]], collapse = " + ")
                data <- identify_prev_cases_list[[k]](x[[i]])
                S <- Surv(data[[surv_time[k]]], data[[indicator[k]]])
                model_list[[i]] <- cph(as.formula(paste("S ~ age_scaled + ",
                                                        model_exposures)),
                                       x = TRUE, y = TRUE, data = data)
                
                # df of anova results per variable
                df <- as.data.frame(anova(model_list[[i]]))
                # df <- df[c(1:(nrow(df)-1)), ]
                df$Variable <- rownames(df)
                
                if (i == 1) {
                    dw <- df[c(4,2,1)]
                } else {
                    dw <- merge(
                        dw, 
                        df[c(1,4)],
                        by = "Variable"
                    )
                }
            }
            
        } else {
            
            for (i in seq_along(x)){
                model_exposures <- paste(exposures_list[[k]], collapse = " + ")
                data <- identify_prev_cases_list[[k]](x[[i]])
                S <- Surv(data[[surv_time[k]]], data[[indicator[k]]])
                model_list[[i]] <- cph(as.formula(paste("S ~ age_scaled + sex + ",
                                                        model_exposures)),
                                       x = TRUE, y = TRUE, data = data)
                
                # df of anova results per variable
                df <- as.data.frame(anova(model_list[[i]]))
                # df <- df[c(1:(nrow(df)-1)), ]
                df$Variable <- rownames(df)
                
                if (i == 1) {
                    dw <- df[c(4,2,1)]
                } else {
                    dw <- merge(
                        dw, 
                        df[c(1,4)],
                        by = "Variable"
                    )
                }
            }
        }
        
        csub <- which(grepl("Chi-Square", colnames(dw)))
        totals <- unlist(dw[which(dw$Variable == "TOTAL"), csub])
        
        # get percentage of total variation
        for (j in 1:nrow(dw)) {
            dw$pctexp[j] <- sum(dw[j,csub])/sum(totals)
        }
        # add group for disease
        dw$group <- disease_list[k]
        # duplicate
        rw <- dw
        
        #rename
        df_list[[k]] <- dw
        
        cat("\r", paste("completed:", 
                        paste(which(cdis == k), length(cdis), sep = "/")))
     }
    names(df_list) <- disease_list
    exclude <- which(sapply(df_list, is.numeric))
    df_list <- df_list[-exclude]
    return(df_list)
}    
    
# run model
plots3 <- anova_df_exp(all_data_ncd)
save(plots3,
     file = glue("./results/chisq_models_{Sys.Date()}_exposome_indiv.RData"))
```
