
### Coding UK Biobank All-Cause Mortality

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(results = 'hide')
knitr::opts_chunk$set(eval =  FALSE)
```

``` {r mortality, results='hide'}
library(readr)

# ### import mortality data
mort <- read_delim("/path/to/file/mortality_may_04_2022.txt",
    "\t", escape_double = FALSE, trim_ws = TRUE)

### import dataset 
dat <- readRDS("/path/to/file/ukb_full_recoded_dataset_march_6_2021.rds")

### prepare death date data 

# remove duplicate date of death record row for any participant (e.g., where "ins_index = 1"). 
# date in ins_index = 1 shows the same date so it is redundant
mort <- mort[which(mort$ins_index == '0'), ]

# check how date is formatted for correct as.Date formatting
head(mort$date_of_death) 

# set as date
mort$date_of_death <- as.Date(mort$date_of_death, 
                              format = "%d/%m/%Y")

# check for any formatting errors
head(mort$date_of_death) 

# merge with full dataset
mort <- merge(mort,
              dat,
              by = "eid",
              all = TRUE,
              sort = FALSE)

### coding event indicator
mort$ACM_event_indicator <- NA
mort$ACM_event_indicator[which(!is.na(mort$date_of_death))] <- 1
mort$ACM_event_indicator[which(is.na(mort$date_of_death))] <- 0 

# censoring date
mort$ACM_censor_date <- mort$date_of_death 

# add in censor date to those who are still alive (death date = NA)

scotland <- c(
    # edinburgh
    "11005", 
    # glasgow
    "11004"
) 

# Sept 30 2021 is the suggested censor date from UKB for England/Wales as of May 20, 2022
mort$ACM_censor_date[which(is.na(mort$ACM_censor_date) & 
                               mort$recruitment_centre %nin% scotland)] <- "2021-9-30" 

# Oct 31 2021 is the suggested censor date from UKB for Scotland as of May 20, 2022
mort$ACM_censor_date[which(is.na(mort$ACM_censor_date) & 
                               mort$recruitment_centre %in% scotland)] <- "2021-10-31" 

# create survival time variable (censoring date - recruitment date)
mort$ACM_survival_time <- as.numeric(mort$ACM_censor_date - mort$recruitment_date)

# select only mortality columns
mort <- subset(mort, 
               select = c("eid",
                          "date_of_death",
                          "ACM_censor_date",
                          "ACM_survival_time",
                          "ACM_event_indicator"))

# save mortality dataset
save(mort, file = "/path/to/file/ukb_ACM_mortality_may_20_2022.RData")

```
