# Multiple imputation

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(results = 'asis')
knitr::opts_chunk$set(fig.align='center')
```

```{r import_imp, results='hide'}
library(mice)
library(survival)
library(Hmisc)
library(summarytools)
library(missRanger)
library(plotly)

# load recoded dataset
dat <- readRDS("/path/to/file/ukb_full_recoded_dataset_march_6_2021.rds")

# load mortality data
load("/path/to/file/ukb_ACM_mortality_jun_05_2021.RData")

# merge full dataset with mortality outcome data
dat <- merge(dat, 
             mort, 
             by = "eid", 
             all = TRUE) 

# remove participants who requested to be removed from UK Biobank analyses
# (eids sent in Aug 23, 2020 and January 2021 emails from UKB)
eid_remove <- c(
  Cs(
    1118928,
    1189363,
    1520532,
    1926850,
    2145109,
    2224549,
    2627502,
    3007346,
    3195734,
    3286603,
    3585254,
    3777213,
    3845241,
    4189779,
    4738692,
    5133093
  )
)

dat <- dat[which(dat$eid %nin% eid_remove), ]
```

## Participant exclusions

```{r subset_datasets, results='hide'}

### subset dataset to England participants only 

# vector of recruitment centres from scotland & wales
scot_wales <- c(
    # edinburgh
    "11005", 
    # glasgow
    "11004", 
    # cardiff
    "11003", 
    # wrexham
    "11023", 
    # swansea
    "11022" 
) 

scot_wales <- as.vector(scot_wales)

#subset to just england participants
dat_eng <- dat[which(dat$recruitment_centre %nin% scot_wales), ]
table(dat_eng$recruitment_centre) # check

# check sample sizes after removing participants 
paste("n removed excluding non-England:", (nrow(dat) - nrow(dat_eng)))

# remove empty recruitment centre response levels
levels <- levels(dat_eng$recruitment_centre)
england <- levels[levels %nin% scot_wales]
dat_eng$recruitment_centre <- factor(dat_eng$recruitment_centre, 
                                     levels = c(england),
                                     ordered = FALSE)

# remove levels with no responses for home population density after removing non-England participants
table(dat_eng$home_population_density)
levels <- levels(dat_eng$home_population_density)
scot <- c(
    "Postcode not linkable",
    "Scotland - Large Urban Area",
    "Scotland - Other Urban Area",
    "Scotland - Accessible Small Town",
    "Scotland - Remote Small Town",
    "Scotland - Accessible Rural",
    "Scotland - Remote Rural",
    "Scotland - Very Remote Rural"
)
england <- levels[levels %nin% scot]
dat_eng$home_population_density <- 
    factor(dat_eng$home_population_density, 
           levels = c(england), 
           ordered = FALSE)

rows1 <- nrow(dat_eng)

### subset dataset to only those that weren't adopted
dat_eng <- dat_eng[which(dat_eng$adopted == "No"), ]

rows2 <- nrow(dat_eng)

# check sample sizes after removing adopted participants 
paste("n removed excluding adopted:", (rows1 - rows2))

### recoding pack years (it's a nested variable) so that those who answered never to smoking status have a 0 instead of NA
dat_eng$pack_years <- 
    ifelse(!is.na(dat_eng$pack_years), 
           dat_eng$pack_years, 
           ifelse(dat_eng$smoking_status == "Never", 
                  0,
                  NA))


dat_eng$pack_years_prop <- 
    ifelse(!is.na(dat_eng$pack_years_prop), 
           dat_eng$pack_years_prop,
           ifelse(dat_eng$smoking_status == "Never",
                  0,
                  NA))

```

``` {r male_female, results='hide'}                                          
                                          
### create male and female datasets
mdat <- dat_eng[which(dat_eng$sex == "Male"), ]
fdat <- dat_eng[which(dat_eng$sex == "Female"), ]

```

```{r repro_recode, results='hide'}

### recode some nested female reproduction variables 
### I want to keep for later analyses and don't want excluded in the next step

fdat$menopause_age <- ifelse(!is.na(fdat$menopause_age),
                             fdat$menopause_age, # if it is not NA, then keep the value
                             ifelse(is.na(fdat$menopause) |
                                      fdat$menopause == "No", 
                                    777, # else if response to menopause is NA or no, code nested missing as 777
                                    NA)) # or else NA (i.e., response to menopause is 1, but the response to menopause age is truly missing)
fdat$menopause_age <- as.numeric(fdat$menopause_age)

fdat$birth_age <- ifelse(!is.na(fdat$birth_age),
                         fdat$birth_age,
                         ifelse(is.na(fdat$number_births) |
                                  fdat$number_births != 1,
                                777,
                                NA))
fdat$birth_age <- as.numeric(fdat$birth_age)

fdat$first_birth_age <- ifelse(!is.na(fdat$first_birth_age), 
                               fdat$first_birth_age,
                               ifelse(is.na(fdat$number_births) |
                                        fdat$number_births == 1, 
                                      777,
                                      NA))
fdat$first_birth_age <- as.numeric(fdat$first_birth_age)

fdat$last_birth_age <- ifelse(!is.na(fdat$last_birth_age),
                              fdat$last_birth_age,
                              ifelse(is.na(fdat$number_births) |
                                       fdat$number_births == 1,
                                     777,
                                     NA))
fdat$last_birth_age <- as.numeric(fdat$last_birth_age)
```

```{r recode}

#re-code "can't walk" as 0 mins
mdat$walked_over_10mins_days[which(mdat$walked_over_10mins_days == "-2")] <- 0 

#re-code "can't walk" as 0 mins
fdat$walked_over_10mins_days[which(fdat$walked_over_10mins_days == "-2")] <- 0 
  
# recode home population density - men
mdat$home_population_density <-
    ifelse(
        mdat$home_population_density == "England/Wales - Urban - less sparse" |
            mdat$home_population_density == "England/Wales - Urban - sparse",
        "Urban",
        ifelse(
            mdat$home_population_density == "England/Wales - Village - less sparse" |
                mdat$home_population_density == "England/Wales - Village - sparse",
            "Village",
            ifelse(
                mdat$home_population_density == "England/Wales - Town and Fringe - less sparse" |
                    mdat$home_population_density == "England/Wales - Town and Fringe - sparse",
                "Town and Fringe",
                "Hamlet and Isolated Dwelling"
            )
        )
    )

mdat$home_population_density <- 
    factor(mdat$home_population_density, 
           ordered = FALSE)

mdat$home_population_density <- 
    relevel(mdat$home_population_density, 
            ref = "Urban")

# recode home population density - women
fdat$home_population_density <-
    ifelse(
        fdat$home_population_density == "England/Wales - Urban - less sparse" |
            fdat$home_population_density == "England/Wales - Urban - sparse",
        "Urban",
        ifelse(
            fdat$home_population_density == "England/Wales - Village - less sparse" |
                fdat$home_population_density == "England/Wales - Village - sparse",
            "Village",
            ifelse(
                fdat$home_population_density == "England/Wales - Town and Fringe - less sparse" |
                    fdat$home_population_density == "England/Wales - Town and Fringe - sparse",
                "Town and Fringe",
                "Hamlet and Isolated Dwelling"
            )
        )
  )

fdat$home_population_density <- factor(fdat$home_population_density, 
                                            ordered = FALSE)

fdat$home_population_density <- relevel(fdat$home_population_density, 
                                             ref = "Urban")


# ethnicity - men
mdat$ethnicity_old <- mdat$ethnicity
mdat$ethnicity <- NA

mdat$ethnicity <-
    ifelse(
        mdat$ethnicity_old == "Black or Black British" |
            mdat$ethnicity_old == "Caribbean" |
            mdat$ethnicity_old == "African" |
            mdat$ethnicity_old == "Any other Black background",
        "Black",
        ifelse(
            mdat$ethnicity_old == "White" |
                mdat$ethnicity_old == "British" |
                mdat$ethnicity_old == "Irish" |
                mdat$ethnicity_old == "Any other white background",
            "White",
            ifelse(
                mdat$ethnicity_old == "Mixed" |
                    mdat$ethnicity_old == "White and Black Caribbean" |
                    mdat$ethnicity_old == "White and Black African" |
                    mdat$ethnicity_old == "White and Asian" |
                    mdat$ethnicity_old == "Any other mixed background",
                "Mixed",
                ifelse(
                    mdat$ethnicity_old == "Asian or Asian British" |
                        mdat$ethnicity_old == "Chinese" |
                        mdat$ethnicity_old == "Indian" |
                        mdat$ethnicity_old == "Pakistani" |
                        mdat$ethnicity_old == "Bangladeshi" |
                        mdat$ethnicity_old == "Any other Asian background",
                    "Asian",
                    ifelse(mdat$ethnicity_old == "Other ethnic group",
                           "Other",
                           NA)
                )
            )
        )
    )

mdat$ethnicity <- factor(mdat$ethnicity, 
                         ordered = FALSE)

mdat$ethnicity <- relevel(mdat$ethnicity, 
                          ref = "White")

# ethnicity - women
fdat$ethnicity_old <- fdat$ethnicity
fdat$ethnicity <- NA

fdat$ethnicity <-
    ifelse(
        fdat$ethnicity_old == "Black or Black British" |
            fdat$ethnicity_old == "Caribbean" |
            fdat$ethnicity_old == "African" |
            fdat$ethnicity_old == "Any other Black background",
        "Black",
        ifelse(
            fdat$ethnicity_old == "White" |
                fdat$ethnicity_old == "British" |
                fdat$ethnicity_old == "Irish" |
                fdat$ethnicity_old == "Any other white background",
            "White",
            ifelse(
                fdat$ethnicity_old == "Mixed" |
                    fdat$ethnicity_old == "White and Black Caribbean" |
                    fdat$ethnicity_old == "White and Black African" |
                    fdat$ethnicity_old == "White and Asian" |
                    fdat$ethnicity_old == "Any other mixed background",
                "Mixed",
                ifelse(
                    fdat$ethnicity_old == "Asian or Asian British" |
                        fdat$ethnicity_old == "Chinese" |
                        fdat$ethnicity_old == "Indian" |
                        fdat$ethnicity_old == "Pakistani" |
                        fdat$ethnicity_old == "Bangladeshi" |
                        fdat$ethnicity_old == "Any other Asian background",
                    "Asian",
                    ifelse(fdat$ethnicity_old == "Other ethnic group",
                           "Other",
                           NA)
                )
            )
        )
    )

fdat$ethnicity <- factor(fdat$ethnicity, 
                         ordered = FALSE)

fdat$ethnicity <- relevel(fdat$ethnicity, 
                          ref = "White")

mdat <- subset(mdat, 
               select = -c(ethnicity_old))

fdat <- subset(fdat, 
               select = -c(ethnicity_old))

```

``` {r missing, results='hide'}

# remove variable columns with >80% missing
mdat_nomiss <- mdat[ ,which(colMeans(is.na(mdat)) < 0.8)] 
fdat_nomiss <- fdat[ ,which(colMeans(is.na(fdat)) < 0.8)]

```

``` {r nested, results='hide'}

### remove all nested variables 

# create csv files of all column names to scan for nested variables
mcols <- colnames(mdat_nomiss)
fcols <- colnames(fdat_nomiss)

write.csv(mcols, file = "/path/to/file/male_check_for_nested.csv")
write.csv(fcols, file = "/path/to/file/female_check_for_nested.csv")

# list of all nested variables
nested <- c(
    Cs(
        glasses_age,
        MI_diagnosis_age,
        angina_diagnosis_age,
        stroke_diagnosis_age,
        bp_diagnosis_age,
        DVT_diagnosis_age,
        pulm_embolism_diagnosis_age,
        emphysema_diagnosis_age,
        asthma_diagnosis_age,
        rhinitis_diagnosis_age,
        gest_diabetes_only,
        diabetes_diagnosis_age,
        diabetes_insulin_1yr,
        myopia_eye,
        hypertropia_eye,
        presbyopia_eye,
        astigmatism_eye,
        strabismus_eye,
        amblyopia_eye,
        other_eye,
        other_serious_eye,
        diabetes_eye,
        glaucoma_eye,
        injury_eye,
        cataract_eye,
        macular_degeneration_eye,
        diabetes_eye_age,
        glaucoma_age,
        injury_eye_age,
        cataract_age,
        macular_degeneration_age,
        other_serious_eye_age,
        bowel_cancer_screening_recent,
        PSA_test_time_since,
        light_smoking,
        smoking_start_age_former,
        tobacco_type_previous,
        number_cigarettes_previous,
        smoking_stop_age,
        ever_stop_smoking_6months,
        number_quit_attempts,
        light_smoking,
        smoking_start_age_current,
        tobacco_type,
        previous_smoker,
        number_cigarettes,
        cigarettes_stop_age,
        previous_number_cigarettes,
        waking_smoke_time,
        difficulty_not_smoking_1day,
        stop_smoking_attempt,
        stop_smoking_desire,
        smoking_10yrs,
        smoking_start_age_former,
        tobacco_type_previous,
        number_cigarettes_previous,
        smoking_stop_age,
        ever_stop_smoking_6months,
        number_quit_attempts,
        alcohol_former,
        red_wine_monthly,
        white_wine_monthly,
        beer_monthly,
        spirits_monthly,
        fortified_wine_monthly,
        other_alcohol_monthly,
        red_wine_weekly,
        white_wine_weekly,
        beer_weekly,
        spirits_weekly,
        fortified_wine_weekly,
        other_alcohol_weekly,
        alcohol_with_meals,
        alcohol_10yrs,
        reason_reducing_alcohol,
        reason_stopped_alcohol,
        glasses_myopia,
        glasses_presbyopia,	
        glasses_hypermetropia,	
        glasses_amblyopia,	
        glasses_astigmatism,	
        glasses_strabismus,	
        glasses_other,
        glaucoma,
        headaches_3months,
        facial_pain_3months,
        neck_pain_3months,
        stomach_pain_3months,
        hip_pain_3months,
        knee_pain_3months,
        general_pain_3months,
        chest_pain_walking_normal,
        chest_pain_ceases_still,
        chest_pain_walking_uphill,
        father_age,
        father_age_death,
        mother_age,
        mother_age_death,
        heavy_DIY_duration,
        light_DIY_duration,
        moderate_activity_duration,
        other_exercise_duration,
        strenuous_sports_duration,
        vigorous_activity_duration,
        walks_duration,
        pleasure_walks_duration,
        heavy_DIY_freq_4wks,
        light_DIY_freq_4wks,
        other_exercise_freq_4wks,
        stair_climbing_freq_4wks,
        strenuous_sports_freq_4wks,
        pleasure_walks_freq_4wks,
        menstruating_today,
        oral_contraceptive_age_first,
        oral_contraceptive_age_last,
        HRT_age_first,
        HRT_age_last,
        hysterectomy_age,
        bilateral_oophorectomy_age,
        mammogram_years_since,
        cervical_smear_years_since,
        first_child_birth_weight,
        number_stillbirths,
        number_miscarriages,
        number_pregnancy_terminations,
        period_time_since,
        resume_smoking_likelihood,
        stopped_smoking_health,
        stopped_smoking_illness,
        stopped_smoking_financial,
        stopped_smoking_doctor,
        reduced_smoking_health,
        reduced_smoking_illness,
        reduced_smoking_financial,
        reduced_smoking_doctor,
        education_age_complete,
        country_birth_non_UK,
        past_tobacco,
        spread_type_details,
        tobacco_exposure_outside,
        tobacco_exposure_home,
        hshld_smokers
    )
)

other_remove <- c(
    Cs(
        childhood_love,
        childhood_physical_abuse,
        childhood_hate,
        childhood_sex_abuse,
        childhood_doctor,
        birth_weight_known,
        ankle_spacing_width_left,
        ankle_spacing_width_right,
        heel_bone_mineral_density_left,
        heel_bone_mineral_density_right,
        heel_bone_mineral_density_t_score_left,
        heel_bone_mineral_density_t_score_right,
        heel_broadband_attenuation_left,
        heel_broadband_attenuation_right,
        heel_QUI_left,
        heel_QUI_right,
        heel_sound_speed_left,
        heel_sound_speed_right,
        heel_bone_mineral_density_t_score,
        heel_QUI,
        heel_broadband_attenuation,
        heel_sound_speed,
        ankle_spacing_width,
        bone_density_measure_foot,
        fractured_heel_left,
        fractured_heel_right,
        other_diagnosis
    )
)

# remove all columns with nested variables
mdat_nonest <- mdat_nomiss[ ,which(colnames(mdat_nomiss) %nin% nested)] 
fdat_nonest <- fdat_nomiss[ ,which(colnames(fdat_nomiss) %nin% nested)] 

# remove all columns with other variables too exclude
mdat_nonest <- mdat_nonest[ ,which(colnames(mdat_nonest) %nin% other_remove)] 
fdat_nonest <- fdat_nonest[ ,which(colnames(fdat_nonest) %nin% other_remove)] 

```

```{r ordinal_vars}

### re-classing ordinal categorical variables as ordinal

# get position of all factor variables
factors <- sapply(mdat_nonest, is.factor)

# subset dataset to just factors
data <- mdat_nonest[factors]

# make list of levels for each factor
factor_list <- sapply(data, nlevels)

# get position of all factors with >2 responses
non_binary <- factor_list > 2

# subset data to non-binary factors
data_cat <- data[non_binary]

# get names of non-binary factors to check if ordinal 
colnames(data_cat)

# function to order ordinal factors
make_ordered <- function(x) {

  x$number_operations <- as.numeric(x$number_operations)
  
  x$family_visit_freq <-
    factor(x$family_visit_freq,
           ordered = TRUE,
           levels = c("No friends/family outside household",
                      "Never or almost never",
                      "Once every few months",
                      "About once a month",
                      "About once a week",
                      "2-4 times a week",
                      "Almost daily"))
  
  x$confide_freq <-
    factor(x$confide_freq,
           ordered = TRUE,
           levels = c("Never or almost never",
                      "Once every few months",
                      "About once a month",
                      "About once a week",
                      "2-4 times a week",
                      "Almost daily"))
  
  x$hshld_vehicles <-
    factor(x$hshld_vehicles,
           ordered = TRUE,
           levels = c("None",
                      "One",
                      "Two",
                      "Three",
                      "Four or more"))
  
  x$hshld_income <-
    factor(x$hshld_income,
           ordered = TRUE,
           levels = c("Less than 18,000",
                      "18,000 to 30,999",
                      "31,000 to 51,999",
                      "52,000 to 100,000",
                      "Greater than 100,000"))
  
  x$employment_standing <-
    factor(x$employment_standing,
           ordered = TRUE,
           levels = c("Never/rarely",
                      "Sometimes",
                      "Usually",
                      "Always"))
  
  x$employment_heavy_manual <-
    factor(x$employment_heavy_manual,
           ordered = TRUE,
           levels = c("Never/rarely",
                      "Sometimes",
                      "Usually",
                      "Always"))
  
  x$shift_work <-
    factor(x$shift_work,
           ordered = TRUE,
           levels = c("Never/rarely",
                      "Sometimes",
                      "Usually",
                      "Always"))
  
  x$noisy_workplace <-
    factor(x$noisy_workplace,
           ordered = TRUE,
           levels = c("No",
                      "Yes, for less than a year",
                      "Yes, for around 1-5 years",
                      "Yes, for more than 5 years"))
  
  x$private_healthcare <-
    factor(x$private_healthcare,
           ordered = TRUE,
           levels = c("No, never",
                      "Yes, sometimes",
                      "Yes, most of the time",
                      "Yes, all of the time"))
  
  x$overall_health <-
    factor(x$overall_health,
           ordered = TRUE,
           levels = c("Poor",
                      "Fair",
                      "Good",
                      "Excellent"))
  
  x$falls_last_1yr <-
    factor(x$falls_last_1yr,
           ordered = TRUE,
           levels = c("No falls",
                      "Only one fall",
                      "More than one fall"))
  
  x$tinnitus <-
    factor(x$tinnitus,
           ordered = TRUE,
           levels = c("No, never",
                      "Yes, but not now, but have in the past",
                      "Yes, now some of the time",
                      "Yes, now a lot of the time",
                      "Yes, now most or all of the time"))
  
  x$loud_music_exposure <-
    factor(x$loud_music_exposure,
           ordered = TRUE,
           levels = c("No",
                      "Yes, for less than a year",
                      "Yes, for around 1-5 years",
                      "Yes, for more than 5 years"))
  
  x$depressed_mood_freq <-
    factor(x$depressed_mood_freq,
           ordered = TRUE,
           levels = c("Not at all",
                      "Several days",
                      "More than half the days",
                      "Nearly every day"))
  
  x$unenthusiasm_freq <-
    factor(x$unenthusiasm_freq,
           ordered = TRUE,
           levels = c("Not at all",
                      "Several days",
                      "More than half the days",
                      "Nearly every day"))
  
  x$tenseness_freq <-
    factor(x$tenseness_freq,
           ordered = TRUE,
           levels = c("Not at all",
                      "Several days",
                      "More than half the days",
                      "Nearly every day"))
  
  x$tiredness_freq <-
    factor(x$tiredness_freq,
           ordered = TRUE,
           levels = c("Not at all",
                      "Several days",
                      "More than half the days",
                      "Nearly every day"))
  
  x$mobile_phone_duration <-
    factor(x$mobile_phone_duration,
           ordered = TRUE,
           levels = c("Never used mobile phone at least once per week",
                      "One year or less",
                      "Two to four years",
                      "Five to eight years",
                      "More than eight years"))
  
  x$mobile_phone_weekly_usage <-
    factor(x$mobile_phone_weekly_usage,
           ordered = TRUE,
           levels = c("Less than 5mins",
                      "5-29 mins",
                      "30-59 mins",
                      "1-3 hours",
                      "4-6 hours",
                      "More than 6 hours"))
  
  x$speakerphone <-
    factor(x$speakerphone,
           ordered = TRUE,
           levels = c("Never or almost never",
                      "Less than half the time",
                      "About half the time",
                      "More than half the time",
                      "Always or almost always"))
  
  x$computer_games <-
    factor(x$computer_games,
           ordered = TRUE,
           levels = c("Never/rarely",
                      "Sometimes",
                      "Often"))
  
  x$easy_wake <-
    factor(x$easy_wake,
           ordered = TRUE,
           levels = c("Not at all easy",
                      "Not very easy",
                      "Fairly easy",
                      "Very easy"))
  
  x$nap <-
    factor(x$nap,
           ordered = TRUE,
           levels = c("Never/rarely",
                      "Sometimes",
                      "Usually"))
  
  x$sleep_difficulty <-
    factor(x$sleep_difficulty,
           ordered = TRUE,
           levels = c("Never/rarely",
                      "Sometimes",
                      "Usually"))
  
  x$narcolepsy <-
    factor(x$narcolepsy,
           ordered = TRUE,
           levels = c("Never/rarely",
                      "Sometimes",
                      "Often",
                      "All of the time"))
  
  x$tobacco <-
    factor(x$tobacco,
           ordered = TRUE,
           levels = c("No",
                      "Only occasionally",
                      "Yes, on most or all days"))
  
  x$hshld_smokers <-
    factor(x$hshld_smokers,
           ordered = TRUE,
           levels = c("No",
                      "Yes, one household member smokes",
                      "Yes, more than one household member smokes"))
  
  x$alcohol_freq <-
    factor(x$alcohol_freq,
           ordered = TRUE,
           levels = c("Never",
                      "Special occasions only",
                      "One to three times a month",
                      "Once or twice a week",
                      "Three or four times a week",
                      "Daily or almost daily"))
  
  x$oily_fish <-
    factor(x$oily_fish,
           ordered = TRUE,
           levels = c("Never",
                      "Less than once a week",
                      "Once a week",
                      "2-4 times a week",
                      "5-6 times a week",
                      "Once or more daily"))
  
  x$non_oily_fish <-
    factor(x$non_oily_fish,
           ordered = TRUE,
           levels = c("Never",
                      "Less than once a week",
                      "Once a week",
                      "2-4 times a week",
                      "5-6 times a week",
                      "Once or more daily"))
  
  x$processed_meat <-
    factor(x$processed_meat,
           ordered = TRUE,
           levels = c("Never",
                      "Less than once a week",
                      "Once a week",
                      "2-4 times a week",
                      "5-6 times a week",
                      "Once or more daily"))
  
  x$poultry <-
    factor(x$poultry,
           ordered = TRUE,
           levels = c("Never",
                      "Less than once a week",
                      "Once a week",
                      "2-4 times a week",
                      "5-6 times a week",
                      "Once or more daily"))
  
  x$beef <-
    factor(x$beef,
           ordered = TRUE,
           levels = c("Never",
                      "Less than once a week",
                      "Once a week",
                      "2-4 times a week",
                      "5-6 times a week",
                      "Once or more daily"))
  
  x$lamb <-
    factor(x$lamb,
           ordered = TRUE,
           levels = c("Never",
                      "Less than once a week",
                      "Once a week",
                      "2-4 times a week",
                      "5-6 times a week",
                      "Once or more daily"))
  
  x$pork <-
    factor(x$pork,
           ordered = TRUE,
           levels = c("Never",
                      "Less than once a week",
                      "Once a week",
                      "2-4 times a week",
                      "5-6 times a week",
                      "Once or more daily"))
  
  x$cheese <-
    factor(x$cheese,
           ordered = TRUE,
           levels = c("Never",
                      "Less than once a week",
                      "Once a week",
                      "2-4 times a week",
                      "5-6 times a week",
                      "Once or more daily"))
  
  x$salt <-
    factor(x$salt,
           ordered = TRUE,
           levels = c("Never/rarely",
                      "Sometimes",
                      "Usually",
                      "Always"))
  
  x$hot_drink_temp <-
    factor(x$hot_drink_temp,
           ordered = TRUE,
           levels = c("Do not drink hot drinks",
                      "Warm",
                      "Hot",
                      "Very hot"))
  
  x$diet_variation <-
    factor(x$diet_variation,
           ordered = TRUE,
           levels = c("Never/rarely",
                      "Sometimes",
                      "Often" ))
  
  x$skin_tan_ease <-
    factor(x$skin_tan_ease,
           ordered = TRUE,
           levels = c("Never tan, only burn",
                      "Get mildly or occasionally tanned",
                      "Get moderately tanned",
                      "Get very tanned"))
  
  x$sun_protection_use <-
    factor(x$sun_protection_use,
           ordered = TRUE,
           levels = c("Do not go out in sunshine",
                      "Never/rarely",
                      "Sometimes",
                      "Most of the time",
                      "Always"))
  
  x$IPAQ_activity_group <-
    factor(x$IPAQ_activity_group,
           ordered = TRUE,
           levels = c("low",
                      "moderate",
                      "high"))
  
  x$fast_driving <-
    factor(x$fast_driving,
           ordered = TRUE,
           levels = c("Do not drive on the motorway",
                      "Never/rarely",
                      "Sometimes",
                      "Often",
                      "Most of the time"))
  
  x$happiness <-
    factor(x$happiness,
           ordered = TRUE,
           levels = c("Extremely unhappy",
                      "Very unhappy",
                      "Moderately unhappy",
                      "Moderately happy",
                      "Very happy",
                      "Extremely happy"))
  
  x$job_satisfaction <-
    factor(x$job_satisfaction,
           ordered = TRUE,
           levels = c("I am not employed",
                      "Extremely unhappy",
                      "Very unhappy",
                      "Moderately unhappy",
                      "Moderately happy",
                      "Very happy",
                      "Extremely happy"))
  
  x$health_satisfaction <-
    factor(x$health_satisfaction,
           ordered = TRUE,
           levels = c("Extremely unhappy",
                      "Very unhappy",
                      "Moderately unhappy",
                      "Moderately happy",
                      "Very happy",
                      "Extremely happy"))
  
  x$family_satisfaction <-
    factor(x$family_satisfaction,
           ordered = TRUE,
           levels = c("Extremely unhappy",
                      "Very unhappy",
                      "Moderately unhappy",
                      "Moderately happy",
                      "Very happy",
                      "Extremely happy"))
  
  x$friends_satisfaction <-
    factor(x$friends_satisfaction,
           ordered = TRUE,
           levels = c("Extremely unhappy",
                      "Very unhappy",
                      "Moderately unhappy",
                      "Moderately happy",
                      "Very happy",
                      "Extremely happy"))
  
  x$financial_satisfaction <-
    factor(x$financial_satisfaction,
           ordered = TRUE,
           levels = c("Extremely unhappy",
                      "Very unhappy",
                      "Moderately unhappy",
                      "Moderately happy",
                      "Very happy",
                      "Extremely happy"))
  
  return(x)
}

# apply to male and female datasets
mdat_nonest <- make_ordered(mdat_nonest)
fdat_nonest <- make_ordered(fdat_nonest)

```

``` {r final_exclusions, results='hide'}

rows1 <- nrow(mdat_nonest)
rows2 <- nrow(fdat_nonest)

# remove participant rows who still have >80% missing after excluding nested vars
mdat_nonest <- mdat_nonest[which(rowMeans(is.na(mdat_nonest)) < 0.8), ]
fdat_nonest <- fdat_nonest[which(rowMeans(is.na(fdat_nonest)) < 0.8), ] 

rows3 <- nrow(mdat_nonest)
rows4 <- nrow(fdat_nonest)

# check sample sizes after removing vars 
paste("n removed excluding missing >80% of vars - men:", rows1 - rows3)
paste("n removed excluding missing >80% of vars - women:", rows2 - rows4)
paste("n removed excluding missing >80% of vars:", (rows1 + rows2) - (rows3 + rows4))

rows1 <- nrow(mdat_nonest)
rows2 <- nrow(fdat_nonest)

mdat_final <- mdat_nonest[which(mdat_nonest$recruitment_age >= 40), ]
fdat_final <- fdat_nonest[which(fdat_nonest$recruitment_age >= 40), ]

rows3 <- nrow(mdat_final)
rows4 <- nrow(fdat_final)

# check sample sizes after removing vars 
paste("n removed < 40 - men:", rows1 - rows3)
paste("n removed < 40 - women:", rows2 - rows4)
paste("n removed < 40 total:", (rows1 + rows2) - (rows3 + rows4))

# check final sample sizes
paste("final men analytic sample:", nrow(mdat_final))
paste("final women analytic sample:", nrow(fdat_final))
paste("final total analytic sample:", nrow(mdat_final) + nrow(fdat_final))

```

```{r hazard, results='hide'}

# create nelson aalen estimator (cumulative hazard rate). 
# note: needs event indicator to be numeric and not a factor
mdat_final$hazard <- nelsonaalen(mdat_final, # dataset
                                 NCDM_survival_time, # survival time
                                 NCDM_event_indicator) # event indicator

fdat_final$hazard <- nelsonaalen(fdat_final, # dataset
                                 NCDM_survival_time, # survival time
                                 NCDM_event_indicator) # event indicator
```

``` {r save_exclusions}
# save after also excluding all nested variables except select female reproduction vars

mdat_final <- subset(mdat_final, 
                     select = -c(adopted,
                                 ACM_censor_date))

fdat_final <- subset(fdat_final, 
                     select = -c(adopted,
                                 ACM_censor_date))

save(mdat_final,
     fdat_final,
     file = "/path/to/file/ACM_datasets_jun_05_2021.RData")
```

```{r save_data_dictionary}

# get variables in datasets used for imputation
mcols <- colnames(mdat_final)
fcols <- colnames(fdat_final)

# add cols together and keep only unique
total_cols <- c(mcols, fcols)
total_cols <- unique(total_cols)

# remove eid
total_cols <- total_cols[which(total_cols != "eid")]

# load data dictionary
dict <- read.csv("/path/to/file/Argentieri UKB dataset data dictionary.csv")

# rename to match
dict$Variable[which(dict$Description == "Lipoprotein A")] <- "lipoprotein_A"

# subset data dictionary to just variables used in imputation
dict <- dict[which(dict$Variable %in% total_cols), ]

# save 
write.csv(dict, "/path/to/file/imputation_data_dictionary_mar_18_2022.csv")

```

```{r imputation, eval=FALSE}

# more instructions here: https://cran.r-project.org/web/packages/missRanger/vignettes/vignette_missRanger.html

library(missRanger)

### men
# create case weights to weight down the contribution of rows with many missings during the imputation
non_miss <- rowSums(!is.na(mdat_final))

# multiple imputation in men
mult <- lapply(3456:3460, function(x)
  missRanger(
    mdat_final,
    . ~ . - ACM_survival_time -
      eid -
      sex, # do not use to predict
    maxiter = 10,
    pmm.k = 3,
    verbose = 1,
    seed = x,
    num.trees = 200,
    returnOOB = TRUE,
    case.weights = non_miss
  )
)

save(mult, file = "/path/to/file/missRAnger_ACM_200t_jun_05_2021_male.RData")


### women

# create case weights to weight down the contribution of rows with many missings during the imputation
non_miss <- rowSums(!is.na(fdat_final))

fmult <- lapply(3456:3460, function(x)
  missRanger(
    fdat_final,
    . ~ . - ACM_survival_time -
      eid -
      sex -
      menopause_age -
      birth_age -
      first_birth_age -
      last_birth_age, # do not use to predict for imputation
    maxiter = 10,
    pmm.k = 3,
    verbose = 1,
    seed = x,
    num.trees = 200,
    returnOOB = TRUE,
    case.weights = non_miss
  )
)

save(fmult, file = "/path/to/file/missRAnger_ACM_200t_jun_05_2021_female.RData")
```

``` {r OOB_error, eval=FALSE}

### Checking OOB error rates from multiple imputation
library(tidyverse)

## Retrieve OOB error rates to compare
error_200t <- lapply(mult, function(x) as.data.frame(attr(x, "oob")))

for(j in seq_along(error_200t)) { 
  colnames(error_200t[[j]]) <- c(paste("Imputation", j))
  error_200t[[j]]$Exposure <- rownames(error_200t[[j]])
}

error_200t <-
  error_200t %>% 
  reduce(left_join, by = "Exposure")

cols <- c("Exposure",
          "Imputation 1",
          "Imputation 2",
          "Imputation 3",
          "Imputation 4",
          "Imputation 5")

error_200t <- error_200t[cols]


avg_oob_err_200t <- c(
  mean(error_200t[ ,2]),
  mean(error_200t[ ,3]),
  mean(error_200t[ ,4]),
  mean(error_200t[ ,5]),
  mean(error_200t[ ,6])
)

range_oob_err_200t <- c(
  range(error_200t[ ,2]),
  range(error_200t[ ,3]),
  range(error_200t[ ,4]),
  range(error_200t[ ,5]),
  range(error_200t[ ,6])
)

total_avg_error <- mean(avg_oob_err_200t)
total_avg_range_high <- mean(range_oob_err_200t[c(2,4,6,8,10)])

total_avg_error # avg OBB error in men: 0.08
total_avg_range_high # avg OBB error range in men: 0 - 0.70

### Female

## Retrieve OOB error rates to compare
error_200t <- lapply(fmult, function(x) as.data.frame(attr(x, "oob")))

for(j in seq_along(error_200t)) { 
  colnames(error_200t[[j]]) <- c(paste("Imputation", j))
  error_200t[[j]]$Exposure <- rownames(error_200t[[j]])
}

error_200t <-
  error_200t %>% 
  reduce(left_join, by = "Exposure")

cols <- c("Exposure",
          "Imputation 1",
          "Imputation 2",
          "Imputation 3",
          "Imputation 4",
          "Imputation 5")

error_200t <- error_200t[cols]


favg_oob_err_200t <- c(
  mean(error_200t[ ,2]),
  mean(error_200t[ ,3]),
  mean(error_200t[ ,4]),
  mean(error_200t[ ,5]),
  mean(error_200t[ ,6])
)

frange_oob_err_200t <- c(
  range(error_200t[ ,2]),
  range(error_200t[ ,3]),
  range(error_200t[ ,4]),
  range(error_200t[ ,5]),
  range(error_200t[ ,6])
)

ftotal_avg_error <- mean(favg_oob_err_200t)
ftotal_avg_range_high <- mean(frange_oob_err_200t[c(2,4,6,8,10)])

ftotal_avg_error # avg OBB error in women: 0.08
ftotal_avg_range_high # avg OBB error range in women: 0 - 0.77
```

``` {r derived_men}

### loop to create derived variables in each of the 5 imputed datasets

### men

for(j in seq_along(mult)){  

  # create empty columns for new derived variables
  mult[[j]]$sleep_hours_categorical <- NA
  mult[[j]]$education_years <- NA
  mult[[j]]$hand_grip_strength_left_normalized <- NA
  mult[[j]]$hand_grip_strength_right_normalized <- NA
  mult[[j]]$FEV1_standardized <- NA
  mult[[j]]$FVC_standardized <- NA
  
  # sleep hours categorical
  mult[[j]]$sleep_hours_categorical <- ifelse(mult[[j]]$sleep_hours < 7, 
                                              '<7 hours', 
                                              ifelse(mult[[j]]$sleep_hours >= 7 & 
                                                       mult[[j]]$sleep_hours <= 9, 
                                                     '7-9 hours',
                                                     '>9 hours'))
  
  mult[[j]]$sleep_hours_categorical <- factor(mult[[j]]$sleep_hours_categorical, 
                                              levels = c('<7 hours',
                                                         '7-9 hours',
                                                         '>9 hours'),
                                              ordered = FALSE)
  
  mult[[j]]$sleep_hours_categorical <- relevel(mult[[j]]$sleep_hours_categorical, 
                                               ref = '7-9 hours')
  
  # education years
  mult[[j]]$education_years <-
    ifelse(
      mult[[j]]$education_college == 'Yes',
      '20 years',
      ifelse(
        mult[[j]]$education_NVQ == 'Yes',
        '19 years',
        ifelse(
          mult[[j]]$education_other_professional == 'Yes',
          '15 years',
          ifelse(
            mult[[j]]$education_A_levels == 'Yes',
            '13 years',
            ifelse(
              mult[[j]]$education_O_levels == 'Yes' |
                mult[[j]]$education_CSEs == 'Yes',
              '10 years',
              ifelse(mult[[j]]$education_none == 'Yes',
                     '7 years',
                     '7 years')
            )
          )
        )
      )
    )
  
  mult[[j]]$education_years <- factor(mult[[j]]$education_years, 
                                      levels = c('7 years',
                                                 '10 years',
                                                 '13 years',
                                                 '15 years',
                                                 '19 years',
                                                 '20 years'),
                                      ordered = TRUE)
  
  # hand grip strength normalized by body weight
  mult[[j]]$hand_grip_strength_left_normalized <- 
    (mult[[j]]$hand_grip_strength_left / mult[[j]]$weight)
  
  mult[[j]]$hand_grip_strength_right_normalized <- 
    (mult[[j]]$hand_grip_strength_right / mult[[j]]$weight)
  
  mult[[j]]$hand_grip_strength_left_normalized <- 
    as.numeric(mult[[j]]$hand_grip_strength_left_normalized)
  
  mult[[j]]$hand_grip_strength_right_normalized <- 
    as.numeric(mult[[j]]$hand_grip_strength_right_normalized)
  
  # lung function standardized by height
  mult[[j]]$FEV1_standardized <- 
    (mult[[j]]$FEV1_best / (mult[[j]]$standing_height / 100)^2) # divide by 100 to get m instead of cm
  
  mult[[j]]$FVC_standardized <- 
    (mult[[j]]$FVC_best / (mult[[j]]$standing_height / 100)^2) # divide by 100 to get m instead of cm

  mult[[j]]$FEV1_standardized <- as.numeric(mult[[j]]$FEV1_standardized)
  mult[[j]]$FVC_standardized <- as.numeric(mult[[j]]$FVC_standardized)
  
  
}

```

``` {r derived_women}

### women
for(j in seq_along(fmult)){  
  
  # create empty columns for new derived variables
  fmult[[j]]$sleep_hours_categorical <- NA
  fmult[[j]]$education_years <- NA
  fmult[[j]]$hand_grip_strength_left_normalized <- NA
  fmult[[j]]$hand_grip_strength_right_normalized <- NA
  fmult[[j]]$FEV1_standardized <- NA
  fmult[[j]]$FVC_standardized <- NA
  
  # sleep hours categorical
  fmult[[j]]$sleep_hours_categorical <- ifelse(fmult[[j]]$sleep_hours < 7, 
                                               '<7 hours', 
                                               ifelse(fmult[[j]]$sleep_hours >= 7 & 
                                                        fmult[[j]]$sleep_hours <= 9, 
                                                      '7-9 hours',
                                                      '>9 hours'))
  
  fmult[[j]]$sleep_hours_categorical <- factor(fmult[[j]]$sleep_hours_categorical, 
                                               levels = c('<7 hours',
                                                          '7-9 hours',
                                                          '>9 hours'),
                                               ordered = FALSE)
  
  fmult[[j]]$sleep_hours_categorical <- relevel(fmult[[j]]$sleep_hours_categorical, 
                                                ref = '7-9 hours')
  
  # education years
  fmult[[j]]$education_years <-
    ifelse(
      fmult[[j]]$education_college == 'Yes',
      '20 years',
      ifelse(
        fmult[[j]]$education_NVQ == 'Yes',
        '19 years',
        ifelse(
          fmult[[j]]$education_other_professional == 'Yes',
          '15 years',
          ifelse(
            fmult[[j]]$education_A_levels == 'Yes',
            '13 years',
            ifelse(
              fmult[[j]]$education_O_levels == 'Yes' |
                fmult[[j]]$education_CSEs == 'Yes',
              '10 years',
              ifelse(fmult[[j]]$education_none == 'Yes',
                     '7 years',
                     '7 years')
            )
          )
        )
      )
    )
  
  fmult[[j]]$education_years <- factor(fmult[[j]]$education_years, 
                                       levels = c('7 years',
                                                  '10 years',
                                                  '13 years',
                                                  '15 years',
                                                  '19 years',
                                                  '20 years'),
                                       ordered = TRUE)
  
  # hand grip strength normalized by body weight
  fmult[[j]]$hand_grip_strength_left_normalized <- 
    (fmult[[j]]$hand_grip_strength_left / fmult[[j]]$weight)
  
  fmult[[j]]$hand_grip_strength_right_normalized <- 
    (fmult[[j]]$hand_grip_strength_right / fmult[[j]]$weight)
  
  fmult[[j]]$hand_grip_strength_left_normalized <- 
    as.numeric(fmult[[j]]$hand_grip_strength_left_normalized)
  
  fmult[[j]]$hand_grip_strength_right_normalized <- 
    as.numeric(fmult[[j]]$hand_grip_strength_right_normalized)
  
  # lung function standardized by height
  fmult[[j]]$FEV1_standardized <- 
    (fmult[[j]]$FEV1_best / (fmult[[j]]$standing_height / 100)^2) # divide by 100 to get m instead of cm
  
  fmult[[j]]$FVC_standardized <- 
    (fmult[[j]]$FVC_best / (fmult[[j]]$standing_height / 100)^2) # divide by 100 to get m instead of cm
  
  fmult[[j]]$FEV1_standardized <- as.numeric(fmult[[j]]$FEV1_standardized)
  fmult[[j]]$FVC_standardized <- as.numeric(fmult[[j]]$FVC_standardized)
  
}

```

``` {r XWAS_pre_process}

## re-coding variables after checking exposure x mortality crosstabs
crosstab_recode <- function(x) {
  
  # alcohol_freq
  x$alcohol_freq[which(x$alcohol_status == "Previous")] <- NA
  
  # usual_walking_pace
  x$usual_walking_pace[which(x$usual_walking_pace == "None of the above")] <- NA
  old_levels <- levels(x$usual_walking_pace)
  x$usual_walking_pace <- factor(x$usual_walking_pace,
                                 ordered = TRUE,
                                 levels = c("Brisk pace",
                                            "Steady average pace",
                                            "Slow pace"))
  
  # family_satisfaction
  x$family_satisfaction[which(x$family_satisfaction == "Extremely unhappy")] <- "Very unhappy"
  old_levels <- levels(x$family_satisfaction)
  x$family_satisfaction <- factor(x$family_satisfaction,
                                 ordered = TRUE,
                                 levels = old_levels[which(old_levels != "Extremely unhappy")])
  
  # friends_satisfaction
  x$friends_satisfaction[which(x$friends_satisfaction == "Extremely unhappy")] <- "Very unhappy"
  old_levels <- levels(x$friends_satisfaction)
  x$friends_satisfaction <- factor(x$friends_satisfaction,
                                   ordered = TRUE,
                                   levels = old_levels[which(old_levels != "Extremely unhappy")])
  
  # happiness
  x$happiness[which(x$happiness == "Extremely unhappy")] <- "Very unhappy"
  old_levels <- levels(x$happiness)
  x$happiness <- factor(x$happiness,
                        ordered = TRUE,
                        levels = old_levels[which(old_levels != "Extremely unhappy")])
  
  # job_satisfaction
  x$job_satisfaction[which(x$job_satisfaction == "I am not employed")] <- NA
  x$job_satisfaction[which(x$job_satisfaction == "Extremely unhappy")] <- "Very unhappy"
  old_levels <- levels(x$job_satisfaction)
  x$job_satisfaction <- factor(x$job_satisfaction,
                               ordered = TRUE,
                               levels = old_levels[which(old_levels %nin% c("I am not employed",
                                                                            "Extremely unhappy"))])
  
  # processed_meat
  x$processed_meat[which(x$processed_meat == "Once or more daily")] <- "5-6 times a week"
  old_levels <- levels(x$processed_meat)
  x$processed_meat <- factor(x$processed_meat,
                             ordered = TRUE,
                             levels = old_levels[which(old_levels != "Once or more daily")])
  
  # poultry
  x$poultry[which(x$poultry == "Once or more daily")] <- "5-6 times a week"
  old_levels <- levels(x$poultry)
  x$poultry <- factor(x$poultry,
                      ordered = TRUE,
                      levels = old_levels[which(old_levels != "Once or more daily")])
  
  # pork
  x$pork[which(x$pork == "Once or more daily")] <- "5-6 times a week"
  old_levels <- levels(x$pork)
  x$pork <- factor(x$pork,
                   ordered = TRUE,
                   levels = old_levels[which(old_levels != "Once or more daily")])
  
  # lamb
  x$lamb[which(x$lamb == "Once or more daily")] <- "5-6 times a week"
  old_levels <- levels(x$lamb)
  x$lamb <- factor(x$lamb,
                   ordered = TRUE,
                   levels = old_levels[which(old_levels != "Once or more daily")])
  
  # beef
  x$beef[which(x$beef == "Once or more daily")] <- "5-6 times a week"
  old_levels <- levels(x$beef)
  x$beef <- factor(x$beef,
                   ordered = TRUE,
                   levels = old_levels[which(old_levels != "Once or more daily")])
  
  # oily_fish
  x$oily_fish[which(x$oily_fish == "Once or more daily")] <- "5-6 times a week"
  old_levels <- levels(x$oily_fish)
  x$oily_fish <- factor(x$oily_fish,
                        ordered = TRUE,
                        levels = old_levels[which(old_levels != "Once or more daily")])
  
  # non_oily_fish
  x$non_oily_fish[which(x$non_oily_fish == "Once or more daily")] <- "5-6 times a week"
  old_levels <- levels(x$non_oily_fish)
  x$non_oily_fish <- factor(x$non_oily_fish,
                            ordered = TRUE,
                            levels = old_levels[which(old_levels != "Once or more daily")])
  
  # narcolepsy
  x$narcolepsy[which(x$narcolepsy == "All of the time")] <- "Often"
  old_levels <- levels(x$narcolepsy)
  x$narcolepsy <- factor(x$narcolepsy,
                            ordered = TRUE,
                            levels = old_levels[which(old_levels != "All of the time")])
  
  # bipolar
  x$bipolar <- NA
  x$bipolar[which(x$bipolar_MDD == "No Bipolar or Depression")] <- "No"
  x$bipolar[which(x$bipolar_MDD == "Single Probable major depression episode")] <- "No"
  x$bipolar[which(x$bipolar_MDD == "Probable Recurrent major depression (moderate)")] <- "No"
  x$bipolar[which(x$bipolar_MDD == "Probable Recurrent major depression (severe)")] <- "No"
  x$bipolar[which(x$bipolar_MDD == "Bipolar I Disorder")] <- "Yes"  
  x$bipolar[which(x$bipolar_MDD == "Bipolar II Disorder")] <- "Yes"
  x$bipolar <- factor(x$bipolar,
                      ordered = FALSE)
  x$bipolar <- relevel(x$bipolar,
                       ref = "No")
  
  # MDD
  x$MDD <- NA
  x$MDD[which(x$bipolar_MDD == "No Bipolar or Depression")] <- "No depression"
  x$MDD[which(x$bipolar_MDD == "Bipolar I Disorder")] <- "No depression"  
  x$MDD[which(x$bipolar_MDD == "Bipolar II Disorder")] <- "No depression"
  x$MDD[which(x$bipolar_MDD == "Single Probable major depression episode")] <- "Single episode"
  x$MDD[which(x$bipolar_MDD == "Probable Recurrent major depression (moderate)")] <- "Moderate"
  x$MDD[which(x$bipolar_MDD == "Probable Recurrent major depression (severe)")] <- "Severe"
  x$MDD <- factor(x$MDD,
                  ordered = TRUE,
                  levels = c("No depression",
                             "Single episode", 
                             "Moderate", 
                             "Severe"))
  
  # remove old bipolar_MDD var from dataset
  x <- subset(x, select = -c(bipolar_MDD))
    
  # hearing_difficulty
  x$hearing_difficulty[which(x$hearing_difficulty == "I am completely deaf")] <- "Yes"
  old_levels <- levels(x$hearing_difficulty)
  x$hearing_difficulty <- factor(x$hearing_difficulty,
                                 ordered = FALSE,
                                 levels = old_levels[which(old_levels != "I am completely deaf")])
  x$hearing_difficulty <- relevel(x$hearing_difficulty,
                                  ref = "No")
  
  # own_or_rent
  x$own_or_rent[which(x$own_or_rent == "None of the above")] <- NA
  old_levels <- levels(x$own_or_rent)
  x$own_or_rent <- factor(x$own_or_rent,
                          ordered = FALSE,
                          levels = old_levels[which(old_levels != "None of the above")])
  x$own_or_rent <- relevel(x$own_or_rent,
                           ref = "Own outright (by you or someone in your household)")
  
  # accommodation_type
  x$accommodation_type[which(x$accommodation_type == "None of the above")] <- NA
  x$accommodation_type[which(x$accommodation_type == "Care home")] <- NA
  old_levels <- levels(x$accommodation_type)
  x$accommodation_type <- factor(x$accommodation_type,
                                 ordered = FALSE,
                                 levels = old_levels[which(old_levels %nin% c("None of the above",
                                                                              "Care home"))])
  x$accommodation_type <- relevel(x$accommodation_type,
                                  ref = "A house or bungalow")
  
  # milk_type
  x$milk_type[which(x$milk_type == "Other type of milk")] <- NA
  old_levels <- levels(x$milk_type)
  x$milk_type <- factor(x$milk_type,
                        ordered = FALSE,
                        levels = old_levels[which(old_levels != "Other type of milk")])
  x$milk_type <- relevel(x$milk_type,
                         ref = "Semi-skimmed")
  
  # bread_type
  x$bread_type[which(x$bread_type == "Other type of bread")] <- NA
  old_levels <- levels(x$bread_type)
  x$bread_type <- factor(x$bread_type,
                         ordered = FALSE,
                         levels = old_levels[which(old_levels != "Other type of bread")])
  x$bread_type <- relevel(x$bread_type,
                          ref = "Wholemeal or wholegrain")
  
  # coffee_type
  x$coffee_type[which(x$coffee_type == "Other type of coffee")] <- NA
  old_levels <- levels(x$coffee_type)
  x$coffee_type <- factor(x$coffee_type,
                          ordered = FALSE,
                          levels = old_levels[which(old_levels != "Other type of coffee")])
  x$coffee_type <- relevel(x$coffee_type,
                           ref = "Instant coffee")
  
  # hair_color
  x$hair_color[which(x$hair_color == "Other")] <- NA
  old_levels <- levels(x$hair_color)
  x$hair_color <- factor(x$hair_color,
                         ordered = FALSE,
                         levels = old_levels[which(old_levels != "Other")])
  x$hair_color <- relevel(x$hair_color,
                           ref = "Light brown")
  
  return(x)
  
}

# run in datasets
mult <- lapply(mult, crosstab_recode)
fmult <- lapply(fmult, crosstab_recode)

```

``` {r diet_recoding_men}
## recode diet type variables to account for nested

## bread type
for (k in seq_along(mult)) {
    
    levels(mult[[k]]$bread_type) <- c("Wholemeal or wholegrain",
                                      "White",
                                      "Brown",
                                      "Never eat bread")
    
    mult[[k]]$bread_type[which(mult[[k]]$bread == 0)] <- "Never eat bread"
}
 
# check for most common response type
prop.table(table(mult[[1]]$bread_type))

# set reference to most common
for (k in seq_along(mult)) {   
    
    mult[[k]]$bread_type <- relevel(mult[[k]]$bread_type, 
                                    ref = "Wholemeal or wholegrain")
}

## cereal type
for (k in seq_along(mult)) {
    
    levels(mult[[k]]$cereal_type) <- 
        c("Oat cereal (e.g. Ready Brek, porridge)",
          "Bran cereal (e.g. All Bran, Branflakes)",
          "Biscuit cereal (e.g. Weetabix)",
          "Muesli",
          "Other (e.g. Cornflakes, Frosties)",
          "Never eat cereal")
    
    mult[[k]]$cereal_type[which(mult[[k]]$cereal == 0)] <- "Never eat cereal"
}
 
# check for most common response type
prop.table(table(mult[[1]]$cereal_type))

## set reference to most common
for (k in seq_along(mult)) {   
    
    mult[[k]]$cereal_type <- relevel(mult[[k]]$cereal_type, 
                                     ref = "Other (e.g. Cornflakes, Frosties)")
}

# coffee type
for (k in seq_along(mult)) {
    
    levels(mult[[k]]$coffee_type) <- 
        c("Instant coffee",
          "Decaffeinated coffee (any type)",
          "Ground coffee (include espresso, filter etc)",
          "Never drink coffee")

    mult[[k]]$coffee_type[which(mult[[k]]$coffee == 0)] <- "Never drink coffee"
}
 
# check for most common response type
prop.table(table(mult[[1]]$coffee_type))

# set reference to most common
for (k in seq_along(mult)) {   
    
    mult[[k]]$coffee_type <- relevel(mult[[k]]$coffee_type, 
                                     ref = "Instant coffee")
}
```

``` {r diet_recoding_women}
## recode diet type variables to account for nested

## bread type
for (k in seq_along(fmult)) {
    
    levels(fmult[[k]]$bread_type) <- c("Wholemeal or wholegrain",
                                       "White",
                                       "Brown",
                                       "Never eat bread")
    
    fmult[[k]]$bread_type[which(fmult[[k]]$bread == 0)] <- "Never eat bread"
}

# check for most common response type
prop.table(table(fmult[[1]]$bread_type))

# set reference to most common
for (k in seq_along(fmult)) {   
    
    fmult[[k]]$bread_type <- relevel(fmult[[k]]$bread_type, 
                                     ref = "Wholemeal or wholegrain")
}

## cereal type
for (k in seq_along(fmult)) {
    
    levels(fmult[[k]]$cereal_type) <- 
        c("Oat cereal (e.g. Ready Brek, porridge)",
          "Bran cereal (e.g. All Bran, Branflakes)",
          "Biscuit cereal (e.g. Weetabix)",
          "Muesli",
          "Other (e.g. Cornflakes, Frosties)",
          "Never eat cereal")
    
    fmult[[k]]$cereal_type[which(fmult[[k]]$cereal == 0)] <- "Never eat cereal"
}

# check for most common response type
prop.table(table(fmult[[1]]$cereal_type))

## set reference to most common
for (k in seq_along(fmult)) {   
    
    fmult[[k]]$cereal_type <- relevel(fmult[[k]]$cereal_type, 
                                      ref = "Other (e.g. Cornflakes, Frosties)")
}

# coffee type
for (k in seq_along(fmult)) {
    
    levels(fmult[[k]]$coffee_type) <- 
        c("Instant coffee",
          "Decaffeinated coffee (any type)",
          "Ground coffee (include espresso, filter etc)",
          "Never drink coffee")
    
    fmult[[k]]$coffee_type[which(fmult[[k]]$coffee == 0)] <- "Never drink coffee"
}

# check for most common response type
prop.table(table(fmult[[1]]$coffee_type))

# set reference to most common
for (k in seq_along(fmult)) {   
    
    fmult[[k]]$coffee_type <- relevel(fmult[[k]]$coffee_type, 
                                      ref = "Instant coffee")
}
```

``` {r random_sampling, eval=FALSE}

### create random sample of discovery and validation 
### random sampling occurs within each level of the event indicator
### should preserve the overall outcome distribution of the data
### https://www.r-bloggers.com/2016/08/data-splitting/

library(caret)
library(summarytools)

set.seed(2345) # set the seed to make partition reproducible
train.rows <- createDataPartition(y = mult[[1]]$ACM_event_indicator, 
                                  p = 0.50, # 50% random subsample
                                  list = FALSE) # do not return data as list

# subset the data
mult_disc <- lapply(mult, function(x) x[train.rows, ])
mult_rep <- lapply(mult, function(x) x[-train.rows, ])

# check that proportion of cases is maintained
dfSummary(mult_disc[[1]]$ACM_event_indicator)
dfSummary(mult_rep[[1]]$ACM_event_indicator)
dfSummary(mult[[1]]$ACM_event_indicator)

set.seed(2345) # set the seed to make partition reproducible
train.rows <- createDataPartition(y = fmult[[1]]$ACM_event_indicator, 
                                  p = 0.50, # 50% random subsample
                                  list = FALSE) # do not return data as list

# subset the data
fmult_disc <- lapply(fmult, function(x) x[train.rows, ])
fmult_rep <- lapply(fmult, function(x) x[-train.rows, ])

# check that proportion of cases is maintained
dfSummary(fmult_disc[[1]]$ACM_event_indicator)
dfSummary(fmult_rep[[1]]$ACM_event_indicator)
dfSummary(fmult[[1]]$ACM_event_indicator)

# save
save(
    mult,
    mult_disc, 
    mult_rep, 
    fmult,
    fmult_disc,
    fmult_rep,
    file = "/path/to/file/ACM_final_analysis_datasets_feb_16_2022.RData")

```

```{r check_variance}
### check for any variables with 0 variance after splitting datasets in male/female and discovery/replication

library(dplyr)

# function to get number of unique responses to variables
find_unique <- function(x) {
  x %>%
    summarise_each(funs(n_distinct)) 
}

# get variables with 0 variance in discovery dataset 
unique <- lapply(mult_disc, find_unique)
no_variance <- lapply(unique, function(x) x[ ,which(x == 1)])

# get variables with 0 variance in replication dataset 
unique2 <- lapply(mult_rep, find_unique)
no_variance2 <- lapply(unique2, function(x) x[ ,which(x == 1)])

# get variables with 0 variance in discovery dataset 
funique <- lapply(fmult_disc, find_unique)
fno_variance <- lapply(funique, function(x) x <- x[ ,which(x == 1)])

# get variables with 0 variance in replication dataset 
funique2 <- lapply(fmult_rep, find_unique)
fno_variance2 <- lapply(funique2, function(x) x[ ,which(x == 1)])

# No variables with no variance in men
# 3 variables with no variance in women:
## cholesterol_meds
## blood_pressure_meds
## insulin

```