# Table 1 descriptive statistics

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(results = 'asis')
```

```{r packages, echo=FALSE }
library(table1)

```

```{r path}
path <- "/path/to/file"
```

```{r load}
# load analysis datasets
load(paste0(path, "/datasets/ACM_final_analysis_datasets_feb_16_2022.RData"))

# load data on disease status at baseline
load("/path/to/file/ID_and_NCD_may_15_2021.RData")
```

```{r combining_sex_datasets}

# get vector of common columns (vars) between men and women
common_cols <- intersect(colnames(mult[[1]]), colnames(fmult[[1]]))

# function to subset datasets to common columns
common_col_subset <- function(x) {
    x <- x[common_cols]
    return(x)
}

# run in datasets
mult_common <- lapply(mult, common_col_subset)
fmult_common <- lapply(fmult, common_col_subset)

# rbind male and female discovery datasets
all_data <- as.list(seq_along(fmult))
for (k in seq_along(all_data)) {
    all_data[[k]] <- rbind(mult_common[[k]],
                           fmult_common[[k]])
}

```

```{r table1_full_cohort}

# use just first imputed dataset
data <- all_data[[1]]

# make mortality event indicator a factor for table
data$ACM_event_indicator <- factor(data$ACM_event_indicator)

# rename factor levels
levels(data$ACM_event_indicator) <- c("Alive", "Dead")

# rename factor labels
label(data$education_years) <- "Education years"
label(data$recruitment_age) <- "Age"
label(data$BMI) <- "BMI"
label(data$pack_years) <- "Smoking pack years"
label(data$ethnicity) <- "Ethnicity"
label(data$hshld_income) <- "Household income"
label(data$ACM_event_indicator) <- "Mortality"
label(data$cancer_diagnosis) <- "Cancer diagnosis"
label(data$diabetes_diagnosis) <- "Diabetes diagnosis"
label(data$heart_attack_diagnosis) <- "Heart attack diagnosis"
label(data$stroke_diagnosis) <- "Stroke diagnosis"

# function to format continuous results
my.render.cont <- function(x) {
    with(stats.apply.rounding(stats.default(x), digits=2), c("",
        "Mean (SD)"=sprintf("%s (%s)", MEAN, SD)))
}

# function to format categorical results
my.render.categorical <- function(x, ...) {
    c("", sapply(stats.apply.rounding(stats.default(x)), function(y) with(y,
      sprintf("%s (%s%%)", prettyNum(FREQ, big.mark=","), PCT))))
}

# function to add in commas and number formatting
my.render.strat <- function (label, n, ...) {
    sprintf("<span class='stratlabel'>%s<br><span class='stratn'>(N=%s)</span></span>", 
        label, prettyNum(n, big.mark=","))
}

# create table
table <- 
    table1(~ recruitment_age + 
               hshld_income + 
               education_years + 
               ethnicity + 
               BMI + 
               pack_years + 
               cancer_diagnosis + 
               diabetes_diagnosis + 
               heart_attack_diagnosis + 
               stroke_diagnosis + 
               ACM_event_indicator | 
               # split dexcriptives by sex
               sex,
           data = data, 
           caption = "<font size='+1'><b>Descriptive statistics - UK Biobank</b></font>",
           render.continuous = my.render.cont,
           render.strat = my.render.strat,
           render.categorical = my.render.categorical,
           overall = "Total")

# show table. copy and paste into word
table
```

```{r healthy_prep}

# merge ICD-10 data with ACM datasets
data_disease <- lapply(all_data, function(x)
    as.data.frame(
        merge(x, 
              dat_all,
              by = "eid",
              all = FALSE,
              sort = FALSE)
    )
)

# function to code baseline disease indicator
identify_prev_disease <- function(x) {
    
    # define all participants with NCD diagnosis before or equal to recruitment date
    baseline_ncd <- which(x$NCD_censor_date <= x$recruitment_date)
    
    # creating health indicator for baseline disease in total population
    x$baseline_disease_indicator <- NA
    x$baseline_disease_indicator[baseline_ncd] <- 1
    x$baseline_disease_indicator[which(x$bronchitis_emphysema_diagnosis == "Yes")] <- 1
    x$baseline_disease_indicator[which(x$cancer_diagnosis == "Yes")] <- 1
    x$baseline_disease_indicator[which(x$diabetes_diagnosis == "Yes")] <- 1
    x$baseline_disease_indicator[which(x$heart_attack_diagnosis == "Yes")] <- 1
    x$baseline_disease_indicator[which(x$stroke_diagnosis == "Yes")] <- 1
    x$baseline_disease_indicator[which(x$number_cancers > 0)] <- 1
    x$baseline_disease_indicator[which(is.na(x$baseline_disease_indicator))] <- 0
    x$baseline_disease_indicator <- factor(x$baseline_disease_indicator)
    
    return(x)
}

# run function in each dataset
data_disease <- lapply(data_disease, identify_prev_disease)

# subset to those without disease at baseline
data_disease <- lapply(data_disease, function(x) {
    x <- x[which(x$baseline_disease_indicator == 0), ]
    return(x)
}
)

```

```{r table_healthy_subset}
# use just first imputed dataset
data <- data_disease[[1]]

# make mortality event indicator a factor for table
data$ACM_event_indicator <- factor(data$ACM_event_indicator)
# rename factor levels
levels(data$ACM_event_indicator) <- c("Alive", "Dead")

# rename factor labels
label(data$education_years) <- "Education years"
label(data$recruitment_age) <- "Age"
label(data$BMI) <- "BMI"
label(data$pack_years) <- "Smoking pack years"
label(data$ethnicity) <- "Ethnicity"
label(data$hshld_income) <- "Household income"
label(data$ACM_event_indicator) <- "Mortality"

# create table
table2 <- 
    table1(~ recruitment_age + 
               hshld_income + 
               education_years + 
               ethnicity + 
               BMI + 
               pack_years + 
               ACM_event_indicator | 
               sex,
           data = data, 
           caption = "<font size='+1'><b>Descriptive statistics - UK Biobank disease sensitivity subsample</b></font>",
           render.continuous = my.render.cont,
           render.strat = my.render.strat,
           render.categorical = my.render.categorical,
           overall = "Total")

# show table. copy and paste into word
table2
```

