
### Coding baseline illness diangoses from clinical interview data


## Set codes

```{r illness_codes, results='hide', eval=FALSE}

### defining chronic disease diagnosis codes 

### data field 20001 (cancer diagnoses)

# colorectal cancer 
colon_cancer_dx <- c(
    # large bowel cancer/colorectal cancer
    "1020",
    # colon cancer/sigmoid cancer
    "1022", 
    # rectal cancer
    "1023")

# lung cancer 
lung_cancer_dx <- c(
    # lung cancer
    "1001", 
    # small cell lung cancer
    "1027", 
    # non-small cell lung cancer
    "1028", 
    # trachea cancer
    "1080")

# eso cancer 
eso_cancer_dx <- c(
    # oesophageal cancer
    "1017")

# liver cancer 
liver_cancer_dx <- c(
    # liver/hepatocellular cancer
    "1024")

# pancreatic cancer 
pancreatic_cancer_dx <- c(
    # pancreas cancer
    "1026")

# brain cancer 
brain_cancer_dx <- c(
    # brain cancer / primary malignant brain tumour
    "1032")

# leukemia
leukemia_dx <- c(
    # leukaemia
    "1048")

# lymphoma
lymphoma_dx <- c(
    # lymphoma
    "1047")

# breast cancer 
breast_cancer_dx <- c(
    # breast cancer
    "1002")

# ovarian cancer
ovarian_cancer_dx <- c(
    # ovarian cancer
    "1039")

# prostate cancer 
prostate_cancer_dx <- c(
    # prostate cancer
    "1044")


### data field 20002 (non-cancer diagnoses)

# type II diabetes (E11)
diabetes_dx <- c(
    # type 2 diabetes
    "1223")

# ischemic heart diseases (I20–I25)
cardio_dx <- c(
    # angina
    "1074", 
    # heart attack/myocardial infarction
    "1075")

# hypertension (I10–I15)
hypertension_dx <- c(
    # hypertension
    "1065", 
    # essential hypertension
    "1072")

#cerebrovascular disease (I60–I69)
cerebro_dx <- c(
    # stroke
    "1081", 
    # subarachnoid haemorrhage
    "1086", 
    # brain haemorrhage
    "1491", 
    # ischaemic stroke
    "1583")

# COPD and emphysema (J40–J47)
copd_dx <- c(
    # chronic obstructive airways disease/copd
    "1112", 
    # emphysema
    "1472") 

# chronic liver disease (K70, K73-K74)
liver_dx <- c(
    # non-infective hepatitis
    "1157", 
    # liver failure/cirrhosis
    "1158", 
    # alcoholic liver disease / alcoholic cirrhosis
    "1604")

# chronic kidney disease (N18)
kidney_dx <- c(
    # renal/kidney failure
    "1192", 
    # renal failure requiring dialysis
    "1193", 
    # renal failure not requiring dialysis
    "1194")

# all-cause dementia (A81.0, F00-F03, F05.1, F10.6, G30-G31, I67.3)
all_dementia_dx <- c(
    # dementia/alzheimers/cognitive impairment
    "1263")

# vascular dementia (F01, I67.3)
vasc_dementia_dx <- c(
    # dementia/alzheimers/cognitive impairment
    "1263")

# Alzheimer's (F00, G30)
alzheimers_dx <- c(
    # dementia/alzheimers/cognitive impairment
    "1263")

# Parkinsons (G20-G22)
parkinsons_dx <- c(
    # parkinsons disease
    "1262")

# rheumatoid arthritis (M05-06)
rheumatoid_dx <- c(
    # rheumatoid arthritis
    "1464")

# macular degeneration (H35.3)
macular_dx <- c(
    # macular degeneration
    "1528")

# osteoporosis (M80-M81)
osteoporosis_dx <- c(
    # osteoporosis
    "1309")

# osteoarthritis (M15-M19)
osteoarthritis_dx <- c(
    # osteoarthritis
    "1465")


# create list of all NCD codes
dx_include <- c(
    colon_cancer_dx,
    lung_cancer_dx,
    breast_cancer_dx,
    prostate_cancer_dx,
    diabetes_dx,
    cardio_dx,
    hypertension_dx,
    cerebro_dx,
    copd_dx,
    liver_dx, 
    kidney_dx,
    all_dementia_dx,
    vasc_dementia_dx,
    alzheimers_dx,
    parkinsons_dx,
    rheumatoid_dx,
    macular_dx,
    osteoporosis_dx,
    osteoarthritis_dx
)

```

## Import raw UKB data

```{r import}
# import main UKB dataset
dat <- readRDS("/path/to/file/ukb42114.rds")

# cancer codes
prefix <- "f.20001.0."
suffix <- seq(0,5)
cancer_all <- paste0(prefix, suffix)

# non-cancer codes
prefix <- "f.20002.0."
suffix <- seq(0,33)
illness_all <- paste0(prefix, suffix)

dat <- subset(dat, 
              select = c("f.eid",
                         "f.53.0.0",
                         cancer_all,
                         illness_all
              ))


# save dataset with just dx data
save(dat, file = "/path/to/file/interview_dx_data.RData")
```

## Create diagnosis indicators

``` {r indicators}

load("/path/to/file/interview_dx_data.RData")

library(Hmisc)

# cancer codes
prefix <- "f.20001.0."
suffix <- seq(0,5)
cancer_all <- paste0(prefix, suffix)

# non-cancer codes
prefix <- "f.20002.0."
suffix <- seq(0,33)
illness_all <- paste0(prefix, suffix)

all_dx_data <- c(cancer_all, illness_all)


### NCD event indicator -------------------------------------------------------------------

# total # of NCD diagnoses per participant
dat$total_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", dx_include),
    na.rm = TRUE))

# indicator for any NCD diagnosis
dat$any_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", dx_include),
    na.rm = TRUE) > 0)

### Colon cancer event indicator -------------------------------------------------------------------

dat$colon_cancer_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", colon_cancer_dx),
    na.rm = TRUE) > 0)

### Lung cancer event indicator -------------------------------------------------------------------

dat$lung_cancer_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", lung_cancer_dx),
    na.rm = TRUE) > 0)

### eso cancer event indicator -------------------------------------------------------------------

dat$eso_cancer_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", eso_cancer_dx),
    na.rm = TRUE) > 0)

### liver cancer event indicator -------------------------------------------------------------------

dat$liver_cancer_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", liver_cancer_dx),
    na.rm = TRUE) > 0)

### pancreatic cancer event indicator ------------------------------------------------------

dat$pancreatic_cancer_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", pancreatic_cancer_dx),
    na.rm = TRUE) > 0)

### brain cancer event indicator -------------------------------------------------------------------

dat$brain_cancer_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", brain_cancer_dx),
    na.rm = TRUE) > 0)

### leukemia event indicator -------------------------------------------------------------------

dat$leukemia_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", leukemia_dx),
    na.rm = TRUE) > 0)

### lymphoma event indicator -------------------------------------------------------------------

dat$lymphoma_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", lymphoma_dx),
    na.rm = TRUE) > 0)

### Breast cancer event indicator -------------------------------------------------------------------

dat$breast_cancer_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", breast_cancer_dx),
    na.rm = TRUE) > 0)

### ovarian cancer event indicator -------------------------------------------------------------------

dat$ovarian_cancer_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", ovarian_cancer_dx),
    na.rm = TRUE) > 0)

### Prostate cancer event indicator -------------------------------------------------------------------

dat$prostate_cancer_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", prostate_cancer_dx),
    na.rm = TRUE) > 0)

### Type II diabetes event indicator -------------------------------------------------------------------

dat$diabetes_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", diabetes_dx),
    na.rm = TRUE) > 0)

### CVD event indicator -------------------------------------------------------------------

dat$CVD_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", cardio_dx),
    na.rm = TRUE) > 0)

### Hypertension event indicator -------------------------------------------------------------------

dat$hypertension_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", hypertension_dx),
    na.rm = TRUE) > 0)

### Cerebrovascular event indicator -------------------------------------------------------------------

dat$cerebro_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", cerebro_dx),
    na.rm = TRUE) > 0)

### COPD event indicator -------------------------------------------------------------------

dat$COPD_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", copd_dx),
    na.rm = TRUE) > 0)

### Liver disease event indicator -------------------------------------------------------------------

dat$liver_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", liver_dx),
    na.rm = TRUE) > 0)

### Kidney disease event indicator -------------------------------------------------------------------

dat$kidney_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", kidney_dx),
    na.rm = TRUE) > 0)

### All-cause dementia event indicator -------------------------------------------------------------------

dat$all_dementia_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", all_dementia_dx),
    na.rm = TRUE) > 0)

### Vascular dementia event indicator -------------------------------------------------------------------

dat$vasc_dementia_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", vasc_dementia_dx),
    na.rm = TRUE) > 0)

### Alzheimer's disease event indicator ------------------------------------------------------------------

dat$alzheimers_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", alzheimers_dx),
    na.rm = TRUE) > 0)

### Parkinson's disease event indicator ------------------------------------------------------------------

dat$parkinsons_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", parkinsons_dx),
    na.rm = TRUE) > 0)

### Rheumatoid arthritis event indicator -----------------------------------------------------------------

dat$rheumatoid_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", rheumatoid_dx),
    na.rm = TRUE) > 0)

### Macular degeneration event indicator ---------------------------------------------------------

dat$macular_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", macular_dx),
    na.rm = TRUE) > 0)

### Osteoporosis arthritis event indicator -----------------------------------------------------------------

dat$osteoporosis_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", osteoporosis_dx),
    na.rm = TRUE) > 0)

### osteoarthritis arthritis event indicator -----------------------------------------------------------------

dat$osteoarthritis_baseline_dx <- as.numeric(
  rowSums(
    sapply(dat[all_dx_data], "%in%", osteoarthritis_dx),
    na.rm = TRUE) > 0)


### Save -------------------------------------------------------------------

# rename eid
dat$eid <- dat$f.eid

dat_dx <- subset(
  dat,
  select = c(
    Cs(
        eid,
        total_baseline_dx,
        any_baseline_dx,
        colon_cancer_baseline_dx,
        lung_cancer_baseline_dx,
        eso_cancer_baseline_dx,
        liver_cancer_baseline_dx,
        pancreatic_cancer_baseline_dx,
        brain_cancer_baseline_dx,
        leukemia_baseline_dx,
        lymphoma_baseline_dx,
        breast_cancer_baseline_dx,
        ovarian_cancer_baseline_dx,
        prostate_cancer_baseline_dx,
        diabetes_baseline_dx,
        CVD_baseline_dx,
        hypertension_baseline_dx,
        cerebro_baseline_dx,
        COPD_baseline_dx,
        liver_baseline_dx,
        kidney_baseline_dx,
        all_dementia_baseline_dx,
        vasc_dementia_baseline_dx,
        alzheimers_baseline_dx,
        parkinsons_baseline_dx,
        rheumatoid_baseline_dx,
        macular_baseline_dx,
        osteoporosis_baseline_dx,
        osteoarthritis_baseline_dx
    )
  )
)


save(dat_dx, file = "/path/to/file/baseline_dx_data_july_07_2022.RData")
```
