# Comparison plot between female and male XWAS hazard ratios

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# set directory path
path <- "/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Analysis projects/ACM EWAS 2021"
```

```{r plot}
library(plotly)
library(ggplot2)
library(htmlwidgets)
library(ggpubr)

options(scipen = 999)

# load color palette
load(paste0(path,"/results/color_palette.RData"))

# load female results
load(paste0(path,"/results/full cohort/ACM_XWAS_results_feb_21_2022_women.RData"))

# rename
female_XWAS_total <- XWAS_total

#load male results
load(paste0(path,"/results/full cohort/ACM_XWAS_results_feb_16_2022_men.RData"))

# get common exposures
common_exposures <- intersect(XWAS_total$Exposure, female_XWAS_total$Exposure)

# merge
plots_df <- merge(XWAS_total[which(XWAS_total$Exposure %in% common_exposures), ], 
                  female_XWAS_total[which(female_XWAS_total$Exposure %in% common_exposures), ],
                  by = "Exposure",
                  all = TRUE,
                  sort = FALSE)

# merge categories for plot
plots_df$Category <- ifelse(!is.na(plots_df$Category.x),
                            plots_df$Category.x,
                            plots_df$Category.y)

# add in row for female reproductive factors to color_map
rep_factors <- data.frame("Female reproductive factors", "#678F63")
names(rep_factors) <- names(color_map)
color_map <- rbind(color_map, rep_factors)
color_map <- color_map[order(color_map$sequence), ]

color_map$color[which(color_map$sequence == "Stressful life events")] <- 
    color_map$color[which(color_map$sequence == "General health")]

color_map$sequence[which(color_map$sequence == "Medications")] <- "Supplements"
color_map$color[which(color_map$sequence == "Supplements")] <- 
    color_map$color[which(color_map$sequence == "Urine biomarkers")]

# merge color map with plots df
plots_df <- merge(plots_df, 
                  color_map, 
                  by.x = "Category",
                  by.y = "sequence", 
                  all = F)

# add in grey/black color for non-significant points
plots_df$color <- ifelse((plots_df$FDR.rep.x > 0.05 |
                             is.na(plots_df$FDR.rep.x)) &
                             (plots_df$FDR.rep.y > 0.05 |
                             is.na(plots_df$FDR.rep.y)),
                         "#4c4c4c",
                         plots_df$color)

# add in red color for points only significant in men
plots_df$color[which(plots_df$FDR.rep.x < 0.05 &
                         (plots_df$FDR.rep.y > 0.05 |
                              is.na(plots_df$FDR.rep.y)))] <- "#cc0610"

# add in blue color for points only significant in women
plots_df$color[which(plots_df$FDR.rep.y < 0.05 &
                         (plots_df$FDR.rep.x > 0.05 |
                              is.na(plots_df$FDR.rep.x)))] <- "#012380"

# add in "non-significant" category for plots
plots_df$Category <- ifelse(plots_df$color == "#4c4c4c",
                            "* Non-significant",
                            plots_df$Category)

# add in "non-significant" category for plots
plots_df$Category <- ifelse(plots_df$color == "#cc0610",
                            "* Only replicated in men",
                            plots_df$Category)

# add in "non-significant" category for plots
plots_df$Category <- ifelse(plots_df$color == "#012380",
                            "* Only replicated in women",
                            plots_df$Category)

names(plots_df)[names(plots_df) == "Hazard.Ratio.x"] <- "Hazard.Ratio.Men"
names(plots_df)[names(plots_df) == "Hazard.Ratio.y"] <- "Hazard.Ratio.Women"

# re-order so that black dots are behind colored dots
plots_df <- plots_df[order(plots_df$Category), ]

# correlation coefficient between men and women
hr_corr <- cor(plots_df$Hazard.Ratio.Men, 
               plots_df$Hazard.Ratio.Women)

beta_corr <- cor(plots_df$Beta.x, 
                 plots_df$Beta.y)

# regression line for plot
hazard.ratio.lm <- lm(Hazard.Ratio.Women ~ Hazard.Ratio.Men, plots_df)

# ggplot
comp_plot <- 
    ggplot(
        plots_df,
        aes(x = Hazard.Ratio.Men, 
            y = Hazard.Ratio.Women, 
            label = Exposure
        )) + 
    geom_point(
        aes(color = Category),
        size = 3) + 
    scale_color_manual(values = unique(plots_df$color)) +
    ggtitle("Comparison of Mortality XWAS Hazard Ratios - Men vs. Women") +
    labs(x = "Men",
         y = "Women") +
    theme_classic(base_size = 18) +
    # theme(legend.position = "none") +
    geom_hline(yintercept = 1, 
               color = "gray", 
               linetype = "dashed") + 
    geom_vline(xintercept = 1, 
               color = "gray", 
               linetype = "dashed") +
    scale_x_continuous(limits = c(0,3)) +
    # show correlation coefficient and p-value between hazard ratios
    stat_cor(method = "pearson",
             label.x.npc = "center",
             label.y.npc = "bottom",
             p.digits = 5,
             size = 6) +
    # show regression line between hazard ratios
    geom_abline(slope = coef(hazard.ratio.lm)[[2]], 
                intercept = coef(hazard.ratio.lm)[[1]],
                color = "red")


ggsave(comp_plot, 
       filename = paste0(path, "/output/full cohort/ACM_XWAS_HR_comparison_feb_21_2022.png"), width = 15, height = 10)

# text styling for plotly
t <- list(family = "sans-serif",
          size = 18,
          color = 'black')

# plotly interactive plot
fig <- ggplotly(comp_plot, 
                tooltip = c("x", 
                            "y", 
                            "label")) %>% 
  layout(title = "Comparison of Mortality XWAS Hazard Ratios - Men vs. Women", 
         font = t)

hide_legend(fig) 

# save HTML
saveWidget(fig, 
           file = paste0(path, "/output/full cohort/html/ACM_XWAS_HR_comparison_feb_21_2022.html"))
```

```{r}

library(Hmisc)

## create lists of vars significant in only men/women

# vars sig in men
men_sig_vars <- unique(XWAS_total$Variable[which(XWAS_total$FDR.rep <0.05)])

# vars sig in women
women_sig_vars <- unique(female_XWAS_total$Variable[which(female_XWAS_total$FDR.rep <0.05)])

# vars sig only in men
only_men <- men_sig_vars[which(men_sig_vars %nin% women_sig_vars)]

# vars sig only in women
only_women <- women_sig_vars[which(women_sig_vars %nin% men_sig_vars)]

# save
write.csv(only_men, file = paste0(path, "/output/full cohort/exposome_vars_sig_only_men_feb_21_2022.csv"))
write.csv(only_women, file = paste0(path, "/output/full cohort/exposome_vars_sig_only_women_feb_21_2022.csv"))

```