
### Cluster multivariable analyses

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(results = 'asis')
```

```{r packages, echo=FALSE}
library(survival)
library(mice)
library(modelsummary)
library(kableExtra)
library(readr)
library(Hmisc)
library(car)
library(MASS)
library(EValue)
library(Greg)
library(rms)
library(ggplot2)
library(shiny)
library(magrittr)
library(factoextra)
library(dplyr)
library(flextable)

options(scipen = 999)
```

## Data prep

```{r load}
# set path
path <- "/path/to/file"

# load datasets
load(paste0(path, "/datasets/ACM_final_analysis_datasets_aug_20_2022_all_data.RData"))

# load cluster results
clusters <- read.csv(file = paste0(path, "/output/correlation/hierarchical_exposome_8_clusters_sept_08_2022_all_data.csv"))

# remove junk first column
clusters <- clusters[, -1]

# create vector of variable names
variables <- as.vector(as.matrix(clusters)) 
variables <- variables[!is.na(variables)]


# load list of variables not significant in disease sensitivity
disease_vars <- read.csv(file = paste0(path, "/output/healthy subset/ACM_XWAS_sensitivity_non_sig_vars_list_sept_07_2022_all_sexes.csv"))
disease_vars <- as.vector(disease_vars[[2]])

variables <- variables[which(variables %nin% disease_vars)]

# load cluster reduce function
source(paste0(path, "/code/XWAS_cluster_reduce_function.R")) 
```

```{r data_prep}

# load XWAS results
load(paste0(path,"/results/full cohort/ACM_XWAS_results_sept_07_2022_all_sexes_summary.RData"))

# create vector of exposures (only variables replicated in the main XWAS)
exposures <- XWAS_total[which(XWAS_total$FDR.rep < 0.05), ]
exposures <- unique(exposures$Variable)

# use all_data file, which is men and women together + discovery and replication together too

# create age at censoring variables for age-at-risk analysis
for(j in seq_along(all_data)) {
    # divide survival time (days) by 365.25 to get time in years
    # change to numeric because survival time is a difftime object
    all_data[[j]]$time <- 
        as.numeric(all_data[[j]]$ACM_survival_time / 365.25) 
    # add time (years) to recruitment age to get censor age
    all_data[[j]]$censor_age <-
        all_data[[j]]$recruitment_age + all_data[[j]]$time 
}


### Create 5-year birth cohorts -------------------------------------------------------------------

# function to calculate birth cohorts
split_birth_year <- function(x){
    x$birth_cohort <- ifelse(
        x$birth_year >= 1935 & x$birth_year < 1940,
        "1935-1940",
        ifelse(
            x$birth_year >= 1940 & x$birth_year < 1945,
            "1940-1945",
            ifelse(
                x$birth_year >= 1945 & x$birth_year < 1950,
                "1945-1950",
                ifelse(
                    x$birth_year >= 1950 & x$birth_year < 1955,
                    "1950-1955",
                    ifelse(
                        x$birth_year >= 1955 & x$birth_year < 1960,
                        "1955-1960",
                        ifelse(
                            x$birth_year >= 1960 & x$birth_year < 1965,
                            "1960-1965",
                            ifelse(
                                x$birth_year >= 1965 & x$birth_year <= 1970, 
                                "1965-1970", 
                                NA
                            )
                        )
                    )
                )
            )
        )
    )
    
    x$birth_cohort <- as.factor(x$birth_cohort)
    return(x)
}

# execute function across imputed datasets to create 5-year age bands
all_data <- lapply(all_data, split_birth_year)


# copy datasets to have a version with no scaling
all_data_noscale <- all_data

### Scale -------------------------------------------------------------------

# scale function
scale_numeric <- function(x) { 
    # create logical vector of numeric columns
    nums <- sapply(x, is.numeric)
    
    # list of numeric variables to exclude from scaling
    scale_exclude <- c(
        Cs(
            recruitment_age,
            censor_age,
            ACM_event_indicator,
            eid,
            time,
            ACM_survival_time,
            hazard,
            birth_year
        )
    )
    
    # exclude those columns I don't want to scale
    nums[names(nums) %in% scale_exclude] <- FALSE # don't want to scale these
    
    # don't bother scaling other numeric cols not in analysis
    nums[names(nums) %nin% exposures] <- FALSE 
    
    # perform scale
    x[nums] <- scale(x[nums],
                     scale = TRUE)
    
    # return entire dataset
    return(x)
}

# scale desired numeric columns
all_data <- lapply(all_data, scale_numeric)


# copy datasets without changes to contrasts
all_data_contrasts <- all_data

# set contrasts for regression
set_contrasts <- function(x) {
    
    # find ordered variables
    ord <- sapply(x, is.ordered)
    
    # set contrasts to only linear
    for (k in seq(ncol(x[ord]))) {
        contrasts(x[ord][[k]], how.many = 1) <- contr.poly(nlevels(x[ord][[k]]))
    }
    
    return(x)
    
}

# run in datasets
all_data <- lapply(all_data, set_contrasts)

```

## Run cluster multivariable models

# Cluster 1

```{r cluster_1}

strata <- c(Cs(birth_cohort,sex))
c1.clusters <- 2
covariates <- c(Cs(recruitment_centre, ethnicity))
outcome = "Surv(recruitment_age, censor_age, ACM_event_indicator)"

source(paste0(path, "/code/XWAS_cluster_reduce_function.R"))
c1.reduce <- cluster_reduce(
    data = all_data,
    vif.data = all_data_contrasts,
    exclude.vars = disease_vars,
    clusters = c1.clusters,
    cluster.mat = clusters,
    model.type = "coxph",
    outcome = outcome,
    covariates = covariates,
    strata = strata,
    vif.limit = 1.6,
    vif.type = "GVIF^(1/(2*Df))",
    multi.imputation = TRUE
)


sig_vars.c1 <- c1.reduce$sig.vars
non_sig_vars.c1 <- c1.reduce$non.sig.vars
# summary(c1.reduce$pooled_models[[1]])

```

# Cluster 2

```{r cluster_2}
strata <- c(Cs(birth_cohort,sex))
c2.clusters <- 1
covariates <- c(Cs(recruitment_centre, ethnicity, hshld_income, education_years, overall_health))
outcome = "Surv(recruitment_age, censor_age, ACM_event_indicator)"

source(paste0(path, "/code/XWAS_cluster_reduce_function.R"))
c2.reduce <- cluster_reduce(
    data = all_data,
    vif.data = all_data_contrasts,
    exclude.vars = disease_vars,
    clusters = c2.clusters,
    cluster.mat = clusters,
    model.type = "coxph",
    outcome = outcome,
    covariates = covariates,
    strata = strata,
    vif.limit = 1.6,
    vif.type = "GVIF^(1/(2*Df))",
    multi.imputation = TRUE
)


sig_vars.c2 <- c2.reduce$sig.vars
non_sig_vars.c2 <- c2.reduce$non.sig.vars
# summary(c2.reduce$pooled_models[[1]])
```

# Check VIF of physical environment clusters

```{r VIF_check_physical_environment}

strata <- c(Cs(birth_cohort,sex))
c3.clusters <- 5
covariates <- c(Cs(ethnicity, education_years, recruitment_centre))
outcome = "Surv(recruitment_age, censor_age, ACM_event_indicator)"

# check VIF
source(paste0(path, "/code/XWAS_cluster_reduce_function.R"))
c3.reduce <- cluster_reduce(
    data = all_data,
    vif.data = all_data_contrasts,
    exclude.vars = disease_vars,
    clusters = c3.clusters,
    cluster.mat = clusters,
    vif.only = TRUE,
    model.type = "coxph",
    outcome = outcome,
    covariates = covariates,
    strata = strata,
    vif.limit = 1.6,
    vif.type = "GVIF^(1/(2*Df))",
    multi.imputation = TRUE
)

c5.clusters <- 7
c5.reduce <- cluster_reduce(
    data = all_data,
    vif.data = all_data_contrasts,
    exclude.vars = disease_vars,
    clusters = c4.clusters,
    cluster.mat = clusters,
    vif.only = TRUE,
    model.type = "coxph",
    outcome = outcome,
    covariates = covariates,
    strata = strata,
    vif.limit = 1.6,
    vif.type = "GVIF^(1/(2*Df))",
    multi.imputation = TRUE
)

c7.clusters <- 4
c7.reduce <- cluster_reduce(
    data = all_data,
    vif.data = all_data_contrasts,
    exclude.vars = disease_vars,
    clusters = c5.clusters,
    cluster.mat = clusters,
    vif.only = TRUE,
    model.type = "coxph",
    outcome = outcome,
    covariates = covariates,
    strata = strata,
    vif.limit = 1.6,
    vif.type = "GVIF^(1/(2*Df))",
    multi.imputation = TRUE
)

```

# Run PCA for physical environment variables

```{r environment_PCA}

# duplicate dataset for PCA
data_pca <- all_data

# make rownames eid
for (k in seq_along(data_pca)) {
    rownames(data_pca[[k]]) <- data_pca[[k]]$eid
}

# all pollution vars significant in XWAS
pollution_vars <- 
    c(
        Cs(
            NO_2010,
            NO2_2005,
            NO2_2006,
            NO2_2007,
            NO2_2010,
            PM10_2007,
            PM10_2010,
            PM2.5_2010,
            PM2.5_absorbance_2010
        )
    )

# all greenspace and natural environment vars significant in XWAS
greenspace_vars <- 
    c(
        Cs(
            greenspace_buffer_1000m,
            greenspace_buffer_300m,
            natural_environment_buffer_1000m,
            natural_environment_buffer_300m
        )
    )

# all noise pollution vars
noise_pollution_vars <-
    c(
        Cs(
            daytime_sound_average,
            evening_sound_average,
            night_sound_average,
            sound_average_16hr,
            sound_average_24hr
        )
    )

# all traffic vars
traffic_vars <-
    c(
        Cs(
            road_length_sum_100m,
            traffic_load_major_roads
        )
    )


# run PCA in each imputed dataset - set scale to F because already scaled above
set.seed(3456)
pollution_PCA_list <- 
    lapply(data_pca, function(x) {
        prcomp(x[which(names(x) %in% pollution_vars)], 
               scale = FALSE)
    }
)

set.seed(3456)
greenspace_PCA_list <- 
    lapply(data_pca, function(x) {
        prcomp(x[which(names(x) %in% greenspace_vars)], 
               scale = FALSE)
    }
)

set.seed(3456)
noise_pollution_PCA_list <- 
    lapply(data_pca, function(x) {
        prcomp(x[which(names(x) %in% noise_pollution_vars)], 
               scale = FALSE)
    }
)

set.seed(3456)
traffic_PCA_list <- 
    lapply(data_pca, function(x) {
        prcomp(x[which(names(x) %in% traffic_vars)], 
               scale = FALSE)
    }
)

# summary to see explained variance per PC
summary(pollution_PCA_list[[1]])
summary(pollution_PCA_list[[2]])
summary(pollution_PCA_list[[3]])
summary(pollution_PCA_list[[4]])
summary(pollution_PCA_list[[5]])
# first 3 PCs explain > 90% of variance in all datasets

summary(greenspace_PCA_list[[1]])
summary(greenspace_PCA_list[[2]])
summary(greenspace_PCA_list[[3]])
summary(greenspace_PCA_list[[4]])
summary(greenspace_PCA_list[[5]])
# first 2 PCs explain > 96% of variance in all datasets

summary(noise_pollution_PCA_list[[1]])
summary(noise_pollution_PCA_list[[2]])
summary(noise_pollution_PCA_list[[3]])
summary(noise_pollution_PCA_list[[4]])
summary(noise_pollution_PCA_list[[5]])
# first PC explains > 99% of variance in all datasets

summary(traffic_PCA_list[[1]])
summary(traffic_PCA_list[[2]])
summary(traffic_PCA_list[[3]])
summary(traffic_PCA_list[[4]])
summary(traffic_PCA_list[[5]])
# first PC explains > 91% of variance in all datasets

# get df of pollution PC scores for each participant
pollution_PCA_dfs <- 
    lapply(pollution_PCA_list, function(x) {
        # get individual PC scores
        df <- data.frame(x$x)
        # subset to just 3 PCs
        df <- df[1:3]
        # rename columns
        colnames(df) <- c("air_pollution_PC1", 
                          "air_pollution_PC2",
                          "air_pollution_PC3")
        # return df
        return(df)
    }
)

# get df of greenspace PC scores for each participant
greenspace_PCA_dfs <- 
    lapply(greenspace_PCA_list, function(x) {
        # get individual PC scores
        df <- data.frame(x$x)
        # subset to just 2 PCs
        df <- df[1:2]
        # rename columns
        colnames(df) <- c("greenspace_PC1", 
                          "greenspace_PC2")
        # return df
        return(df)
    }
)

# get df of noise pollution PC scores for each participant
noise_pollution_PCA_dfs <- 
    lapply(noise_pollution_PCA_list, function(x) {
        # get individual PC scores
        df <- data.frame(x$x)
        # subset to just 1 PC
        df <- df[1:1]
        # rename columns
        colnames(df) <- c("noise_pollution_PC1")
        # return df
        return(df)
    }
)

# get df of traffic PC scores for each participant
traffic_PCA_dfs <- 
    lapply(traffic_PCA_list, function(x) {
        # get individual PC scores
        df <- data.frame(x$x)
        # subset to just 1 PC
        df <- df[1:1]
        # rename columns
        colnames(df) <- c("traffic_PC1")
        # return df
        return(df)
    }
)

# make eids a column again for merge with larger dataset
for (k in seq_along(pollution_PCA_dfs)) {
    pollution_PCA_dfs[[k]]$eid <- rownames(pollution_PCA_dfs[[k]])
}

# make eids a column again for merge with larger dataset
for (k in seq_along(greenspace_PCA_dfs)) {
    greenspace_PCA_dfs[[k]]$eid <- rownames(greenspace_PCA_dfs[[k]])
}

# make eids a column again for merge with larger dataset
for (k in seq_along(noise_pollution_PCA_dfs)) {
    noise_pollution_PCA_dfs[[k]]$eid <- rownames(noise_pollution_PCA_dfs[[k]])
}

# make eids a column again for merge with larger dataset
for (k in seq_along(traffic_PCA_dfs)) {
    traffic_PCA_dfs[[k]]$eid <- rownames(traffic_PCA_dfs[[k]])
}

# merge PCA dfs together and save
pca_dfs <- as.list(seq_along(greenspace_PCA_dfs))
for (k in seq_along(pca_dfs)) {
    pca_dfs[[k]] <- 
        merge(pollution_PCA_dfs[[k]],
              greenspace_PCA_dfs[[k]],
              by = "eid",
              sort = FALSE)
}

for (k in seq_along(pca_dfs)) {
    pca_dfs[[k]] <- 
        merge(pca_dfs[[k]],
              noise_pollution_PCA_dfs[[k]],
              by = "eid",
              sort = FALSE)
}

for (k in seq_along(pca_dfs)) {
    pca_dfs[[k]] <- 
        merge(pca_dfs[[k]],
              traffic_PCA_dfs[[k]],
              by = "eid",
              sort = FALSE)
}

# check
colnames(pca_dfs[[1]])
nrow(pca_dfs[[1]])

```

```{r plot_PCA}
## make figures of variable loadings
## heatmap of loadings
library(reshape2)

pca1 <- pollution_PCA_list[[1]]
pca2 <- greenspace_PCA_list[[1]]
pca3 <- noise_pollution_PCA_list[[1]]
pca4 <- traffic_PCA_list[[1]]

pca_mat1 <- as.matrix(pca1$rotation[,1:3])
pca_mat1 <- ifelse(pca_mat1 > -0.3 & pca_mat1 < 0.3, 
                  0,
                  pca_mat1)
melted_cormat1 <- melt(pca_mat1)

pca_mat2 <- as.matrix(pca2$rotation[,1:2])
pca_mat2 <- ifelse(pca_mat2 > -0.3 & pca_mat2 < 0.3, 
                  0,
                  pca_mat2)
melted_cormat2 <- melt(pca_mat2)

pca_mat3 <- as.matrix(pca3$rotation[,1])
pca_mat3 <- ifelse(pca_mat3 > -0.3 & pca_mat3 < 0.3, 
                  0,
                  pca_mat3)
melted_cormat3 <- melt(pca_mat3)
melted_cormat3$Var2 <- "PC1"

pca_mat4 <- as.matrix(pca4$rotation[,1])
pca_mat4 <- ifelse(pca_mat4 > -0.3 & pca_mat4 < 0.3, 
                  0,
                  pca_mat4)
melted_cormat4 <- melt(pca_mat4)
melted_cormat4$Var2 <- "PC1"

heat1 <- 
    ggplot(data = melted_cormat1, aes(x=Var2, y=Var1, fill=value)) + 
    geom_tile(color = "white") +
    scale_fill_gradient2(
        low = "blue",
        high = "red",
        mid = "white",
        midpoint = 0,
        limit = c(-1, 1),
        space = "Lab",
        name = ""
    ) +
    ggtitle("PCA loadings for physical environment variables - UK Biobank") +
    theme_classic(base_size = 16) +   
    theme(
        legend.position = "right",
        # legend.title = element_text(size = 18)
        legend.title = element_blank(),
        plot.title.position = "plot",
        plot.title = element_text(size = 16),
        plot.subtitle = element_text(
            size = 14,
            face = "italic",
            margin = margin(0,0,30,0)
        )
    ) +
    labs(x = "",
         y = "",
         subtitle = "Note: only loadings < -0.3 or > 0.3 are colored"
    ) 

heat2 <- 
    ggplot(data = melted_cormat2, aes(x=Var2, y=Var1, fill=value)) + 
    geom_tile(color = "white") +
    scale_fill_gradient2(
        low = "blue",
        high = "red",
        mid = "white",
        midpoint = 0,
        limit = c(-1, 1),
        space = "Lab",
        name = ""
    ) +
    theme_classic(base_size = 16) +   
    theme(
        legend.position = "right",
        legend.title = element_blank(),
    ) +
    labs(x = "",
         y = ""
    ) 

heat3 <- 
    ggplot(data = melted_cormat3, aes(x=Var2, y=Var1, fill=value)) + 
    geom_tile(color = "white") +
    scale_fill_gradient2(
        low = "blue",
        high = "red",
        mid = "white",
        midpoint = 0,
        limit = c(-1, 1),
        space = "Lab",
        name = ""
    ) +
    theme_classic(base_size = 16) +   
    theme(
        legend.position = "right",
        legend.title = element_blank(),
    ) +
    labs(x = "",
         y = ""
    )

heat4 <- 
    ggplot(data = melted_cormat4, aes(x=Var2, y=Var1, fill=value)) + 
    geom_tile(color = "white") +
    scale_fill_gradient2(
        low = "blue",
        high = "red",
        mid = "white",
        midpoint = 0,
        limit = c(-1, 1),
        space = "Lab",
        name = ""
    ) +
    theme_classic(base_size = 16) +   
    theme(
        legend.position = "right",
        legend.title = element_blank(),
    ) +
    labs(x = "",
         y = ""
    )

library(gridExtra)
grid <- grid.arrange(heat1, heat2, heat3, heat4, ncol = 1, nrow = 4, widths = c(6), heights = c(20, 10, 10, 10))

ggsave(grid, filename = paste0(path, "/output/full cohort/cluster multivariate/phys_environment_PCA_nov_07_2022_four_PCAs.png"), width = 9, height = 11)
```

```{r merge_PCA}
# according to loadings, PC1 is inversely related to the pollution vars. So flip sign for sensible interpretation.
for (k in seq_along(pca_dfs)) {
pca_dfs[[k]]$air_pollution_PC1 <- pca_dfs[[k]]$air_pollution_PC1 * (-1)
}

# save
save(pca_dfs, file = paste0(path, "/results/physical_environment_PCA_nov_07_2022_all_sexes.RData"))

# scale for analyses
for (k in seq_along(pca_dfs)) {
pca_dfs[[k]][-1] <- scale(pca_dfs[[k]][-1], scale = TRUE)
}

# merge with analysis data
data_pca <- all_data
for (k in seq_along(data_pca)) {
    data_pca[[k]] <- 
        merge(data_pca[[k]],
              pca_dfs[[k]],
              by = "eid",
              sort = FALSE)
}

# merge also with contrasts dfs
data_contrasts_PCA <- all_data_contrasts
for (k in seq_along(data_contrasts_PCA)) {
    data_contrasts_PCA[[k]] <- 
        merge(data_contrasts_PCA[[k]],
              pca_dfs[[k]],
              by = "eid",
              sort = FALSE)
}

#check
nrow(data_pca[[1]])
```

# Cluster 3

```{r cluster_3}

strata <- c(Cs(birth_cohort,sex))
covariates <- c(Cs(ethnicity, hshld_income, education_years, recruitment_centre))
outcome = "Surv(recruitment_age, censor_age, ACM_event_indicator)"
c3.clusters <- 5

# combine cluster 1 and 2 together, since there are similar vars in each
vars_list <- as.vector(unlist(clusters[c3.clusters]))
vars_list <- vars_list[!is.na(vars_list)]
vars_list <- vars_list[vars_list %nin% greenspace_vars]
vars_list <- vars_list[vars_list %nin% disease_vars]
vars_list <- c(vars_list, c("greenspace_PC1", "greenspace_PC2"))

source(paste0(path, "/code/XWAS_cluster_reduce_function.R"))
c3.reduce <- cluster_reduce(
    data = data_pca,
    # data = all_data,
    vif.data = data_contrasts_PCA,
    # vif.data = all_data_contrasts,
    vars.list = vars_list,
    model.type = "coxph",
    outcome = outcome,
    covariates = covariates,
    strata = strata,
    vif.limit = 1.6,
    vif.type = "GVIF^(1/(2*Df))",
    multi.imputation = TRUE
)


sig_vars.c3 <- c3.reduce$sig.vars
non_sig_vars.c3 <- c3.reduce$non.sig.vars
# summary(c3.reduce$pooled_models[[1]])
```

# Clusters 1-3 combined

```{r cluster_1_2_3}

strata <- c(Cs(birth_cohort,sex))
covariates <- c(Cs(ethnicity, recruitment_centre))
outcome = "Surv(recruitment_age, censor_age, ACM_event_indicator)"

# combine cluster 1 and 2 together, since there are similar vars in each
vars_list <- c(sig_vars.c1, sig_vars.c2, sig_vars.c3)

source(paste0(path, "/code/XWAS_cluster_reduce_function.R"))
c1.c2.c3.reduce <- cluster_reduce(
    data = data_pca,
    vif.data = data_contrasts_PCA,
    vars.list = vars_list,
    model.type = "coxph",
    outcome = outcome,
    covariates = covariates,
    strata = strata,
    vif.limit = 1.6,
    vif.type = "GVIF^(1/(2*Df))",
    multi.imputation = TRUE
)


sig_vars.c1.c2.c3 <- c1.c2.c3.reduce$sig.vars
non_sig_vars.c1.c2.c3 <- c1.c2.c3.reduce$non.sig.vars
# summary(c1.c2.c3.reduce$pooled_models[[1]])
```

# Cluster 4

```{r cluster_4}

strata <- c(Cs(birth_cohort,sex))
c4.clusters <- 8
covariates <- c(Cs(recruitment_centre, education_years, hshld_income, ethnicity))
outcome = "Surv(recruitment_age, censor_age, ACM_event_indicator)"

source(paste0(path, "/code/XWAS_cluster_reduce_function.R"))
c4.reduce <- cluster_reduce(
    data = all_data,
    vif.data = all_data_contrasts,
    exclude.vars = disease_vars,
    clusters = c4.clusters,
    cluster.mat = clusters,
    alias.vars = "tobacco",
    vif.override = "pack_years_prop",
    model.type = "coxph",
    outcome = outcome,
    covariates = covariates,
    strata = strata,
    vif.limit = 1.6,
    vif.type = "GVIF^(1/(2*Df))",
    multi.imputation = TRUE
)


sig_vars.c4 <- c4.reduce$sig.vars
non_sig_vars.c4 <- c4.reduce$non.sig.vars
# summary(c4.reduce$pooled_models[[1]])

```

# Cluster 5

```{r cluster_5}

strata <- c(Cs(birth_cohort,sex))
covariates <- c(Cs(hshld_income, education_years, recruitment_centre, ethnicity))
outcome = "Surv(recruitment_age, censor_age, ACM_event_indicator)"
c5.clusters <- 7

# combine cluster 1 and 2 together, since there are similar vars in each
vars_list <- as.vector(unlist(clusters[c5.clusters]))
vars_list <- vars_list[!is.na(vars_list)]
vars_list <- vars_list[vars_list %nin% c(traffic_vars, noise_pollution_vars)]
vars_list <- vars_list[vars_list %nin% disease_vars]
vars_list <- c(vars_list, c("traffic_PC1", "noise_pollution_PC1"))

source(paste0(path, "/code/XWAS_cluster_reduce_function.R"))
c5.reduce <- cluster_reduce(
    data = data_pca,
    vif.data = data_contrasts_PCA,
    vars.list = vars_list,
    model.type = "coxph",
    outcome = outcome,
    covariates = covariates,
    strata = strata,
    vif.limit = 1.6,
    vif.type = "GVIF^(1/(2*Df))",
    multi.imputation = TRUE
)


sig_vars.c5 <- c5.reduce$sig.vars
non_sig_vars.c5 <- c5.reduce$non.sig.vars
# summary(c5.reduce$pooled_models[[1]])

```

# Cluster 6

```{r cluster_6}
strata <- c(Cs(birth_cohort,sex))
c6.clusters <- 3
covariates <- c(Cs(recruitment_centre, education_years, hshld_income))
outcome = "Surv(recruitment_age, censor_age, ACM_event_indicator)"

source(paste0(path, "/code/XWAS_cluster_reduce_function.R"))
c6.reduce <- cluster_reduce(
    data = all_data,
    vif.data = all_data_contrasts,
    exclude.vars = disease_vars,
    clusters = c6.clusters,
    cluster.mat = clusters,
    model.type = "coxph",
    outcome = outcome,
    covariates = covariates,
    strata = strata,
    vif.limit = 1.6,
    vif.type = "GVIF^(1/(2*Df))",
    multi.imputation = TRUE
)


sig_vars.c6 <- c6.reduce$sig.vars
non_sig_vars.c6 <- c6.reduce$non.sig.vars
# summary(c6.reduce$pooled_models[[1]])

```

# Cluster 7

```{r cluster_7}
strata <- c(Cs(birth_cohort,sex))
c7.clusters <- 4
covariates <- c(Cs(recruitment_centre, education_years, hshld_income, ethnicity))
outcome = "Surv(recruitment_age, censor_age, ACM_event_indicator)"

# combine cluster 1 and 2 together, since there are similar vars in each
vars_list <- as.vector(unlist(clusters[c7.clusters]))
vars_list <- vars_list[!is.na(vars_list)]
vars_list <- vars_list[vars_list %nin% pollution_vars]
vars_list <- vars_list[vars_list %nin% disease_vars]
vars_list <- c(vars_list, c("air_pollution_PC1", "air_pollution_PC2", "air_pollution_PC3"))

source(paste0(path, "/code/XWAS_cluster_reduce_function.R"))
c7.reduce <- cluster_reduce(
    data = data_pca,
    vif.data = data_contrasts_PCA,
    vars.list = vars_list,
    model.type = "coxph",
    outcome = outcome,
    covariates = covariates,
    strata = strata,
    vif.limit = 1.6,
    vif.type = "GVIF^(1/(2*Df))",
    multi.imputation = TRUE
)


sig_vars.c7 <- c7.reduce$sig.vars
non_sig_vars.c7 <- c7.reduce$non.sig.vars
# summary(c7.reduce$pooled_models[[1]])

```

# Cluster 8

```{r cluster_8}
strata <- c(Cs(birth_cohort,sex))
c8.clusters <- 6
covariates <- c(Cs(recruitment_centre, education_years, hshld_income, ethnicity))
outcome = "Surv(recruitment_age, censor_age, ACM_event_indicator)"

source(paste0(path, "/code/XWAS_cluster_reduce_function.R"))
c8.reducea <- cluster_reduce(
    data = all_data,
    vif.data = all_data_contrasts,
    exclude.vars = disease_vars,
    clusters = c8.clusters,
    cluster.mat = clusters,
    # vars.list = vars_list,
    model.type = "coxph",
    outcome = outcome,
    covariates = covariates,
    strata = strata,
    vif.limit = 1.6,
    vif.type = "GVIF^(1/(2*Df))",
    multi.imputation = TRUE
)


sig_vars.c8a <- c8.reducea$sig.vars
non_sig_vars.c8a <- c8.reducea$non.sig.vars
# summary(c8.reducea$pooled_models[[1]])

## remove two variables that flip signs and must be suffering from collinearity
vars_list <- sig_vars.c8a
vars_list <- vars_list[vars_list %nin% c("irritability", "worry_embarassment")]

source(paste0(path, "/code/XWAS_cluster_reduce_function.R"))
c8.reduce <- cluster_reduce(
    data = all_data,
    vif.data = all_data_contrasts,
    # exclude.vars = disease_vars,
    # clusters = c8.clusters,
    # cluster.mat = clusters,
    vars.list = vars_list,
    model.type = "coxph",
    outcome = outcome,
    covariates = covariates,
    strata = strata,
    vif.limit = 1.6,
    vif.type = "GVIF^(1/(2*Df))",
    multi.imputation = TRUE
)


sig_vars.c8 <- c8.reduce$sig.vars
non_sig_vars.c8 <- c8.reduce$non.sig.vars
# summary(c8.reduce$pooled_models[[1]])
```

# Clusters 4-8 combined

```{r cluster_4_to_8_combined}

strata <- c(Cs(birth_cohort,sex))
covariates <- c(Cs(hshld_income, education_years, recruitment_centre))
outcome = "Surv(recruitment_age, censor_age, ACM_event_indicator)"

# combine cluster 4 and 5 together, since there are similar vars in each
vars_list <- c(sig_vars.c4, sig_vars.c5, sig_vars.c6, sig_vars.c7, sig_vars.c8)

source(paste0(path, "/code/XWAS_cluster_reduce_function.R"))
c4.c8.reduce <- cluster_reduce(
    data = data_pca,
    vif.data = data_contrasts_PCA,
    vars.list = vars_list,
    model.type = "coxph",
    outcome = outcome,
    covariates = covariates,
    strata = strata,
    vif.limit = 1.6,
    vif.type = "GVIF^(1/(2*Df))",
    multi.imputation = TRUE
)


sig_vars.c4.c8 <- c4.c8.reduce$sig.vars
non_sig_vars.c4.c8 <- c4.c8.reduce$non.sig.vars
# summary(c4.c8.reduce$pooled_models[[1]])
```

## Create list of significant variables across all cluster models

```{r sig_vars_list}

all_sig_vars <- c(
    sig_vars.c1.c2.c3,
    sig_vars.c4.c8
)

length(all_sig_vars)

all_non_sig_vars <- c(
    non_sig_vars.c1,
    non_sig_vars.c2,
    non_sig_vars.c3,
    non_sig_vars.c1.c2.c3,
    non_sig_vars.c4,
    non_sig_vars.c5,
    non_sig_vars.c6,
    non_sig_vars.c7,
    non_sig_vars.c8a,
    non_sig_vars.c8,
    non_sig_vars.c4.c8
)

# check that all vars are accounted for
length(c(all_sig_vars, all_non_sig_vars))
total <- c(all_sig_vars, all_non_sig_vars)
variables[variables %nin% total]

# save variable list
write.csv(all_sig_vars, row.names = FALSE, file = paste0(path, "/output/full cohort/cluster multivariate/total_sig_vars_list_nov_07_2022_all_sexes.csv"))

# save variable list
write.csv(all_non_sig_vars, row.names = FALSE, file = paste0(path, "/output/full cohort/cluster multivariate/total_non_sig_vars_list_nov_07_2022_all_sexes.csv"))

```

## Save model output

```{r model_list}

# create list to store all model results
cluster_pool <- as.list(seq(1:11))
cluster_pool[[1]] <- c1.c2.c3.reduce$pooled_models[[1]]
cluster_pool[[2]] <- c4.c8.reduce$pooled_models[[1]]
cluster_pool[[3]] <- c1.reduce$pooled_models[[1]]
cluster_pool[[4]] <- c2.reduce$pooled_models[[1]]
cluster_pool[[5]] <- c3.reduce$pooled_models[[1]]
cluster_pool[[6]] <- c4.reduce$pooled_models[[1]]
cluster_pool[[7]] <- c5.reduce$pooled_models[[1]]
cluster_pool[[8]] <- c6.reduce$pooled_models[[1]]
cluster_pool[[9]] <- c7.reduce$pooled_models[[1]]
cluster_pool[[10]] <- c8.reducea$pooled_models[[1]]
cluster_pool[[11]] <- c8.reduce$pooled_models[[1]]

save(cluster_pool, file = paste0(path, "/results/full cohort/cluster multivariate/final_cluster_model_output_nov_07_2022_all_sexes.RData"))
```



















