
### Aging biomarker analysis

```{r packages, results='hide'}
library(Hmisc)
library(dplyr)
library(pbapply)
library(mice)
library(data.table)
```

## Load extra Vitamin D variables

```{r vit_D}

# import raw UKB dataset
dat <- readRDS("/path/to/file/ukb42114.rds")

# get date of vitamin assay (to control for seasonality of sun exposure)
vitamin_data <- 
    subset(dat,
           select = c(
               Cs(
                   f.eid,
                   f.30891.0.0
               )
           ))

# rename
vitamin_data <- 
    rename(vitamin_data,
           eid            = f.eid,    
           vitamin_D_date = f.30891.0.0
    )

# check how date is formatted for correct as.Date formatting
head(vitamin_data$vitamin_D_date) 

# set as date
vitamin_data$vitamin_D_date <- 
    as.Date(vitamin_data$vitamin_D_date, 
            format = "%Y/%m/%d")

# check for any formatting errors
head(vitamin_data$vitamin_D_date) 

# extract just month
vitamin_data$vitamin_D_month <- 
    months(vitamin_data$vitamin_D_date)

# check
head(vitamin_data$vitamin_D_month) 

# format as factor
vitamin_data$vitamin_D_month <- 
    factor(vitamin_data$vitamin_D_month, ordered = FALSE)

# check most common level
sort(table(vitamin_data$vitamin_D_month))

# set reference as most common level
vitamin_data$vitamin_D_month <- 
    relevel(vitamin_data$vitamin_D_month, ref = "May")

save(vitamin_data, file = "/path/to/file/vitamin_data_mar_24_2022.RData")

# remove raw dataset - very large
rm(dat)

# refresh working memory
gc()
```

## Load extra telomere variables

```{r telomeres}

# load raw UKB dataset containing telomere/metabolomics
dat <- readRDS("/path/to/file/ukb47736.rds")

### telomeres
telomere_data <- 
  subset(dat,
         select = c(
           Cs(
               f.eid,
               f.22190.0.0,
               f.22190.1.0,
               f.22190.2.0,
               f.22191.0.0,
               f.22191.1.0,
               f.22191.2.0,
               f.22192.0.0,
               f.22192.1.0,
               f.22192.2.0,
               f.22194.0.0,
               f.22194.1.0,
               f.22194.2.0	
           )
         ))

# vector of original col names
old_cols <- colnames(telomere_data)

# rename
telomere_data <- 
  rename(telomere_data,
         eid = f.eid,    
         LTL_unadj = f.22190.0.0,
         LTL_unadj_01 = f.22190.1.0,
         LTL_unadj_02 = f.22190.2.0,
         LTL_adj = f.22191.0.0,
         LTL_adj_01 = f.22191.1.0,
         LTL_adj_02 = f.22191.2.0,
         LTL_zadj = f.22192.0.0,
         LTL_zadj_01 = f.22192.1.0,
         LTL_zadj_02 = f.22192.2.0,
         LTL_dilution_bias = f.22194.0.0,
         LTL_dilution_bias_01 = f.22194.1.0,
         LTL_dilution_bias_02 = f.22194.2.0
  )

# vector of new col names
new_cols <- colnames(telomere_data)

# key that maps old col names to new col names
column_key_telomeres <- as.data.frame(cbind(old_cols, new_cols))

# check whether coded as numeric
sapply(telomere_data, is.numeric) 

# save
save(telomere_data, 
     column_key_telomeres,
     file = "/path/to/file/telomere_data_mar_07_2022.RData")

# remove raw dataset - very large
rm(dat)

# refresh working memory
gc()

```

## Load and merge exposure data

```{r load, results='hide'}

path <- "/path/to/file"

# load analysis datasets
load(paste0(path, "/datasets/ACM_final_analysis_datasets_aug_20_2022_all_data.RData"))

# load vitamin data
load(paste0(path, "/datasets/vitamin_data_mar_24_2022.RData"))

# load physical environment PCA results
load(paste0(path, "/results/physical_environment_PCA_nov_07_2022_all_sexes.RData"))

# load telomere data
load(paste0(path, "/datasets/telomere_data_mar_07_2022.RData"))

# load variable categories
categories <- read.csv("/Users/austin.argentieri/OneDrive - Nexus365/DPhil Research/UKB/Data dictionaries/Argentieri UKB dataset data dictionary.csv")
```

```{r merge}

nrow(all_data[[1]])
# merge telomere data
for (k in seq_along(all_data)) {
    all_data[[k]] <- merge(
        all_data[[k]],
        telomere_data,
        by = "eid",
        all.x = TRUE,
        all.y = FALSE,
        sort = FALSE
    )
}

# merge vitamin data
for (k in seq_along(all_data)) {
    all_data[[k]] <- merge(
        all_data[[k]],
        vitamin_data,
        by = "eid",
        all.x = TRUE,
        all.y = FALSE,
        sort = FALSE
    )
}

# merge PCA data
for (k in seq_along(all_data)) {
    all_data[[k]] <- merge(
        all_data[[k]],
        pca_dfs[[k]],
        by = "eid",
        all.x = TRUE,
        all.y = FALSE,
        sort = FALSE
    )
}

nrow(all_data[[1]])

```

## List of biomarkers

```{r biomarkers}
library(Hmisc)
## all aging-related biomarkers
## excluded:
# oestradiol
# testosterone
# SHBG
# calcium
# total_protein
# rheumatoid_factor - previously removed

biomarkers <-
    c(
        Cs(
            alanine_aminotransferase,
            albumin,
            alkaline_phosphatase,
            apolipoprotein_A,
            apolipoprotein_B,
            aspartate_aminotransferase,
            C_reactive_protein,
            cholesterol,
            creatinine,
            cystatin_C,
            direct_bilirubin,
            gamma_glutamyltransferase,
            glucose,
            hbA1c,
            HDL_cholesterol,
            IGF1,
            LDL_direct,
            lipoprotein_A,
            phosphate,
            total_bilirubin,
            triglycerides,
            urate,
            urea,
            vitamin_D
        )
    )

```

## Data prep

```{r variable_prep}

# load list of vars significant in cluster multivariate analyses
exposures <- read.csv(paste0(path, "/output/full cohort/cluster multivariate/total_sig_vars_list_nov_07_2022_all_sexes.csv"))

exposures <- as.vector(unlist(exposures[1]))

### Create 5-year birth cohorts -------------------------------------------------------------------

# function to calculate birth cohorts
split_birth_year <- function(x){
    x$birth_cohort <- ifelse(
        x$birth_year >= 1935 & x$birth_year < 1940,
        "1935-1940",
        ifelse(
            x$birth_year >= 1940 & x$birth_year < 1945,
            "1940-1945",
            ifelse(
                x$birth_year >= 1945 & x$birth_year < 1950,
                "1945-1950",
                ifelse(
                    x$birth_year >= 1950 & x$birth_year < 1955,
                    "1950-1955",
                    ifelse(
                        x$birth_year >= 1955 & x$birth_year < 1960,
                        "1955-1960",
                        ifelse(
                            x$birth_year >= 1960 & x$birth_year < 1965,
                            "1960-1965",
                            ifelse(
                                x$birth_year >= 1965 & x$birth_year <= 1970, 
                                "1965-1970", 
                                NA
                            )
                        )
                    )
                )
            )
        )
    )
    
    x$birth_cohort <- as.factor(x$birth_cohort)
    return(x)
}

# execute function across imputed datasets to create 5-year age bands
all_data <- lapply(all_data, split_birth_year)

### Scale -------------------------------------------------------------------

# scale function
scale_numeric <- function(x) { 
    # create logical vector of numeric columns
    nums <- sapply(x, is.numeric)
    
    # list of numeric variables to exclude from scaling
    scale_exclude <- c(
        biomarkers, 
        Cs(
            recruitment_age,
            censor_age,
            ACM_event_indicator,
            eid,
            time,
            ACM_survival_time,
            hazard,
            birth_year
        )
    )
    
    # exclude those columns I don't want to scale
    nums[names(nums) %in% scale_exclude] <- FALSE # don't want to scale these
    
    # don't bother scaling other numeric cols not in analysis
    nums[names(nums) %nin% exposures] <- FALSE 

    # perform scale
    x[nums] <- scale(x[nums],
                     scale = TRUE)
    
    # return entire dataset
    return(x)
}

# scale desired numeric columns
all_data <- lapply(all_data, scale_numeric)

# set contrasts for regression
set_contrasts <- function(x) {
    
    # find ordered variables
    ord <- sapply(x, is.ordered)
    
    # set contrasts to only linear
    for (k in seq(ncol(x[ord]))) {
        contrasts(x[ord][[k]], how.many = 1) <- contr.poly(nlevels(x[ord][[k]]))
    }
    
    return(x)
    
}

# run in datasets
all_data <- lapply(all_data, set_contrasts)

```

## Log transform biomarkers

```{r log_transform}

# create var names for log-transformed variables
log_names <- paste0("log_", biomarkers)

# log transform all biomarkers
all_data <- lapply(all_data, function(x) {
    x[log_names] <- NA
    x[log_names] <- log(x[biomarkers])
    return(x)
})

# add telomere variable to log names (it was already log transformed)
log_names <- c(log_names, "LTL_zadj")

```

## Adjust biomarkers for age (sex-specific)

```{r age_adjusted_residuals, eval=FALSE}

## make male and female datasets
male_dat <- as.list(seq_along(all_data))
for (k in seq_along(all_data)) {
    male_dat[[k]] <- all_data[[k]][which(all_data[[k]]$sex == "Male"), ]
}

female_dat <- as.list(seq_along(all_data))
for (k in seq_along(all_data)) {
    female_dat[[k]] <- all_data[[k]][which(all_data[[k]]$sex == "Female"), ]
}


## regress biomarkers against age in men

# set list of models
marker_models_men <- as.list(seq_along(log_names))
for (k in seq_along(marker_models_men)) {
    marker_models_men[[k]] <- as.list(seq_along(all_data))
}

marker_models_women <- as.list(seq_along(log_names))
for (k in seq_along(marker_models_women)) {
    marker_models_women[[k]] <- as.list(seq_along(all_data))
}

# run regressions of log biomarkers on age
marker_models_men <- lapply(log_names, function(x){
    
    fit <- as.list(seq_along(male_dat))
    
    for (k in seq_along(fit)) {
        fit[[k]] <- lm(as.formula(
            paste0(x,
                   " ~ recruitment_age")),
            data = male_dat[[k]],
            # to get NA rows in residuals where there's missing biomarker data
            na.action = na.exclude)
    
    }
    
    return(fit)
})

marker_models_women <- lapply(log_names, function(x){
    
    fit <- as.list(seq_along(female_dat))
    
    for (k in seq_along(fit)) {
        fit[[k]] <- lm(as.formula(
            paste0(x,
                   " ~ recruitment_age")),
            data = female_dat[[k]],
            # to get NA rows in residuals where there's missing biomarker data
            na.action = na.exclude)
        
    }
    
    return(fit)
})    
    
# check summary
summary(marker_models_men[[1]][[1]])
summary(marker_models_women[[1]][[1]])


## retrieve residuals

# set list of models
residuals_men <- as.list(seq_along(log_names))
for (k in seq_along(residuals_men)) {
    residuals_men[[k]] <- as.list(seq_along(all_data))
}

residuals_women <- as.list(seq_along(log_names))
for (k in seq_along(residuals_women)) {
    residuals_women[[k]] <- as.list(seq_along(all_data))
}

# retrieve residuals
residuals_men <- lapply(marker_models_men, function(x){
    res <- as.list(seq_along(male_dat))
    for (k in seq_along(male_dat)) {
        res[[k]] <- ifelse(!is.na(resid(x[[k]])),
                           resid(x[[k]]) + x[[k]]$coefficients["(Intercept)"],
                           NA)
    }
    
    return(res)
    
})

residuals_women <- lapply(marker_models_women, function(x) {
    res <- as.list(seq_along(female_dat))
    for (k in seq_along(female_dat)) {
        res[[k]] <- ifelse(!is.na(resid(x[[k]])),
                           resid(x[[k]]) + x[[k]]$coefficients["(Intercept)"],
                           NA)
    }
    
    return(res)
    
})

# check
all.equal(length(residuals_men[[1]][[1]]), nrow(male_dat[[1]]))
all.equal(length(residuals_women[[1]][[1]]), nrow(female_dat[[1]]))

## add residuals to data

# names of new residuals variables 
resid_vars <- paste0("r", log_names)

# add in residuals to datasets
for (j in seq_along(resid_vars)) {
    
    for (k in seq_along(male_dat)) {
        # add residuals to data
        male_dat[[k]][resid_vars[j]] <- residuals_men[[j]][[k]]
    }
}

for (j in seq_along(resid_vars)) {
    
    for (k in seq_along(female_dat)) {
        # add residuals to data
        female_dat[[k]][resid_vars[j]] <- residuals_women[[j]][[k]]
    }
}


# subset to just eid and residual variables
for (k in seq_along(female_dat)) {
    female_dat[[k]] <- subset(female_dat[[k]],
                              select = c("eid", resid_vars))
    male_dat[[k]] <- subset(male_dat[[k]],
                            select = c("eid", resid_vars))
}

# re-comine male and female residual data
resid_dat <- as.list(seq_along(all_data))
for (k in seq_along(resid_dat)) {
    resid_dat[[k]] <- rbind(male_dat[[k]],
                            female_dat[[k]])
}

# check
all.equal(nrow(resid_dat[[1]]), nrow(all_data[[1]]))

t <- nrow(all_data[[1]])

# merge
for (k in seq_along(all_data)) {
    all_data[[k]] <- merge(all_data[[k]],
                           resid_dat[[k]],
                           by = "eid",
                           all = FALSE,
                           sort = FALSE)
}

f <- nrow(all_data[[1]])

# check
t-f
```

```{r save_biomarker_dfs}

# save for quicker loading later
save(
    all_data,
    file = paste0(path, "/datasets/biomarker_analysis_datasets_nov_07_2022.RData"))

```

```{r load_final_data}

library(Hmisc)

# set path
path <- "/path/to/file"

# load biomarker analysis datasets
load(paste0(path, "/datasets/biomarker_analysis_datasets_nov_07_2022.RData"))

# load variable categories
categories <- read.csv("/path/to/file/Argentieri UKB dataset data dictionary.csv")

# set date for saving
date <- "nov_07_2022"

cores <- 2

# set list of outcome variable names
biomarkers <-
    c(
        Cs(
            alanine_aminotransferase,
            albumin,
            alkaline_phosphatase,
            apolipoprotein_A,
            apolipoprotein_B,
            aspartate_aminotransferase,
            C_reactive_protein,
            cholesterol,
            creatinine,
            cystatin_C,
            direct_bilirubin,
            gamma_glutamyltransferase,
            glucose,
            hbA1c,
            HDL_cholesterol,
            IGF1,
            LDL_direct,
            lipoprotein_A,
            phosphate,
            total_bilirubin,
            triglycerides,
            urate,
            urea,
            vitamin_D
        )
    )

# create var names for log-transformed variables
log_names <- paste0("log_", biomarkers)
# add telomere variable to log names
log_vars <- c(log_names, "LTL_zadj")
# names of new residuals variables 
resid_vars <- paste0("r", log_vars)

```

## Run biomarker models

```{r biomarker_analysis_model2_resid}

library(pbapply)
# set global R options
options(scipen = 999) # turn off scientific notation
pboptions(type = "timer", char = "=") # initialize progress bar

### Setting exposures -------------------------------------------------------------------

# load list of vars significant in cluster multivariate analyses
exposures <- read.csv(paste0(path, "/output/full cohort/cluster multivariate/total_sig_vars_list_nov_07_2022_all_sexes.csv"))
exposures <- as.vector(unlist(exposures[1]))

# add in categories to sort
exposures <- as.data.frame(exposures) # create df from exposure list
summary <- merge(exposures,
                 categories,
                 by.x = "exposures",
                 by.y = names(categories[1]),
                 all = F) # merge with categories
summary <- summary[order(summary$Category), ] # order exposures by category

# make final vector of exposures ordered by category
exposures <- as.vector(summary$exposures)

# list of XWAS covars
covar_list <- c("recruitment_centre", "education_years", "ethnicity")

# list of biomarkers with no special covariates
log_rest <- resid_vars[which(resid_vars %nin% c("rlog_IGF1", "rlog_vitamin_D", "rLTL_zadj"))]

### All biomarker model function -------------------------------------------------------------------

biomarker_model2 <- function(x){
    
    if (x %in% c("smoking_status", "pack_years_prop")) {
        
        models <- lapply(all_data, function(y)
            lm(as.formula(
                paste0(
                    paste0(
                        log_rest[[j]],
                        " ~ sex +
                            birth_cohort +
                            recruitment_centre + education_years + ethnicity + 
                            number_medications + 
                            IPAQ_activity_group + "),
                    x
                )
            ), data = y)
        )
        
        pool <- pool(models)
        rm(models)
    }
    
    else if (x == "IPAQ_activity_group") {
        
        models <- lapply(all_data, function(y)
            lm(as.formula(
                paste0(
                    paste0(
                        log_rest[[j]],
                        " ~ sex +
                            birth_cohort +
                            recruitment_centre + education_years + ethnicity + 
                            number_medications + 
                            smoking_status + "),
                    x
                )
            ), data = y)
        )
        
        pool <- pool(models)
        rm(models)
    }
    
    else if (x == "alcohol_freq") {
        
        models <- lapply(all_data, function(y)
            lm(as.formula(
                paste0(
                    paste0(
                        log_rest[[j]],
                        " ~ sex +
                            birth_cohort +
                            recruitment_centre + education_years + ethnicity + 
                            number_medications + 
                            smoking_status + IPAQ_activity_group + overall_health + "),
                    x
                )
            ), data = y)
        )
        
        pool <- pool(models)
        rm(models)
    }
    
    else if (x %in% covar_list) {
        
        models <- lapply(all_data, function(y)
            lm(
                paste0(
                    log_rest[[j]],
                    " ~ sex +
                        birth_cohort +
                        recruitment_centre + education_years + ethnicity + 
                        number_medications + 
                        smoking_status + IPAQ_activity_group"), 
                data = y)
        )
        
        pool <- pool(models)
        rm(models)
    }
    
    else {
        
        models <- lapply(all_data, function(y)
            lm(as.formula(
                paste0(
                    paste0(
                        log_rest[[j]],
                        " ~ sex +
                            birth_cohort +
                            recruitment_centre + education_years + ethnicity + 
                            number_medications + 
                            smoking_status + IPAQ_activity_group + "),
                    x
                )
            ), data = y)
        )
        
        pool <- pool(models)
        rm(models)
    }
    
    return(pool)
}

### IGF-1 model function -------------------------------------------------------------------

biomarker_model2_igf1 <- function(x){
    
    if (x %in% c("smoking_status", "pack_years_prop")) {
        
        models <- lapply(all_data, function(y)
            lm(as.formula(
                paste0(
                    "rlog_IGF1 ~ 
                        sex +
                        birth_cohort +
                        recruitment_centre + education_years + ethnicity + 
                        number_medications + 
                        standing_height +
                        IPAQ_activity_group + ",
                    x
                )
            ), data = y)
        )
        
        pool <- pool(models)
        rm(models)
    }
    
    else if (x == "IPAQ_activity_group") {
        
        models <- lapply(all_data, function(y)
            lm(as.formula(
                paste0(
                    "rlog_IGF1 ~ 
                        sex +
                        birth_cohort +
                        recruitment_centre + education_years + ethnicity + 
                        number_medications + 
                        standing_height +
                        smoking_status + ",
                    x
                )
            ), data = y)
        )
        
        pool <- pool(models)
        rm(models)
    }
    
    else if (x == "alcohol_freq") {
        
        models <- lapply(all_data, function(y)
            lm(as.formula(
                paste0(
                    "rlog_IGF1 ~ 
                        sex +
                        birth_cohort +
                        recruitment_centre + education_years + ethnicity + 
                        number_medications + 
                        standing_height +
                        smoking_status + IPAQ_activity_group + overall_health + ",
                    x
                )
            ), data = y)
        )
        
        pool <- pool(models)
        rm(models)
    }
    
    else if (x %in% covar_list) {
        
        models <- lapply(all_data, function(y)
            lm(rlog_IGF1 ~ 
                   sex +
                   birth_cohort +
                   recruitment_centre + education_years + ethnicity + 
                   number_medications + 
                   standing_height +
                   smoking_status + IPAQ_activity_group, 
               data = y)
        )
        
        pool <- pool(models)
        rm(models)
    }
    
    else {
        
        models <- lapply(all_data, function(y)
            lm(as.formula(
                paste0(
                    "rlog_IGF1 ~ 
                        sex +
                        birth_cohort +
                        recruitment_centre + education_years + ethnicity + 
                        number_medications + 
                        standing_height +
                        smoking_status + IPAQ_activity_group + ",
                    x
                )
            ), data = y)
        )
        
        pool <- pool(models)
        rm(models)
    }
    
    return(pool)
}

### vitamin D model function -------------------------------------------------------------------

biomarker_model2_vitD <- function(x){
    
    if (x %in% c("smoking_status", "pack_years_prop")) {
        
        models <- lapply(all_data, function(y)
            lm(as.formula(
                paste0(
                    "rlog_vitamin_D ~ 
                        sex +
                        birth_cohort +
                        recruitment_centre + education_years + ethnicity + 
                        number_medications + 
                        vitamin_D_month +
                        IPAQ_activity_group + ",
                    x
                )
            ), data = y)
        )
        
        pool <- pool(models)
        rm(models)
    }
    
    else if (x == "IPAQ_activity_group") {
        
        models <- lapply(all_data, function(y)
            lm(as.formula(
                paste0(
                    "rlog_vitamin_D ~ 
                        sex +
                        birth_cohort +
                        recruitment_centre + education_years + ethnicity + 
                        number_medications + 
                        vitamin_D_month +
                        smoking_status + ",
                    x
                )
            ), data = y)
        )
        
        pool <- pool(models)
        rm(models)
    }
    
    else if (x == "alcohol_freq") {
        
        models <- lapply(all_data, function(y)
            lm(as.formula(
                paste0(
                    "rlog_vitamin_D ~ 
                        sex +
                        birth_cohort +
                        recruitment_centre + education_years + ethnicity + 
                        number_medications + 
                        vitamin_D_month +
                        smoking_status + IPAQ_activity_group + overall_health + ",
                    x
                )
            ), data = y)
        )
        
        pool <- pool(models)
        rm(models)
    }
    
    else if (x %in% covar_list) {
        
        models <- lapply(all_data, function(y)
            lm(rlog_vitamin_D ~ 
                   sex +
                   birth_cohort +
                   recruitment_centre + education_years + ethnicity + 
                   number_medications + 
                   vitamin_D_month +
                   smoking_status + IPAQ_activity_group, 
               data = y)
        )
        
        pool <- pool(models)
        rm(models)
    }
    
    else {
        
        models <- lapply(all_data, function(y)
            lm(as.formula(
                paste0(
                    "rlog_vitamin_D ~ 
                        sex +
                        birth_cohort +
                        recruitment_centre + education_years + ethnicity + 
                        number_medications + 
                        vitamin_D_month +
                        smoking_status + IPAQ_activity_group + ",
                    x
                )
            ), data = y)
        )
        
        pool <- pool(models)
        rm(models)
    }
    
    return(pool)
}

### LTL model function -------------------------------------------------------------------

biomarker_model2_LTL <- function(x){
    
    if (x %in% c("smoking_status", "pack_years_prop")) {
        
        models <- lapply(all_data, function(y)
            lm(as.formula(
                paste0(
                    "rLTL_zadj ~ 
                        sex +
                        birth_cohort +
                        recruitment_centre + education_years + ethnicity + 
                        number_medications + 
                        leukocyte_count +
                        IPAQ_activity_group + ",
                    x
                )
            ), data = y)
        )
        
        pool <- pool(models)
        rm(models)
    }
    
    else if (x == "IPAQ_activity_group") {
        
        models <- lapply(all_data, function(y)
            lm(as.formula(
                paste0(
                    "rLTL_zadj ~ 
                        sex +
                        birth_cohort +
                        recruitment_centre + education_years + ethnicity + 
                        number_medications + 
                        leukocyte_count +
                        smoking_status + ",
                    x
                )
            ), data = y)
        )
        
        pool <- pool(models)
        rm(models)
    }
    
    else if (x == "alcohol_freq") {
        
        models <- lapply(all_data, function(y)
            lm(as.formula(
                paste0(
                    "rLTL_zadj ~ 
                        sex +
                        birth_cohort +
                        recruitment_centre + education_years + ethnicity + 
                        number_medications + 
                        leukocyte_count +
                        smoking_status + IPAQ_activity_group + overall_health + ",
                    x
                )
            ), data = y)
        )
        
        pool <- pool(models)
        rm(models)
    }
    
    else if (x %in% covar_list) {
        
        models <- lapply(all_data, function(y)
            lm(rLTL_zadj ~ 
                   sex +
                   birth_cohort +
                   recruitment_centre + education_years + ethnicity + 
                   number_medications + 
                   leukocyte_count +
                   smoking_status + IPAQ_activity_group, 
               data = y)
        )
        
        pool <- pool(models)
        rm(models)
    }
    
    else {
        
        models <- lapply(all_data, function(y)
            lm(as.formula(
                paste0(
                    "rLTL_zadj ~ 
                        sex +
                        birth_cohort +
                        recruitment_centre + education_years + ethnicity + 
                        number_medications + 
                        leukocyte_count +
                        smoking_status + IPAQ_activity_group + ",
                    x
                )
            ), data = y)
        )
        
        pool <- pool(models)
        rm(models)
    }
    
    return(pool)
}

### Run models -------------------------------------------------------------------

library(lubridate)

n_iter <- length(log_rest)
pb <- txtProgressBar(min = 0,
                     max = n_iter,
                     style = 3,
                     width = n_iter, # Needed to avoid multiple printings
                     char = "=") 
init <- numeric(n_iter)
end <- numeric(n_iter)

biomarker_models_rest <- as.list(seq_along(log_rest)) 
for (j in seq_along(log_rest)) {
    
    init[j] <- Sys.time()
    
    biomarker_models_rest[[j]] <- as.list(seq(1,length(exposures)))
    biomarker_models_rest[[j]] <- pblapply(exposures, biomarker_model2, cl = cores)

    invisible(gc())

    end[j] <- Sys.time()

    setTxtProgressBar(pb, j)
    time <- round(seconds_to_period(sum(end - init)), 0)
  
    # Estimated remaining time based on the
    # mean time that took to run the previous iterations
    est <- n_iter * (mean(end[end != 0] - init[init != 0])) - time
    remaining <- round(seconds_to_period(est), 0)
  
    cat(paste(" // Execution time:", time,
              " // Estimated time remaining:", remaining), "")
}

close(pb)

# run biomarker models that need extra covariates 
biomarker_models_igf1 <- pblapply(exposures, biomarker_model2_igf1, cl = cores)
invisible(gc())
biomarker_models_vitD <- pblapply(exposures, biomarker_model2_vitD, cl = cores)
invisible(gc())
biomarker_models_LTL  <- pblapply(exposures, biomarker_model2_LTL, cl = cores)
invisible(gc())

# combine lists of pooled models
biomarker_models <- biomarker_models_rest
biomarker_models[[23]] <- biomarker_models_igf1
biomarker_models[[24]] <- biomarker_models_vitD
biomarker_models[[25]] <- biomarker_models_LTL

### Summaries -------------------------------------------------------------------

covars <- which(exposures %in% covar_list)
smoke <- which(exposures %in% c("smoking_status", "pack_years_prop"))
ipaq <- which(exposures == "IPAQ_activity_group")
rest <- which(exposures %nin% c(covar_list, 
                                "smoking_status", 
                                "pack_years_prop", 
                                "IPAQ_activity_group"))

process_output <- function(x) {
    
    # get list of summaries for all pooled models (minus 3 above that overlap with covariates)
    smry <- lapply(x[rest],
                   summary,
                   conf.int = TRUE,
                   conf.level = 0.95)
    
    # extract all model summaries from the lists and convert to single data frame of estimates
    bio_rest <- rbindlist(smry)
    
    # rename column for exposure
    names(bio_rest)[names(bio_rest) == "term"] <- "Exposure"
    
    # calculate Hazard Ratio
    bio_rest$"exp(Beta)" <- exp(bio_rest$estimate)
    
    # exponentiate beta 95% CIs for HR 95% CIs
    bio_rest$"exp(Beta)_2.5%" <- exp(bio_rest$`2.5 %`)
    bio_rest$"exp(Beta)_97.5%" <- exp(bio_rest$`97.5 %`)
    
    # rename column for betas
    names(bio_rest)[names(bio_rest) == "estimate"] <- "Beta"
    
    # rename column for beta 95% CIs
    names(bio_rest)[names(bio_rest) == "2.5 %"] <- "Beta_2.5%"
    names(bio_rest)[names(bio_rest) == "97.5 %"] <- "Beta_97.5%"
    
    ### Getting accurate p-values  -------------------------------------------------------------------
    
    ### using summary on a mipo object (output from the pool function) rounds very small p-values to 0
    ### even when we set the # of digits to the max in R (22)
    ### so we have to hard code the math to get the p-values manually from the mipo object
    
    ## discovery 
    tstat <- as.list(seq(1,length(x[rest]))) # create list to store t stats
    p.val <- as.list(seq(1,length(x[rest]))) # create list to store p-values
    p_table <- as.list(seq(1,length(x[rest]))) # create list to p table dfs
    
    # loop to calculate p-values and create table of results
    for (j in seq_along(x[rest])) {
        # t statistic test using pooled estimate and pooled variance (t)
        tstat[[j]] <- x[rest][[j]]$pooled$estimate / sqrt(x[rest][[j]]$pooled$t)
        # calculate p-values
        p.val[[j]] <- as.data.frame(2 * pt(-abs(tstat[[j]]), df = x[rest][[j]]$pooled$df))
        # create df in p table
        p_table[[j]] <- data.frame(matrix(NA, nrow = nrow(p.val[[j]]), ncol = 2))
        # fill in p table
        p_table[[j]]$X2 <- p.val[[j]][[1]]
        # add in variable names
        p_table[[j]]$X1 <- x[rest][[j]]$pooled$term
    }
    
    # extract list into a single df
    p_table <- rbindlist(p_table)
    
    # change column names
    colnames(p_table) <- c("Exposure.p.table",
                           "p.value.full")
    
    # merge p table with XWAS results
    bio_rest <- cbind(bio_rest, p_table)
    
    # test to make sure the rows didn't get mixed up
    all.equal(bio_rest$Exposure, bio_rest$Exposure.p.table)
    
    # replace all 0 p-values from pooling with actual value
    bio_rest$p.value <- ifelse(bio_rest$p.value == 0, 
                               bio_rest$p.value.full,
                               bio_rest$p.value)
    
    # test to see if any 0 p-values remain
    paste("number of p-values rounded to 0:", 
          nrow(bio_rest[which(bio_rest$p.value == 0), ]))
    
    
    ### Remove covariate estimates ------------------------------------------------
    
    # remove the unwanted rows with coefficients for the covariates from each model
    # will need to add more lines if more covariates are used
    # strata terms (birth_cohort) are not listed in output and don't need removing
    
    bio_rest <- bio_rest[!grepl("(Intercept)", bio_rest$Exposure), ]
    bio_rest <- bio_rest[!grepl("recruitment_centre", bio_rest$Exposure), ]
    bio_rest <- bio_rest[!grepl("education_years", bio_rest$Exposure), ]
    bio_rest <- bio_rest[!grepl("ethnicity", bio_rest$Exposure), ]
    bio_rest <- bio_rest[!grepl("number_medications", bio_rest$Exposure), ]
    bio_rest <- bio_rest[!grepl("standing_height", bio_rest$Exposure), ]
    bio_rest <- bio_rest[!grepl("vitamin_D_month", bio_rest$Exposure), ]
    bio_rest <- bio_rest[!grepl("leukocyte_count", bio_rest$Exposure), ]
    bio_rest <- bio_rest[!grepl("smoking_status", bio_rest$Exposure), ]
    bio_rest <- bio_rest[!grepl("IPAQ_activity_group", bio_rest$Exposure), ]
    bio_rest <- bio_rest[!grepl("overall_health", bio_rest$Exposure), ]

    # remove ".L" from exposure names for ordinal variables - need to do after p-value step above
    bio_rest$Exposure <- gsub(".L", "", bio_rest$Exposure, fixed = TRUE)
    
    ### smoking -------------------------------------------------------------------

    # get list of summaries for all pooled models (minus 3 above that overlap with covariates)
    smry <- lapply(x[smoke],
                   summary,
                   conf.int = TRUE,
                   conf.level = 0.95)

    # extract all model summaries from the lists and convert to single data frame of estimates
    bio_smoke <- rbindlist(smry)

    # rename column for exposure
    names(bio_smoke)[names(bio_smoke) == "term"] <- "Exposure"

    # calculate Hazard Ratio
    bio_smoke$"exp(Beta)" <- exp(bio_smoke$estimate)

    # exponentiate beta 95% CIs for HR 95% CIs
    bio_smoke$"exp(Beta)_2.5%" <- exp(bio_smoke$`2.5 %`)
    bio_smoke$"exp(Beta)_97.5%" <- exp(bio_smoke$`97.5 %`)

    # rename column for betas
    names(bio_smoke)[names(bio_smoke) == "estimate"] <- "Beta"

    # rename column for beta 95% CIs
    names(bio_smoke)[names(bio_smoke) == "2.5 %"] <- "Beta_2.5%"
    names(bio_smoke)[names(bio_smoke) == "97.5 %"] <- "Beta_97.5%"

    ### Getting accurate p-values  -------------------------------------------------------------------

    ### using summary on a mipo object (output from the pool function) rounds very small p-values to 0
    ### even when we set the # of digits to the max in R (22)
    ### so we have to hard code the math to get the p-values manually from the mipo object

    ## discovery
    tstat <- as.list(seq(1,length(x[smoke]))) # create list to store t stats
    p.val <- as.list(seq(1,length(x[smoke]))) # create list to store p-values
    p_table <- as.list(seq(1,length(x[smoke]))) # create list to p table dfs

    # loop to calculate p-values and create table of results
    for (j in seq_along(x[smoke])) {
        # t statistic test using pooled estimate and pooled variance (t)
        tstat[[j]] <- x[smoke][[j]]$pooled$estimate / sqrt(x[smoke][[j]]$pooled$t)
        # calculate p-values
        p.val[[j]] <- as.data.frame(2 * pt(-abs(tstat[[j]]), df = x[smoke][[j]]$pooled$df))
        # create df in p table
        p_table[[j]] <- data.frame(matrix(NA, nrow = nrow(p.val[[j]]), ncol = 2))
        # fill in p table
        p_table[[j]]$X2 <- p.val[[j]][[1]]
        # add in variable names
        p_table[[j]]$X1 <- x[smoke][[j]]$pooled$term
    }

    # extract list into a single df
    p_table <- rbindlist(p_table)

    # change column names
    colnames(p_table) <- c("Exposure.p.table",
                           "p.value.full")

    # merge p table with XWAS results
    bio_smoke <- cbind(bio_smoke, p_table)

    # test to make sure the rows didn't get mixed up
    all.equal(bio_smoke$Exposure, bio_smoke$Exposure.p.table)

    # replace all 0 p-values from pooling with actual value
    bio_smoke$p.value <- ifelse(bio_smoke$p.value == 0,
                                bio_smoke$p.value.full,
                                bio_smoke$p.value)

    # test to see if any 0 p-values remain
    paste("number of p-values rounded to 0:",
          nrow(bio_smoke[which(bio_smoke$p.value == 0), ]))

    ### Remove covariate estimates ------------------------------------------------

    # remove the unwanted rows with coefficients for the covariates from each model
    # will need to add more lines if more covariates are used
    # strata terms (birth_cohort) are not listed in output and don't need removing

    bio_smoke <- bio_smoke[!grepl("(Intercept)", bio_smoke$Exposure), ]
    bio_smoke <- bio_smoke[!grepl("recruitment_centre", bio_smoke$Exposure), ]
    bio_smoke <- bio_smoke[!grepl("education_years", bio_smoke$Exposure), ]
    bio_smoke <- bio_smoke[!grepl("ethnicity", bio_smoke$Exposure), ]
    bio_smoke <- bio_smoke[!grepl("number_medications", bio_smoke$Exposure), ]
    bio_smoke <- bio_smoke[!grepl("standing_height", bio_smoke$Exposure), ]
    bio_smoke <- bio_smoke[!grepl("vitamin_D_month", bio_smoke$Exposure), ]
    bio_smoke <- bio_smoke[!grepl("leukocyte_count", bio_smoke$Exposure), ]
    bio_smoke <- bio_smoke[!grepl("IPAQ_activity_group", bio_smoke$Exposure), ]

    # remove ".L" from exposure names for ordinal variables - need to do after p-value step above
    bio_smoke$Exposure <- gsub(".L", "", bio_smoke$Exposure, fixed = TRUE)

    ### physical activity -------------------------------------------------------------------

    # extract all model summaries from the lists and convert to single data frame of estimates
    bio_pa <- summary(x[[ipaq]],
                      conf.int = TRUE,
                      conf.level = 0.95)

    # rename column for exposure
    names(bio_pa)[names(bio_pa) == "term"] <- "Exposure"

    # calculate Hazard Ratio
    bio_pa$"exp(Beta)" <- exp(bio_pa$estimate)

    # exponentiate beta 95% CIs for HR 95% CIs
    bio_pa$"exp(Beta)_2.5%" <- exp(bio_pa$`2.5 %`)
    bio_pa$"exp(Beta)_97.5%" <- exp(bio_pa$`97.5 %`)

    # rename column for betas
    names(bio_pa)[names(bio_pa) == "estimate"] <- "Beta"

    # rename column for beta 95% CIs
    names(bio_pa)[names(bio_pa) == "2.5 %"] <- "Beta_2.5%"
    names(bio_pa)[names(bio_pa) == "97.5 %"] <- "Beta_97.5%"

    ### Getting accurate p-values  -------------------------------------------------------------------

    ### using summary on a mipo object (output from the pool function) rounds very small p-values to 0
    ### even when we set the # of digits to the max in R (22)
    ### so we have to hard code the math to get the p-values manually from the mipo object

    # t statistic test using pooled estimate and pooled variance (t)
    tstat <- x[[ipaq]]$pooled$estimate / sqrt(x[[ipaq]]$pooled$t)
    # calculate p-values
    p.val <- as.data.frame(2 * pt(-abs(tstat), df = x[[ipaq]]$pooled$df))
    # create df in p table
    p_table <- data.frame(matrix(NA, nrow = nrow(p.val), ncol = 2))
    # fill in p table
    p_table$X2 <- p.val[[1]]
    # add in variable names
    p_table$X1 <- x[[ipaq]]$pooled$term

    # change column names
    colnames(p_table) <- c("Exposure.p.table",
                           "p.value.full")

    # merge p table with XWAS results
    bio_pa <- cbind(bio_pa, p_table)

    # test to make sure the rows didn't get mixed up
    all.equal(bio_pa$Exposure, bio_pa$Exposure.p.table)

    # replace all 0 p-values from pooling with actual value
    bio_pa$p.value <- ifelse(bio_pa$p.value == 0,
                             bio_pa$p.value.full,
                             bio_pa$p.value)

    # test to see if any 0 p-values remain
    paste("number of p-values rounded to 0:",
          nrow(bio_pa[which(bio_pa$p.value == 0), ]))


    ### Remove covariate estimates ------------------------------------------------

    # remove the unwanted rows with coefficients for the covariates from each model
    # will need to add more lines if more covariates are used
    # strata terms (birth_cohort) are not listed in output and don't need removing

    bio_pa <- bio_pa[!grepl("(Intercept)", bio_pa$Exposure), ]
    bio_pa <- bio_pa[!grepl("recruitment_centre", bio_pa$Exposure), ]
    bio_pa <- bio_pa[!grepl("education_years", bio_pa$Exposure), ]
    bio_pa <- bio_pa[!grepl("ethnicity", bio_pa$Exposure), ]
    bio_pa <- bio_pa[!grepl("number_medications", bio_pa$Exposure), ]
    bio_pa <- bio_pa[!grepl("standing_height", bio_pa$Exposure), ]
    bio_pa <- bio_pa[!grepl("vitamin_D_month", bio_pa$Exposure), ]
    bio_pa <- bio_pa[!grepl("leukocyte_count", bio_pa$Exposure), ]
    bio_pa <- bio_pa[!grepl("smoking_status", bio_pa$Exposure), ]

    # remove ".L" from exposure names for ordinal variables - need to do after p-value step above
    bio_pa$Exposure <- gsub(".L", "", bio_pa$Exposure, fixed = TRUE)

    ### covars -------------------------------------------------------------------

    # extract model summaries from just the first one, since they're all identical
    bio_covars <- summary(x[covars][[1]],
                          conf.int = TRUE,
                          conf.level = 0.95)

    # rename column for exposure
    names(bio_covars)[names(bio_covars) == "term"] <- "Exposure"

    # calculate Hazard Ratio
    bio_covars$"exp(Beta)" <- exp(bio_covars$estimate)

    # exponentiate beta 95% CIs for HR 95% CIs
    bio_covars$"exp(Beta)_2.5%" <- exp(bio_covars$`2.5 %`)
    bio_covars$"exp(Beta)_97.5%" <- exp(bio_covars$`97.5 %`)

    # rename column for betas
    names(bio_covars)[names(bio_covars) == "estimate"] <- "Beta"

    # rename column for beta 95% CIs
    names(bio_covars)[names(bio_covars) == "2.5 %"] <- "Beta_2.5%"
    names(bio_covars)[names(bio_covars) == "97.5 %"] <- "Beta_97.5%"

    ### Getting accurate p-values  -------------------------------------------------------------------

    ### using summary on a mipo object (output from the pool function) rounds very small p-values to 0
    ### even when we set the # of digits to the max in R (22)
    ### so we have to hard code the math to get the p-values manually from the mipo object

    tstat <- x[covars][[1]]$pooled$estimate / sqrt(x[covars][[1]]$pooled$t)
    # calculate p-values
    p.val <- as.data.frame(2 * pt(-abs(tstat), df = x[covars][[1]]$pooled$df))
    # create df in p table
    p_table <- data.frame(matrix(NA, nrow = nrow(p.val), ncol = 2))
    # fill in p table
    p_table$X2 <- p.val[[1]]
    # add in variable names
    p_table$X1 <- x[covars][[1]]$pooled$term

    # change column names
    colnames(p_table) <- c("Exposure.p.table",
                           "p.value.full")

    # merge p table with XWAS results
    bio_covars <- cbind(bio_covars, p_table)

    # test to make sure the rows didn't get mixed up
    all.equal(bio_covars$Exposure, bio_covars$Exposure.p.table)

    # replace all 0 p-values from pooling with actual value
    bio_covars$p.value <- ifelse(bio_covars$p.value == 0,
                                 bio_covars$p.value.full,
                                 bio_covars$p.value)

    # test to see if any 0 p-values remain
    paste("number of p-values rounded to 0:",
          nrow(bio_covars[which(bio_covars$p.value == 0), ]))

    ### Remove covariate estimates ------------------------------------------------

    # remove the unwanted rows with coefficients for the covariates from each model
    # will need to add more lines if more covariates are used
    # strata terms (birth_cohort) are not listed in output and don't need removing

    bio_covars <- bio_covars[!grepl("(Intercept)", bio_covars$Exposure), ]
    bio_covars <- bio_covars[!grepl("number_medications", bio_covars$Exposure), ]
    bio_covars <- bio_covars[!grepl("standing_height", bio_covars$Exposure), ]
    bio_covars <- bio_covars[!grepl("vitamin_D_month", bio_covars$Exposure), ]
    bio_covars <- bio_covars[!grepl("leukocyte_count", bio_covars$Exposure), ]
    bio_covars <- bio_covars[!grepl("smoking_status", bio_covars$Exposure), ]
    bio_covars <- bio_covars[!grepl("IPAQ_activity_group", bio_covars$Exposure), ]

    # remove ".L" from exposure names for ordinal variables - need to do after p-value step above
    bio_covars$Exposure <- gsub(".L", "", bio_covars$Exposure, fixed = TRUE)

    ### Merge -------------------------------------------------------------------

    # list of 4 output dfs
    dfs <- list(bio_rest, bio_smoke, bio_pa, bio_covars)

    # merge with rbind
    bio_total <- as.data.frame(do.call(rbind, dfs))


    ### Categories -------------------------------------------------------------------
    
    ## map variable names to results
    bio_total$Variable <- NA
    # create vector of variable names
    variables <- sort(as.vector(summary$exposures))
    
    # add variable names based on partial match with XWAS output exposure column with variable response level 
    # (e.g., match "alcohol_daily_intake" to "alcohol_daily_intakeDaily or almost daily")
    for(j in seq_along(variables)) {
        bio_total$Variable[bio_total$Exposure %in% bio_total$Exposure[substring(
            bio_total$Exposure,
            1,
            nchar(variables[[j]])) == variables[[j]]]] <- variables[[j]]
    }
    
    ## add in categories according to match with variable name
    bio_total <- merge(bio_total,  
                       subset(categories, select = c("Variable", "Category")), 
                       by = "Variable", 
                       all = F, 
                       sort = F)
    
    ### FDR -------------------------------------------------------------------
    
    ## calculate FDR in the discovery analyses using benjamini-hochberg method
    bio_total$FDR <- p.adjust(bio_total$p.value, 
                              method = "BH")
    
    ### Save -------------------------------------------------------------------
    
    # Re-order columns
    bio_total <- subset(bio_total,
                        select = c("Exposure",
                                   "Beta",
                                   "Beta_2.5%",
                                   "Beta_97.5%",
                                   "exp(Beta)",
                                   "exp(Beta)_2.5%",
                                   "exp(Beta)_97.5%",
                                   "p.value",
                                   "FDR",
                                   "std.error",
                                   "statistic",
                                   "df",
                                   "Variable",
                                   "Category"
                        ))
    
    rm(bio_covars,
       bio_pa,
       bio_smoke,
       bio_rest,
       p_table,
       tstat,
       p.val)
    
    return(bio_total)
}

# run summary function in all results
biomarker_results <- pblapply(biomarker_models, process_output)

# name each df with outcome biomarker variable
names <- biomarkers[which(biomarkers %nin% c(Cs(IGF1, vitamin_D)))]
names <- c(names, "IGF1", "vitamin_D", "LTL")
names(biomarker_results) <- names

# save
save(biomarker_results,
     biomarker_models,
     biomarker_models_rest,
     biomarker_models_igf1,
     biomarker_models_vitD,
     biomarker_models_LTL,
     biomarker_model2,
     biomarker_model2_igf1,
     biomarker_model2_vitD,
     biomarker_model2_LTL,
     file = paste0(paste0(paste0(path, "/results/mechanisms/biomarker_analysis_results_"), date), "_all_sexes_model2_resid.RData")
)

```
