
### Importing genetic and PRS data

```{r packages, echo=FALSE}
library(Hmisc)
library(dplyr)
```

```{r load}
# set path
path <- "/path/to/file"

# load analysis datasets
load(paste0(path, "/ACM_final_analysis_datasets_aug_20_2022_all_data.RData"))
load(paste0(path, "/ACM_final_analysis_datasets_aug_20_2022_scotwales.RData"))

# merge england and scotland/wales datasets
data <- rbind(all_data[[1]], scotwales[[1]])

# pull out just eid column
data <- as.data.frame(data$eid)
names(data) <- "eid"

# genotyping coding
coding <- read.csv("/coding22000_flat_GenotypingArray.csv")

# import PRS results from PLINK
PRS_leukemia <- read.delim("/path/to/file/prs_leukaemia75graff_20220805.sscore", header=TRUE) %>% rename(ID = IID)

PRS_lung <- read.delim("/path/to/file/prs_lung109graff_20220805.sscore", header=TRUE) %>% rename(ID = IID)

PRS_eso <- read.delim("/path/to/file/prs_oesophagus14choi_20220805.sscore", header=TRUE) %>% rename(ID = IID)

PRS_ovarian <- read.delim("/path/to/file/prs_ovary27kdareng_20220805.sscore", header=TRUE) %>% rename(ID = IID)

PRS_pancreatic <- read.delim("/path/to/file/prs_pancreas22graff_20220805.sscore", header=TRUE) %>% rename(ID = IID)

PRS_COPD <- read.delim("/path/to/file/prs_copd900kwang_20221103_flipalleles.sscore", header=TRUE) %>% rename(ID = IID)

# import raw UKB data with genotype batch and PC data
genotype_dat <- readRDS("/path/to/file/ukb51932.rds")

# import raw UKB data with pre-calculated PRS
PRS_dat <- readRDS("/path/to/file/ukb52679.rds")

```

## Exctract UKB pre-calculated PRS variables

```{r UKB_PRS}

### PRS data
PRS_dat <- 
  subset(PRS_dat,
         select = c(
           Cs(
               f.eid,
               f.26201.0.0,
               f.26220.0.0,
               f.26218.0.0,
               f.26267.0.0,
               f.26285.0.0,
               f.26223.0.0,
               f.26227.0.0,
               f.26248.0.0,
               f.26206.0.0,
               f.26260.0.0,
               f.26273.0.0,
               f.26204.0.0,
               f.26258.0.0,
               f.26216.0.0,
               f.26232.0.0,
               f.26244.0.0,
               f.26252.0.0,
               f.26242.0.0,
               f.26250.0.0
           )
         ))

# vector of original col names
old_cols <- colnames(PRS_dat)

# rename
PRS_dat <- 
  rename(PRS_dat,
         eid = f.eid,    
         PRS_PCAs = f.26201.0.0,
         PRS_breast = f.26220.0.0,
         PRS_bowel = f.26218.0.0,
         PRS_prostate = f.26267.0.0,
         PRS_T2D = f.26285.0.0,
         PRS_CVD = f.26223.0.0,
         PRS_CAD = f.26227.0.0,
         PRS_stroke = f.26248.0.0,
         PRS_alzheimers = f.26206.0.0,
         PRS_parkinsons = f.26260.0.0,
         PRS_rheumatoid = f.26273.0.0,
         PRS_macular = f.26204.0.0,
         PRS_osteoporosis = f.26258.0.0,
         PRS_BMI = f.26216.0.0,
         PRS_ovarian = f.26232.0.0,
         PRS_hypertension = f.26244.0.0,
         PRS_melanoma = f.26252.0.0,
         PRS_HDL = f.26242.0.0,
         PRS_LDL = f.26250.0.0
  )

# vector of new col names
new_cols <- colnames(PRS_dat)

# key that maps old col names to new col names
column_key_PRS <- as.data.frame(cbind(old_cols, new_cols))

# check whether coded as numeric
sapply(PRS_dat, is.numeric) 
sapply(PRS_dat, function(x) length(!is.na(x))) 

```

## Extract genotyping data

```{r genotyping_data}

gene_data <- 
  subset(genotype_dat,
         select = c(
           Cs(
               f.eid,
               f.22000.0.0,
               f.22009.0.1,
               f.22009.0.2,
               f.22009.0.3,
               f.22009.0.4,
               f.22009.0.5,
               f.22009.0.6,
               f.22009.0.7,
               f.22009.0.8,
               f.22009.0.9,
               f.22009.0.10,
               f.22009.0.11,
               f.22009.0.12,
               f.22009.0.13,
               f.22009.0.14,
               f.22009.0.15,
               f.22009.0.16,
               f.22009.0.17,
               f.22009.0.18,
               f.22009.0.19,
               f.22009.0.20
           )
         ))


# vector of original col names
old_cols <- colnames(gene_data)

# rename
gene_data <- 
  rename(gene_data,
         eid = f.eid,    
         GeP_Batch.0.0 = f.22000.0.0,
         GeP_PC1 = f.22009.0.1,
         GeP_PC2 = f.22009.0.2,
         GeP_PC3 = f.22009.0.3,
         GeP_PC4 = f.22009.0.4,
         GeP_PC5 = f.22009.0.5,
         GeP_PC6 = f.22009.0.6,
         GeP_PC7 = f.22009.0.7,
         GeP_PC8 = f.22009.0.8,
         GeP_PC9 = f.22009.0.9,
         GeP_PC10 = f.22009.0.10,
         GeP_PC11 = f.22009.0.11,
         GeP_PC12 = f.22009.0.12,
         GeP_PC13 = f.22009.0.13,
         GeP_PC14 = f.22009.0.14,
         GeP_PC15 =  f.22009.0.15,
         GeP_PC16 =  f.22009.0.16,
         GeP_PC17 = f.22009.0.17,
         GeP_PC18 =  f.22009.0.18,
         GeP_PC19 =  f.22009.0.19,
         GeP_PC20 = f.22009.0.20
  )

# vector of new col names
new_cols <- colnames(gene_data)

# key that maps old col names to new col names
column_key_hunter_PRS <- as.data.frame(cbind(old_cols, new_cols))

# code batch as binary
gene_data$GeP_Array <- coding$L0[match(gene_data$GeP_Batch.0.0, coding$Code)]
gene_data$GeP_Array <- factor(gene_data$GeP_Array, ordered = FALSE)
gene_data$GeP_Array <- relevel(gene_data$GeP_Array, ref = "Axiom")

```

## Process PRS variables calculated by our team

```{r hunter_PRS}

# leukemia rename
names(PRS_leukemia)[which(names(PRS_leukemia) == "SCORE1_AVG")] <- "PRS_leukemia"
# lekemia quintile
PRS_leukemia$PRS_leukemia_quintile <- NA
PRS_leukemia$PRS_leukemia_quintile <- cut(PRS_leukemia$PRS_leukemia, quantile(PRS_leukemia$PRS_leukemia, probs = seq(0, 1, 0.20), na.rm = TRUE))
table(PRS_leukemia$PRS_leukemia_quintile)
PRS_leukemia$PRS_leukemia_quintile <- factor(PRS_leukemia$PRS_leukemia_quintile, ordered = FALSE)
PRS_leukemia$PRS_leukemia_quintile <- relevel(PRS_leukemia$PRS_leukemia_quintile, ref = "(-0.0265,0.0124]")

# lung rename
names(PRS_lung)[which(names(PRS_lung) == "SCORE1_AVG")] <- "PRS_lung"
# lung quintile
PRS_lung$PRS_lung_quintile <- NA
PRS_lung$PRS_lung_quintile <- cut(PRS_lung$PRS_lung, quantile(PRS_lung$PRS_lung, probs = seq(0, 1, 0.20), na.rm = TRUE))
table(PRS_lung$PRS_lung_quintile)
PRS_lung$PRS_lung_quintile <- factor(PRS_lung$PRS_lung_quintile, ordered = FALSE)
PRS_lung$PRS_lung_quintile <- relevel(PRS_lung$PRS_lung_quintile, ref = "(-0.0165,0.00332]")

# eso rename
names(PRS_eso)[which(names(PRS_eso) == "SCORE1_AVG")] <- "PRS_eso"
# eso quintile
PRS_eso$PRS_eso_quintile <- NA
PRS_eso$PRS_eso_quintile <- cut(PRS_eso$PRS_eso, quantile(PRS_eso$PRS_eso, probs = seq(0, 1, 0.20), na.rm = TRUE))
table(PRS_eso$PRS_eso_quintile)
PRS_eso$PRS_eso_quintile <- factor(PRS_eso$PRS_eso_quintile, ordered = FALSE)
PRS_eso$PRS_eso_quintile <- relevel(PRS_eso$PRS_eso_quintile, ref = "(-0.378,-0.214]")

# ovarian rename
names(PRS_ovarian)[which(names(PRS_ovarian) == "SCORE1_AVG")] <- "PRS_ovarian_hunter"
# ovarian quintile
PRS_ovarian$PRS_ovarian_hunter_quintile <- NA
PRS_ovarian$PRS_ovarian_hunter_quintile <- cut(PRS_ovarian$PRS_ovarian_hunter, quantile(PRS_ovarian$PRS_ovarian_hunter, probs = seq(0, 1, 0.20), na.rm = TRUE))
table(PRS_ovarian$PRS_ovarian_hunter_quintile)
PRS_ovarian$PRS_ovarian_hunter_quintile <- factor(PRS_ovarian$PRS_ovarian_hunter_quintile, ordered = FALSE)
PRS_ovarian$PRS_ovarian_hunter_quintile <- relevel(PRS_ovarian$PRS_ovarian_hunter_quintile, ref = "(-4.25e-05,-1.86e-05]")

# pancreatic rename
names(PRS_pancreatic)[which(names(PRS_pancreatic) == "SCORE1_AVG")] <- "PRS_pancreatic"
# pancreatic quintile
PRS_pancreatic$PRS_pancreatic_quintile <- NA
PRS_pancreatic$PRS_pancreatic_quintile <- cut(PRS_pancreatic$PRS_pancreatic, quantile(PRS_pancreatic$PRS_pancreatic, probs = seq(0, 1, 0.20), na.rm = TRUE))
table(PRS_pancreatic$PRS_pancreatic_quintile)
PRS_pancreatic$PRS_pancreatic_quintile <- factor(PRS_pancreatic$PRS_pancreatic_quintile, ordered = FALSE)
PRS_pancreatic$PRS_pancreatic_quintile <- relevel(PRS_pancreatic$PRS_pancreatic_quintile, ref = "(-0.0593,-0.0204]")

# pancreatic rename
names(PRS_COPD)[which(names(PRS_COPD) == "SCORE1_AVG")] <- "PRS_COPD"
# pancreatic quintile
PRS_COPD$PRS_COPD_quintile <- NA
PRS_COPD$PRS_COPD_quintile <- cut(PRS_COPD$PRS_COPD, quantile(PRS_COPD$PRS_COPD, probs = seq(0, 1, 0.20), na.rm = TRUE))
table(PRS_COPD$PRS_COPD_quintile)
PRS_COPD$PRS_COPD_quintile <- factor(PRS_COPD$PRS_COPD_quintile, ordered = FALSE)
PRS_COPD$PRS_COPD_quintile <- relevel(PRS_COPD$PRS_COPD_quintile, ref = "(1.46e-07,3.97e-07]")

```

## Merge all datasets

```{r merge}

# merge data with genotype
PRS_data <- 
    merge(data, 
          gene_data,
          by = "eid",
          all = FALSE,
          sort = FALSE)

# merge data with UKB PRS data
PRS_data <- 
    merge(PRS_data, 
          PRS_dat,
          by = "eid",
          all = FALSE,
          sort = FALSE)

PRS_data <- 
    merge(PRS_data, 
          subset(PRS_leukemia, select = c("ID", "PRS_leukemia", "PRS_leukemia_quintile")),
          by.x = "eid",
          by.y = "ID",
          all = FALSE,
          sort = FALSE)

PRS_data <- 
    merge(PRS_data, 
          subset(PRS_lung, select = c("ID", "PRS_lung", "PRS_lung_quintile")),
          by.x = "eid",
          by.y = "ID",
          all = FALSE,
          sort = FALSE)

PRS_data <- 
    merge(PRS_data, 
          subset(PRS_eso, select = c("ID", "PRS_eso", "PRS_eso_quintile")),
          by.x = "eid",
          by.y = "ID",
          all = FALSE,
          sort = FALSE)

PRS_data <- 
    merge(PRS_data, 
          subset(PRS_ovarian, select = c("ID", "PRS_ovarian_hunter", "PRS_ovarian_hunter_quintile")),
          by.x = "eid",
          by.y = "ID",
          all = FALSE,
          sort = FALSE)

PRS_data <- 
    merge(PRS_data, 
          subset(PRS_pancreatic, select = c("ID", "PRS_pancreatic", "PRS_pancreatic_quintile")),
          by.x = "eid",
          by.y = "ID",
          all = FALSE,
          sort = FALSE)

PRS_data <- 
    merge(PRS_data, 
          subset(PRS_COPD, select = c("ID", "PRS_COPD", "PRS_COPD_quintile")),
          by.x = "eid",
          by.y = "ID",
          all = FALSE,
          sort = FALSE)

```

## Save

``` {r save}
# save
save(PRS_data, 
     column_key_PRS,
     column_key_hunter_PRS,
     file = "/path/to/file/PRS_data_nov_04_2022.RData")
```
