
### Fig S4 - calculate percent missing for final 55 exposures in unimputed data

```{r packages}
library(ggplot2)
library(Hmisc)
```

```{r load}

path <- "/path/to/file"

# load recoded dataset
dat <- readRDS("/path/to/file/ukb_full_recoded_dataset_aug_02_2022.rds")

# set list of exposures that were tested
exposures <- read.csv(paste0(path, "/output/full cohort/cluster multivariate/total_sig_vars_list_sept_08_2022_all_sexes.csv"))
exposures <- as.vector(unlist(exposures[1]))
```

## Make pretty exposure labels

```{r pretty_labels}
pretty_lables <- function(x) {
    
    x$pretty_labels <- x$Variable
    # make pretty labels for plot
    # this section will need to be tweaked for each new set of results
    x$pretty_labels <-
        gsub("_England", "", 
             x$pretty_labels, 
             fixed = TRUE)
    x$pretty_labels <-
        gsub("_", " ",
             x$pretty_labels,
             fixed = TRUE)
    x$pretty_labels <-
        gsub("hshld", "household", 
             x$pretty_labels, 
             fixed = TRUE)
    x$pretty_labels <-
        gsub("freq", "frequency", 
             x$pretty_labels, 
             fixed = TRUE)
    x$pretty_labels <-
        gsub("prop", "prop.",
             x$pretty_labels,
             fixed = TRUE)
    x$pretty_labels <- 
        gsub("pack", "smoking pack",
             x$pretty_labels,
             fixed = TRUE)
    x$pretty_labels <- 
        gsub("tobacco", "tobacco use",
             x$pretty_labels,
             fixed = TRUE)
    x$pretty_labels <- 
        gsub("environ", "environment",
             x$pretty_labels,
             fixed = TRUE)
    x$pretty_labels <- 
        gsub("10yrs", "10 yrs",
             x$pretty_labels,
             fixed = TRUE)
    
    x$pretty_labels[x$Variable == "worry_embarassment"] <- 
        "worry after embarassment"
    
    x$pretty_labels[x$Variable == "psychiatrist_visit_mental_health"] <- 
        "psychiatrist visit for MH"
    x$pretty_labels[x$Variable == "doctor_visit_mental_health"] <- 
        "doctor visit for MH"
    
    x$pretty_labels[x$Variable == "maternal_smoking"] <- 
        "maternal smoking around birth"
    
    x$pretty_labels[x$Variable == "open_fire_heat"] <- 
        "uses open fire for heating"
    x$pretty_labels[x$Variable == "gas_hob_heat"] <- 
        "uses gas hob for heating"
    x$pretty_labels[x$Variable == "gas_fire_heat"] <- 
        "uses gas fire for heating"
    
    x$pretty_labels[x$Variable == "mobile_phone_duration"] <- 
        "years using mobile phone"
    x$pretty_labels[x$Variable == "mobile_phone_2yrs"] <- 
        "mobile phone use now vs. 2 yrs ago"
    
    x$pretty_labels[x$Variable == "sex_age_first"] <- 
        "age first sexual intercourse"
    
    x$pretty_labels[x$Variable == "easy_wake"] <- 
        "easy to wake in the morning"
    
    x$pretty_labels[x$Variable == "hshld_vehicles"] <- 
        "no. household vehicles"
    
    x$pretty_labels[x$Variable == "hshld_number"] <- 
        "no. people living in household"
    
    x$pretty_labels[x$Variable == "own_or_rent"] <- 
        "home ownership"
    
    x$pretty_labels[x$Variable == "air_pollution_PC1"] <- 
        "air pollution"
    
    x$pretty_labels[x$Variable == "greenspace_PC1"] <- 
        "greenspace"
    
    return(x)
    
}

```

## Create plot

```{r plot}

# remove derived vars
vars <- exposures[exposures %nin% c("partial_fiber_score", "air_pollution_PC1", "greenspace_PC1", "education_years", "LTPA", "sedentary", "red_meat")]

# change name to original var used to make derived
vars[vars == "sleep_hours_categorical"] <- "sleep_hours"

# add components of derived vars
vars <- c(vars, 
          "beef",
          "lamb", 
          "pork", 
          "cereal_type", 
          "bread_type",
          "fresh_fruit",
          "dried_fruit",
          "cooked_veg",
          "salad_or_raw_veg",
          "pleasure_walks_4wks",
          "other_exercise_4wks",
          "strenuous_sports_4wks",
          "heavy_DIY_4wks",
          "light_DIY_4wks",
          "TV_time",
          "computer_time",
          "driving_time",
          "education_college",
          "education_NVQ",
          "education_other_professional",
          "education_A_levels",
          "education_O_levels",
          "education_CSEs",
          "education_none",
          "NO_2010",
          "NO2_2005",
          "NO2_2006",
          "NO2_2007",
          "NO2_2010",
          "PM10_2007",
          "PM10_2010",
          "PM2.5_2010",
          "PM2.5_absorbance_2010",
          "greenspace_buffer_1000m",
          'greenspace_buffer_300m',
          "natural_environment_buffer_1000m",
          "natural_environment_buffer_300m")

# subset data to vars
missdat <- dat[vars]

# make df of missing percentages
missdf <- data.frame(matrix(ncol = 2, nrow = ncol(missdat)))
colnames(missdf) <- c("Variable", "pct_miss")
missdf$Variable <- colnames(missdat)
missdf$pct_miss <- sapply(missdat, function(x) length(which(is.na(x)))/length(x))
missdf$pct_miss <- missdf$pct_miss*100
missdf <- pretty_lables(missdf)
missdf <- missdf[order(missdf$pct_miss, decreasing = TRUE), ]
var_order <- missdf$pretty_labels
missdf$pretty_labels <- factor(missdf$pretty_labels, levels = var_order)

# add in variable categories
missdf <- merge(missdf,
                subset(categories, select = c("Variable", "Category")),
                by = "Variable",
                all.x = TRUE,
                all.y = FALSE)

# color palette
load(paste0(path,"/results/color_palette.RData"))
color_map$sequence[which(color_map$sequence == "Medications")] <- "Supplements"
color_map$color[which(color_map$sequence == "Supplements")] <- 
    color_map$color[which(color_map$sequence == "Urine biomarkers")]
pal <- merge(missdf, 
             color_map, 
             by.x = "Category",
             by.y = "sequence", 
             all = T)
pal <- pal[which(!is.na(pal$Variable)), ]
pal <- unique(pal$color)

# plot
miss <- ggplot(missdf, aes(x = pct_miss, y = pretty_labels, fill = Category)) + 
    geom_bar(position = "dodge", stat = "identity") +
    scale_fill_manual(values = pal) +
    theme_classic() +
    ylab("Exposome variable") +
    xlab("Percent missing") +
    scale_x_continuous(expand = expansion(mult = c(0.02, 0.1)),
                       limits = c(0,70), breaks = seq(0,70, by = 5)) +
    scale_y_discrete(expand = expansion(mult = c(0.02, 0.01))) +
    theme(
        axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.position =  c(0.8,0.6),
        legend.text = element_text( size = 8),
        legend.title = element_text( size = 10),
        legend.key.width = unit(0.4, "cm"),
        legend.key.height = unit(0.4, "cm"))

# save
ggsave(miss, filename = paste0(path, "/output/supplement/missing_percent_unimputed_sept_16_2022.jpg"), width = 9, height = 11)

```
