
### Tables S5-S6 - mortality by cause of death

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(results = 'hide')
knitr::opts_chunk$set(eval =  FALSE)
```

```{r packages}

library(readr)
library(tidyr)
library(dplyr)
library(Hmisc)
library(table1)
library(flextable)

```

```{r path}
path <- "/path/to/file"
```

``` {r load}

# import mortality data
mort <- read_delim("/path/to/file/mortality_may_04_2022.txt",
    "\t", escape_double = FALSE, trim_ws = TRUE)


# import cause of death (COD) data. 
# more info here: http://biobank.ndph.ox.ac.uk/showcase/showcase/docs/DeathLinkage.pdf.
dat_COD <- read_delim("/path/to/file/mortality_cause_may_04_2022.txt", # cause of death table. 
    "\t", 
    escape_double = FALSE, 
    trim_ws = TRUE)

# load analysis datasets
load(paste0(path, "/datasets/ACM_final_analysis_datasets_aug_20_2022_all_data.RData"))
load(paste0(path, "/datasets/ACM_final_analysis_datasets_aug_20_2022_scotwales.RData"))

```

## Set ICD-10 codes

```{r ICD, results='hide', eval=FALSE}

# import list of ICD-10 codes from UKB website: https://biobank.ctsu.ox.ac.uk/crystal/coding.cgi?id=19&nl=1 
ICD10list3d <- read_delim("/path/to/file/icd10_coding19.tsv", 
    "\t", 
    escape_double = FALSE, 
    trim_ws = TRUE)

# make character vector with just ICD codes
ICD10list3d <- as.vector(ICD10list3d$coding)

### defining chronic diseases by ICD 10 codes --------------------------------------------------
## all incident diseases associated with at least 1 exposure in analyses

# colorectal cancer (C18-C20)
prefix <- "C18"
suffix <- sprintf('%0.1d', 0:9)
seq <- paste0(prefix, suffix)
seq1 <- paste0("C19", suffix)
seq2 <- paste0("C20", suffix)

colon_cancer <- c("C18", "C19", "C20", seq, seq1, seq2)
colon_cancer_icd <- ICD10list3d[which(ICD10list3d %in% colon_cancer)]

# lung cancer (C33-34)
prefix <- "C33"
suffix <- sprintf('%0.1d', 0:9)
seq <- paste0(prefix, suffix)
seq1 <- paste0("C34", suffix)

lung_cancer <- c("C33", "C34", seq, seq1)
lung_cancer_icd <- ICD10list3d[which(ICD10list3d %in% lung_cancer)]

# esophageal cancer (C15)
prefix <- "C15"
suffix <- sprintf('%0.1d', 0:9)
seq <- paste0(prefix, suffix)

eso_cancer <- c("C15", seq)
eso_cancer_icd <- ICD10list3d[which(ICD10list3d %in% eso_cancer)]

# liver cancer (C22)
prefix <- "C22"
suffix <- sprintf('%0.1d', 0:9)
seq <- paste0(prefix, suffix)

liver_cancer <- c("C22", seq)
liver_cancer_icd <- ICD10list3d[which(ICD10list3d %in% liver_cancer)]

# pancreatic cancer (C25)
prefix <- "C25"
suffix <- sprintf('%0.1d', 0:9)
seq <- paste0(prefix, suffix)

pancreatic_cancer <- c("C25", seq)
pancreatic_cancer_icd <- ICD10list3d[which(ICD10list3d %in% pancreatic_cancer)]

# leukemia (C91-C95)
prefix <- "C"
suffix <- seq(91,95)
seq <- paste0(prefix, suffix)

prefix <- "C"
suffix <- seq(910,959)
seq2 <- paste0(prefix, suffix)

leukemia <- c(seq, seq2)
leukemia_icd <- ICD10list3d[which(ICD10list3d %in% leukemia)]

# lymphoma (C81-C86, C88)
prefix <- "C"
suffix <- seq(81,86)
seq <- paste0(prefix, suffix)

prefix <- "C"
suffix <- seq(810,869)
seq2 <- paste0(prefix, suffix)

prefix <- "C88"
suffix <- sprintf('%0.1d', 0:9)
seq3 <- paste0(prefix, suffix)

lymphoma <- c(seq, seq2, "C88", seq3)
lymphoma_icd <- ICD10list3d[which(ICD10list3d %in% lymphoma)]

# breast cancer (C50)
prefix <- "C50"
suffix <- sprintf('%0.1d', 0:9)
seq <- paste0(prefix, suffix)

breast_cancer <- c("C50", seq)
breast_cancer_icd <- ICD10list3d[which(ICD10list3d %in% breast_cancer)]

# ovarian cancer (C56)
prefix <- "C56"
suffix <- sprintf('%0.1d', 0:9)
seq <- paste0(prefix, suffix)

ovarian_cancer <- c("C56", seq)
ovarian_cancer_icd <- ICD10list3d[which(ICD10list3d %in% ovarian_cancer)]

# prostate cancer (C61)
prefix <- "C61"
suffix <- sprintf('%0.1d', 0:9)
seq <- paste0(prefix, suffix)

prostate_cancer <- c("C61", seq)
prostate_cancer_icd <- ICD10list3d[which(ICD10list3d %in% prostate_cancer)]


# type II diabetes (E11)
prefix <- "E"
suffix <- seq(110,119)
seq <- paste0(prefix, suffix)

diabetes <- c("E11", seq)
diabetes_icd <- ICD10list3d[which(ICD10list3d %in% diabetes)]


# ischemic heart diseases (I20–I25)
prefix <- "I"
suffix <- seq(20,25)
seq <- paste0(prefix, suffix)

prefix <- "I"
suffix <- seq(200,259)
seq2 <- paste0(prefix, suffix)

cardio <- c(seq, seq2)
cardio_icd <- ICD10list3d[which(ICD10list3d %in% cardio)]


#cerebrovascular disease (I60–I69)
prefix <- "I"
suffix <- seq(60,69)
seq <- paste0(prefix, suffix)

prefix <- "I"
suffix <- seq(600,699)
seq2 <- paste0(prefix, suffix)

cerebro <- c(seq, 
             seq2)
cerebro_icd <- ICD10list3d[which(ICD10list3d %in% cerebro)]


# COPD and emphysema (J43–J44)
prefix <- "J"
suffix <- seq(43,44)
seq <- paste0(prefix, suffix)

prefix <- "J"
suffix <- seq(430,449)
seq2 <- paste0(prefix, suffix)

copd <- c(seq, 
          seq2)
copd_icd <- ICD10list3d[which(ICD10list3d %in% copd)]


# chronic liver disease (K70, K73-K74)
prefix <- "K"
suffix <- seq(73,74)
seq <- paste0(prefix, suffix)

prefix <- "K"
suffix <- seq(700,709)
seq2 <- paste0(prefix, suffix)

prefix <- "K"
suffix <- seq(730,749)
seq3 <- paste0(prefix, suffix)

liver <- c("K70", 
           seq, 
           seq2, 
           seq3)
liver_icd <- ICD10list3d[which(ICD10list3d %in% liver)]


# chronic kidney disease (N18)
prefix <- "N"
suffix <- seq(180,189)
seq <- paste0(prefix, suffix)

kidney <- c("N18", seq)
kidney_icd <- ICD10list3d[which(ICD10list3d %in% kidney)]


# all-cause dementia (A81.0, F00-F03, F05.1, F10.6, G30-G31, I67.3)
prefix <- "F"
suffix <- sprintf('%0.3d', 0:9)
seq <- paste0(prefix, suffix)

prefix <- "F0"
suffix <- sprintf('%0.d', 10:39)
seq2 <- paste0(prefix, suffix)

all_dementia <- c("A810", "F00", "F01", "F02", "F03", seq, seq2, "F051", "F106", "I673")
all_dementia_icd <- ICD10list3d[which(ICD10list3d %in% all_dementia)]

# vascular dementia (F01, I67.3)
prefix <- "F0"
suffix <- sprintf('%0.d', 10:19)
seq <- paste0(prefix, suffix)

vasc_dementia <- c("F01", seq, "I673")
vasc_dementia_icd <- ICD10list3d[which(ICD10list3d %in% vasc_dementia)]

# Alzheimer's (F00, G30)
prefix <- "F"
suffix <- sprintf('%0.3d', 0:9)
seq <- paste0(prefix, suffix)

prefix <- "G"
suffix <- seq(300,309)
seq2 <- paste0(prefix, suffix)

alzheimers <- c("F00", seq, "G30", seq2)
alzheimers_icd <- ICD10list3d[which(ICD10list3d %in% alzheimers)]

# Parkinsons (G20-G22)
prefix <- "G"
suffix <- seq(200,229)
seq <- paste0(prefix, suffix)

parkinsons <- c("G20", "G21", "G22", seq)
parkinsons_icd <- ICD10list3d[which(ICD10list3d %in% parkinsons)]


# rheumatoid arthritis (M05-06)
prefix <- "M05"
suffix <- seq(0,9)
seq <- paste0(prefix, suffix)

prefix <- "M06"
suffix <- seq(0,9)
seq2 <- paste0(prefix, suffix)

rheumatoid <- c("M05",
                seq,
                "M06",
                seq2)
rheumatoid_icd <- ICD10list3d[which(ICD10list3d %in% rheumatoid)]


# macular degeneration (H35.3)
macular <- "H353"
macular_icd <- ICD10list3d[which(ICD10list3d %in% macular)]


# osteoporosis (M80-M81)
prefix <- "M8"
suffix <- sprintf('%0.2d', 00:19)
seq <- paste0(prefix, suffix)

osteoporosis <- c("M80",
                  "M81",
                  seq)
osteoporosis_icd <- ICD10list3d[which(ICD10list3d %in% osteoporosis)]


# osteoarthritis (M15-M19)
prefix <- "M"
suffix <- seq(15,19)
seq <- paste0(prefix, suffix)

prefix <- "M1"
suffix <- sprintf('%0.2d', 50:99)
seq2 <- paste0(prefix, suffix)

osteoarthritis <- c(seq, seq2)
osteoarthritis_icd <- ICD10list3d[which(ICD10list3d %in% osteoarthritis)]

# create list of all NCD codes
icd_include <- c(
    colon_cancer_icd,
    lung_cancer_icd,
    eso_cancer_icd,
    liver_cancer_icd,
    pancreatic_cancer_icd,
    leukemia_icd,
    lymphoma_icd,
    breast_cancer_icd,
    ovarian_cancer_icd,
    prostate_cancer_icd,
    diabetes_icd,
    cardio_icd,
    cerebro_icd,
    copd_icd,
    liver_icd, 
    kidney_icd,
    all_dementia_icd,
    vasc_dementia_icd,
    alzheimers_icd,
    parkinsons_icd,
    rheumatoid_icd,
    macular_icd,
    osteoporosis_icd,
    osteoarthritis_icd
)


```

## Prepare cause of death data

``` {r table_prep}

### prepare cause of death data

### transform COD data from long format (with multiple rows per eid) 
### to wide format (multiple columns and one row per eid)
dat_COD <-
    pivot_wider(dat_COD,
                # any new value in "ins_index" or "arr_index" becomes a new column
                names_from = c(ins_index,
                               arr_index),
                # populate new columns with corresponding value from COD column
                values_from = cause_icd10) 

# remove level variable (it's redundant to the arr_index information)
dat_COD <- subset(dat_COD,
                  select = -c(level))

### the dataset now has two rows for each eid: 
### instance index = 0 data are all in one row and instance = 1 are all on second
### now we collapse the two rows for each eid into one row

# prepare dataset
dat_COD <- sapply(dat_COD, as.character) # data need to be character class for transpose function
dat_COD[is.na(dat_COD)] <- "" # NA values will cause errors in the transpose
dat_COD <- as.data.frame(dat_COD) # convert back to df

# transpose dataset by merging all rows with a unique eid into one row
dat_COD %>%
    group_by(eid) %>%
    summarise_all(
        funs(trimws(paste(., collapse = "")))) -> dat_COD

dat_COD[dat_COD == ""] <- NA # convert empty cells back to NA

### replace column names

# new column names
prefix <- "cause_icd.0."
suffix <- seq(0,14)
ICD10_0 <- paste0(prefix, suffix)

# old names to replace
prefix <- "0_"
suffix <- seq(0,14)
replace1 <- paste0(prefix, suffix)

# new column names
prefix <- "cause_icd.1."
suffix <- seq(0,9)
ICD10_1 <- paste0(prefix, suffix)

# old names to replace
prefix <- "1_"
suffix <- seq(0,9)
replace2 <- paste0(prefix, suffix)

# loop to replace instance = 0 column names
for(j in seq_along(replace1)){
  names(dat_COD)[names(dat_COD) == replace1[j]] <- ICD10_0[j]
}

# loop to replace instance = 1 column names
for(j in seq_along(replace2)){
  names(dat_COD)[names(dat_COD) == replace2[j]] <- ICD10_1[j] 
}

# reorder columns in ascending order
col_order <- c("eid", ICD10_0, ICD10_1)
dat_COD <- dat_COD[, col_order]


### prepare death date data 

# remove duplicate date of death record row for any participant (e.g., where "ins_index = 1"). 
# date in ins_index = 1 shows the same date so it is redundant
mort <- mort[which(mort$ins_index == '0'), ]

# check how date is formatted for correct as.Date formatting
head(mort$date_of_death) 

# set as date
mort$date_of_death <- as.Date(mort$date_of_death, 
                              format = "%d/%m/%Y")

# check for any formatting errors
head(mort$date_of_death) 


### merge date and cause of death data 

mort <- merge(dat_COD, 
              mort, 
              by = "eid", 
              all = FALSE) # Note: this will delete 10 participants that have a date of death but no cause of death

### create mortality event indicators by pimary cause of death only

# create vector of all primary COD columns (array > 0 is a secondary cause)
ICD10_primary <- c("cause_icd.0.0", "cause_icd.1.0")
# create vector of all secondary COD columns (array > 0 is a secondary cause)
ICD10_secondary <- c(ICD10_0[-1], ICD10_1[-1])
# any COD (primary or secondary)
ICD10_all <- c(ICD10_0, ICD10_1)

### All NCD mort indicator 

mort$NCD_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", icd_include),
    na.rm = TRUE) > 0)


### Colon cancer mort indicator 

mort$colon_cancer_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", colon_cancer_icd),
    na.rm = TRUE) > 0)

### Lung cancer mort indicator 

mort$lung_cancer_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", lung_cancer_icd),
    na.rm = TRUE) > 0)

### eso cancer mort indicator 

mort$eso_cancer_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", eso_cancer_icd),
    na.rm = TRUE) > 0)

### liver cancer mort indicator 

mort$liver_cancer_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", liver_cancer_icd),
    na.rm = TRUE) > 0)

### pancreatic cancer mort indicator 

mort$pancreatic_cancer_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", pancreatic_cancer_icd),
    na.rm = TRUE) > 0)

### leukemia cancer mort indicator 

mort$leukemia_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", leukemia_icd),
    na.rm = TRUE) > 0)

### lymphoma mort indicator 

mort$lymphoma_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", lymphoma_icd),
    na.rm = TRUE) > 0)

### Breast cancer mort indicator 

mort$breast_cancer_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", breast_cancer_icd),
    na.rm = TRUE) > 0)

### Ovarian cancer mort indicator 

mort$ovarian_cancer_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", ovarian_cancer_icd),
    na.rm = TRUE) > 0)

### Prostate cancer mort indicator 

mort$prostate_cancer_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", prostate_cancer_icd),
    na.rm = TRUE) > 0)

### Diabetes mort indicator 

mort$diabetes_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", diabetes_icd),
    na.rm = TRUE) > 0)

### CVD mort indicator 

mort$CVD_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", cardio_icd),
    na.rm = TRUE) > 0)

### Cerebrovacsular mort indicator 

mort$cerebro_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", cerebro_icd),
    na.rm = TRUE) > 0)

### COPD mort indicator 

mort$COPD_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", copd_icd),
    na.rm = TRUE) > 0)

### Liver disease mort indicator 

mort$liver_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", liver_icd),
    na.rm = TRUE) > 0)

### Kidney disease mort indicator 

mort$kidney_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", kidney_icd),
    na.rm = TRUE) > 0)

### All-cause dementia mort indicator 

mort$all_dementia_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", all_dementia_icd),
    na.rm = TRUE) > 0)

### Vascular dementia mort indicator 

mort$vasc_dementia_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", vasc_dementia_icd),
    na.rm = TRUE) > 0)

### Alzheimer's disease mort indicator

mort$alzheimers_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", alzheimers_icd),
    na.rm = TRUE) > 0)

### Parkinson's disease mort indicator

mort$parkinsons_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", parkinsons_icd),
    na.rm = TRUE) > 0)

### Rheumatoid arthritis mort indicator

mort$rheumatoid_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", rheumatoid_icd),
    na.rm = TRUE) > 0)

### macular degeneration mort indicator

mort$macular_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", macular_icd),
    na.rm = TRUE) > 0)

### osteoporosis mort indicator

mort$osteoporosis_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", osteoporosis_icd),
    na.rm = TRUE) > 0)

### osteoarthritis mort indicator

mort$osteoarthritis_mort_any <- as.numeric(
  rowSums(
    sapply(mort[ICD10_all], "%in%", osteoarthritis_icd),
    na.rm = TRUE) > 0)

```

## Table S5

```{r table_england}

data <- all_data[[1]]

# merge mortality data with analysis dataset
data <- merge(data, 
              mort,
              by = "eid",
              all.x = TRUE, 
              all.y = FALSE,
              sort = FALSE)


# subset to mortality cases
data <- data[which(data$ACM_event_indicator == 1),]

data$NCD_COD_any <- NA
data$NCD_COD_any[which(data$NCD_mort_any == 1)] <- "All diseases"
data$NCD_COD_any <- factor(data$NCD_COD_any, levels = c("All diseases"))


data$colon_cancer_COD_any <- NA
data$colon_cancer_COD_any[which(data$colon_cancer_mort_any == 1)] <- "Colorectal cancer"
data$colon_cancer_COD_any <- factor(data$colon_cancer_COD_any, levels = c("Colorectal cancer"))


data$lung_cancer_COD_any <- NA
data$lung_cancer_COD_any[which(data$lung_cancer_mort_any == 1)] <- "Lung cancer"
data$lung_cancer_COD_any <- factor(data$lung_cancer_COD_any, levels = c("Lung cancer"))


data$eso_cancer_COD_any <- NA
data$eso_cancer_COD_any[which(data$eso_cancer_mort_any == 1)] <- "Esophageal cancer"
data$eso_cancer_COD_any <- factor(data$eso_cancer_COD_any, levels = c("Esophageal cancer"))


data$liver_cancer_COD_any <- NA
data$liver_cancer_COD_any[which(data$liver_cancer_mort_any == 1)] <- "Liver cancer"
data$liver_cancer_COD_any <- factor(data$liver_cancer_COD_any, levels = c("Liver cancer"))


data$pancreatic_cancer_COD_any <- NA
data$pancreatic_cancer_COD_any[which(data$pancreatic_cancer_mort_any == 1)] <- "Pancreatic cancer"
data$pancreatic_cancer_COD_any <- factor(data$pancreatic_cancer_COD_any, levels = c("Pancreatic cancer"))


data$leukemia_COD_any <- NA
data$leukemia_COD_any[which(data$leukemia_mort_any == 1)] <- "Leukemia"
data$leukemia_COD_any <- factor(data$leukemia_COD_any, levels = c("Leukemia"))


data$lymphoma_COD_any <- NA
data$lymphoma_COD_any[which(data$lymphoma_mort_any == 1)] <- "Lymphoma"
data$lymphoma_COD_any <- factor(data$lymphoma_COD_any, levels = c("Lymphoma"))


data$breast_cancer_COD_any <- NA
data$breast_cancer_COD_any[which(data$breast_cancer_mort_any == 1)] <- "Breast cancer"
data$breast_cancer_COD_any <- factor(data$breast_cancer_COD_any, levels = c("Breast cancer"))


data$ovarian_cancer_COD_any <- NA
data$ovarian_cancer_COD_any[which(data$ovarian_cancer_mort_any == 1)] <- "Ovarian cancer"
data$ovarian_cancer_COD_any <- factor(data$ovarian_cancer_COD_any, levels = c("Ovarian cancer"))


data$prostate_cancer_COD_any <- NA
data$prostate_cancer_COD_any[which(data$prostate_cancer_mort_any == 1)] <- "Prostate cancer"
data$prostate_cancer_COD_any <- factor(data$prostate_cancer_COD_any, levels = c("Prostate cancer"))


data$diabetes_COD_any <- NA
data$diabetes_COD_any[which(data$diabetes_mort_any == 1)] <- "Type II diabetes"
data$diabetes_COD_any <- factor(data$diabetes_COD_any, levels = c("Type II diabetes"))


data$CVD_COD_any <- NA
data$CVD_COD_any[which(data$CVD_mort_any == 1)] <- "Ischemic heart disease"
data$CVD_COD_any <- factor(data$CVD_COD_any, levels = c("Ischemic heart disease"))


data$cerebro_COD_any <- NA
data$cerebro_COD_any[which(data$cerebro_mort_any == 1)] <- "Cerebrovascular diseases"
data$cerebro_COD_any <- factor(data$cerebro_COD_any, levels = c("Cerebrovascular diseases"))


data$COPD_COD_any <- NA
data$COPD_COD_any[which(data$COPD_mort_any == 1)] <- "Emphysema, COPD"
data$COPD_COD_any <- factor(data$COPD_COD_any, levels = c("Emphysema, COPD"))


data$liver_COD_any <- NA
data$liver_COD_any[which(data$liver_mort_any == 1)] <- "Chronic liver diseases"
data$liver_COD_any <- factor(data$liver_COD_any, levels = c("Chronic liver diseases"))


data$kidney_COD_any <- NA
data$kidney_COD_any[which(data$kidney_mort_any == 1)] <- "Chronic kidney diseases"
data$kidney_COD_any <- factor(data$kidney_COD_any, levels = c("Chronic kidney diseases"))


data$all_dementia_COD_any <- NA
data$all_dementia_COD_any[which(data$all_dementia_mort_any == 1)] <- "All-cause dementia"
data$all_dementia_COD_any <- factor(data$all_dementia_COD_any, levels = c("All-cause dementia"))


data$vasc_dementia_COD_any <- NA
data$vasc_dementia_COD_any[which(data$vasc_dementia_mort_any == 1)] <- "Vascular dementia"
data$vasc_dementia_COD_any <- factor(data$vasc_dementia_COD_any, levels = c("Vascular dementia"))


data$alzheimers_COD_any <- NA
data$alzheimers_COD_any[which(data$alzheimers_mort_any == 1)] <- "Alzheimer's disease"
data$alzheimers_COD_any <- factor(data$alzheimers_COD_any, levels = c("Alzheimer's disease"))


data$parkinsons_COD_any <- NA
data$parkinsons_COD_any[which(data$parkinsons_mort_any == 1)] <- "Parkinson's disease"
data$parkinsons_COD_any <- factor(data$parkinsons_COD_any, levels = c("Parkinson's disease"))


data$rheumatoid_COD_any <- NA
data$rheumatoid_COD_any[which(data$rheumatoid_mort_any == 1)] <- "Rheumatoid arthritis"
data$rheumatoid_COD_any <- factor(data$rheumatoid_COD_any, levels = c("Rheumatoid arthritis"))


data$macular_COD_any <- NA
data$macular_COD_any[which(data$macular_mort_any == 1)] <- "Macular degeneration"
data$macular_COD_any <- factor(data$macular_COD_any, levels = c("Macular degeneration"))


data$osteoporosis_COD_any <- NA
data$osteoporosis_COD_any[which(data$osteoporosis_mort_any == 1)] <- "Osteoporosis"
data$osteoporosis_COD_any <- factor(data$osteoporosis_COD_any, levels = c("Osteoporosis"))


data$osteoarthritis_COD_any <- NA
data$osteoarthritis_COD_any[which(data$osteoarthritis_mort_any == 1)] <- "Osteoarthritis"
data$osteoarthritis_COD_any <- factor(data$osteoarthritis_COD_any, levels = c("Osteoarthritis"))

# set labels for table
label(data$NCD_COD_any) <- ""
label(data$colon_cancer_COD_any) <- ""
label(data$lung_cancer_COD_any) <- ""
label(data$eso_cancer_COD_any) <- ""
label(data$liver_cancer_COD_any) <- ""
label(data$pancreatic_cancer_COD_any) <- ""
label(data$leukemia_COD_any) <- ""
label(data$lymphoma_COD_any) <- ""
label(data$breast_cancer_COD_any) <- ""
label(data$ovarian_cancer_COD_any) <- ""
label(data$prostate_cancer_COD_any) <- ""
label(data$diabetes_COD_any) <- ""
label(data$CVD_COD_any) <- ""
label(data$cerebro_COD_any) <- ""
label(data$COPD_COD_any) <- ""
label(data$liver_COD_any) <- ""
label(data$kidney_COD_any) <- ""
label(data$all_dementia_COD_any) <- ""
label(data$vasc_dementia_COD_any) <- ""
label(data$alzheimers_COD_any) <- ""
label(data$parkinsons_COD_any) <- ""
label(data$rheumatoid_COD_any) <- ""
label(data$macular_COD_any) <- ""
label(data$osteoporosis_COD_any) <- ""
label(data$osteoarthritis_COD_any) <- ""


# functions to display numbers correctly
my.render.cont <- function(x) {
    with(stats.apply.rounding(stats.default(x), digits=2), 
         c("", "Mean (SD)"=sprintf("%s (%s)", MEAN, SD)))
}

my.render.categorical <- function(x, ...) {
    c("", sapply(stats.apply.rounding(stats.default(x)), function(y) with(y,
                                                                          sprintf("%s (%s%%)", prettyNum(FREQ, big.mark=","), PCT))))
}

my.render.strat <- function (label, n, ...) {
    sprintf("<span class='stratlabel'>%s<br><span class='stratn'>(N=%s)</span></span>", 
            label, prettyNum(n, big.mark=","))
}

# create table
table <- 
    table1(~ NCD_COD_any + 
               CVD_COD_any + 
               lung_cancer_COD_any +
               cerebro_COD_any + 
               COPD_COD_any + 
               colon_cancer_COD_any +
               breast_cancer_COD_any +
               diabetes_COD_any + 
               all_dementia_COD_any +
               pancreatic_cancer_COD_any +
               prostate_cancer_COD_any +
               kidney_COD_any + 
               eso_cancer_COD_any +
               lymphoma_COD_any +
               parkinsons_COD_any + 
               liver_COD_any + 
               alzheimers_COD_any + 
               leukemia_COD_any +
               ovarian_cancer_COD_any +
               liver_cancer_COD_any +
               vasc_dementia_COD_any +
               rheumatoid_COD_any + 
               osteoporosis_COD_any +
               osteoarthritis_COD_any +
               macular_COD_any,
           data = data, 
           render.continuous = my.render.cont,
           render.strat = my.render.strat,
           render.categorical = my.render.categorical,
           render.missing = NULL,
           overall = "Total deaths")

# show - copy and paste into word
table

# save as word doc
ftable <- t1flex(table)
ftable <- add_header_row(ftable,
                          value = "Table S5. Mortality by cause of death - UK Biobank participants recruited in England",
                          top = TRUE,
                          colwidths = 2)
ftable <- padding(ftable, 
                  padding = 0,
                  padding.bottom = 0)
ftable <- fontsize(ftable, size = 9, part = "all")

# save
save_as_docx(ftable, path = paste0(path, "/output/tables/table_S5_sept_02_2022.docx"))
                                    
```

## Table S6

```{r table_scotwales}

data <- scotwales[[1]]

# merge mortality data with analysis dataset
data <- merge(data, 
              mort,
              by = "eid",
              all.x = TRUE, 
              all.y = FALSE,
              sort = FALSE)


# subset to mortality cases
data <- data[which(data$ACM_event_indicator == 1),]

data$NCD_COD_any <- NA
data$NCD_COD_any[which(data$NCD_mort_any == 1)] <- "All diseases"
data$NCD_COD_any <- factor(data$NCD_COD_any, levels = c("All diseases"))


data$colon_cancer_COD_any <- NA
data$colon_cancer_COD_any[which(data$colon_cancer_mort_any == 1)] <- "Colorectal cancer"
data$colon_cancer_COD_any <- factor(data$colon_cancer_COD_any, levels = c("Colorectal cancer"))


data$lung_cancer_COD_any <- NA
data$lung_cancer_COD_any[which(data$lung_cancer_mort_any == 1)] <- "Lung cancer"
data$lung_cancer_COD_any <- factor(data$lung_cancer_COD_any, levels = c("Lung cancer"))


data$eso_cancer_COD_any <- NA
data$eso_cancer_COD_any[which(data$eso_cancer_mort_any == 1)] <- "Esophageal cancer"
data$eso_cancer_COD_any <- factor(data$eso_cancer_COD_any, levels = c("Esophageal cancer"))


data$liver_cancer_COD_any <- NA
data$liver_cancer_COD_any[which(data$liver_cancer_mort_any == 1)] <- "Liver cancer"
data$liver_cancer_COD_any <- factor(data$liver_cancer_COD_any, levels = c("Liver cancer"))


data$pancreatic_cancer_COD_any <- NA
data$pancreatic_cancer_COD_any[which(data$pancreatic_cancer_mort_any == 1)] <- "Pancreatic cancer"
data$pancreatic_cancer_COD_any <- factor(data$pancreatic_cancer_COD_any, levels = c("Pancreatic cancer"))


data$leukemia_COD_any <- NA
data$leukemia_COD_any[which(data$leukemia_mort_any == 1)] <- "Leukemia"
data$leukemia_COD_any <- factor(data$leukemia_COD_any, levels = c("Leukemia"))


data$lymphoma_COD_any <- NA
data$lymphoma_COD_any[which(data$lymphoma_mort_any == 1)] <- "Lymphoma"
data$lymphoma_COD_any <- factor(data$lymphoma_COD_any, levels = c("Lymphoma"))


data$breast_cancer_COD_any <- NA
data$breast_cancer_COD_any[which(data$breast_cancer_mort_any == 1)] <- "Breast cancer"
data$breast_cancer_COD_any <- factor(data$breast_cancer_COD_any, levels = c("Breast cancer"))


data$ovarian_cancer_COD_any <- NA
data$ovarian_cancer_COD_any[which(data$ovarian_cancer_mort_any == 1)] <- "Ovarian cancer"
data$ovarian_cancer_COD_any <- factor(data$ovarian_cancer_COD_any, levels = c("Ovarian cancer"))


data$prostate_cancer_COD_any <- NA
data$prostate_cancer_COD_any[which(data$prostate_cancer_mort_any == 1)] <- "Prostate cancer"
data$prostate_cancer_COD_any <- factor(data$prostate_cancer_COD_any, levels = c("Prostate cancer"))


data$diabetes_COD_any <- NA
data$diabetes_COD_any[which(data$diabetes_mort_any == 1)] <- "Type II diabetes"
data$diabetes_COD_any <- factor(data$diabetes_COD_any, levels = c("Type II diabetes"))


data$CVD_COD_any <- NA
data$CVD_COD_any[which(data$CVD_mort_any == 1)] <- "Ischemic heart disease"
data$CVD_COD_any <- factor(data$CVD_COD_any, levels = c("Ischemic heart disease"))


data$cerebro_COD_any <- NA
data$cerebro_COD_any[which(data$cerebro_mort_any == 1)] <- "Cerebrovascular diseases"
data$cerebro_COD_any <- factor(data$cerebro_COD_any, levels = c("Cerebrovascular diseases"))


data$COPD_COD_any <- NA
data$COPD_COD_any[which(data$COPD_mort_any == 1)] <- "Emphysema, COPD"
data$COPD_COD_any <- factor(data$COPD_COD_any, levels = c("Emphysema, COPD"))


data$liver_COD_any <- NA
data$liver_COD_any[which(data$liver_mort_any == 1)] <- "Chronic liver diseases"
data$liver_COD_any <- factor(data$liver_COD_any, levels = c("Chronic liver diseases"))


data$kidney_COD_any <- NA
data$kidney_COD_any[which(data$kidney_mort_any == 1)] <- "Chronic kidney diseases"
data$kidney_COD_any <- factor(data$kidney_COD_any, levels = c("Chronic kidney diseases"))


data$all_dementia_COD_any <- NA
data$all_dementia_COD_any[which(data$all_dementia_mort_any == 1)] <- "All-cause dementia"
data$all_dementia_COD_any <- factor(data$all_dementia_COD_any, levels = c("All-cause dementia"))


data$vasc_dementia_COD_any <- NA
data$vasc_dementia_COD_any[which(data$vasc_dementia_mort_any == 1)] <- "Vascular dementia"
data$vasc_dementia_COD_any <- factor(data$vasc_dementia_COD_any, levels = c("Vascular dementia"))


data$alzheimers_COD_any <- NA
data$alzheimers_COD_any[which(data$alzheimers_mort_any == 1)] <- "Alzheimer's disease"
data$alzheimers_COD_any <- factor(data$alzheimers_COD_any, levels = c("Alzheimer's disease"))


data$parkinsons_COD_any <- NA
data$parkinsons_COD_any[which(data$parkinsons_mort_any == 1)] <- "Parkinson's disease"
data$parkinsons_COD_any <- factor(data$parkinsons_COD_any, levels = c("Parkinson's disease"))


data$rheumatoid_COD_any <- NA
data$rheumatoid_COD_any[which(data$rheumatoid_mort_any == 1)] <- "Rheumatoid arthritis"
data$rheumatoid_COD_any <- factor(data$rheumatoid_COD_any, levels = c("Rheumatoid arthritis"))


data$macular_COD_any <- NA
data$macular_COD_any[which(data$macular_mort_any == 1)] <- "Macular degeneration"
data$macular_COD_any <- factor(data$macular_COD_any, levels = c("Macular degeneration"))


data$osteoporosis_COD_any <- NA
data$osteoporosis_COD_any[which(data$osteoporosis_mort_any == 1)] <- "Osteoporosis"
data$osteoporosis_COD_any <- factor(data$osteoporosis_COD_any, levels = c("Osteoporosis"))


data$osteoarthritis_COD_any <- NA
data$osteoarthritis_COD_any[which(data$osteoarthritis_mort_any == 1)] <- "Osteoarthritis"
data$osteoarthritis_COD_any <- factor(data$osteoarthritis_COD_any, levels = c("Osteoarthritis"))

# set labels for table
label(data$NCD_COD_any) <- ""
label(data$colon_cancer_COD_any) <- ""
label(data$lung_cancer_COD_any) <- ""
label(data$eso_cancer_COD_any) <- ""
label(data$liver_cancer_COD_any) <- ""
label(data$pancreatic_cancer_COD_any) <- ""
label(data$leukemia_COD_any) <- ""
label(data$lymphoma_COD_any) <- ""
label(data$breast_cancer_COD_any) <- ""
label(data$ovarian_cancer_COD_any) <- ""
label(data$prostate_cancer_COD_any) <- ""
label(data$diabetes_COD_any) <- ""
label(data$CVD_COD_any) <- ""
label(data$cerebro_COD_any) <- ""
label(data$COPD_COD_any) <- ""
label(data$liver_COD_any) <- ""
label(data$kidney_COD_any) <- ""
label(data$all_dementia_COD_any) <- ""
label(data$vasc_dementia_COD_any) <- ""
label(data$alzheimers_COD_any) <- ""
label(data$parkinsons_COD_any) <- ""
label(data$rheumatoid_COD_any) <- ""
label(data$macular_COD_any) <- ""
label(data$osteoporosis_COD_any) <- ""
label(data$osteoarthritis_COD_any) <- ""


# functions to display numbers correctly
my.render.cont <- function(x) {
    with(stats.apply.rounding(stats.default(x), digits=2), 
         c("", "Mean (SD)"=sprintf("%s (%s)", MEAN, SD)))
}

my.render.categorical <- function(x, ...) {
    c("", sapply(stats.apply.rounding(stats.default(x)), function(y) with(y,
                                                                          sprintf("%s (%s%%)", prettyNum(FREQ, big.mark=","), PCT))))
}

my.render.strat <- function (label, n, ...) {
    sprintf("<span class='stratlabel'>%s<br><span class='stratn'>(N=%s)</span></span>", 
            label, prettyNum(n, big.mark=","))
}

# create table
table2 <- 
    table1(~ NCD_COD_any + 
               CVD_COD_any + 
               lung_cancer_COD_any +
               cerebro_COD_any + 
               COPD_COD_any + 
               diabetes_COD_any + 
               colon_cancer_COD_any +
               all_dementia_COD_any +
               breast_cancer_COD_any +
               pancreatic_cancer_COD_any +
               alzheimers_COD_any + 
               kidney_COD_any + 
               prostate_cancer_COD_any +
               eso_cancer_COD_any +
               liver_COD_any + 
               lymphoma_COD_any +
               parkinsons_COD_any + 
               liver_cancer_COD_any +
               ovarian_cancer_COD_any +
               vasc_dementia_COD_any +
               leukemia_COD_any +
               rheumatoid_COD_any + 
               osteoporosis_COD_any +
               osteoarthritis_COD_any +
               macular_COD_any,
           data = data, 
           render.continuous = my.render.cont,
           render.strat = my.render.strat,
           render.categorical = my.render.categorical,
           render.missing = NULL,
           overall = "Total deaths")

# show - copy and paste into word
table2

# save as word doc
ftable2 <- t1flex(table2)
ftable2 <- add_header_row(ftable2,
                          value = "Table S6. Mortality by cause of death - UK Biobank participants recruited in Scotland/Wales",
                          top = TRUE,
                          colwidths = 2)
ftable2 <- padding(ftable2, 
                  padding = 0,
                  padding.bottom = 0)
ftable2 <- fontsize(ftable2, size = 9, part = "all")

# save
save_as_docx(ftable2, path = paste0(path, "/output/tables/table_S6_sept_02_2022.docx"))
                                    
```
